return {
	ACTIONFAIL =
	{
		SHAVE =
		{
			AWAKEBEEFALO = "I will wait until he is not looking.",
			GENERIC = "That cannot be shaved.",
			NOBITS = "I cannot shave when there are no hairs.",
		},
		WRITE =
        {
            GENERIC = "Wolfgang not good with tiny letters.",
        },
		RUMMAGE =
        {   
            GENERIC = "Maybe Wolfgang do later.",
        },
		COOK =
        {
            GENERIC = "Wolfgang not in cooking mood.",
            TOOFAR = "Is pot very small, or just far away?",
        },
		REPAIRBOAT =
		{
			GENERIC = "Small boat has no damages to repair! Wolfgang could punch it?",
		},
		STORE =
		{
			GENERIC = "I will make it fit!",
			NOTALLOWED = "Bah! Useless.",
		},
		GIVE =
        {
            DEAD = "You know is dead, yes?",
            SLEEPING = "Is sleeping now!",
            BUSY = "The Mighty Wolfgang will try again soon!",
        },
        CHANGEIN =
        {
            GENERIC = "Clothes only good for ripping with strong muscles!",
            BURNING = "Wolfgang's weekday undergarments burning? Wolfgang is sad.",
        },
        TEACH =
        {
            KNOWN = "Wolfgang already knows this!",
            CANTLEARN = "I do not get it.",
        },
	},
	ACTIONFAIL_GENERIC = "I am not mighty enough to do that.",
	
	ANNOUNCE_NORMALTOMIGHTY="I AM MIGHTY!",
	ANNOUNCE_NORMALTOWIMPY="I am not feeling so good.",
	ANNOUNCE_WIMPYTONORMAL="Wolfgang is better.",
	ANNOUNCE_MIGHTYTONORMAL="I need to fill my mighty belly again!",

	ANNOUNCE_MAGIC_FAIL = "Is not making the magics now. Why?",
	ANNOUNCE_NOSLEEPONFIRE = "Is too hot for sleeping.",
	ANNOUNCE_NODANGERSIESTA = "Wolfgang prefer fight to nap.",
	ANNOUNCE_NONIGHTSIESTA = "Wolfgang have principles against siesta at night.",
	ANNOUNCE_NONIGHTSIESTA_CAVE = "Wolfgang is tense. Too tense to relax.",
	ANNOUNCE_NOHUNGERSIESTA = "Wolfgang take siesta after eating time.",
	ANNOUNCE_SHELTER = "Wolfgang hide under tree.",
	ANNOUNCE_BURNT = "Burny is not fair!",
	ANNOUNCE_TOOL_SLIP = "Is too slippery for holding!",
	ANNOUNCE_DAMP = "Water time.",
	ANNOUNCE_WET = "Wolfgang does not like bath time.",
	ANNOUNCE_WETTER = "It is like sitting in pond.",
	ANNOUNCE_SOAKED = "Wolfgang is maybe now made of water.",
	ANNOUNCE_ADVENTUREFAIL = "Next time I will be mightier!",
	ANNOUNCE_BOOMERANG = "Ow! Why did you hurt me, throwy stick?",
	ANNOUNCE_CHARLIE = "Show yourself!",
	ANNOUNCE_CHARLIE_ATTACK = "Ow! It got me!",
	ANNOUNCE_COLD = "Brrrrrrr! Is frosty!",
	ANNOUNCE_HOT = "Hah, is sticky and hot!",
	ANNOUNCE_CRAFTING_FAIL = "I need to gather more things to make that.",
	ANNOUNCE_DUSK = "The scary time is coming soon.",

	ANNOUNCE_ENTER_DARK = "I cannot see! I am scared!",
	ANNOUNCE_ENTER_LIGHT = "I can see again!",
	ANNOUNCE_HOUNDS = "I hear puppies!",
	ANNOUNCE_HUNGRY = "My mighty belly is empty!",
	ANNOUNCE_HUNT_BEAST_NEARBY = "Animal is close!",
	ANNOUNCE_HUNT_LOST_TRAIL = "No animal here.",
	ANNOUNCE_HUNT_LOST_TRAIL_SPRING = "Animal tracks is mud now.",
	ANNOUNCE_INV_FULL = "My mighty arms can carry no more.",
	ANNOUNCE_FAN_OUT = "Tiny fan is broken!",
    ANNOUNCE_COMPASS_OUT = "Little needle broke off!",
	ANNOUNCE_PECKED = "What I do to deserve this?",
	ANNOUNCE_TORCH_OUT = "Oh no! The light is gone!",
	ANNOUNCE_WORMHOLE = "It makes me feel alive!",
	ANNOUNCE_TRAP_WENT_OFF = "Ack! Do not surprise Wolfgang!",
    ANNOUNCE_QUAKE = "Ground is shake. Wolfgang hate shaking ground.",
    ANNOUNCE_NODANGERSLEEP = "Wolfgang prefer fight to sleep.",
    ANNOUNCE_UNIMPLEMENTED = "Is not ready.",
    ANNOUNCE_NOHUNGERSLEEP = "Wolfgang say never sleep with empty stomach.",
    ANNOUNCE_FREEDOM = "I am free! Strong freedom!",
    ANNOUNCE_RESEARCH = "Is lot of information.",
    ANNOUNCE_NO_TRAP = "Easy like lift weights.",
    ANNOUNCE_HIGHRESEARCH = "Is maybe too much information.",
    ANNOUNCE_THORNS = "Pointy is not fair!",
    ANNOUNCE_NODAYSLEEP_CAVE = "Is creepy in cave.",
    ANNOUNCE_BEES = "Bees! Nasty stinging bug men!",
    ANNOUNCE_KNOCKEDOUT = "Ugh, I must have hit head.",
    ANNOUNCE_LOWRESEARCH = "Is tiny information.",
    ANNOUNCE_DEERCLOPS = "Sound like big strong man coming.",
    ANNOUNCE_MOSQUITOS = "Wolfgang need blood, get away sucking bugs!",
    ANNOUNCE_NODAYSLEEP = "Is too bright for sleep.",
	ANNOUNCE_CANFIX = "\nMighty brain could make this better!",
	ANNOUNCE_ACCOMPLISHMENT= "I am doing great things with tiny arrow!",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "I have defeated the tiny arrow!",	
	ANNOUNCE_INSUFFICIENTFERTILIZER = "Is not enough poop.",
	ANNOUNCE_LIGHTNING_DAMAGE_AVOIDED = "Lightning is weak compared to Wolfgang clothes!",
	ANNOUNCE_WORMS = "Earth is tremble beneath Wolfgang's mighty feet!",

	ANNOUNCE_OTHER_WORLD_PLANT = "Not mighty enough to grow here! Unlike Wolfgang!",

	ANNOUNCE_BOAT_DAMAGED = "Ship is weak! Needs fixingtimes.",
	ANNOUNCE_BOAT_SINKING = "I will fight sea!",
	ANNOUNCE_BOAT_SINKING_IMMINENT = "Wolfgang will punch death!",
	ANNOUNCE_CRAB_ESCAPE = "Crabbit has fled. I do not blame it.",
	ANNOUNCE_EAT =
	{
		GENERIC = "Good food make Wolfgang strong!",
		PAINFUL = "Ooooh. I have belly ache.",
		SPOILED = "Ew! Tastes like garbage!",
		STALE = "Tastes funny.",
		INVALID = "Hahah! That's not food!",
		YUCKY = "Stomach is not strong enough for that.",
	},
	ANNOUNCE_MAPWRAP_LOSECONTROL = "Boat not listen to mighty Wolfgang!",
	ANNOUNCE_MAPWRAP_RETURN = "Wolfgang cannot be stopped!",
	ANNOUNCE_MAPWRAP_WARN = "Is getting scary!",
	ANNOUNCE_MORETREASURE = "Wolfgang find more shinies!",
	ANNOUNCE_OTHER_WORLD_TREASURE = "Treasure does not look close by.",
	ANNOUNCE_SHARX = "Wolfgang has made new friends!",
	ANNOUNCE_TRAWL_FULL = "Net is fat with treasures!",
	ANNOUNCE_TREASURE = "Wolfgang sees presents!",
	ANNOUNCE_VOLCANO_ERUPT = "Ha ha! Time to fight MOUNTAIN!",
	ANNOUNCE_WAVE_BOOST = "I am mighty!",
	ANNOUNCE_WHALE_HUNT_BEAST_NEARBY = "Wolfgang will find you, big fishie!",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL = "Argh! Big fishie outsmart Wolfgang!",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL_SPRING = "Wolfgang cannot follow big fishie!",
	ANNOUNCE_MESSAGEBOTTLE =
	{
		"Eh... Wolfgang can not read.",
	},

	BATTLECRY =
	{
		GENERIC = "I will punch you!",
		PIG = "I am sorry, my friend!",
		PREY = "Stomp! Stomp! Stomp!",
		SPIDER = "Die, evil scary bug!",
		SPIDER_WARRIOR = "I am still stronger, scary bug!",
	},
	COMBAT_QUIT =
	{
		GENERIC = "Ha! I win!",
		PIG = "I forgive you, pig man.",
		PREY = "You keep running!",
		SPIDER = "He ran away from me.",
		SPIDER_WARRIOR = "He knows I am stronger.",
	},
	DESCRIBE =
	{
		BABYOX = "He will grow very strong. Or she?",
		BIGFISHINGROD = "Is catching big fish?",
		BLOWDART_POISON = "Is like many tiny punches!",
		COFFEEBOT = "Is hard worker.",
		COMPASS =
		{
			E = "Is East.",
			GENERIC = "Is all directions, but no directions.",
			N = "Is North.",
			NE = "Is Northeast.",
			NW = "Is Northwest.",
			S = "Is South.",
			SE = "Is Southeast.",
			SW = "Is Southwest.",
			W = "Is West.",
		},
		DEPLETED_BAMBOOTREE = "Bush is done for.",
		DEPLETED_BUSH_VINE = "Vine bush is look pathetic!",
		DEPLETED_GRASS_WATER = "Maybe grass just need to eat.",
		DEVTOOL = "Wolfgang will smash!",
		DEVTOOL_NODEV = "Smash!",
		MUSSELBOUILLABAISE = "It belongs in Wolfgang's mouth.",
		OBSIDIANSPEARGUN = "Not as fun as punches, but still very good!",
		RELIC =
		{
			BROKEN = "Tiny bits.",
			GENERIC = "Is dumb thing.",
		},
		SPEARGUN_POISON = "My sickness shooter!",
		SUPERTELESCOPE = "Make eyes strong!",
		SWEETPOTATOSOUFFLE = "Wolfgang will eat!",
		TREASURECHEST_TRAP = "Raagh!",
		WOODLEGSBOAT = "Is very bad boat.",
		WOODLEGSHAT = "Is head clothes.",
		WOODLEGSSAIL = "Is scary sail!",
		WORMHOLE_LIMITED = "It is weak and feeble.",
		GLOMMER = "Why you follow me, weird bug?",
        GLOMMERFLOWER = 
        {
        	GENERIC = "Is shiny flower.",
        	DEAD = "Is sad and shiny flower.",
        },
        GLOMMERWINGS = "Small like fairy wings.",
        GLOMMERFUEL = "Weird bug make weird poop.",
        BELL = "Bell make dainty sound.",
        STATUEGLOMMER = 
        {	
        	GENERIC = "Why statue is not flying?",
        	EMPTY = "Smash!",
    	},
		WEBBERSKULL = "I crush skull!",
		MOLE =
		{
			HELD = "Wolfgang have mercy for soft tiny animal.",
			UNDERGROUND = "Stay underground where you are safe from Wolfgang.",
			ABOVEGROUND = "Now you will know Wolfgang's strength!",
		},
		MOLEHILL = "Mole hole.",
		MOLEHAT = "Mole skin is stretchy.",
		NIGHTSTICK = "Wolfgang like fists better.",
		RABBITHOUSE=
		{
			GENERIC = "I hear nomming inside.",
			BURNT = "Nomming is over.",
		},
		TURF_DECIDUOUS = "Step stones.",
		TURF_SANDY = "Step stones.",
		TURF_BADLANDS = "Step stones.",
		BEARGER = "Wolfgang not want to fight big bear.",
		BEARGERVEST = "Big bear shirt.",
		ICEPACK = "Furry bag.",
		BEARGER_FUR = "Is like hair on Wolfgang chest.",
		BIGFOOT = "Foot is too big!",
		BONESHARD = "Wolfgang crush into even smaller bones!",
		BUZZARD = "Carry on.",
		CACTUS = 
		{
			GENERIC = "Wolfgang not like sharp plant.",
			PICKED = "Ha! Is flat plant.",
		},
		CACTUS_MEAT_COOKED = "Is safe now.",
		CACTUS_MEAT = "Spiky plant meat.",
		CACTUS_FLOWER = "Is not worth it.",
		COLDFIRE =
		{
			EMBERS = "The darkness is coming!",
			GENERIC = "Good bye dark times!",
			HIGH = "Is too much fire!",
			LOW = "The fire is not cold enough.",
			NORMAL = "Is good fire!",
			OUT = "Uh oh. It turned off.",
		},
		CATCOON = "Wolfgang does not trust it.",
		CATCOONDEN = 
		{
			GENERIC = "Stump is suspicious.",
			EMPTY = "Wolfgang more comfortable now that stump is empty.",
		},
		CATCOONHAT = "Now Wolfgang not trust himself.",
		COONTAIL = "Wiggly cat part!",
		COOKPOT =
		{
			COOKING_LONG = "This take long time.",
			COOKING_SHORT = "Is almost cook!",
			DONE = "Is time to eat!",
			EMPTY = "Empty pot make Wolfgang think hungry thoughts.",
			BURNT = "Pot is dead.",
		},
		EYEBRELLAHAT =	"Is always looking up.",
		ARMORDRAGONFLY = "Wolfgang not need protection.",
		DRAGON_SCALES = "Glowy scales.",
		DRAGONFLYCHEST = "Chest is not afraid of fire.",
		DECIDUOUSTREE = 
		{
			BURNING = "I broke it.",
			BURNT = "Is small and broken now.",
			CHOPPED = "Ha! I win!",
			GENERIC = "Hello, tree!",
			POISON = "Is big angry tree.",
		},
		ACORN_COOKED = "Wolfgang cook tree out of nut.",
		BIRCHNUTDRAKE = "Is small and angry nut.",
		FARMPLOT =
		{
			GENERIC = "I will grow mighty crops here!",
			GROWING = "Grow my little friends! Grow!",
			NEEDSFERTILIZER = "Dirt is not dirty enough to make plants.",
			BURNT = "No more growing.",
		},
		COLDFIREPIT =
		{
			EMBERS = "The darkness is coming!",
			GENERIC = "Good bye dark times!",
			HIGH = "Is too much fire!",
			LOW = "The fire is not cold enough.",
			NORMAL = "Is good fire!",
			OUT = "Uh oh. It turned off.",
		},
		FIRESUPPRESSOR = 
		{	
			ON = "I can throw better.",
			OFF = "Machine know Wolfgang is stronger.",
			LOWFUEL = "Are you hungry, machine?",
		},
		ICEHAT = "Why put big ice on head?",
		LIGHTNINGGOAT = 
		{
			GENERIC = "Hello, goat.",
			CHARGED = "Is flash before eyes.",
		},
		LIGHTNINGGOATHORN = "Tiny lightning bone.",
		GOATMILK = "Milk for muscles!",
		MEATRACK =
		{
			DONE = "Yum, meaty leather!",
			DRYING = "Dry meaty things! Dry!",
			DRYINGINRAIN = "Go away, rain! Meat is drying!",
			GENERIC = "I can dry meat!",
			BURNT = "Cannot dry meat now.",
		},
		MERMHEAD = 
		{
			GENERIC = "What a handsome devil!",
			BURNT = "Not so nice looking now.",
		},
		MERMHOUSE = 
		{
			GENERIC = "The house was not strong enough.",
			BURNT = "The house was really not strong enough.",
		},
		FLOWERSALAD = "Is not spinach, but maybe still work!",
        ICECREAM = "Well, is Sunday after all.",
        WATERMELONICLE = "Ha! Melon on a stick.",
        TRAILMIX = "Berries and nuts, berries and nuts!",
        HOTCHILI = "Haha, nothing is too spicy for Wolfgang!",
        GUACAMOLE = "Wolfgang does not trust green mush.",
		MOOSE = "Very strange creature.",
		MOOSEEGG = "Breakfast for whole family!",
		MOSSLING = "Mmmm. Is still breakfast, I think.",
		FEATHERFAN = "Ha! Is as big as head!",
		MINIFAN = "It's so twirly when I run! Haha!",
		TROPICALFAN = "Ha! Is as big as head!",
		GOOSE_FEATHER = "Tickle tickle tickle!",
		STAFF_TORNADO = "Spin and spin!",
		PIGHEAD = 
		{	
			GENERIC = "Why long face?",
			BURNT = "Why no face?",
		},
		PIGHOUSE =
		{
			FULL = "Hey! Come out here, pig man!",
			GENERIC = "The door is too small for me.",
			LIGHTSOUT = "Where did he go?",
			BURNT = "Pig home is gone.",
		},
		FERTILIZER = "Bucket full of smelly.",
		RAINOMETER = 
		{	
			GENERIC = "Splish! Splash!",
			BURNT = "Crackle!",
		},
		RAINCOAT = "Dry is nice.",
		RAINHAT = "Is like water off mole's back.",
		RESEARCHLAB = 
		{	
			GENERIC = "I am not sure how I feel about... science.",
			BURNT = "Science not so strong after all.",
		},
		RESEARCHLAB2 = 
		{
			GENERIC = "I am not sure how I feel about... science.",
			BURNT = "Science not so strong after all.",
		},
		RESEARCHLAB3 = 
		{
			GENERIC = "What has Wolfgang done?",
			BURNT = "Well, is over now.",
		},
		RESEARCHLAB4 = 
		{
			GENERIC = "Hat not just for head.",
			BURNT = "Hat also for burning.",
		},
		RESURRECTIONSTATUE = 
		{
			GENERIC = "I'm not going to die.",
			BURNT = "Better him than real life Wolfgang.",
		},
		ROCK_ICE = 
		{
			GENERIC = "Rocks made of water.",
			MELTED = "I cannot grab water.",
		},
		ROCK_ICE_MELTED = "I cannot grab water.",
		ICE = "Good for refreshing snack.",
        REFLECTIVEVEST = "A vest's a vest.",
		HAWAIIANSHIRT = "Is vacation shirt.",
		TENT = 
		{
			GENERIC = "It is time for a mighty nap.",
			BURNT = "Nothing left to nap in.",
		},
		SIESTAHUT = 
		{
			GENERIC = "Napping place.",
			BURNT = "Napping place is gone.",
		},
		TRANSISTOR = "Science bean.",
		TREASURECHEST = 
		{
			GENERIC = "I put stuff there!",
			BURNT = "Nothing will stay inside.",
		},
		TUMBLEWEED = "Come back little tumbling ball!",
		GRASS_UMBRELLA = "I do not like tiny umbrella.",
		PALMLEAF_UMBRELLA = "I do not like tiny umbrella.",
		UNIMPLEMENTED = "I do not trust unfinished business.",
		WALL_HAY = 
		{	
			GENERIC = "Wall is made of grass!",
			BURNT = "Grass burned up!",
		},
		WALL_WOOD = 
		{
			GENERIC = "Hello, pointy sticks!",
			BURNT = "Goodbye, pointy sticks!",
		},
		WARG = "Big puppy!",
		WATERMELON = "So many seeds.",
		WATERMELON_COOKED = "I cook seeds out of melon.",
		WATERMELONHAT = "Why not wear melon on head! Haha!",
		WINTEROMETER = 
		{
			GENERIC = "Cold go up! Red go down!",
			BURNT = "Flames go up! Measure machine go down!",
		},
		HOMESIGN = 
		{
			GENERIC = "Is no time for reading signs!",
			BURNT = "Sign can't be read.",
		},
		BEEBOX =
		{
			GENERIC = "Many bees!",
			READY = "Is ready for harvest!",
			FULLHONEY = "Is ready for harvest!",
			NOHONEY = "It has no honey.",
			SOMEHONEY = "Bees are busy.",
			BURNT = "Bees are burned.",
		},
		LIVINGTREE = "I do not like tree with eyes.",
		ICESTAFF = "Frosted tip.",
		WORMLIGHT = "Pretty light.",
		WORMLIGHT_LESSER = "Nice little light.",
		WORM =
		{
		    PLANT = "Pretty light.",
		    DIRT = "Is dirt moving?",
		    WORM = "Did not expect this!",
		},
		WORMLIGHT_PLANT = "Pretty light.",
		EEL = "I must cook this!",
		EEL_COOKED = "Eel has been cooked.",
		UNAGI = "Food makes me mighty!",
		EYETURRET = "Mighty structure will help me fight!",
		EYETURRET_ITEM = "I must place this.",
		MINOTAURHORN = "Is trophy from mighty foe.",
		MINOTAURCHEST = "Chest have big strong horns.",
		THULECITE_PIECES = "I can smash together to make bigger piece!",
		POND_ALGAE = "Plant is so small! Is funny to me.",
		GREENSTAFF = "This stick has a green gem on it.",
		POTTEDFERN = "It makes me happy.",

		LIGHTER = "Is tiny firestarter!",
		BOOK_BIRDS = "Book reading is for the birds!",
		BOOK_TENTACLES = "Wolfgang will summon many foes to fight!",
		BOOK_GARDENING = "Wolfgang prefers growing muscle mass to flowers.",
		BOOK_SLEEP = "Wolfgang's eyes feel heavy, like dumbells.",
		BOOK_BRIMSTONE = "Tiny book scares Wolfgang!",
		LUCY = "Wolfgang loves a sharp missus.",
		BALLOONS_EMPTY = "Wolfgang will make balloon muscles.",
		SPEAR_WATHGRITHR = "Is a fine weapon.",
		WAXWELLJOURNAL = "Wolfgang is glad he cannot read!",

		ABIGAIL_FLOWER = 
		{ 
			GENERIC = "Is pretty.",
			LONG = "Delicate.",
			MEDIUM = "Little flower gives Wolfgang the... \"heebie jeebies\".",
			SOON = "I do not like it.",
			HAUNTED_POCKET = "Wolfgang is feeling a little squeamish.",
			HAUNTED_GROUND = "Does it want to fight?",

		},

		SLURPER = "No! No! Stay off head!",
		SLURPER_PELT = "It's still moving!",
		SLURPERPELT = "Strange fur clump.",
		ARMORSLURPER = "It moves with my many muscles!",
		ORANGEAMULET = "I can wear it around my neck.",
		YELLOWSTAFF = "Pretty gem sits in stick.",
		TREECLUMP = "Do not block Wolfgang's way!",
		YELLOWGEM = "Pretty rock.",
		ORANGEGEM = "Pretty rock.",
		TELEBASE = 
		{
			VALID = "Glow is good sign.",
			GEMS = "Do not think it working.",
		},
		GEMSOCKET = 
		{
			VALID = "Pretty rock now hovers.",
			GEMS = "Is empty.",
		},
		STAFFLIGHT = "It hurts to touch.",

        ANCIENT_ALTAR =
        {
        	WORKING = "Is nasty, creepy altar.",
        	BROKEN = "Is broken altar.",
        },  
        ANCIENT_ALTAR_BROKEN = "Is broken altar.",

        ANCIENT_STATUE = "Ugly, ugly, ugly.",

        LICHEN = "I'm lichen this!",
		CUTLICHEN = "Tastes terrible.",

        CAVE_BANANA = "Is tasty!",
        CAVE_BANANA_COOKED = "Is warm and tasty!",
        CAVE_BANANA_TREE = "Hello, upside-down tree.",
        CAVE_BANANA_BURNT = "Is crisp.",
        ROCKY = "He is mighty! Like me!",

        BLUEAMULET = "Would make good ice cube!",
		PURPLEAMULET = "This amulet... it frightens Wolfgang.",
		TELESTAFF = "It gives me a headache.",
		MINERHAT = "Lamp for put on head.",
		MONKEY = "Ugly monkey man!",
		MONKEYBARREL = "This... thing. It smells not so good.",

		HOUNDSTOOTH="Puppy tooth!",
		ARMORSNURTLESHELL="Is sticky inside.",
		BAT="Flying mousey!",
		BATBAT = "This club makes me feel funny.",
		BATWING="Is all hairy and gross.",
		BATWING_COOKED="Crispy!",
		BEDROLL_FURRY="So comfy!",
		BUNNYMAN="Hello rabbit!",
		FLOWER_CAVE="Is light plant.",
		FLOWER_CAVE_DOUBLE="Is light plant.",
		FLOWER_CAVE_TRIPLE="Is light plant.",
		GUANO="More poop.",
		LANTERN="It keeps me safe from dark.",
		LIGHTBULB="Is food?",
		MANRABBIT_TAIL="Puffy!",
		MUSHTREE_TALL  ="Big mushtree is big.",
		MUSHTREE_MEDIUM="Mushy bush.",
		MUSHTREE_SMALL ="Mushy shrub.",
		MUSHTREE_TALL=
		{
            GENERIC = "Big mushtree is big.",
            BLOOM = "Woah! It's even bigger!",
        },
		MUSHTREE_MEDIUM=
		{
            GENERIC = "Mushy bush.",
            BLOOM = "It's having fun!",
        },
		MUSHTREE_SMALL=
		{
            GENERIC = "Mushy shrub.",
            BLOOM = "Even smell is strong!",
        },
        MUSHTREE_TALL_WEBBED = "Aw, cheer up!",
        SPORE_TALL = "Is tiny bug?",
        SPORE_MEDIUM = "Is tiny bug?",
        SPORE_SMALL = "Is tiny bug?",
        SPORE_TALL_INV = "I make it my pet.",
        SPORE_MEDIUM_INV = "I make it my pet.",
        SPORE_SMALL_INV = "I make it my pet.",

		SLURTLE="Ha! You are slow!",
		SLURTLE_SHELLPIECES="Is broken.",
		SLURTLEHAT="Keeps my head safe.",
		SLURTLEHOLE="Hole full of slugs.",
		SLURTLESLIME="Boom snot!",
		SNURTLE="Spirally!",
		SPIDER_HIDER="Is scared spider!",
		SPIDER_SPITTER="Ptoo! Ptoo!",
		SPIDERHOLE="Spiders everywhere.",
		STALAGMITE="Is pointy.",
		STALAGMITE_FULL="Is pointy.",
		STALAGMITE_LOW="Is pointy.",
		STALAGMITE_MED="Is pointy.",
		STALAGMITE_TALL="Rock reaching for the roof.",
		STALAGMITE_TALL_FULL="Rock reaching for the roof.",
		STALAGMITE_TALL_LOW="Rock reaching for the roof.",
		STALAGMITE_TALL_MED="Rock reaching for the roof.",

		TURF_CARPETFLOOR = "Step stones.",
		TURF_CHECKERFLOOR = "Step stones.",
		TURF_DIRT = "Step stones.",
		TURF_FOREST = "Step stones.",
		TURF_GRASS = "Step stones.",
		TURF_MARSH = "Step stones.",
		TURF_ROAD = "Step stones.",
		TURF_ROCKY = "Step stones.",
		TURF_SAVANNA = "Step stones.",
		TURF_WOODFLOOR = "Step stones.",

		TURF_CAVE="Step stones.",
		TURF_FUNGUS="Step stones.",
		TURF_SINKHOLE="Step stones.",
		TURF_UNDERROCK="Step stones.",
		TURF_MUD="Step stones.",

		POWCAKE = "Is made of nothings!",
        CAVE_ENTRANCE = 
        {
            GENERIC="Who wants to go in scary cave hole, anyway!",
            OPEN = "World has belly button!",
        },
        CAVE_EXIT = "Is dark and scary down here.",
        CAVE_EXIT = 
        {
            GENERIC = "Please let Wolfgang out!",
            OPEN = "Is dark and scary down here.",
        },
        CAVE_ENTRANCE_RUINS = "Even I am not that mighty.",

		MAXWELLPHONOGRAPH = "Is box that sings!",
		BOOMERANG = "Boom! A rang! Ha!",
		PIGGUARD = "Is bad piggie!",
		ADVENTURE_PORTAL = "Is mouth door! Say \"Ahhhhh!\"",
		AMULET = "Is very pretty.",
		ANIMAL_TRACK = "Animal went this way.",
		ARMORGRASS = "Is prickly.",
		ARMORMARBLE = "I tie rocks to muscles.",
		ARMORWOOD = "Is almost strong as belly!",
		ARMOR_SANITY = "Is like wearing scary little rag!",
		ASH =
		{
			GENERIC = "Is skeleton of fire.",
			REMAINS_GLOMMERFLOWER = "Is burned pieces of flower from I teleport!",
			REMAINS_EYE_BONE = "Is burned pieces of eyebone from I teleport!",
			REMAINS_THINGIE = "Is burned pieces of some thing. Is dead now...",
		},
		AXE = "Chop!",
		BABYBEEFALO = "Baby hair-cow!",
		BACKPACK = "Is for carry more thing.",
		BACONEGGS = "Food has yolk! And meat! More strong!",
		BANDAGE = "I can fix me!",
		BASALT = "Is stronger even than me!",
		BEARDHAIR = "Gross. These are not from my face.",
		BEDROLL_STRAW = "Nap time!",
		BEE =
		{
			GENERIC = "Is fat and angry-looking.",
			HELD = "Is safely in my pocket.",
		},
		BEEFALO =
		{
			FOLLOWER = "Hair-cow follow me!",
			GENERIC = "Is hair-cow thing!",
			NAKED = "Hair-cow has no more hair.",
			SLEEPING = "Hair-cow is sleeping.",
		},
		BEEFALOHAT = "Is good hat!",
		BEEFALOWOOL = "I make clothes of hair-cow.",
		BEEHAT = "Is hat for to protect from stinger bees.",
		BEEHIVE = "Oh, beehive!",
		BEEMINE = "Is ball full of angry bees.",
		BEEMINE_MAXWELL = "Is ball full of angry bitebugs.",
		BERRIES = "Is tasty!",
		BERRIES_COOKED = "Is more tasty!",
		BERRYBUSH =
		{
			BARREN = "I need to poop on it.",
			WITHERED = "Is too hot for bush.",
			GENERIC = "Is full of food-balls!",
			PICKED = "Eating part is gone.",
		},
		BIRDCAGE =
		{
			GENERIC = "Is home for birdies.",
			OCCUPIED = "Hello birdie!",
			SLEEPING = "I should be quiet!",
			HUNGRY = "I hear tiny grumbles!",
			STARVING = "His tiny stomach is empty!",
			DEAD = "Birdie? Are you okay?",
			SKELETON = "He is not okay.",
		},
		BIRDTRAP = "I will catch bird!",
		BIRD_EGG = "Poor birdy.",
		BIRD_EGG_COOKED = "Yum!",
		BISHOP = "Padre!",
		BISHOP_CHARGE_HIT = "Rrrraa!",
		BLOWDART_FIRE = "Careful, Wolfgang.",
		BLOWDART_SLEEP = "Dart do sleeping to enemies.",
		BLOWDART_PIPE = "Dart do pain to enemies.",
		BLUEGEM = "Pretty rock.",
		BLUEPRINT = "Pretty pictures!",
		BELL_BLUEPRINT = "Pretty pictures!",
		BLUE_CAP = "Is good for me, I think.",
		BLUE_CAP_COOKED = "Is not same.",
		BLUE_MUSHROOM =
		{
			GENERIC = "Is mushy room.",
			INGROUND = "Mushy room is hiding!",
			PICKED = "I already took that mushy room.",
		},
		BOARDS = "I break log to make board!",
		BONESTEW = "Is stew full of strong meat.",
		BUGNET = "Catch bugs.",
		BUSHHAT = "I am so sneaky!",
		BUTTER = "Is buttery, and taste like insect.",
		BUTTERFLY =
		{
			GENERIC = "Is pretty flutterby!",
			HELD = "My pet!",
		},
		BUTTERFLYMUFFIN = "Wolfgang did not know about bug muffin. I will taste.",
		BUTTERFLYWINGS = "No fly without wings!",
		CAMPFIRE =
		{
			EMBERS = "The darkness is coming!",
			GENERIC = "Good bye dark times!",
			HIGH = "Is too much fire!",
			LOW = "The fire is not hot enough.",
			NORMAL = "Is good fire!",
			OUT = "Uh oh. It turned off.",
		},
		CANE = "I can walk AND hit things!",
		CARROT = "Is food. I guess.",
		CARROT_COOKED = "Is not more like meat after do cooking.",
		CARROT_PLANTED = "Is hiding?",
		CARROT_SEEDS = "Seeds is too small.",
		CAVE_FERN = "Pretty plant!",
		CHARCOAL = "Is like holding tiny dead tree.",
        CHESSJUNK1 = "Metal junk.",
        CHESSJUNK2 = "Metal junk.",
        CHESSJUNK3 = "Metal junk.",
		CHESTER = "Strange box with legs.",
		CHESTER_EYEBONE =
		{
			GENERIC = "It is eye bone. Eye bone connect to face bone.",
			WAITING = "It sleeps now.",
		},
		COOKEDMEAT = "I made meat good with fire!",
		COOKEDMONSTERMEAT = "I still do not want to eat this.",
		COOKEDSMALLMEAT = "It is even smaller cooked!",
		CORN = "Is corn. What expect?",
		CORN_COOKED = "Pop pop pop! Ha ha, funny corn.",
		CORN_SEEDS = "Is seeds for grow corn.",
		CROW =
		{
			GENERIC = "I do not like birds. Too fragile.",
			HELD = "He is squawky.",
		},
		CUTGRASS = "I made a pile of grass.",
		CUTREEDS = "I made a clump of reeds.",
		CUTSTONE = "I crush rock to make brick!",
		DEADLYFEAST = "Look like evil food.",
		DEERCLOPS = "He looks mightier than me!",
		DEERCLOPS_EYEBALL = "Yuck yuck yuck!",
		DEPLETED_GRASS =
		{
			GENERIC = "Is tuft of grass.",
		},
		DIRTPILE = "Dirty dirt.",
		DIVININGROD =
		{
			COLD = "The robot box is talking.",
			GENERIC = "Is robot box.",
			HOT = "Robot box is scaring me!",
			WARM = "Ha! That is good one, robot box!",
			WARMER = "Robot box is getting angry...",
		},
		DIVININGRODBASE =
		{
			GENERIC = "What is purpose?",
			READY = "Rod thing need key to make start.",
			UNLOCKED = "Rod thing is on!",
		},
		DIVININGRODSTART = "Is funny rod thing.",
		DRAGONFLY = "I confuse... Is dragonfly, or dragon-fly?",
		LAVASPIT = 
		{
			HOT = "Is hot mouth germs.",
			COOL = "Is cold, hard mouth germs.",
		},
		LAVA_POND = "Is not time for swimming!",
		LAVAE = "I must run!",
		LAVAE_PET = 
		{
			STARVING = "Tiny baby is starving!",
			HUNGRY = "Tiny baby is hungry.",
			CONTENT = "Tiny baby looks content.",
			GENERIC = "Tiny baby seems happy.",
		},
		LAVAE_EGG = 
		{
			GENERIC = "Is made of rock?",
		},
		LAVAE_EGG_CRACKED =
		{
			COLD = "Little egg is shivering.",
			COMFY = "Little egg... seems comfortable.",
		},
		LAVAE_TOOTH = "What a mighty tooth!",

		DRAGONFRUIT = "Is funny-looking fruit.",
		DRAGONFRUIT_COOKED = "Is cooked but still look funny.",
		DRAGONFRUIT_SEEDS = "Could use to grow funny fruit, maybe.",
		DRAGONPIE = "Pie made of funny red fruit.",
		DRUMSTICK = "Leg meat for make legs more strong.",
		DRUMSTICK_COOKED = "Eat off bone is good.",
		DUG_BERRYBUSH = "He is cold and lonely.",
		DUG_GRASS = "He is cold and lonely.",
		DUG_MARSH_BUSH = "He is cold and lonely.",
		DUG_SAPLING = "He is cold and lonely.",
		DURIAN = "Is spiky smelly fruit.",
		DURIAN_COOKED = "Now is hot spiky smelly fruit.",
		DURIAN_SEEDS = "Tiny baby spiky fruit plant.",
		EARMUFFSHAT = "Now I look like little bunny!",
		EARMUFFHAT = "Now I look like little bunny!",
		EGGPLANT = "Is not egg!",
		EGGPLANT_COOKED = "Has no yolk! Yolk is strongest part!",
		EGGPLANT_SEEDS = "Teensy fake egg plant.",
		STUFFEDEGGPLANT = "I make yolk of other foods.",
		ACORN = 
		{
		    GENERIC = "I could crush this tree-seed with my hands!",
		    PLANTED = "It will be tree soon.",
		},
		EVERGREEN =
		{
			BURNING = "I broke it.",
			BURNT = "Is small and broken now.",
			CHOPPED = "Ha! I win!",
			GENERIC = "Hello, tree!",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "I broke it.",
			BURNT = "Is small and broken now.",
			CHOPPED = "Ha! I win!",
			GENERIC = "Cheer up, tree!",
		},
		EYEPLANT = "They are not what they seem.",
		FEATHERHAT = "Is silly hat of feather. Is Wolfgang bird now?",
		FEATHER_CROW = "Is feather of bird black.",
		FEATHER_ROBIN = "Is feather of bird red.",
		FEATHER_ROBIN_WINTER = "Is feather of bird white.",
		FEM_PUPPET = "Scary chair scares her!",
		FIREFLIES =
		{
			GENERIC = "Sparkly!",
			HELD = "My pocket is sparkles!",
		},
		FIREHOUND = "Bark!",
		FIREPIT =
		{
			EMBERS = "The darkness is coming!",
			GENERIC = "Good bye dark times!",
			HIGH = "Is too much fire!",
			LOW = "The fire is not hot enough.",
			NORMAL = "Is good fire!",
			OUT = "Uh oh. It turned off.",
		},
		FIRESTAFF = "Is staff for make fire. Careful, Wolfgang.",
		FISH = "Is fishy.",
		FISHINGROD = "Is for get fishy from pond place.",
		FISHSTICKS = "Ha ha, is funny name.",
		FISHTACOS = "Wolfgang hope is not too spicy.",
		FISH_MED = "Is dead.",
		FISH_MED_COOKED = "Meat from water still make Wolfgang strong.",
		FISH_COOKED = "Meat from water still make Wolfgang strong.",
		FLINT = "Is rock, but eh, pointy.",
		FLOWER = "They are very pretty.",
		FLOWER_WITHERED = "Aw, this one is sad.",
		FLOWERHAT = "Is so pretty!",
		FLOWER_EVIL = "Is not potato.",
		FOLIAGE = "I killed the pretty plant.",
		FOOTBALLHELMET = "Is hat for make tackling.",
		FROG =
		{
			DEAD = "Is delicacy in my country.",
			GENERIC = "Hey little froggy, froggy.",
			SLEEPING = "Is asleep.",
		},
		FROGLEGS = "Is delicacy in my country!",
		FROGGLEBUNWICH = "Is sandwich with tasty leg meat.",
		FROGLEGS_COOKED = "Is mostly taste like chicken.",
		FRUITMEDLEY = "Is cup of teensy fruits.",
		GEARS = "Ah ha! Who is bigger muscles now?",
		GHOST = "Aaaaaaaaaaah!",
        GHOST_SAILOR = "Eeeeeeeeeeee!",
		GOLDENAXE = "Fancy axe more good for chop.",
		GOLDENPICKAXE = "Fancy pickaxe do better smash.",
		GOLDENPITCHFORK = "Fancy pitchfork good for stab ground.",
		GOLDENSHOVEL = "Fancy shovel is good hole maker.",
		GOLDNUGGET = "Money is for tiny men!",
		GRASS =
		{
			BARREN = "It needs poop.",
			WITHERED = "Grass has been defeated by heat.",
			BURNING = "Not good!",
			GENERIC = "Is grass.",
			PICKED = "The grass has been defeated!",
		},
		GREEN_CAP = "Is for salads. Blech.",
		GREEN_CAP_COOKED = "Is not same.",
		GREEN_MUSHROOM =
		{
			GENERIC = "Is mushy room.",
			INGROUND = "Mushy room is hiding!",
			PICKED = "I already took that mushy room.",
		},
		GUNPOWDER = "Boom pepper!",
		HAMBAT = "Is still good.",
		HAMMER = "Needs sickle!",
		HEALINGSALVE = "It makes me feel alive!",
		HEATROCK =
		{
			FROZEN = "Brrr! Is cold rock!",
			COLD = "Rock is a little bit cold.",
			GENERIC = "This round rock is like my head!",
			WARM = "Is pretty normal rock.",
			HOT = "Is hot enough for Wolfgang!",
		},
		HONEY = "Is yum!",
		HONEYCOMB = "Bee used to live inside.",
		HONEYHAM = "Big meat with sweet is good meat.",
		HONEYNUGGETS = "Small meats with sweet still is good meat.",
		HORN = "Is hair-cow horn. Wolfgang hear hair-cow.",
		HOUND = "Woof!",
		HOUNDMOUND = "Is house of bones.",
		HOUNDBONE = "Wimpy woof dog was not strong enough.",
		ICEBOX = "Box what makes cold!",
		ICEHOUND = "Bow wow!",
		INSANITYROCK =
		{
			ACTIVE = "Is in my way.",
			INACTIVE = "Hah. I step over tiny obstacle.",
		},
		JAMMYPRESERVES = "Oozes like tiny enemy I crush in hand.",
		KABOBS = "Eat off stick is good.",
		KILLERBEE =
		{
			GENERIC = "Angry bee!",
			HELD = "My angry bee!",
		},
		KNIGHT = "Horsey horse!",
		KOALEFANT_SUMMER = "Nose meat!",
		KOALEFANT_WINTER = "So soft, I want to squish it!",
		KRAMPUS = "Scary goat man! Run!",
		KRAMPUS_SACK = "I have goat man's sack.",
		LEIF = "Wood man!",
		LEIF_SPARSE = "Wood man!",
		LIGHTNING_ROD =
		{
			CHARGED = "Ooooh, sparks!",
			GENERIC = "Is wire in sky!",
		},
		LITTLE_WALRUS = "You think you are mightier than old man?",
		LIVINGLOG = "Creepy face log!",
		LOCKEDWES = "Is puny man trapped by statue men.",
		LOG = "Is thick like my arm.",
		LOG =
		{
			BURNING = "When I stick my hand over it, it tickles.",
			GENERIC = "Remains of tree-fights!",
		},
		LUREPLANT = "You cannot fool Wolfgang!",
		LUREPLANTBULB = "Ah ha! Who is tricky now?",
		MALE_PUPPET = "Scary chair scares him!",
		MANDRAKE =
		{
			DEAD = "Little plant man is died!",
			GENERIC = "Is strange plant.",
			PICKED = "Little plant man friend!",
		},
		COOKEDMANDRAKE = "Little plant man is food?",
		MANDRAKESOUP = "Little plant man is for make soup!",
		MARBLE = "I can lift!",
		MARBLEPILLAR = "Is too heavy to lift.",
		MARBLETREE = "Do not try punch tree.",
		MARSH_BUSH =
		{
			BURNING = "Uh oh. Spiky fire.",
			GENERIC = "Is thorny.",
			PICKED = "Thorns hurt.",
		},
		BURNT_MARSH_BUSH = "Is burnt now.",
		MARSH_PLANT = "Is plant.",
		MARSH_TREE =
		{
			BURNING = "I burn the spikes!",
			BURNT = "Is spiky and black now.",
			CHOPPED = "I chop the spikes off!",
			GENERIC = "Is spiky.",
		},
		MAXWELL = "A fancy suit is no match for my muscles!",
		MAXWELLHEAD = "Scary head is twelve feet tall!",
		MAXWELLLIGHT = "Scary light!",
		MAXWELLLOCK = "Scary lock!",
		MAXWELLTHRONE = "Scary chair!",
		MEAT = "Meat makes me strong!",
		MEATBALLS = "Ball of meats make me strong!",
		MEAT_DRIED = "Look like leather, taste like meat.",
		MERM = "Is fishy man!",
		MONSTERLASAGNA = "Taste like hairs and meats with noodle.",
		MONSTERMEAT = "It is not looking like food.",
		MONSTERMEAT_DRIED = "Look like leather, taste like leather.",
		MOSQUITO =
		{
			GENERIC = "Reminds me of uncle!",
			HELD = "No more blood for you!",
		},
		MOSQUITOSACK = "Uncle did not have gut like this.",
		MOUND =
		{
			DUG = "I am sorry, dead peoples.",
			GENERIC = "Scary! Is probably full of bones!",
		},
		NIGHTLIGHT = "Is strange glow.",
		NIGHTMAREFUEL = "Scary stuff.",
		NIGHTSWORD = "Is real? Is not real? Is sharp!",
		NITRE = "Is rock, but different.",
		ONEMANBAND = "Is big and loud. I like!",
		PANDORASCHEST = "Fancy box!",
		PANFLUTE = "I can play folk song.",
		PAPYRUS = "Is like paper.",
		PENGUIN = "Funny walking birds!",
		PERD = "Dumb bird is take all berries!",
		PEROGIES = "Wolfgang love pierogi!",
		PETALS = "These smell nice.",
		PETALS_EVIL = "They make my brain hurt.",
		PHLEGM = "A ha ha ha! Boogers! Oh ho ho!",
		PICKAXE = "Pick!",
		PIGGYBACK = "Smelly bag!",
		PIGKING = "Ha! Is good people!",
		PIGMAN =
		{
			DEAD = "No! The pig is dead!",
			FOLLOWER = "Is friend now!",
			GENERIC = "Hello pig. How are you?",
			GUARD = "Does he even lift?",
			WEREPIG = "Angry piggie!",
		},
		PIGSKIN = "Why long butt? Ha ha, Wolfgang is funny man.",
		PIGTORCH = "How is fire made?",
		PINECONE = 
		{
		    GENERIC = "I could crush this tree-seed with my hands!",
		    PLANTED = "It will be tree soon.",
		},
		PINECONE_SAPLING = "It will be tree soon.",
        LUMPY_SAPLING = "It pushed right up from the dirt!",
		PITCHFORK = "Reminds me of childhood.",
		PLANTMEAT = "What is this? Meat for baby man?",
		PLANTMEAT_COOKED = "Is slightly better now.",
		PLANT_NORMAL =
		{
			GENERIC = "Leafy!",
			GROWING = "Is still growing.",
			READY = "Mmmm. Is tasty now.",
			WITHERED = "Is sad and dried plant.",
		},
		POMEGRANATE = "Look like smartypants brain.",
		POMEGRANATE_COOKED = "Ha ha ha! I cook brain! Not so smart now.",
		POMEGRANATE_SEEDS = "Is piece of brain?",
		POND = "Is all wet.",
		POOP = "Smelly!",
		SCORCHED_SKELETON = "Wolfgang does not like this!!",
		PUMPKIN = "Is big as head of weakling man! Not Wolfgang head.",
		PUMPKINCOOKIE = "Is tasty cookie.",
		PUMPKIN_COOKED = "I cook your head, puny man! I am strongest Wolfgang.",
		PUMPKIN_LANTERN = "Now is actual head! Wolfgang afraid!",
		PUMPKIN_SEEDS = "This grow food size of wimpy head.",
		PURPLEGEM = "Prettier rock.",
		RABBIT =
		{
			GENERIC = "Tiny rabbit! Hide from me!",
			HELD = "He is my friend.",
		},
		RABBITHOLE = 
		{
			GENERIC = "You can not hide forever, jumping meat!",
			SPRING = "Is busy time in rabbit home.",
		},
		RATATOUILLE = "Is food. Sort of.",
		RAZOR = "My skin is too strong for hairs!",
		REDGEM = "Pretty rock.",
		RED_CAP = "Oh! Is Pretty and shiny!",
		RED_CAP_COOKED = "Is not same.",
		RED_MUSHROOM =
		{
			GENERIC = "Is mushy room.",
			INGROUND = "Mushy room is hiding!",
			PICKED = "I already took that mushy room.",
		},
		REEDS =
		{
			BURNING = "Not good!",
			GENERIC = "Is watery grass.",
			PICKED = "I have beaten the reeds!",
		},
        RELIC = 
        {
            GENERIC = "House stuff.",
            BROKEN = "Smashed all the way!",
        },
        RUBBLE = "Broken house stuff.",
		RESURRECTIONSTONE = "Hop on rock!",
		ROBIN =
		{
			GENERIC = "Is pretty red color bird.",
			HELD = "Is happy bird in pocket.",
		},
		MOOSE_NESTING_GROUND = "Is big bird baby bed!",
		ROBIN_WINTER =
		{
			GENERIC = "Is pretty white color bird.",
			HELD = "Is fluffy bird. Nice bird.",
		},
		ROBOT_PUPPET = "Scary chair scare it!",
		ROCK_LIGHT =
		{
			GENERIC = "A pile of crusty rocks!",
			OUT = "Ha! More thing to smash!",
			LOW = "Is getting cold.",
			NORMAL = "Liquid fire!",
        },
		ROCK = "Is hard! Like me!",
		ROCKS = "Is rock. What you not get?",
        ROOK = "This one jumps the queen!",
		ROPE = "Strong! Like me!",
		ROTTENEGG = "Stinky!",
		SANITYROCK =
		{
			ACTIVE = "Is beautiful!",
			INACTIVE = "Is hiding underground.",
		},
		SAPLING =
		{
			BURNING = "Oops.",
			WITHERED = "Puny tree could not take heat.",
			GENERIC = "Puny tree! I am stronger than you!",
			PICKED = "Ha! Ha! Ha! Tree is floppy!",
		},
		SEEDS = "Too small to eat.",
		SEEDS_COOKED = "Fire make bigger, can eat now.",
		SEWING_KIT = "Is pokey!",
		SHOVEL = "Dirt spoon!",
		SILK = "Is too fancy.",
		SKELETON = "Not enough muscle.",
		SKELETON_PLAYER = "Where did all muscles go?!",
		SKULLCHEST = "This man had big head!",
		SMALLBIRD =
		{
			GENERIC = "Is very small bird.",
			HUNGRY = "Small bird is hungry.",
			STARVING = "Small bird will die from starving.",
		},
		SMALLMEAT = "I need more meat!",
		SMALLMEAT_DRIED = "Look like leather, taste like meat.",
		SPAT = "Look so friendly and cuddly.",
		SPEAR = "It gave me a sliver.",
		SPIDER =
		{
			DEAD = "Is made of sticky goo!",
			GENERIC = "He has scary face!",
			SLEEPING = "Walk quiet, he might not see me.",
		},
		SPIDERDEN = "The bugs are hiding in there.",
		SPIDEREGGSACK = "Nasty spider eggs.",
		SPIDERGLAND = "Squishy and wobbly!",
		SPIDERHAT = "Is like smooch from giant bug.",
		SPIDERQUEEN = "Oh no! Walking bug-house!",
		SPIDER_WARRIOR =
		{
			DEAD = "Not scary now!",
			GENERIC = "This one extra scary.",
			SLEEPING = "I think not smart to poke it.",
		},
		SPOILED_FOOD = "Is ball of yuck!",
		STATUEHARP = "Where is pretty music?",
		STATUEMAXWELL = "Man is rock now! Very tricky...",
		STEELWOOL = "Is like my arm hair.",
		STINGER = "Is sharp like skewer!",
		STRAWHAT = "Is good hat!",
		SUNKBOAT = "Is broken!",
		SWEATERVEST = "Is vest with pattern for fancy man.",
		TAFFY = "Is taffy for crushing!",
		TALLBIRD = "Is tallest bird!",
		TALLBIRDEGG = "There is bird inside.",
		TALLBIRDEGG_COOKED = "Cooked bird. Good for breakfast!",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "Bird like ice cube!",
			GENERIC = "Little bird is trying to get out.",
			HOT = "Is too hot for little bird!",
			LONG = "I wait for bird.",
			SHORT = "Bird comes soon.",
		},
		TALLBIRDNEST =
		{
			GENERIC = "Is big egg!",
			PICKED = "Is nest of emptiness.",
		},
		TEENBIRD =
		{
			GENERIC = "Hah! Not so tall.",
			HUNGRY = "Is hungry, and noisy.",
			STARVING = "Is hungry, noisy and angry!",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "I do not fear what lies beyond!",
			GENERIC = "Strange rock. Do I sit on?",
			LOCKED = "Something missing still.",
			PARTIAL = "Is coming together now.",
		},
		TELEPORTATO_BOX = "Has little lever.",
		TELEPORTATO_CRANK = "Bendy thing is made of metal!",
		TELEPORTATO_POTATO = "Ha ha! Ha ha! What ugly potato!",
		TELEPORTATO_RING = "I will bend into perfect circle!",
		TENTACLE = "Skinny monster!",
		TENTACLESPOTS = "Yuck! Slimy!",
        TENTACLESPIKE = "Perfect for sticking!",
		TENTACLE_PILLAR_HOLE = "You run away from mighty Wolfgang?",
		TENTACLE_PILLAR = "Lots of little friends!",
		TENTACLE_PILLAR_ARM = "Tiny tentacle baby thing! Ha!",
		TENTACLE_GARDEN = "Hmmmm, suspicious!",
		TOPHAT = "Is good hat!",
		TORCH = "I attack night with fire stick.",
		TRAP = "No trap can hold me!",
		TRAP_TEETH = "It bites bottoms from below!",
		TRAP_TEETH_MAXWELL = "Whoever put this is bad fella!",
		TRINKET_1 = "Glob of glass!",
		TRINKET_10 = "Is pearly chompers!",
		TRINKET_11 = "Is very strange!",
		TRINKET_12 = "Yuck.",
		TRINKET_2 = "Fake bless you.",
		TRINKET_3 = "Is knot what Wolfgang expected.",
		TRINKET_4 = "Is junk, I think.",
		TRINKET_5 = "What is do?",
		TRINKET_6 = "Robot bits.",
		TRINKET_7 = "Ball goes in wood hole.",
		TRINKET_8 = "Hardened, like Wolfgang.",
		TRINKET_9 = "Tiny little buttons.",
		TRUNKVEST_SUMMER = "Is warm fuzzy nose.",
		TRUNKVEST_WINTER = "Cozy nosy!",
		TRUNK_COOKED = "Is cooked nose.",
		TRUNK_SUMMER = "Is floppy nose.",
		TRUNK_WINTER = "Is floppy hairy nose.",
		TURKEYDINNER = "Is good feast of bird meat.",
		TWIGS = "Puny twigs! I can break them!",
		UMBRELLA = "The rain hurts my mighty skin.",
		WAFFLES = "Why does bread have holes?",
		WALL_HAY_ITEM = "Scratchy straws!",
		WALL_STONE = "Wall is strong like me!",
		WALL_STONE_ITEM = "Piles of rocks!",
		WALL_RUINS = "Old wall is strong!",
		WALL_RUINS_ITEM = "Stack of old rocks!",
		WALL_WOOD_ITEM = "Pokey sticks!",
		WALL_MOONROCK = "Rock of moon protects Wolfgang.",
		WALL_MOONROCK_ITEM = "Can build with power of moon!",
		WALRUS = "Ha ha. Is blubbery flubbery man.",
		WALRUSHAT = "Sea cow man hat!",
		WALRUS_CAMP =
		{
			EMPTY = "Is locked.",
			GENERIC = "How do they all fit?",
		},
		WALRUS_TUSK = "Sea cow man tooth!",
		WARDROBE = 
		{
			GENERIC = "Box of clothes!",
            BURNING = "Box of fire!",
			BURNT = "Box all gone.",
		},
		WARG = "Big puppy!",
		WASPHIVE = "Mind says no. Muscles say yes!",
		WETGOOP = "Wolfgang ruin food!",
		WINTERHAT = "It make ears happy in cold!",
		WORMHOLE =
		{
			GENERIC = "Like soft pillow, growing on ground.",
			OPEN = "It can not harm this man!",
		},
 		WORMHOLE_LIMITED = "Is not looking very good.",
        ARMORRUINS = "Protect me? I don't need it!",
        BISHOP_NIGHTMARE = "Is angry man. Should relax.",
        GREENAMULET = "What is this thing?", 
        GREENGEM = "Is pretty and not be crushed. Like me!",
        KNIGHT_NIGHTMARE = "Funny metal man.",
        MINOTAUR = "Strong! Like me! I like him!",    
        MULTITOOL_AXE_PICKAXE = "Chop and dig! I can do that all day.",
        NIGHTMARELIGHT = "Is light, but not good light.",
        NIGHTMARE_TIMEPIECE =
        {
            WARN = "The bad light comes soon.",  
            WAXING = "The bad light is here and getting stronger.", 
            STEADY = "I think bad light not get stronger.", 
            WANING = "Bad light time is ending.", 
            DAWN = "Good time is soon.", 
            CALM = "No bad light.", 
            NOMAGIC = "Is safe from bad light.", 
        },
        ORANGESTAFF = "Better to walk I think.",  
        ROOK_NIGHTMARE = "Is no match for my mighty chest!",
        RELIC = "Is junk?",
        RUINS_RUBBLE = "I will make better with crushing.",  
        RUINS_BAT = "Is creepy.",
        RUINSHAT = "Is hat for king.",
        SPIDER_DROPPER = "Scary spider from above.", 
        THULECITE = "Is pretty rock.",
        YELLOWAMULET = "Is glowing yellow.",    
		ACCOMPLISHMENT_SHRINE = "I will defeat you, tiny arrow!",   

		WOODLEGS_CAGE = "Is locked.",
		AERODYNAMICHAT = "Keeps mighty legs free to run!",
		ANTIVENOM = "Wolfgang will flex poison out of veins!",
		ARMORCACTUS = "Hah! Try hit Wolfgang now.",
		ARMORLIMESTONE = "This mighty armor will protect me!",
		ARMOROBSIDIAN = "Is cheap trick, but Wolfgang like!",
		ARMORSEASHELL = "Try your dirty tricks now, poison creatures.",
		ARMOR_LIFEJACKET = "Big seawater will not take Wolfgang now!",
		ARMOR_SNAKESKIN = "Is made to show my mighty muscles.",
		ARMOR_WINDBREAKER = "Wolfgang master of breaking wind!",
		ARMOUREDBOAT = "You are mighty, just like me.",
		BALLPHIN = "Come and fight with me, sea-friends!", 
		BAMBOO = "Very mighty building material!",
		BAMBOOTREE =
		{
			BURNT = "Is not very mighty now.",
			CHOPPED = "I hope is fast growing.",
			GENERIC = "I will harvest you soon, mighty plant!",
		},
		BERMUDATRIANGLE = "Is give me uneasy feelings.",
		BIOLUMINESCENCE = "Pretty sea-lights!",
		BLOWDART_FLUP = "Is workout for my powerful lungs!",
		BLUBBER = "Is not muscle.",
		BLUBBERSUIT = "Would rather wear a muscle suit!",
		BOAT = "Mighty vessel fights the waters.",
		BOATCANNON = "Is the mightiest weapon!",
		BOATREPAIRKIT = "Restore my mighty vessel!",
		BOAT_LANTERN = "Is safer light.",
		BOAT_TORCH = "Flame on boat is good idea!",
		BOTTLELANTERN = "Is good way to keep darkness back.",
		BRAINJELLYHAT = "Agh! Is making Wolfgang think!",
		BUOY = "Ahhh, is marking something.",
		BURIEDTREASURE = "Is mine!",
		BUSH_VINE =
		{
			BURNT = "Ash.",
			CHOPPED = "I won. You lost.",
			GENERIC = "This is bush. Of vines.",
		},
		CAPTAINHAT = "Look at Wolfgang! He is captain now!",
		CARGOBOAT = "What a mighty storage hold!",
		CHIMINEA = "Be safe from wind, little fire.",
		CLOTHSAIL = "I will capture you, wind!",
		COCONADE =
		{
			BURNING = "Is burning up quickly.",
			GENERIC = "So much power!",
		},
		COCONUT = 
		{
		    GENERIC = "Wolfgang will crush with bare hands.",
		    PLANTED = "Is tiny tree! Very small!",
		},
		COCONUT_COOKED = "Coconut is cooked.",
		COCONUT_HALVED = "Wolfgang had no problem smacking hard shell apart.",
		COFFEE = "Strong, like Wolfgang!",
		COFFEEBEANS = "Tiny beans give Wolfgang strength!",
		COFFEEBEANS_COOKED = "Is bitter beans!",
		COFFEEBUSH =
		{
			BARREN = "Where did all tasty beans go?",
			GENERIC = "Coffee bush is proud, strong.",
			PICKED = "Rest now, friend.",
			WITHERED = "Is on death's door.",
		},
		CORAL = "Is very pretty! Will it crush?",
		CORALREEF = "Is so fragile!",
		CORAL_BRAIN = "Heh heh. It squish under Wolfgang's touch.",
		CORAL_BRAIN_ROCK = "Wolfgang's brain will punch this brain.",
		CRAB =
		{
			GENERIC = "If I punch it, it will be food.",
			HIDDEN = "Dun be shellfish.",
		},
		CRABHOLE = "Crabbit is coward.",
		CRATE = "I could smash.",
		CUTLASS = "Wolfgang is ready for battle!",
		DEAD_SWORDFISH = "It was a good fight.",
		DOUBLE_UMBRELLAHAT = "Two umbrellas is better than one.",
		DOYDOY = "Small dumb bird!",
		DOYDOYBABY = "Protect dumb friend, love dumb friend.",
		DOYDOYEGG = "Eat raw, good for mighty muscles!",
		DOYDOYEGG_COOKED = "Stupidly tasty protein.",
		DOYDOYEGG_CRACKED = "I should eat fast before stupid bird comes out.",
		DOYDOYFEATHER = "To remember nice bird by.",
		DOYDOYNEST = "Where dumb friends sleep.",
		DRAGOON = "Is time for flexing contest?",
		DRAGOONDEN = "Wolfgang approves.",
		DRAGOONEGG = "Hatch so we might fight!",
		DRAGOONHEART = "Is mush in my hand.",
		DRAGOONSPIT = "Ha! Wolfgang spit much farther.",
		DUBLOON = "It dents when crushed between Wolfgang's powerful jaws!",
		DUG_BAMBOOTREE = "I will take it with me.",
		DUG_BUSH_VINE = "I will take it with me.",
		DUG_COFFEEBUSH = "It will grow no strong beans like this.",
		DUG_ELEPHANTCACTUS = "I will pick it up with bare hands.",
		EARRING = "Someone drop this, maybe?",
		ELEPHANTCACTUS = "Ouch! Is still sharp.",
		ELEPHANTCACTUS_ACTIVE = "Puny cactus wants to fight me!",
		ELEPHANTCACTUS_STUMP = "It is not dead, only sleeping.",
		FABRIC = "Flimsy cloth-stuffs.",
		FEATHERSAIL = "Wolfgang is master of sea!",
		FISHINHOLE = "Is good place to fish for... fish.",
		FISH_RAW = "Lump of stinky protein.",
		FISH_RAW_SMALL = "Fish lump for eating.",
		FISH_RAW_SMALL_COOKED = "Looks better now.",
		FLAMEGEYSER = "Watch Wolfgang walk over this!",
		FLOTSAM = "Is not a mighty ship.",
		FLUP = "Flup off!",
		FOOTBALLHAT = "It protects my head!",
		FRESHFRUITCREPES = "Manly midmorning brunch.",
		FROG_POISON = "Coward frog!",
		GASHAT = "Little hat is very colorful.",
		GOLDENMACHETE = "Hoighty toighty knife!",
		GRASS_WATER = "Is thirsty grass.",
		HAIL_ICE = "Is cold.",
		HOME = "Is good place to stay.",
		HOUNDFIRE = "Puppy fire!",
		ICEMAKER =
		{
			HIGH = "Machine is doing very good job!",
			LOW = "Little machine looks tired.",
			NORMAL = "Thank you for good ice, machine.",
			OUT = "Small machine is out of juice.",
			VERYLOW = "Machine will not last much longer.",
		},
		INVENTORYGRAVE = "A tiny man came through here.",
		INVENTORYMOUND = "A tiny man came through here.",
		IRONWIND = "Spinny sail!",
		JELLYFISH = "If I punch jelly, it will become jam.",
		JELLYFISH_COOKED = "Jelly looks tasty now.",
		JELLYFISH_DEAD = "It stood no chance against Wolfgang.",
		JELLYFISH_PLANTED = "Can it arm wrestle?",
		JELLYJERKY = "Jerky is tough, like Wolfgang!",
		JUNGLETREE =
		{
			BURNING = "I broke it.",
			BURNT = "Is small and broken now.",
			CHOPPED = "Ha! I win!",
			GENERIC = "Tree is strong and magnificent.",
		},
		JUNGLETREESEED =
        {
            GENERIC = "It might become tree.",
            PLANTED = "It has better chance of being tree now.",
        },
		KNIGHTBOAT = "Let us fight!",
		KRAKEN = "Crummy breadeater!",
		KRAKENCHEST = "It dropped something.",
		KRAKEN_TENTACLE = "You have many arms!",
		LAVAPOOL = "Sad. I forget swim trunks.",
		LIMESTONE = "Corals were crushed to make tiny rock.",
		LIMPETROCK =
		{
			GENERIC = "Looks like tiny snails for eating!",
			PICKED = "Tiny snails are gone for now.",
		},
		LIMPETS = "Is snail? Maybe.",
		LIMPETS_COOKED = "It is slimy going down.",
		TREEGUARD = "Tree man! Fight me!",
		LIVINGJUNGLETREE = "Looks like ordinary tree.",
		LOBSTER = "Wolfgang respects shellbeast's powerful claws.",
		LOBSTERHOLE = "Is home for shellbeasts.",
		LOBSTER_DEAD = "Wolfgang wish he had fearsome hand claws!",
		LOBSTER_DEAD_COOKED = "Is ready to eat now.",
		LOG =
		{
			BURNING = "Is tickly when Wolfgang stick strong hand over it.",
			GENERIC = "The remains of tree-fights!",
		},
		LOGRAFT = "This raft is... not so mighty.",
		LUGGAGECHEST = "Wolfgang will smash and get treasures!",
		MACHETE = "Ah! Very good!",
		MAGIC_SEAL = "Why is sticky?",
		MAGMAROCK = "Is rock left by angry volcano.",
		MAGMAROCK_FULL = "Is rock left by angry volcano.",
		MAGMAROCK_GOLD = "Is shiny volcano rock.",
		MAGMAROCK_GOLD_FULL = "Is shiny volcano rock.",
		MANDRAKE_COOKED = "Little plant man is ready for eating!",
		MANGROVETREE = "Is very thirsty.",
		MANGROVETREE_BURNT = "Could not withstanding even small heat!",
		MARSH_PLANT_TROPICAL = "Puny shrub.",
		MERMFISHER = "Let us fight!",
		MERMHOUSE_FISHER = "Ugly house!",
		MESSAGEBOTTLE = "Wolfgang can't fit meaty hands inside.",
		MESSAGEBOTTLEEMPTY = "Is just a bottle.",
		MONKEYBALL = "Ha ha! Stupid monkey men.",
		MOSQUITOSACK_YELLOW = "Is yellow punching bag.",
		MOSQUITO_POISON = "Fight like real man!",
		MUSSEL = "My muscles are much bigger!",
		MUSSEL_COOKED = "Mussels become protein for muscles!",
		MUSSEL_FARM =
		{
			GENERIC = "Strangely named. They have no muscles.",
			STICKPLANTED = "Pathetic creatures, conquered by my stick!",
		},
		MUSSEL_STICK = "Mussels love little stick.",
		MYSTERYMEAT = "My mighty stomach can handle it!",
		NEEDLESPEAR = "The weapon of a mighty plant!",
		OBSIDIAN = "There is strong fire in this stone.",
		OBSIDIANAXE = "The mightiest of axes!",
		OBSIDIANCOCONADE = "Even more might!",
		OBSIDIANFIREPIT =
		{
			EMBERS = "The darkness is coming!",
			GENERIC = "Wolfgang did good job!",
			HIGH = "Is too much fire!",
			LOW = "The fire is not hot enough.",
			NORMAL = "Hearty fire warms Wolfgang's bones.",
			OUT = "Uh oh. It turned off.",
		},
		OBSIDIANMACHETE = "Is so sharp!",
		OBSIDIAN_WORKBENCH = "Is fire table.",
		OCTOPUSCHEST = "Give Wolfgang your treasures!",
		OCTOPUSKING = "Strong creature! Give Wolfgang many good things!",
		OX = "What a mighty beast!",
		OXHAT = "I have become more mighty!",
		OX_FLUTE = "Wolfgang will play lusty tune.",
		OX_HORN = "Horn of strong ox!",
		PACKIM = "Hello, robust friend!",
		PACKIM_FISHBONE = "Is bone. I like it.",
		PALMLEAF = "Big green leaf.",
		PALMLEAF_HUT = "The great Wolfgang deserves comfort.",
		PALMTREE =
		{
			BURNING = "I broke it.",
			BURNT = "Is small and broken now.",
			CHOPPED = "Ha! I win!",
			GENERIC = "Such jovial tree.",
		},
		PARROT = "Chatty bird!",
		PARROT_PIRATE = "It could maybe be friend?",
		PEACOCK = "Bird is showing off.",
		PEG_LEG = "Is best battle trophy!",
		PIGTENT = "Is tent of pigs.",
		PIKE_SKULL = "Wolfgang not afraid!",
		PIRATEGHOST = "Aaaaaaaaaaahrrrr!!",
		PIRATEHAT = "Ha ha! I like!",
		PIRATEPACK = "Sounds like jingles.",
		PIRATIHATITATOR =
		{
			BURNT = "It does nothing.",
			GENERIC = "Strange contraption.",
		},
		POISONHOLE = "Cowardly hole!",
		PORTAL_SHIPWRECKED = "Where do you go?",
		PRIMEAPE = "Does not look like even match for me.",
		PRIMEAPEBARREL = "Home of tiny monkey men.",
		RAFT = "How will tiny plank support Wolfgang?",
		RAWLING = "Wolfgang plays ball!",
		REDBARREL = "Do not poke barrel.",
		ROCK_CHARCOAL = "Wolfgang rubs it under eyes to scare foes!",
		ROCK_OBSIDIAN = "Very strong rock. Wolfgang would like to have it.",
		ROWBOAT = "I will row with powerful arms!",
		SAIL = "Wolfgang will take to the seas.",
		SAIL_STICK = "Stick makes good sailing!",
		SAND = "When Wolfgang holds it it slips through his large, strong hands.",
		SANDBAG = "Bag soaks up waters.",
		SANDBAGSMALL = "Little bag soaks up waters.",
		SANDBAGSMALL_ITEM = "Is big bag of dirt.",
		SANDBAG_ITEM = "Bag is full of dirt.",
		SANDHILL = "Tiny, crushable hill.",
		SAND_CASTLE =
		{
			GENERIC = "Good for stomping!",
			SAND = "Is more sand than castle.",
		},
		SEAGULL = "It has large mouth. Like me!",
		SEAGULL_WATER = "Resting after good fights, friend?",
		SEASACK = "Wolfgang can carry even more things!",
		SEASHELL = "Tiny shell would crush easily.",
		SEASHELL_BEACHED = "Wolfgang keep bowl of these on table at home.",
		SEATRAP = "Little pincher does not stand a chance.",
		SEAWEED = "A weed, from the sea.",
		SEAWEED_COOKED = "Wolfgang's strong stomach will destroy this!",
		SEAWEED_DRIED = "Is edible.",
		SEAWEED_PLANTED = "Strange leaves from sea.",
		SHADOWSKITTISH_WATER = "I do not like it!",
		SHARKITTEN = "Wolfgang is dog person.",
		SHARKITTENSPAWNER =
		{
			GENERIC = "Is time for cat nap?",
			INACTIVE = "Is just sand.",
		},
		SHARK_FIN = "I lost rest of shark.",
		SHARK_GILLS = "Maybe now Wolfgang breathe underwater? Maybe not.",
		SHARK_TEETHHAT = "Wolfgang's favorite hat!",
		SHARX = "I do not trust these sea-doggies.",
		SHIPWRECKED_ENTRANCE = "Is magical portal. Very sandy...",
		SHIPWRECKED_EXIT = "Is magical portal. Very grassy...",
		SLOTMACHINE = "Wolfgang is gambling man!",
		SNAKE = "I am ready to fight!",
		SNAKEDEN =
		{
			BURNT = "Ash.",
			CHOPPED = "I won. You lost.",
			GENERIC = "This is bush. Of vines.",
		},
		SNAKEOIL = "Good for shining Wolfgang's muscles!",
		SNAKESKIN = "I will use as bandana.",
		SNAKESKINHAT = "Very good.",
		SNAKESKINSAIL = "Skin of dead snake will help me sail.",
		SNAKE_FIRE = "You are slippery snake!",
		SNAKE_POISON = "Poison is weapon of cowards!",
		SOLOFISH = "Face me, fish!",
		SPEARGUN = "Spears will shoot now!",
		SPEAR_LAUNCHER = "Punch from a great distance!",
		SPEAR_OBSIDIAN = "Very strong, warm spear.",
		SPEAR_POISON = "Is not cowardly if I use it.",
		SPOILED_FISH = "Is good no more.",
		STUNGRAY = "Looks smooth. I will pet it!",
		SUNKEN_BOAT =
		{
			ABANDONED = "No one home.",
			GENERIC = "Where is captain?",
		},
		SUNKEN_BOAT_BURNT = "Pile of burnt wood.",
		SUNKEN_BOAT_TRINKET_1 = "Wolfgang loves these!",
		SUNKEN_BOAT_TRINKET_2 = "Wolfgang will not fit!",
		SUNKEN_BOAT_TRINKET_3 = "It is the perfect amount of dampness.",
		SUNKEN_BOAT_TRINKET_4 = "Metal doodad is fun for playtimes.",
		SUNKEN_BOAT_TRINKET_5 = "Tough leather is hard to chew.",
		BANANAPOP = "Wolfgang can eat in one bite!",
		BISQUE = "It will fuel powerful punches!",
		CEVICHE = "It will be better in Wolfgang's belly!",
		SEAFOODGUMBO = "This will make very strong Wolfgang!",
		SURFNTURF = "Very good.",
		SHARKFINSOUP = "Is small shark inside?",
		MONSTERTARTARE = "Blech!",
		LOBSTERDINNER = "A meal fit for Wolfgang!",
		LOBSTERBISQUE = "Seems fancy.",
		JELLYOPOP = "Looks like candy, but tastes like meat!",
		SWEET_POTATO = "Very sweet!",
		SWEET_POTATO_COOKED = "Is ready to eat!",
		SWEET_POTATO_PLANTED = "Potato is strange color inside.",
		SWEET_POTATO_SEEDS = "Seeds would taste better if they were a potato.",
		SWIMMINGHORROR = "If it's a fight you want, Wolfgang will oblige!",
		SWORDFISH = "Wolfgang challenges you to duel!",
		TELEPORTATO_SW_BASE = "Wolfgang must fix it.",
		TELEPORTATO_SW_BOX = "What use is tiny box? Wolfgang would like to know.",
		TELEPORTATO_SW_CRANK = "Wolfgang will hold on to this.",
		TELEPORTATO_SW_POTATO = "Hello, spuddy.",
		TELEPORTATO_SW_RING = "I will carry you.",
		TELESCOPE = "I see far!",
		THATCHPACK = "Wolfgang can carry more on powerful shoulders!",
		TIDALPOOL = "Fishies nibble toes when I stick them in.",
		TIDAL_PLANT = "Is plant.",
		TIGEREYE = "Is giving me dirty look.",
		TIGERSHARK = "I will take you to POUND!",
		TOUCAN = "Bird flees at the sight of Wolfgang.",
		TRAWLNET = "Wolfgang will trap you in his net!",
		TRAWLNETDROPPED =
		{
			GENERIC = "What fishes will I find?",
			SOON = "Is really sinking.",
			SOONISH = "Is sinking.",
		},
		TRIDENT = "I feel like king of sea.",
		TRINKET_13 = "Wolfgang would not like to drink.",
		TRINKET_14 = "Wolfgang does not like that.",
		TRINKET_15 = "It does not fit in Wolfgang's big hands.",
		TRINKET_16 = "I do not know what this is.",
		TRINKET_17 = "Tough leather is hard to chew.",
		TRINKET_18 = "Is broken.",
		TRINKET_19 = "Wolfgang is not eat loose pills.",
		TRINKET_20 = "Wolfgang loves these!",
		TRINKET_21 = "Wolfgang will not fit!",
		TRINKET_22 = "Looks much too dry.",
		TRINKET_23 = "Is very broken.",
		TROPICAL_FISH = "Is yummy looking.",
		TUNACAN = "I will open with bare hands!",
		TURBINE_BLADES = "Blade that does not cut.",
		TURF_SANDY = "Step stones.",
		TURF_ASH = "Step stones.",
		TURF_BEACH = "Step stones.",
		TURF_DESERTDIRT = "Step stones.",
		TURF_FUNGUS_GREEN = "Step stones.",
		TURF_FUNGUS_RED = "Step stones.",
		TURF_JUNGLE = "Step stones.",
		TURF_MAGMAFIELD = "Step stones.",
		TURF_MEADOW = "Step stones.",
		TURF_SNAKESKINFLOOR = "Step stones.",
		TURF_SWAMP = "Step stones.",
		TURF_TIDALMARSH = "Step stones.",
		TURF_VOLCANO = "Step stones.",
		TWISTER = "What might!",
		TWISTER_SEAL = "Ha ha! Is good friend.",
		VENOMGLAND = "Is weapon of cowards.",
		VINE = "For string enemies together.",
		VOLCANO = "Is calling me to fight!",
		VOLCANOSTAFF = "Power of fire mountain is in Wolfgang's hands!",
		VOLCANO_ALTAR =
		{
			GENERIC = "Is not wanting anything right now.",
			OPEN = "Wolfgang is afraid to use.",
		},
		VOLCANO_ALTAR_BROKEN = "This is no more.",
		VOLCANO_ALTAR_TOWER = "Is scary looking.",
		VOLCANO_EXIT = "Goodbye!",
		VOLCANO_SHRUB = "Tree was too weak. Dead now.",
		WALLYINTRO_DEBRIS = "It's lost its battle.",
		WALL_LIMESTONE = "Good, sturdy wall.",
		WALL_LIMESTONE_ITEM = "I will make strong wall.",
		WATERMELON_SEEDS = "Maybe will grow into tasty snacks?",
		WATERYGRAVE = "I do not like this. Is creepy.",
		WHALE_BLUE = "I will eat you!",
		WHALE_BUBBLES = "Large fishie is underneath.",
		WHALE_CARCASS_BLUE = "Well fought, large fish!",
		WHALE_CARCASS_WHITE = "Not-so-great white.",
		WHALE_TRACK = "Massive fish cannot escape me!",
		WHALE_WHITE = "Great white! Fight Wolfgang!",
		WILBUR_CROWN = "Crown is falling apart!",
		WILBUR_UNLOCK = "Welcome, friend! Ha ha!",
		WILDBORE = "I will wrestle you.",
		WILDBOREHEAD = "Very gross!",
		WILDBOREHOUSE = "Puny house could not hold me.",
		WIND_CONCH = "Shell makes scary sounds!",
		WOODLEGS_KEY1 = "Spooky key!",
		WOODLEGS_KEY2 = "Pretty key!",
		WOODLEGS_KEY3 = "Boring key!",
		WRECK = "Not mighty enough to float.",
		CALIFORNIAROLL = "Get in Wolfgang's stomach!",
		
	},
	DESCRIBE_GENERIC = "What is this thing?",
	DESCRIBE_TOODARK = "Help! It is dark!",
	DESCRIBE_SMOLDERING = "Is almost on fire.",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "Not so mighty now!",
	},
}