return {
	ACTIONFAIL =
	{
		SHAVE =
		{
			AWAKEBEEFALO = "I don't think she'd like that.",
			GENERIC = "You can't shave what's not hair.",
			NOBITS = "It's already shorn, eh?",
            REFUSE = "I like my beard.",
		},
		STORE =
		{
			GENERIC = "It's already packed tighter than a Toronto streetcar.",
			NOTALLOWED = "That's probably not the best idea, eh?",
		},
		WRITE =
        {
            GENERIC = "Oh, no thanks. I have terrible writing.",
        },
		RUMMAGE =
        {   
            GENERIC = "Sorry, I can't right now.", 
        },
		COOK =
        {
            GENERIC = "Sorry, I can't cook right now.",
            TOOFAR = "I gotta get closer, eh?",
        },
        CHANGEIN =
        {
            GENERIC = "Ouch. Do I not look skookum enough already?",
            BURNING = "Better it than a tree.",
        },
        GIVE =
        {
            DEAD = "I don't think they... um...",
            SLEEPING = "It's sleeping.",
            BUSY = "I'll try again in a mo'.",
        },
		REPAIRBOAT =
		{
			GENERIC = "I'm afraid I can't.",
		},
		TEACH =
        {
            KNOWN = "I know that already, eh?",
            CANTLEARN = "Err... do you understand this one, 'Luce?",
        },
	},
	ACTIONFAIL_GENERIC = "Sorry, I can't do that.",
	ANNOUNCE_MAGIC_FAIL = "That won't work here, eh.",
	ANNOUNCE_ADVENTUREFAIL = "Oh well. I gave it a good try.",
	ANNOUNCE_BEES = "Bees! Bees!",
	ANNOUNCE_BOOMERANG = "Sorry! Clumsy me!",
	ANNOUNCE_CHARLIE = "Who's there, eh?",
	ANNOUNCE_CHARLIE_ATTACK = "Yeouch! That was rough!",
	ANNOUNCE_COLD = "It's a bit chilly out here!",
	ANNOUNCE_HOT = "It's so hot out here!",
	ANNOUNCE_CRAFTING_FAIL = "I can't do that right now.",
	ANNOUNCE_DEERCLOPS = "What was that?",
	ANNOUNCE_DUSK = "It's almost my bedtime.",
	ANNOUNCE_NOSLEEPONFIRE = "Not sure that's entirely safe.",
	ANNOUNCE_NODANGERSIESTA = "Can't siesta, something's chasing me.",
	ANNOUNCE_NONIGHTSIESTA = "I prefer to siesta between chopping sessions, not at night.",
	ANNOUNCE_NONIGHTSIESTA_CAVE = "I prefer to siesta between chopping sessions, not at night.",
	ANNOUNCE_NOHUNGERSIESTA = "My belly is rumbling. I'd never be able to relax.",
	ANNOUNCE_SHELTER = "Thanks for the shelter, buddy. I'm still gonna chop you.",
	ANNOUNCE_BURNT = "Ouch, that's hot!",
	ANNOUNCE_TOOL_SLIP = "The stuff of nightmares!",
	ANNOUNCE_DAMP = "A bit damp, eh?",
	ANNOUNCE_WET = "Plaid's warm, even when wet.",
	ANNOUNCE_WETTER = "I'm getting quite wet, eh?",
	ANNOUNCE_SOAKED = "Better hold on tight, Lucy.",

	ANNOUNCE_OTHER_WORLD_PLANT = "Wrong kind of soil for this, eh?",

	ANNOUNCE_EAT =
	{
		GENERIC = "Tasty!",
		PAINFUL = "That was past the expiry date.",
		SPOILED = "That was a wee bit manky.",
		STALE = "I got to that one just in time.",
		INVALID = "I don't think my teeth could cut through that.",
		YUCKY = "I'd rather chew on blubber balls.",
	},
	ANNOUNCE_ENTER_DARK = "Who turned out the lights?",
	ANNOUNCE_ENTER_LIGHT = "Brilliance!",
	ANNOUNCE_FREEDOM = "I got out!",
	ANNOUNCE_HOUNDS = "There's something out there.",
	ANNOUNCE_HUNGRY = "I'm getting peckish.",
	ANNOUNCE_HUNT_BEAST_NEARBY = "The beastie is nearby.",
	ANNOUNCE_HUNT_LOST_TRAIL = "I'm more of a woodsman than a hunter anyway.",
	ANNOUNCE_HUNT_LOST_TRAIL_SPRING = "The beastie's tracks washed away.",
	ANNOUNCE_INV_FULL = "I can't carry any more kit.",
	ANNOUNCE_KNOCKEDOUT = "Ow. What was that?",
	ANNOUNCE_MOSQUITOS = "Skeeters!",
	ANNOUNCE_NODANGERSLEEP = "It's too scary out to sleep.",
	ANNOUNCE_NODAYSLEEP = "Only a hoser sleeps during the day.",
	ANNOUNCE_NOHUNGERSLEEP = "My belly is too empty to fall asleep.",
	ANNOUNCE_NO_TRAP = "Close one!",
	ANNOUNCE_PECKED = "Sorry! I'll try harder!",
	ANNOUNCE_QUAKE = "The ground is heaving!",
	ANNOUNCE_THORNS = "Ouch!",
	ANNOUNCE_TORCH_OUT = "My light ran out!",
	ANNOUNCE_FAN_OUT = "I guess I'll just have to suffer now.",
    ANNOUNCE_COMPASS_OUT = "I'll always have the North in my heart.",
	ANNOUNCE_TRAP_WENT_OFF = "Oops!",
	ANNOUNCE_WORMHOLE = "It was gross in there!",
	ANNOUNCE_CANFIX = "\nI think I can fix this!",
	ANNOUNCE_ACCOMPLISHMENT= "Lucy is going to be so proud of me!",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "That's a wrap!",
	ANNOUNCE_INSUFFICIENTFERTILIZER = "Need more poop, eh?",
	ANNOUNCE_LIGHTNING_DAMAGE_AVOIDED = "That tickled a bit, eh?",

	ANNOUNCE_BOAT_DAMAGED = "My boat's pretty banged up, eh?",
	ANNOUNCE_BOAT_SINKING = "I'm aboot to sink!",
	ANNOUNCE_BOAT_SINKING_IMMINENT = "We're goin' down!",
	ANNOUNCE_CRAB_ESCAPE = "It got away.",
	ANNOUNCE_HIGHRESEARCH = "Informative.",
	ANNOUNCE_LOWRESEARCH = "That was barely even worth it, eh?",
	ANNOUNCE_MAPWRAP_LOSECONTROL = "Into waters unknown!",
	ANNOUNCE_MAPWRAP_RETURN = "That was unwise!",
	ANNOUNCE_MAPWRAP_WARN = "I'm leaving charted waters...",
	ANNOUNCE_MESSAGEBOTTLE =
	{
		"The sea has washed away the message.",
	},
	ANNOUNCE_MORETREASURE = "There's more gold to be had!",
	ANNOUNCE_NODAYSLEEP_CAVE = "I'm not feelin' too restful right now.",
	ANNOUNCE_NOWARDROBEONFIRE = "That's okay. I just need a good flannel, anyway.",
	ANNOUNCE_OTHER_WORLD_TREASURE = "I don't believe I can find this here.",
	ANNOUNCE_RESEARCH = "Learnin' keeps your mind sharp. Like an axe.",
	ANNOUNCE_SHARX = "There's a fish nearby... and it's hungry!",
	ANNOUNCE_TRAWL_FULL = "It's time to reel it in!",
	ANNOUNCE_TREASURE = "Here comes the gold rush!",
	ANNOUNCE_UNIMPLEMENTED = "Ouch! I don't think that's ready.",
	ANNOUNCE_VOLCANO_ERUPT = "Ooh, that's some bad weather, eh?",
	ANNOUNCE_WAVE_BOOST = "For the North!",
	ANNOUNCE_WHALE_HUNT_BEAST_NEARBY = "I was born to track beasts!",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL = "I lost the trail. Sorry!",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL_SPRING = "Where did the whale go?!",

	BATTLECRY =
	{
		GENERIC = "Get over here, eh!",
		PIG = "I'll make bacon of you yet!",
		PREY = "This here's the end for you!",
		SPIDER = "For the North!",
		SPIDER_WARRIOR = "Prepare for a choppin'!",
	},
	COMBAT_QUIT =
	{
		GENERIC = "I think that's enough.",
		PIG = "I thought that would go better.",
		PREY = "Sorry, sorry!",
		SPIDER = "Sorry!",
		SPIDER_WARRIOR = "Same time again tomorrow, eh?",
	},
	DESCRIBE =
	{
		PIGMAN =
		{
			FOLLOWER = "We're a team! Yah!",
			GENERIC = "Walking back bacon!",
			GUARD = "That one looks like he means business.",
			WEREPIG = "Happens to the best of us.",
			DEAD = "Not a pig anymore.",
		},
		GLOMMER = "Keep flapping, little guy!",
        GLOMMERFLOWER = 
        {
        	GENERIC = "Even the flower is slimy.",
        	DEAD = "Dead and still slimy.",
        },
        GLOMMERWINGS = "Unsurprisingly, the wings are slimy.",
        GLOMMERFUEL = "Yep, his slime is slimy too.",
        BELL = "I'm amazed it makes such a crisp sound.",
        STATUEGLOMMER = 
        {	
        	GENERIC = "That's a curious statue, eh?",
        	EMPTY = "It had some cool things inside, eh?",
    	},
		WEBBERSKULL = "The skull gives me the willies, too.",
		MOLE =
		{
			HELD = "Want some rocks?",
			UNDERGROUND = "Dig, dig, dig.",
			ABOVEGROUND = "It feels aboot rocks the way I feel aboot trees.",
		},
		MOLEHILL = "I bet it's just a pile of rocks inside.",
		MOLEHAT = "Now featuring night-time chopping!",
		NIGHTSTICK = "That's mighty nifty.",
		RABBITHOUSE=
		{
			GENERIC = "Is it carrot flavoured?",
			BURNT = "Is it roasted carrot flavoured?",
		},
		TURF_DECIDUOUS = "Just some ground, eh?",
		TURF_SANDY = "Just some ground, eh?",
		TURF_BADLANDS = "Just some ground, eh?",

		LAVA_POND_ROCK = "Boulder-dash.",
		LAVA_POND_ROCK2 = "Boulder-dash.",
		LAVA_POND_ROCK3 = "Boulder-dash.",
		LAVA_POND_ROCK4 = "Boulder-dash.",
		LAVA_POND_ROCK5 = "Boulder-dash.",
		LAVA_POND_ROCK6 = "Boulder-dash.",
		LAVA_POND_ROCK7 = "Boulder-dash.",

		BEARGER = "That's a big bear!",
		BEARGERVEST = "Now this is some proper winter gear.",
		CAVE_BANANA_BURNT = "Such a waste.",
		SCORCHED_SKELETON = "Yikes.",
		ICEPACK = "Good for long hikes.",
		BEARGER_FUR = "It's as thick as my head!",
		BIGFOOT = "Watch where you're stepping!",
		BONESHARD = "I wish I knew how to make bread.",
		BUZZARD = "Stay away from my meat snacks!",
		CACTUS = 
		{
			GENERIC = "That's gonna hurt.",
			PICKED = "It certainly did.",
		},
		CACTUS_MEAT_COOKED = "Much better.",
		CACTUS_MEAT = "Would you put nails in your mouth?",
		CACTUS_FLOWER = "It's a wonder anything grows in this climate at all.",
		COLDFIRE =
		{
			EMBERS = "It's almost gone.",
			GENERIC = "This'll make it feel more like home.",
			HIGH = "Uh oh! It's bit high!",
			LOW = "I should probably do something aboot that, eh?",
			NORMAL = "I love a cold fire in the evening.",
			OUT = "It was good while it lasted.",
		},
		CATCOON = "Pests.",
		CATCOONDEN = 
		{
			GENERIC = "Ugh, how many more lives do you have?",
			EMPTY = "Good riddance.",
		},
		CATCOONHAT = "The traditional garb of the woodsman.",
		COONTAIL = "That's the end of that cat's tale.",
		COOKPOT =
		{
			COOKING_LONG = "It'll be a bit longer, eh?",
			COOKING_SHORT = "Oh boy! Here it comes!",
			DONE = "Time for supper!",
			EMPTY = "It seems a waste to just leave it sitting there, empty.",
			BURNT = "Burned to a crisp.",
		},
		EYEBRELLAHAT =	"Always good to have something watching over you.",
		ARMORDRAGONFLY = "Plaid is all the armour I need.",
		DRAGON_SCALES = "I still don't believe in dragons.",
		DRAGONFLYCHEST = "Gaudy if you ask me.",
		DECIDUOUSTREE = 
		{
			BURNING = "Nooo! I could have chopped it!",
			BURNT = "What a waste.",
			CHOPPED = "Ahhhh!",
			GENERIC = "It's calling to me!",
			POISON = "You're due for a chopping.",
		},
		ACORN_COOKED = "What a waste of a perfectly good tree.",
		BIRCHNUTDRAKE = "I'll chop you too!",
		FARMPLOT =
		{
			GENERIC = "I prefer larger plants.",
			GROWING = "They'll never reach chopping size.",
			NEEDSFERTILIZER = "I think it needs some poop.",
			BURNT = "If it was a tree farm, I'd be sad.",
		},
		COLDFIREPIT =
		{
			EMBERS = "I should go chop some wood for that, eh?",
			GENERIC = "It uses wood.",
			HIGH = "I'm using too much wood too fast!",
			LOW = "There should be some wood around here somewhere.",
			NORMAL = "Mmmm. Smells woody.",
			OUT = "If only I had some wood.",
		},
		FIRESUPPRESSOR = 
		{	
			ON = "Save the trees!",
			OFF = "Lazy thing.",
			LOWFUEL = "It craves wood.",
		},
		ICEHAT = "I could chop it if I had to.",
		LIGHTNINGGOAT = 
		{
			GENERIC = "That's a nice pair of horns you've got there.",
			CHARGED = "Nice goat, nice goat!",
		},
		LIGHTNINGGOATHORN = "Your horn is mine.",
		GOATMILK = "I think the electricity curdled it.",
		MEATRACK =
		{
			DONE = "That looks done.",
			DRYING = "This is like watching meat dry.",
			DRYINGINRAIN = "This is like watching meat dry... in the rain.",
			GENERIC = "It's all set up. Just add meat.",
			BURNT = "Its usefulness has dried up.",
		},
		MERMHEAD = 
		{
			GENERIC = "Smells like a factory trawler.",
			BURNT = "Amazingly, it smells even worse now.",
		},
		MERMHOUSE = 
		{
			GENERIC = "They're not the handiest.",
			BURNT = "Couldn't even build a fireproof house.",
		},
		FLOWERSALAD = "Healthy, but not very hardy.",
        ICECREAM = "Only after I've chopped enough!",
        WATERMELONICLE = "Wood AND food?!",
        TRAILMIX = "The perfect snack for a day of chopping.",
        HOTCHILI = "Good after a long day of chopping in the cold.",
        GUACAMOLE = "I'm not sure I trust it.",
		MOOSE = "Whatever it is, it's definitely Canadian.",
		MOOSEEGG = "Well, it lays eggs, apparently.",
		MOSSLING = "Feathery moose baby!",
		FEATHERFAN = "A traditional Canadian fan.",
		TROPICALFAN = "I'm not used to the heat in this place!",
		MINIFAN = "I'm not used to the heat in this place!",
		GOOSE_FEATHER = "Pillowy plumage.",
		STAFF_TORNADO = "I prefer to chop the trees myself.",
		PIGHEAD = 
		{	
			GENERIC = "What a waste of good pork.",
			BURNT = "I'd like to complain to the chef. Politely.",
		},
		PIGHOUSE =
		{
			FULL = "It's bacon-stuffed.",
			GENERIC = "A little duct tape would fix that right up.",
			LIGHTSOUT = "Sorry! I'm not peeping, I swear!",
			BURNT = "A mere shell of its former glory.",
		},
		FERTILIZER = "Poop belongs in a bucket, not on the ground.",
		RAINOMETER = 
		{	
			GENERIC = "Rain makes the trees grow.",
			BURNT = "Its knowledge of rain didn't keep it from being burned.",
		},
		RAINCOAT = "For chopping in the rain.",
		RAINHAT = "Always keep a dry head while chopping.",
		RESEARCHLAB = 
		{	
			GENERIC = "I don't trust all this science stuff.",
			BURNT = "How did it get burned?!",
		},
		RESEARCHLAB2 = 
		{
			GENERIC = "This is getting strange.",
			BURNT = "Well, it obeys some basic laws of physics.",
		},
		RESEARCHLAB3 = 
		{
			GENERIC = "Okay, I kind of get it now.",
			BURNT = "Nope, lost it.",
		},
		RESEARCHLAB4 = 
		{
			GENERIC = "I like to call it the \"Hat Machine\"!",
			BURNT = "This is why I don't use hat warmers.",
		},
		RESURRECTIONSTATUE = 
		{
			GENERIC = "I look good in wood.",
			BURNT = "I don't look as good burnt.",
		},
		ROCK_ICE = 
		{
			GENERIC = "Home sweet home!",
			MELTED = "Back home, they never melt.",
		},
		ROCK_ICE_MELTED = "Back home, they never melt.",
		ICE = "A reminder of home for my pocket.",
        REFLECTIVEVEST = "I'm still not convinced plaid isn't all-weather wear.",
		HAWAIIANSHIRT = "I really prefer plaid.",
		TENT = 
		{
			GENERIC = "I'm used to sleeping in worse.",
			BURNT = "I don't think it can still be considered a tent.",
		},
		SIESTAHUT = 
		{
			GENERIC = "Naps are important during a long day of chopping.",
			BURNT = "It's a husk.",
		},
		TRANSISTOR = "I won't even pretend to know how that works.",
		TREASURECHEST = 
		{
			GENERIC = "Wood is so handy! Look at all the things you can make!",
			BURNT = "I guess wood does have a downside...",
		},
		TUMBLEWEED = "I wish it was sturdier so I could chop it.",
		GRASS_UMBRELLA = "That there could keep my beard moderately dry, eh?",
		PALMLEAF_UMBRELLA = "I think I did a pretty good job on this 'breller.",
		WALL_HAY = 
		{	
			GENERIC = "I could sneeze it over.",
			BURNT = "Well that escalated quickly.",
		},
		WALL_WOOD = 
		{
			GENERIC = "I like the look of that!",
			BURNT = "I miss the old you.",
		},
		WARDROBE = 
        {
        	GENERIC = "It's hard to stay neat and tidy in the woods.",
            BURNING = "Wood is the best at burning.",
        	BURNT = "Not so useful now, eh?",
    	},
		WARG = "That thing could pull a sled by its lonesome.",
		WATERMELON = "How can it be both water and melon?",
		WATERMELON_COOKED = "I'm not sure aboot grilled fruit...",
		WATERMELONHAT = "You can call me Mr. Melon.",
		WINTEROMETER = 
		{
			GENERIC = "We can build these half as tall back home.",
			BURNT = "The ones from home don't burn.",
		},
		WORMLIGHT = "This thing will be useful.",
		WORM =
		{
		    PLANT = "I know a plant when I see one. This's an impostor!",
		    DIRT = "Be wary the moving ground.",
		    WORM = "WOOORM!",
		},
		EEL = "This should cook up nicely.",
		EEL_COOKED = "This cooked up nicely.",
		UNAGI = "It'll fill ya up.",
		EYETURRET = "That'll drive the hosers off.",
		EYETURRET_ITEM = "This needs to be installed properly.",
		MINOTAURHORN = "That's a nice horn, eh.",
		MINOTAURCHEST = "That's a nice chest with horns, eh.",
		THULECITE_PIECES = "It's not wood but it'll do.",
		POND_ALGAE = "Doesn't look edible.",
		GREENSTAFF = "This'll help me dismantle stuff!",
		POTTEDFERN = "It shows my love of plant life.",

		THULECITE = "It's the wood of the caves!",
		ARMORRUINS = "That'll stop the hurt.",
		RUINS_BAT = "Metal on a stick.",
		RUINSHAT = "It's no toque, but it'll do.",
		NIGHTMARE_TIMEPIECE = --Keeps track of the nightmare cycle
		{
			CALM = "I think it's off.",	--calm phase
			WARN = "This thing just turned on!",	--Before nightmare
			WAXING = "It's vibrating!", --Nightmare Phase first 33%
			STEADY = "It's going crazy!", --Nightmare 33% - 66%
			WANING = "It's settling down.", --Nightmare 66% +
			DAWN = "It's nearly still.", --After nightmare
			NOMAGIC = "I think it's off.", --Place with no nightmare cycle.
		},
		BISHOP_NIGHTMARE = "I can see the internal workings!",
		ROOK_NIGHTMARE = "The gears are spilling out.",
		KNIGHT_NIGHTMARE = "Doesn't look to be in the best of shape.",
		MINOTAUR = "Another poor soul with a curse.",	--Monster in labyrinth
		SPIDER_DROPPER = "They're smart to live away from the corruption.",	--White spider that comes from the roof
		NIGHTMARELIGHT = "They should have used wood.",	--Lights that activate during nightmare.
		RELIC = "Piece of furniture.",	--Fixed relic
		RUINS_RUBBLE = "All busted up.",	--Broken relic
		MULTITOOL_AXE_PICKAXE = "It's... it's beautiful.",	--Works as axe and pickaxe
		GREENGEM = "How flashy.",
		ORANGESTAFF = "This will help me get around quickly.",	--Teleports player.
		YELLOWAMULET = "I could cut wood at night with this.",	--Emits light, player walks faster.
		GREENAMULET = "I've always been better at cuttin' anyways.",	--Reduce cost of crafting

		LIGHTER = "Keep it away from the trees!",
		BOOK_BIRDS = "I already know more than I want to aboot those things.",
		BOOK_TENTACLES = "They don't have tentacles in Canada.",
		BOOK_GARDENING = "Does it grow trees?",
		BOOK_SLEEP = "The perfect book for a full moon.",
		BOOK_BRIMSTONE = "I know better than to mess with that, eh.",
		BALLOONS_EMPTY = "Are those balloons?",
		SPEAR_WATHGRITHR = "Who needs a spear when you've got ol' Luce?",
		WAXWELLJOURNAL = "Trees made into... paper? No wonder it's cursed.",

		ABIGAIL_FLOWER = 
		{ 
			GENERIC = "It's a flower? I guess.",
			LONG = "Yup. It's a flower.",
			MEDIUM = "That flower's acting funny...",
			SOON = "Did it just move?",
			HAUNTED_POCKET = "I'm not comfortable with this.",
			HAUNTED_GROUND = "Maybe we should split, eh?",

		},

		SLURPER = "I think it's living hair.",
		SLURPER_PELT = "Looks like a dead beaver.",
		SLURPERPELT = "Where's the nearest fur trader?",
		ARMORSLURPER = "It tickles. I think it's still alive.",
		SPIDERHOLE_ROCK ="I should skedaddle before they come out of there.",
		ORANGEAMULET = "This'll make the chores go by quicker!",
		YELLOWSTAFF = "Useful in a pinch!",
		YELLOWGEM = "I can see the stars in it.",
		ORANGEGEM = "It's shimmering.",
		RELIC =
		{
			BROKEN = "I don't plan on fixin' that.",
			GENERIC = "What's this all aboot?",
		},
		TELEBASE = 
		{
			VALID = "It's humming with energy.",
			GEMS = "I don't think it has power.",
		},
		GEMSOCKET = 
		{
			VALID = "Looks ready.",
			GEMS = "It'll need a gem.",
		},
		STAFFLIGHT = "Well ain't that something.",	
		LUCY = "I love Lucy!",
        ANCIENT_ALTAR =
        {
        	WORKING = "There's axe marks on these altar stones.",
        	BROKEN = "Looks a little worn out.",
        },             
        ANCIENT_ALTAR_BROKEN = "Looks a little worn out.",
        ANCIENT_STATUE = "Another hoser.",
        LICHEN = "Looks barely edible.",
		CUTLICHEN = "Yum! Tastes woody!",
		CAVE_BANANA = "It tastes tropical.",
		CAVE_BANANA_COOKED = "I cooked it for some reason.",
		CAVE_BANANA_TREE = "They don't have those back home.",
		ROCKY = "Lobster supper time!",
		
		COMPASS =
		{
			GENERIC="Points to the True North.",
			N = "True North.",
			S = "South.",
			E = "East.",
			W = "West.",
			NE = "Northeast.",
			SE = "Southeast.",
			NW = "Northwest.",
			SW = "Southwest.",
		},

		BLUEAMULET = "Now I can keep my beverages frosty.",
		PURPLEAMULET = "The sparkle is gone from the gem.",
		TELESTAFF = "Just another use for wood.",
		MONKEY = "Well then. That's a new one.",
		MONKEYBARREL = "What a fine choice of building materials.",

		HOUNDSTOOTH="It's a beaut.",
		ARMORSNURTLESHELL="You can never be too safe.",
		BAT="Who taught that rat to fly?",
		BATBAT = "A mouse with wings?",
		BATWING="Gross!",
		BATWING_COOKED="Gross! And tasty! So confusing!",
		BATCAVE = "Full of the little critters!",
		
		BEDROLL_FURRY="I love camping.",
		BUNNYMAN="He looks friendly enough.",
		FLOWER_CAVE="Shiny!",
		FLOWER_CAVE_DOUBLE="Shiny!",
		FLOWER_CAVE_TRIPLE="Shiny!",
		GUANO="It stinks less than the other kind.",
		LANTERN="Well that's enlightening, eh?",
		LIGHTBULB="It looks chewy.",
		MANRABBIT_TAIL="I feel sorry for it.",
		MUSHTREE_TALL  ="I can't let that stand.",
		MUSHTREE_MEDIUM="Maybe I should chop it.",
		MUSHTREE_SMALL ="It's made of wood.",
		MUSHTREE_TALL=
		{
            GENERIC = "I can't let that stand.",
            BLOOM = "Chop it down before it spreads!",
        },
		MUSHTREE_MEDIUM=
		{
            GENERIC = "Maybe I should chop it.",
            BLOOM = "I like the colour of this one.",
        },
		MUSHTREE_SMALL=
		{
            GENERIC = "It's made of wood.",
            BLOOM = "Well, I can't cut it down now...",
        },
        MUSHTREE_TALL_WEBBED = "This one needs pruning, at least.",
        SPORE_TALL = "Flying pinecones!",
        SPORE_MEDIUM = "Flying pinecones!",
        SPORE_SMALL = "Flying pinecones!",
        SPORE_TALL_INV = "One day this might be a tree.",
        SPORE_MEDIUM_INV = "One day this might be a tree.",
        SPORE_SMALL_INV = "One day this might be a tree.",
		SLURTLE="He's just misunderstood.",
		SLURTLE_SHELLPIECES="I broke his home. I feel bad.",
		SLURTLEHAT="This will keep my noggin safe.",
		SLURTLEHOLE="Are you guys doing okay in there?",
		SLURTLESLIME="Someone needs a tissue.",
		SNURTLE="Spirals!",
		SPIDER_HIDER="Tricky devil!",
		SPIDER_SPITTER="Spitting is rude!",
		SPIDERHOLE="I should skedaddle before they come out of there.",
		STALAGMITE="I'm not too interested in rocks.",
		STALAGMITE_FULL="I'm not too interested in rocks.",
		STALAGMITE_LOW="I'm not too interested in rocks.",
		STALAGMITE_MED="I'm not too interested in rocks.",
		STALAGMITE_TALL="I'm not too interested in rocks.",
		STALAGMITE_TALL_FULL="I'm not too interested in rocks.",
		STALAGMITE_TALL_LOW="I'm not too interested in rocks.",
		STALAGMITE_TALL_MED="I'm not too interested in rocks.",


		TURF_CARPETFLOOR = "Some ground.",
		TURF_CHECKERFLOOR = "Some ground.",
		TURF_DIRT = "Some ground.",
		TURF_FOREST = "Some ground.",
		TURF_GRASS = "Some ground.",
		TURF_MARSH = "Some ground.",
		TURF_ROAD = "Some ground.",
		TURF_ROCKY = "Some ground.",
		TURF_SAVANNA = "Some ground.",
		TURF_WOODFLOOR = "Some ground.",

		TURF_CAVE="Some ground.",
		TURF_FUNGUS="It's mushy like peas.",
		TURF_SINKHOLE="I found this underground.",
		TURF_UNDERROCK="Rocks. Bleh.",	
		TURF_MUD="At least you don't have to clean it.",

		
		POWCAKE = "I like the ones made with real sugar better.",
        CAVE_ENTRANCE = "It's all bunged up.",
        CAVE_ENTRANCE_RUINS = "It's all bunged up.",

		CAVE_ENTRANCE_OPEN = 
        {
            GENERIC = "There're probably no trees down there anyway.",
            OPEN = "It looks like Sudbury down there.",
        },
        CAVE_EXIT = 
        {
            GENERIC = "Maybe later. I've gotten cozy down here.",
            OPEN = "There are probably trees up there.",
        },
		
		MAXWELLPHONOGRAPH = "Better than most of the stuff on the radio.",
		BOOMERANG = "That looks hard to throw.",
		PIGGUARD = "I don't want to make him mad.",
		ADVENTURE_PORTAL = "I wonder if that's the way out of here.",
		AMULET = "Always have a backup plan.",
		ANIMAL_TRACK = "A large woodland creature passed this way!",
		ARMORGRASS = "It's better than nothing.",
		ARMORMARBLE = "It's hard to swing an axe while wearing this.",
		ARMORWOOD = "It fits me so well!",
		ARMOR_SANITY = "It makes me queasy to look at.",
		ASH =
		{
			GENERIC = "It's all burnt up.",
			REMAINS_GLOMMERFLOWER = "This used to be a slimy flower.",
			REMAINS_EYE_BONE = "This used to be an eyebone.",
			REMAINS_THINGIE = "I guess that doesn't go through there.",
		},
		AXE = "It's not as nice as Lucy.",
		BABYBEEFALO = "A face only a mother could love.",
		BACKPACK = "That's my rucksack.",
		BACONEGGS = "Awww. It's just front bacon.",
		BANDAGE = "At least I didn't have to pay for it.",
		BASALT = "That rock ain't going to move.",
		BEARDHAIR = "My hair's not that colour. Not my beard, anyway.",
		BEDROLL_STRAW = "I slept on worse back at the lumber camp.",
		BEE =
		{
			GENERIC = "She's making the flowers grow.",
			HELD = "Now what do I do with it?",
		},
		BEEBOX =
		{
			FULLHONEY = "Maple syrup substitute!",
			READY = "Maple syrup substitute!",
			GENERIC = "Buzzers!",
			NOHONEY = "I'm getting hungry just looking at it.",
			SOMEHONEY = "I could get more if I waited.",
			BURNT = "No, not the bees!",
		},
		BEEFALO =
		{
			FOLLOWER = "I think he likes me.",
			GENERIC = "He smells like a sod house.",
			NAKED = "Cheer up, eh?",
			SLEEPING = "He's catching some zeds.",
		},
		BEEFALOHAT = "Now I'm the king of the beefalo!",
		BEEFALOWOOL = "It feels like my beard.",
		BEEHAT = "That'll keep the bees out of my eyes.",
		
		BEEHIVE = "They're all comfy-cozy in there.",
		
		BEEMINE = "I don't know if the bees like this.",
		BEEMINE_MAXWELL = "Hey! That's just mean!",
		BERRIES = "I have a heartier appetite than that.",
		BERRIES_COOKED = "Tastes like warm berries.",
		BERRYBUSH =
		{
			BARREN = "It needs a good poopin'.",
			WITHERED = "It's perished from the heat, eh?",
			GENERIC = "Saskatoon berries?",
			PICKED = "No berries left!",
		},
		BIRDCAGE =
		{
			GENERIC = "Where I try to make birds reform their evil ways.",
			OCCUPIED = "Think aboot what you've done, bird!",
			SLEEPING = "They look so innocent when they dream.",
			HUNGRY = "I'll get you something to eat soon, buddy.",
			STARVING = "He's got a hankering for some poutine!",
			DEAD = "I'm sorry. I failed you.",
			SKELETON = "That's starting to smell.",
		},
		BIRDTRAP = "I'll show those birds yet!",
		BIRD_EGG = "There's a bird in there thinking evil bird thoughts.",
		BIRD_EGG_COOKED = "Well, at least it never became a bird.",
		BISHOP = "It's been a while since my last confession.",
		BLOWDART_FIRE = "This seems a bit aggressive.",
		BLOWDART_SLEEP = "I can make my escape if I use this!",
		BLOWDART_PIPE = "Let's see what my huge lungs can do with this!",
		BLUEGEM = "It's very cold.",
		BLUEPRINT = "I'm not one for book learning.",
		BELL_BLUEPRINT = "I'm not one for book learning.",
		BLUE_CAP = "That's not meat.",
		BLUE_CAP_COOKED = "That's not meat.",
		BLUE_MUSHROOM =
		{
			GENERIC = "I can never remember which ones you can eat.",
			INGROUND = "I'll come back later.",
			PICKED = "Well, that's over.",
		},
		BOARDS = "So smooth. You can really see the grain.",
		BOAT = "Must have hit a Nor'easter.",
		BONESTEW = "Sticks to your ribs.",
		BUGNET = "It can collect skeeters.",
		BUSHHAT = "It's good for hiding from nature.",
		BUTTER = "I prefer margarine.",
		BUTTERFLY =
		{
			GENERIC = "I never trusted those things, eh?",
			HELD = "Where are you going to run?",
		},
		BUTTERFLYMUFFIN = "Crunchy! ...But soft?",
		BUTTERFLYWINGS = "I'm sorry! I'm a terrible person!",
		CAMPFIRE =
		{
			EMBERS = "It's almost gone.",
			GENERIC = "Now where's my guitar?",
			HIGH = "Uh oh! It's bit high!",
			LOW = "I should probably do something aboot that, eh?",
			NORMAL = "I love a fire in the evening.",
			OUT = "It was good while it lasted.",
		},
		CANE = "It's good for the back country.",
		CARROT = "That's rabbit food.",
		CARROT_COOKED = "That's cooked rabbit food.",
		CARROT_PLANTED = "I'm not one for vegetables, eh?",
		CARROT_SEEDS = "Tiny carrots.",
		CAVE_FERN = "Hey! It's a fern!",

		CHARCOAL = "This makes me a bit sad.",

        CHESSJUNK1 = "Dead metal.",
        CHESSJUNK2 = "Dead metal.",
        CHESSJUNK3 = "Dead metal.",

		CHESTER = "He's doing his best!",
		CHESTER_EYEBONE =
		{
			GENERIC = "No one ever told him it was rude to stare.",
			WAITING = "I wonder if it will ever wake up again.",
		},
		COOKEDMANDRAKE = "Was that a bad thing to do?",
		COOKEDMEAT = "Just like my dear old ma used to make.",
		COOKEDMONSTERMEAT = "I still don't want to eat it.",
		COOKEDSMALLMEAT = "That'll just make me hungrier!",
		CORN = "I like it, but not in everything that I eat.",
		CORN_COOKED = "Cooked with the goodness of corn.",
		CORN_SEEDS = "I'm more of a hewer of wood than a tiller of soil.",
		CROW =
		{
			GENERIC = "He's planning something. I can tell.",
			HELD = "You'll pay for your crimes, crow!",
		},
		CUTGRASS = "I think I might be allergic to this.",
		CUTREEDS = "Want to hear my loon call?",
		CUTSTONE = "Part of the Canadian shield.",
		DEADLYFEAST = "That doesn't smell quite right, eh.",
		DEERCLOPS = "That's a big moose!",
		DEERCLOPS_EYEBALL = "Now what is this good for?",
		DEPLETED_GRASS =
		{
			GENERIC = "It's probably a tuft of grass.",
		},
		DEVTOOL = "I'm not commenting on that.",
		DIRTPILE = "Hey! A clue!",
		DIVININGROD =
		{
			COLD = "It's really fuzzy from here.",
			GENERIC = "I wonder if it gets the hockey game.",
			HOT = "Loud and clear! Something's near!",
			WARM = "I think I'm getting closer.",
			WARMER = "Woah, careful there, bud.",
		},
		
		DIVININGRODBASE =
		{
			GENERIC = "It looks like something should plug in.",
			READY = "It's ready to be unlocked.",
			UNLOCKED = "Now all it needs is to be turned on.",
		},
		DIVININGRODSTART = "That's a weird looking rod.",
		DRAGONFLY = "She'll burn all the trees before I can chop them!",
		LAVAE = "Death by axe!",
		LAVAE_PET = 
		{
			STARVING = "Skinnier than a blue heron's legs.",
			HUNGRY = "Poor gal's getting hungry.",
			CONTENT = "Look how happy she is!",
			GENERIC = "That's my lil critter.",
		},
		LAVAE_EGG = 
		{
			GENERIC = "There's a fire burning in there.",
		},
		LAVAE_EGG_CRACKED =
		{
			COLD = "She could use a parka.",
			COMFY = "Cozier than a moose wrapped in duct tape!",
		},
		LAVAE_TOOTH = "Not as sharp as Lucy!",

		LAVASPIT = 
		{
			HOT = "Aaaah! Tree killer!",
			COOL = "My trees are safe now.",
		},
		LAVA_POND = "I wouldn't get too close to that, eh?",
		DRAGONFRUIT = "I've never seen one of those before.",
		DRAGONFRUIT_COOKED = "It tastes like maple syrup.",
		DRAGONFRUIT_SEEDS = "Maybe I can grow more.",
		DRAGONPIE = "Almost as good as butter tarts!",
		DRUMSTICK = "October food.",
		DRUMSTICK_COOKED = "Thanks, turkey.",
		DUG_BERRYBUSH = "Time for a little landscaping.",
		DUG_GRASS = "It makes my eyes water.",
		DUG_MARSH_BUSH = "I should plant this.",
		DUG_SAPLING = "Mmmmm. It's all twiggy.",
		DURIAN = "It smells bad.",
		DURIAN_COOKED = "It smells even worse.",
		DURIAN_SEEDS = "Why would I want to grow more of those things?",
		EARMUFFSHAT = "Where I'm from these would only work in the fall.",
		EGGPLANT = "I bet birds have something to do with this.",
		EGGPLANT_COOKED = "Suspiciously birdy.",
		EGGPLANT_SEEDS = "Hmmm. I'm not sure.",
		ACORN = 
		{
		    GENERIC = "I should grow it and then chop it down!",
		    PLANTED = "Here comes a tree!",
		},
		EVERGREEN =
		{
			BURNING = "Nooo! I could have chopped it!",
			BURNT = "What a waste.",
			CHOPPED = "Ahhhh!",
			GENERIC = "It's calling to me!",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "I'm sorry!",
			BURNT = "I feel terrible!",
			CHOPPED = "Another one!",
			GENERIC = "Lucy would want me to chop it down.",
		},
		EYEPLANT = "It needs to mind its own business.",
		FEATHERHAT = "I want nothing to do with that... thing.",
		FEATHER_CROW = "A gross feather.",
		FEATHER_ROBIN = "A disgusting feather.",
		FEATHER_ROBIN_WINTER = "A stupid feather.",
		FEM_PUPPET = "She's trapped!",
		FIREFLIES =
		{
			GENERIC = "Reminds me of Algonquin park.",
			HELD = "I've got a pocket full of sunshine!",
		},
		FIREHOUND = "Hot hound!",
		FIREPIT =
		{
			EMBERS = "I should go chop some wood for that, eh?",
			GENERIC = "It uses wood.",
			HIGH = "I'm using too much wood too fast!",
			LOW = "There should be some wood around here somewhere.",
			NORMAL = "Mmmm. Smells woody.",
			OUT = "If only I had some wood.",
		},
		FIRESTAFF = "I don't trust this magic business.",
		FISH = "Looks like a cod.",
		FISHINGROD = "I should spend some time at the lake.",
		FISHSTICKS = "Elegant dining in a box.",
		FISHTACOS = "Tastes like the sea.",
		FISH_MED = "It wants to be dinner.",
		FISH_MED_COOKED = "I wish I had some chips.",
		FISH_COOKED = "I wish I had some chips.",
		FLINT = "This could be an axe head.",
		FLOWER = "That's nice.",
		FLOWER_WITHERED = "Someone's got a brown thumb.",
		FLOWERHAT = "I think wildflowers look nice with my red hair.",
		FLOWER_EVIL = "Something is wrong with that flower.",
		FOLIAGE = "Looks like a salad.",
		FOOTBALLHAT = "Will this give me hockey hair?",
		FROG =
		{
			DEAD = "Ex-frog.",
			GENERIC = "I don't trust anything that can't decide between air and water.",
			SLEEPING = "It's tired.",
		},
		FROGGLEBUNWICH = "You can really taste the swamp.",
		FROGLEGS = "They're still jumping!",
		FROGLEGS_COOKED = "At least they stopped moving.",
		FRUITMEDLEY = "In syrup!",
		GEARS = "I never could figure these things out.",
		GHOST = "Boo! Ha ha!",
        GHOST_SAILOR = "Not a bad beard for a dead guy.",
		GOLDENAXE = "It's almost as nice as Lucy.",
		GOLDENPICKAXE = "It's pretty, but can't chop down trees.",
		GOLDENPITCHFORK = "Welp. I can't unmake it, so...",
		GOLDENSHOVEL = "Time to dig golden holes.",
		GOLDNUGGET = "You can't make a coffee table out of gold.\nWell, maybe you can. But you shouldn't.",
		GRASS =
		{
			BARREN = "I need to poop on it.",
			WITHERED = "Maybe it'd thrive if it was cooler out?",
			BURNING = "I hope that doesn't spread to the trees.",
			GENERIC = "Looks like kindling.",
			PICKED = "It's gone all nubbly.",
		},
		GREEN_CAP = "I've eaten stranger things in the woods.",
		GREEN_CAP_COOKED = "I don't trust it.",
		GREEN_MUSHROOM =
		{
			GENERIC = "It's a green mushroom.",
			INGROUND = "They have their own schedule.",
			PICKED = "I think I broke it.",
		},
		GUNPOWDER = "Never did like this stuff.",
		HAMBAT = "What a waste of good ham.",
		HAMMER = "Everyone makes mistakes, eh?",
		HEALINGSALVE = "Healthiness in goo form.",
		HEATROCK =
		{
			FROZEN = "Brrr! It's frozen.",
			COLD = "It's gone cold, eh?",
			GENERIC = "We call those \"night rocks\" back home.",
			WARM = "It's getting a bit... medium.",
			HOT = "I could chop all winter with that in my pocket!",
		},
		HOME = "Who's there?",
		HOMESIGN = 
		{
			GENERIC = "Is there anything wood can't do?",
			BURNT = "Wood is the best at burning.",
		},
		HONEY = "Mmmmmm-mmmm. Bee syrup.",
		HONEYCOMB = "I almost feel bad taking this.",
		HONEYHAM = "But it's not a holiday...",
		HONEYNUGGETS = "One of my favourite meals!",
		HORN = "I don't know if I should put my mouth on that.",
		HOUND = "They'd be good at pulling a sled.",
		HOUNDBONE = "It's covered with dog spit, eh?",
		HOUNDMOUND = "I know better than to mess with that.",
		ICEBOX = "Ahhhh. Reminds me of home.",
		ICEHOUND = "Arctic hounds?",
		INSANITYROCK =
		{
			ACTIVE = "Where did it go?!",
			INACTIVE = "I don't know how to move that.",
		},
		JAMMYPRESERVES = "Now to find peanut butter.",
		KABOBS = "The stick really adds to the flavour.",
		KILLERBEE =
		{
			GENERIC = "That bee doesn't seem as friendly.",
			HELD = "She's none too pleased with her situation.",
		},
		KNIGHT = "Maxwell's own mounted police.",
		KOALEFANT_SUMMER = "He looks tasty.",
		KOALEFANT_WINTER = "They get tastier in the winter.",
		KRAMPUS = "Back off, hoser!",
		KRAMPUS_SACK = "I feel bad taking someone else's sack.",
		LEIF = "I'm sorry aboot all of those trees!",
		LEIF_SPARSE = "I'm sorry aboot all of those trees!",
		LIGHTNING_ROD =
		{
			CHARGED = "It's pretty as the Northern lights.",
			GENERIC = "Weather's not going to get the drop on me now.",
		},
		LITTLE_WALRUS = "Why are they so far South?",
		LIVINGLOG = "I am going to keep you, and call you \"Frank\".",
		LOCKEDWES = "Who's that hoser?",
		LOG =
		{
			BURNING = "Oh no! Don't put another log on the fire!",
			GENERIC = "It makes it all worthwhile.",
		},
		LUREPLANT = "Is that meat?",
		LUREPLANTBULB = "It's warm and lumpy.",
		MALE_PUPPET = "Do you need help?",
		MANDRAKE =
		{
			DEAD = "Sorry, little guy.",
			GENERIC = "It's looking at me.",
			PICKED = "What have I done?",
		},
		MANDRAKESOUP = "It's a tiring soup.",
		MANDRAKE_COOKED = "Sorry!",
		MARBLE = "Feels like a government building.",
		MARBLEPILLAR = "Somebody must have built that.",
		MARBLETREE = "Even Lucy can't chop that one down.",
		MARSH_BUSH =
		{
			BURNING = "Foomph!",
			GENERIC = "That's a bramble.",
			PICKED = "Was that worth it?",
		},
		MARSH_PLANT = "Plant.",
		MARSH_TREE =
		{
			BURNING = "That's what you get for being spiky!",
			BURNT = "It deserved it.",
			CHOPPED = "It was a hard battle, but I won.",
			GENERIC = "Trees shouldn't fight back!",
		},
		MAXWELL = "Why does he hate me?",
		MAXWELLHEAD = "Just a head, eh?",
		MAXWELLLIGHT = "That's unnatural.",
		MAXWELLLOCK = "Where is the key?",
		MAXWELLTHRONE = "I've seen nicer chairs.",
		MEAT = "Tastes like moose.",
		MEATBALLS = "All the meats!",
		MEAT_DRIED = "It tastes like survival.",
		MERM = "What foul sea did that crawl out of?",
		MINERHAT = "Down deep in a coal mine.",
		MONSTERLASAGNA = "This is cat food!",
		MONSTERMEAT = "I'm not hungry enough for that.",
		MONSTERMEAT_DRIED = "I still don't want to eat it.",
		MOSQUITO =
		{
			GENERIC = "That'll take a pint out of me!",
			HELD = "What do I do with this, eh?",
		},
		MOSQUITOSACK = "Blood and guts, eh?",
		MOUND =
		{
			DUG = "Sorry! Don't haunt me!",
			GENERIC = "I should probably leave that alone.",
		},
		NIGHTLIGHT = "What kind of darkness is that?",
		NIGHTMAREFUEL = "All of my fears in liquid form, eh?",
		
		NIGHTSWORD = "Nightmares can't hurt ya!",
		NITRE = "It's how we built the railway.",
		ONEMANBAND = "I stand on guard for thee!",
		PANDORASCHEST = "What's in the box?!",
		PANFLUTE = "I only sing for Lucy.",
		PAPYRUS = "I'd rather chop than write.",
		PENGUIN = "Doesn't matter if you're from the Great White North. Still a bird.",
		PERD = "More birds! Why is it always birds?",
		PEROGIES = "I call them \"Yum pockets\".",
		PETALS = "I wonder if Lucy would like these.",
		PETALS_EVIL = "They're frowning at me with little evil faces.",
		PHLEGM = "I wouldn't want that in my moustache.",
		PICKAXE = "Almost an axe, but not quite.",
		PIGGYBACK = "I used all parts of the pig.",
		PIGKING = "He's not MY king.",
		PIGSKIN = "Bacon with a tail.",
		PIGTORCH = "How did they do that without thumbs?",
		PINECONE = 
		{
		    GENERIC = "I should grow it and then chop it down!",
		    PLANTED = "Here comes a tree!",
		},
		LUMPY_SAPLING = "Shucks, I'm gonna have to chop it again.",
		PITCHFORK = "This really isn't my style.",
		PLANTMEAT = "That's gross!",
		PLANTMEAT_COOKED = "Cooking it didn't help much.",
		PLANT_NORMAL =
		{
			GENERIC = "I wonder what it will be.",
			GROWING = "A watched plant never grows.",
			READY = "Time for grub.",
			WITHERED = "It's got no life left, eh?",
		},
		POMEGRANATE = "That's too fancy for me.",
		POMEGRANATE_COOKED = "This would go good on flapjacks.",
		POMEGRANATE_SEEDS = "Seedy.",
		POND = "I can't swim!",
		POOP = "Don't poop in camp!",
		PUMPKIN = "I don't like to eat things that grow on the ground.",
		PUMPKINCOOKIE = "This will keep me chopping.",
		PUMPKIN_COOKED = "Pies are good.",
		PUMPKIN_LANTERN = "It'd better not tip over.",
		PUMPKIN_SEEDS = "It's a seed.",
		PURPLEGEM = "It's nothing a good chopping wouldn't fix.",
		RABBIT =
		{
			GENERIC = "Dang ground squirrels...",
			HELD = "I'd feel bad eating him.",
		},
		RABBITHOLE = 
		{
			GENERIC = "I doubt there are trees down there.",
			SPRING = "Nothing going in or out.",
		},
		RATATOUILLE = "It's like a forest in a bowl.",
		RAZOR = "A true lumberjack never shaves.",
		REDGEM = "I see within it the fiery death of a thousand trees.",
		RED_CAP = "I don't know...",
		RED_CAP_COOKED = "Only if I get really hungry.",
		RED_MUSHROOM =
		{
			GENERIC = "It's a red mushroom.",
			INGROUND = "They have their own schedule.",
			PICKED = "I think I broke it.",
		},
		REEDS =
		{
			BURNING = "Fire makes me nervous.",
			GENERIC = "Reeds.",
			PICKED = "They'll be back.",
		},
        RUBBLE = "Broken furniture.",
		RESURRECTIONSTONE = "I don't know if I should touch it.",
		ROBIN =
		{
			GENERIC = "What a snotty little jerk.",
			HELD = "Don't get comfortable, birdie.",
		},
		ROBIN_WINTER =
		{
			GENERIC = "Go fly south or something!",
			HELD = "It's stealing my warmth.",
		},
		ROBOT_PUPPET = "They're trapped!",
		ROCK_LIGHT =
		{
			GENERIC = "It's looking a tad crusty.",
			OUT = "It looks like it could break.",
			LOW = "Needs more... wood?",
			NORMAL = "A fire that needs no wood? Unnn-natural!",
		},
		ROCK = "I could break it down if I tried hard enough.",
		ROCKS = "Could make a decent little inukshuk with these.",
        ROOK = "Hmm... does the rook move in a straight line? I forget.",
		ROPE = "Good for holding stuff to other stuff.",
		ROTTENEGG = "One less bird. Good.",
		SANITYROCK =
		{
			ACTIVE = "Something is off aboot that rock, eh?",
			INACTIVE = "That makes sense.",
		},
		SAPLING =
		{
			BURNING = "Aw! He barely had a chance!",
			WITHERED = "With this heat, it'll never grow to chopping size!",
			GENERIC = "I want to see it grow so I can chop it down.",
			PICKED = "Picking isn't as fun as chopping.",
		},
		SEEDS = "Not trees.",
		SEEDS_COOKED = "We call this \"lumberjack surprise\".",
		SEWING_KIT = "I'm pretty good at sewing.",
		SHOVEL = "Dig a hole. Plant a tree!",
		SILK = "Spiders give me the willies.",
		SKELETON = "Sorry, friend.",
		SKELETON_PLAYER = "That's just downright unnerving.",
		SKULLCHEST = "That's scary!",
		SMALLBIRD =
		{
			GENERIC = "What do you want?",
			HUNGRY = "It wants something.",
			STARVING = "I think it's starving.",
		},
		SMALLMEAT = "I wish this were bigger.",
		SMALLMEAT_DRIED = "Just a bite.",
		SPAT = "Reminds me of momma!",
		SPEAR = "It lacks the heft of a good solid axe.",
		SPIDER =
		{
			GENERIC = "That's the biggest spider I've ever seen!",
			SLEEPING = "Careful, now, eh?",
			DEAD = "Good!",
		},
		SPIDERDEN = "Holy Mackinaw! Look at that thing!",
		SPIDEREGGSACK = "Why would I want to carry that around?",
		SPIDERGLAND = "I think it's poison.",
		SPIDERHAT = "She's a real beaut, ain't she?",
		SPIDERQUEEN = "You're not my queen!",
		SPIDER_WARRIOR =
		{
			GENERIC = "They come in yellow now?",
			SLEEPING = "You're snoozin' fer a bruisin'.",
			DEAD = "Great!",
		},
		SPOILED_FOOD = "Aw, it's Diefenbakered.",
		STATUEHARP = "You lost your head, eh?",
		STATUEMAXWELL = "He's kind of a jerk, eh?",
		STEELWOOL = "That'll put the shine back on yer axe.",
		STINGER = "Ouch! It's pointy.",
		STRAWHAT = "It will keep the sun off my head.",
		STUFFEDEGGPLANT = "I'm getting better at cooking.",
		SUNKBOAT = "That wood has seen better days.",
		SWEATERVEST = "It's not plaid, but it'll do.",
		TAFFY = "Sugary. Good.",
		TALLBIRD = "I don't trust birds that can't fly, either.",
		TALLBIRDEGG = "What's in here?",
		TALLBIRDEGG_COOKED = "It tastes like justice.",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "Too cold for you?",
			GENERIC = "It's hatching.",
			HOT = "Is it crying?",
			LONG = "Birds are never prompt.",
			SHORT = "Anytime now.",
		},
		TALLBIRDNEST =
		{
			GENERIC = "I should steal its egg to teach it a lesson.",
			PICKED = "Nothing there.",
		},
		TEENBIRD =
		{
			GENERIC = "It's growing up to be a jerk, just like its parents.",
			HUNGRY = "Are you ALWAYS hungry?",
			STARVING = "It's getting wild with hunger.",
		},
		TELEBASE =
		{
			VALID = "It's ready, but am I?",
			GEMS = "Needs gems, eh?",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "Ready to go, eh?",
			GENERIC = "It's a... magic thing, I think.",
			LOCKED = "There are bits missing, eh?",
			PARTIAL = "It's almost ready, eh?",
		},
		TELEPORTATO_BOX = "Box-y, eh?",
		TELEPORTATO_CRANK = "Crank-y, eh?",
		TELEPORTATO_POTATO = "Potato-y, eh?",
		TELEPORTATO_RING = "Ring-y, eh?",
		TELESTAFF = "I wonder what this thing does.",
		TENTACLE = "There a squid down there?",
		TENTACLESPIKE = "It wobbles when you wave it.",
		TENTACLESPOTS = "I'm blushing!",
		TENTACLE_PILLAR = "It's so big!",
		TENTACLE_PILLAR_HOLE = "Not even a stump left behind!",
		TENTACLE_PILLAR_ARM = "Are those squid babies?",
		TENTACLE_GARDEN = "I'm tired of these squids!",
		TOPHAT = "It's too fancy.",
		TORCH = "Trees by torchlight.",
		TRAP = "Work smarter, eh?",
		TRAP_TEETH = "This seems a bit rough.",
		TRAP_TEETH_MAXWELL = "He's not playing fair, eh?",
		TREASURECHEST_TRAP = "Something is not quite right aboot that chest.",
		MOOSE_NESTING_GROUND = "I hate it.",
		TRINKET_1 = "I used to play that game.",
		TRINKET_10 = "Choppers for old folks.",
		TRINKET_11 = "Quiet, you!",
		TRINKET_12 = "It's all withered.",
		TRINKET_2 = "Not the real thing, eh?",
		TRINKET_3 = "Reminds me of a story I heard once.",
		TRINKET_4 = "Don't ask me.",
		TRINKET_5 = "It needs a robot arm, eh?",
		TRINKET_6 = "They're not good any more, eh?",
		TRINKET_7 = "I could play this for hours!",
		TRINKET_8 = "If I find a tub, I'm all set.",
		TRINKET_9 = "I just sew my clothing shut around me when I put it on.",
		TRUNKVEST_SUMMER = "Nice and breezy.",
		TRUNKVEST_WINTER = "This could stand up to the winters back home, eh?",
		TRUNK_COOKED = "I think it boiled off all of the nose cheese.",
		TRUNK_SUMMER = "It's pretty thin.",
		TRUNK_WINTER = "It's thick and hairy.",
		TURF_CARPETFLOOR = "Too classy for my taste.",
		TURF_CHECKERFLOOR = "Looks like one of those city-people outhouses.",
		TURF_DIRT = "Just some ground, eh?",
		TURF_FOREST = "Just some ground, eh?",
		TURF_GRASS = "Just some ground, eh?",
		TURF_MARSH = "Just some ground, eh?",
		TURF_ROAD = "Just some ground, eh?",
		TURF_ROCKY = "Just some ground, eh?",
		TURF_SAVANNA = "Just some ground, eh?",
		TURF_WOODFLOOR = "Flooring fit for a king!",
		TURF_DRAGONFLY = "Fire doesn't quite take here, eh?",
		TURF_DESERTDIRT = "Just some ground, eh?",
		TURF_FUNGUS_GREEN = "Just some ground, eh?",
		TURF_FUNGUS_RED = "Just some ground, eh?",
		TURKEYDINNER = "Turkey day is here again!",
		TWIGS = "I should build a tiny axe to chop these.",
		BANANAPOP = "I'd prefer maple taffy...",
		BISQUE = "Hearty.",
		CEVICHE = "I'd be loonie not to eat this.",
		SEAFOODGUMBO = "We don't have this back home.",
		SURFNTURF = "Good eating, that.",
		SHARKFINSOUP = "He'll swim in my stomach from now on.",
		LOBSTERDINNER = "I'd prefer salmon.",
		LOBSTERBISQUE = "Looks pretty good for desert island food.",
		JELLYOPOP = "I guess this is a dessert island, eh?",
		UMBRELLA = "This will keep my beard dry, eh?",
		UNIMPLEMENTED = "It doesn't look safe.",
		WAFFLES = "I prefer flapjacks.",
		WALL_HAY_ITEM = "I could sneeze it over.",
		WALL_STONE = "Safe and secure, eh?",
		WALL_STONE_ITEM = "Safe and secure, eh?",
		WALL_RUINS = "Crumbling but still secure, eh?",
		WALL_RUINS_ITEM = "Heh, stoned again eh?",
		WALL_WOOD_ITEM = "I like the look of that!",
		WALL_MOONROCK = "Looks nice'n'sturdy.",
		WALL_MOONROCK_ITEM = "It's not much use like that.",
		WALRUS = "Oh no. Walruses again!",
		WALRUSHAT = "My granddad wore a hat like this.",
		WALRUS_CAMP =
		{
			EMPTY = "This won't be safe come winter.",
			GENERIC = "Walruses are nearby, eh?",
		},
		WALRUS_TUSK = "He had a cavity, eh?",
		WASPHIVE = "Why are those bees so angry?",
		WORMLIGHT_LESSER = "Wrinklier than the underside of a beaver.",
		WETGOOP = "Better than some of the things I've eaten!",
        WHIP = "I hope that doesn't end up hurting any lil critters.",
		WINTERHAT = "It's a nice toque, eh?",
		WORMHOLE =
		{
			GENERIC = "That looks like a bum!",
			OPEN = "I'm not sure I want to look at that, eh?",
		},
		WORMHOLE_LIMITED = "It smells a bit off, eh?",
		ACCOMPLISHMENT_SHRINE = "It seems a bit show-offy to me.",  
		BISHOP_CHARGE_HIT = "Hey now!",        		
		LIVINGTREE = "I feel conflicted, eh?",
		ICESTAFF = "It reminds me of home.",
		MOONROCKNUGGET = "It's uh, a moon rock.",
        ROCK_MOON = "It's uh, a moon rock.",

		------------------------------capy---------------------------------

		WOODLEGS_CAGE = "Are you okay in there, buddy?",

		TWISTER = "Mother Nature's throwing a tantrum!",
		WIND_CONCH = "I can hear the chime of twenty-nine bells.",

		AERODYNAMICHAT = "It's a speed toque.",
		ANTIVENOM = "Tastes awful, but it works!",
		ARMORCACTUS = "Pretty prickly protection, eh?",
		ARMORLIMESTONE = "Makes me feel sorta tough.",
		ARMOROBSIDIAN = "Hot stuff, eh?",
		ARMORSEASHELL = "This doesn't seem very hardy.",
		ARMOR_LIFEJACKET = "A lil reassurance.",
		ARMOR_SNAKESKIN = "I feel suave in it.",
		ARMOR_WINDBREAKER = "I feel right at home in this, eh.",
		ARMOUREDBOAT = "That's aboot as safe as it gets on the sea.",
		BABYOX = "Hey, little buddy!",
		BALLPHIN = "Hey buddy, you know any tricks?",
		BAMBOO = "It's like diet wood, eh?",
		BAMBOOTREE =
		{
			BURNT = "Burnt like bacon, eh?",
			CHOPPED = "That was some good chopping!",
			GENERIC = "Lucy's got too much kick for this.",
		},
		BERMUDATRIANGLE = "Kinda spooky, eh?",
		BIGFISHINGROD = "Walk tall and carry a big rod.",
		BIOLUMINESCENCE = "Just like the Northern Lights.",
		BLOWDART_FLUP = "Eye'll get you!",
		BLOWDART_POISON = "Aim for a main vein, eh?",
		BLUBBER = "Quit your blubbering.",
		BLUBBERSUIT = "It's not very flattering.",
		BOATCANNON = "This'll blow'em up real good!",
		BOATREPAIRKIT = "Patch'er up, eh?",
		BOAT_LANTERN = "It's a boat light.",
		BOAT_TORCH = "I can go night fishing.",
		BOTTLELANTERN = "You okay in there, glowing buddies?",
		BRAINJELLYHAT = "I feel like a keener when I put it on.",
		BUOY = "Floating through life. Got the right idea there.",
		BURIEDTREASURE = "Time to get digging!",
		BUSH_VINE =
		{
			BURNT = "Welp, that's not coming back.",
			CHOPPED = "Not as fun as a tree, but it was good chopping nonetheless.",
			GENERIC = "It's just asking to be chopped.",
		},
		CAPTAINHAT = "I hope I don't have to go down with the ship.",
		CARGOBOAT = "I'd prefer cargo shorts.",
		CHIMINEA = "It's like armor for fire.",
		CLOTHSAIL = "This should help me get around.",
		COCONADE =
		{
			BURNING = "Time to run!",
			GENERIC = "I'm gonna do some serious damage with this.",
		},
		COCONUT = 
		{
		    GENERIC = "It's just a coconut.",
		    PLANTED = "Now it's a tiny palm tree.",
		},
		COCONUT_COOKED = "Ready to eat.",
		COCONUT_HALVED = "One for me and one for Lucy.",
		COFFEE = "Good old joe.",
		COFFEEBEANS = "I should cook these up.",
		COFFEEBEANS_COOKED = "Canadians love their coffee.",
		COFFEEBOT = "Makes coffee, don't it.",
		COFFEEBUSH =
		{
			BARREN = "You look a little down, bud.",
			GENERIC = "Coffee beans!",
			PICKED = "I wish it had more beans.",
			WITHERED = "It could use good cuppa joe.",
		},
		CORAL = "Maybe I could crush it down to make something new.",
		CORALREEF = "Ripe for the picking.",
		CORAL_BRAIN = "How brainy.",
		CORAL_BRAIN_ROCK = "What're you, some sort of keener?",
		CRAB =
		{
			GENERIC = "Maybe we could be buds?",
			HIDDEN = "Can't hide forever, bud.",
		},
		CRABHOLE = "That's where my crabbit buddies live.",
		CRATE = "That there's a box.",
		CUTLASS = "That's a pretty neat little cutter, eh?",
		DEAD_SWORDFISH = "Sorry, guy.",
		DEPLETED_BAMBOOTREE = "Grow so I can chop you down again!",
		DEPLETED_BUSH_VINE = "I guess it'll regrow.",
		DEPLETED_GRASS_WATER = "I don't like waiting.",
		DEVTOOL_NODEV = "What a curious thing.",
		DOUBLE_UMBRELLAHAT = "Double the protection!",
		DOYDOY = "Not too sure how this awful thing survives.",
		DOYDOYBABY = "It's filthy.",
		DOYDOYEGG = "Looks like good eating to me.",
		DOYDOYEGG_COOKED = "Could use a side of Canadian bacon.",
		DOYDOYEGG_CRACKED = "Well, can't do nothing aboot it now.",
		DOYDOYFEATHER = "It's nothing like the plumage of the proud Canadian goose.",
		DOYDOYNEST = "Those filthy birds breed here.",
		DRAGOON = "Seems a little hot under the toque!",
		DRAGOONDEN = "That doesn't look like a beaver dam.",
		DRAGOONEGG = "That looks a little suspicious to me.",
		DRAGOONHEART = "The heart of the beast.",
		DRAGOONSPIT = "Rude.",
		DUBLOON = "I've struck gold!",
		DUG_BAMBOOTREE = "You're coming with me!",
		DUG_BUSH_VINE = "Are you ready to go on a little trip?",
		DUG_COFFEEBUSH = "I'm going to take you everywhere with me.",
		DUG_ELEPHANTCACTUS = "Are you headed my way?",
		EARRING = "Shouldn't there be two?",
		ELEPHANTCACTUS = "It's prickly, eh?",
		ELEPHANTCACTUS_ACTIVE = "Watch out! That plant's gonna give'r!",
		ELEPHANTCACTUS_STUMP = "This cactus gave'r. Now it's tired.",
		FABRIC = "How do I dye it plaid?",
		FEATHERSAIL = "I guess touching all those gross feathers was worth it.",
		FISHINHOLE = "If only it were a little colder, would be perfect for ice fishin'!",
		FISH_RAW = "I'd prefer salmon.",
		FISH_RAW_SMALL = "I hope I don't attract bears.",
		FISH_RAW_SMALL_COOKED = "Looks good to me.",
		FLAMEGEYSER = "Woah, cool it!",
		FLOTSAM = "Justa bunch of junk.",
		FLUP = "Gross.",
		FRESHFRUITCREPES = "I can get maple syrup on that?",
		FROG_POISON = "Keep your poison spit to yourself, eh!",
		GASHAT = "Nothin' stinks when I got this on.",
		GOLDENMACHETE = "It chops AND sparkles!",
		GRASS_WATER = "A bit damp, eh?",
		HAIL_ICE = "You think this is cold? How cute.",
		HOUNDFIRE = "It burns so mightily!",
		ICEMAKER =
		{
			HIGH = "Furiously icy! Reminds me of home.",
			LOW = "Gettin' low.",
			NORMAL = "It's pumping along nicely.",
			OUT = "It's hooped.",
			VERYLOW = "It'll give out any second.",
		},
		INVENTORYGRAVE = "Someone was here. Not anymore.",
		INVENTORYMOUND = "Someone was here. Not anymore.",
		IRONWIND = "Looks speedy.",
		JELLYFISH = "That's a jellyfish, don'tcha know.",
		JELLYFISH_COOKED = "I think this is as edible as it gets.",
		JELLYFISH_DEAD = "The life's all but drained out of it, eh?",
		JELLYFISH_PLANTED = "A little jellyfish buddy.",
		JELLYJERKY = "Jerky! The food of my people.",
		JUNGLETREE =
		{
			BURNING = "Waste of a good chopping stump.",
			BURNT = "What a waste.",
			CHOPPED = "Those were good times.",
			GENERIC = "The tree's call fills my ears!",
		},
		JUNGLETREESEED =
        {
            GENERIC = "This could grow into a good chopping tree.",
            PLANTED = "Now we wait.",
        },
		KNIGHTBOAT = "That guy's got an attitude problem!",
		KRAKEN = "For Lucy!",
		KRAKENCHEST = "Show me the loot!",
		KRAKEN_TENTACLE = "A bit grabby, don'tcha think?",
		LAVAPOOL = "I'm breaking a sweat just looking at it.",
		LIMESTONE = "I crushed up that pretty coral to make this.",
		LIMPETROCK =
		{
			GENERIC = "I could make a snack out of those.",
			PICKED = "Just a big rock, eh?",
		},
		LIMPETS = "Some sort of water-dwelling snail.",
		LIMPETS_COOKED = "Dinner's on.",
		TREEGUARD = "I've angered the forest!",
		LIVINGJUNGLETREE = "It wants me to cut it down, I can tell.",
		LOBSTER = "A little melted butter and it'd be delicious.",
		LOBSTERHOLE = "Come on out, little guy.",
		LOBSTER_DEAD = "He's thoroughly hooped.",
		LOBSTER_DEAD_COOKED = "Good eats!",
		LOGRAFT = "My specialty!",
		LUGGAGECHEST = "Anything good inside?",
		MACHETE = "Ooh, that's a thing for chopping.",
		MAGIC_SEAL = "It's pulsing with power.",
		MAGMAROCK = "A little rearranging and it'd make a nice inukshuk.",
		MAGMAROCK_FULL = "A little rearranging and it'd make a nice inukshuk.",
		MAGMAROCK_GOLD = "That looks worth digging into.",
		MAGMAROCK_GOLD_FULL = "That looks worth digging into.",
		MANGROVETREE = "Looks tasty!",
		MANGROVETREE_BURNT = "Hurts my hoser heart to look at.",
		MARSH_PLANT_TROPICAL = "That's a little plant.",
		MERMFISHER = "I don't know aboot that guy.",
		MERMHOUSE_FISHER = "I'd prefer a log cabin.",
		MESSAGEBOTTLE = "Is someone trying to talk to me?",
		MESSAGEBOTTLEEMPTY = "What was in it?",
		MONKEYBALL = "What're you smiling at?",
		MONSTERTARTARE = "Isn't there anything else to eat?",
		MOSQUITOSACK_YELLOW = "It smells a little sour.",
		MOSQUITO_POISON = "It's dripping with disease.",
		MUSSEL = "Those look like good eating.",
		MUSSELBOUILLABAISE = "Best meal I've seen in awhile, eh?",
		MUSSEL_COOKED = "These look tasty.",
		MUSSEL_FARM =
		{
			GENERIC = "They want to be food.",
			STICKPLANTED = "I predict a mussel dinner in my future.",
		},
		MUSSEL_STICK = "The mussels can't get enough of this thing.",
		MYSTERYMEAT = "What on earth is that!",
		NEEDLESPEAR = "Hoo-boy. That's sharp.",
		OBSIDIAN = "It's a little toasty.",
		OBSIDIANAXE = "Watch out Lucy, you've got competition! (Just kidding!)",
		OBSIDIANCOCONADE = "It packs a major punch.",
		OBSIDIANFIREPIT =
		{
			EMBERS = "I should go chop some wood for that, eh?",
			GENERIC = "Looks like the perfect place to light a fire.",
			HIGH = "I'm using too much wood too fast!",
			LOW = "There should be some wood around here somewhere.",
			NORMAL = "Mmmm. Smells woody.",
			OUT = "If only I had some wood.",
		},
		OBSIDIANMACHETE = "It singes everything it touches.",
		OBSIDIANSPEARGUN = "It lights stuff on fire, eh.",
		OBSIDIAN_WORKBENCH = "I can make some fiery tools here.",
		OCTOPUSCHEST = "Thanks for the stuff, guy!",
		OCTOPUSKING = "How you holding up out here, guy?",
		OX = "Poor guy's the butt of every yoke.",
		OXHAT = "This is a hat befitting a Northerner.",
		OX_FLUTE = "I'm more of a guitar player.",
		OX_HORN = "It used to be attached to an ox.",
		PACKIM = "I can tolerate him.",
		PACKIM_FISHBONE = "This better not attract any feathered vermin.",
		PALMLEAF = "I use it for fanning myself.",
		PALMLEAF_HUT = "The best shelter a woodcutter could ask for.",
		PALMTREE =
		{
			BURNING = "Waste of a good chopping stump.",
			BURNT = "What a waste.",
			CHOPPED = "Those were good times.",
			GENERIC = "Makes me pine for the lumber yards.",
		},
		PARROT = "Shoo, filthy featherbag!",
		PARROT_PIRATE = "I'd rather not smalltalk with a birdbrain.",
		PEACOCK = "What a ridiculous thing. Bah!",
		PEG_LEG = "Can I chop this?",
		PIGTENT = "Looks to be some sort of tent.",
		PIKE_SKULL = "Well that there's a tacky decoration.",
		PIRATEGHOST = "Maybe he's friendly?",
		PIRATEHAT = "It's the pirate's life for me now.",
		PIRATEPACK = "A bag for my booty.",
		PIRATIHATITATOR =
		{
			BURNT = "Not so funny anymore.",
			GENERIC = "That's a funny lookin' contraption.",
		},
		POISONHOLE = "I think I'll give that a wide berth.",
		PORTAL_SHIPWRECKED = "Looks hooped to me.",
		PRIMEAPE = "This guy's a bit of a keener.",
		PRIMEAPEBARREL = "Where the keeners sleep.",
		RAFT = "Pitiful little boat.",
		RAWLING = "What a nutter!",
		REDBARREL = "That looks dangerous.",
		RELIC =
		{
			BROKEN = "I don't plan on fixing that.",
			GENERIC = "What's this all aboot?",
		},
		ROCK_CHARCOAL = "It makes my hands all sooty.",
		ROCK_OBSIDIAN = "There's a fire burning within it.",
		ROWBOAT = "Powered by elbow grease.",
		SAIL = "I've got the wind in my sails.",
		SAIL_STICK = "The Northern winds are at my disposal.",
		SAND = "Sandy.",
		SANDBAG = "Building dams is my specialty.",
		SANDBAGSMALL = "Building dams is my specialty.",
		SANDBAGSMALL_ITEM = "A tiny, portable dam.",
		SANDBAG_ITEM = "A portable dam.",
		SANDHILL = "It's a big pile of sand.",
		SAND_CASTLE =
		{
			GENERIC = "Who knew sand could look so good.",
			SAND = "Looks good.",
		},
		SEAGULL = "Vermin of the sky.",
		SEAGULL_WATER = "Vermin of the sea.",
		SEASACK = "It's for holding my treasures.",
		SEASHELL = "It makes me want to get back into arts and crafts.",
		SEASHELL_BEACHED = "A pretty shell.",
		SEATRAP = "I'm looking forward to a wobster dinner.",
		SEAWEED = "It's slimy.",
		SEAWEED_COOKED = "It has a weird texture.",
		SEAWEED_DRIED = "It sort of sticks to my tongue.",
		SEAWEED_PLANTED = "That's some seaweed, eh?",
		SHADOWSKITTISH_WATER = "Hoo-boy!",
		SHARKITTEN = "Just a big sweet kitty cat.",
		SHARKITTENSPAWNER =
		{
			GENERIC = "I think I hear meowing...?",
			INACTIVE = "Looks like just a bunch of sand to me, eh?",
		},
		SHARK_FIN = "I'm sure the shark won't miss this.",
		SHARK_GILLS = "Fish lungs.",
		SHARK_TEETHHAT = "It's a hat made of teeth.",
		SHARX = "Not gonna make a buddy of that one, that's for sure.",
		SHIPWRECKED_ENTRANCE = "I'm ready for adventure, eh!",
		SHIPWRECKED_EXIT = "See ya later, bud.",
		SLOTMACHINE = "The spirit of the North guides my fate.",
		SLURPERPELT = "Where's the nearest fur trader?",
		SNAKE = "It's an alright sort, as far as snakes go.",
		SNAKEDEN =
		{
			BURNT = "Welp, that's not coming back.",
			CHOPPED = "Not as fun as a tree, but it was good chopping nonetheless.",
			GENERIC = "It's just asking to be chopped.",
		},
		SNAKEOIL = "I'm not falling for this.",
		SNAKESKIN = "I'm sure the snake didn't need this.",
		SNAKESKINHAT = "Now would this be a \"touque\" or a \"tuque\"?",
		SNAKESKINSAIL = "Sailin' in style.",
		SNAKE_FIRE = "It's looking a little heated.",
		SNAKE_POISON = "I'd rather not get bitten by that.",
		SOLOFISH = "Nice doggy.",
		SPEARGUN = "This is one skookum weapon!",
		SPEARGUN_POISON = "This skookum weapon poisons my enemies!",
		SPEAR_LAUNCHER = "This is one skookum weapon!",
		SPEAR_OBSIDIAN = "This is one fiery spear.",
		SPEAR_POISON = "This spear has a little extra bite.",
		SPOILED_FISH = "I think it's time to throw this out.",
		STUNGRAY = "Smells worse than a waterlogged moose!",
		SUNKEN_BOAT =
		{
			ABANDONED = "Waste of good wood.",
			GENERIC = "Hey buddy.",
		},
		SUNKEN_BOAT_BURNT = "That there won't float no more.",
		SUNKEN_BOAT_TRINKET_1 = "That's a little too fancy for my liking.",
		SUNKEN_BOAT_TRINKET_2 = "That boat seems a little on the small side.",
		SUNKEN_BOAT_TRINKET_3 = "I can't imagine this having a use.",
		SUNKEN_BOAT_TRINKET_4 = "A toy for a keener.",
		SUNKEN_BOAT_TRINKET_5 = "Not my size, that.",
		SUPERTELESCOPE = "As easy as looking over the plains of Alberta.",
		SWEETPOTATOSOUFFLE = "Pretty extravagant!",
		SWEET_POTATO = "I'll cook this up good.",
		SWEET_POTATO_COOKED = "Could use some marshmallows.",
		SWEET_POTATO_PLANTED = "Looks like some sorta fancy potato.",
		SWEET_POTATO_SEEDS = "These would be of more use to me planted.",
		SWIMMINGHORROR = "I don't want nothin' to do with that, eh!",
		SWORDFISH = "That there's one pointy fish.",
		TELEPORTATO_SW_BASE = "Nothing some duct tape wouldn't fix.",
		TELEPORTATO_SW_BOX = "There must be a use for this, eh?",
		TELEPORTATO_SW_CRANK = "I should keep a hold of this.",
		TELEPORTATO_SW_POTATO = "Doesn't look anything like a potato. And I know potatoes.",
		TELEPORTATO_SW_RING = "Some sort of ring?",
		TELESCOPE = "Helps my eyesight, eh?",
		THATCHPACK = "Now I can carry more delicious wood.",
		TIDALPOOL = "Seems like a popular hangout spot for fishes.",
		TIDAL_PLANT = "No wood to be had from that thing.",
		TIGEREYE = "Don'tcha know it's rude to stare?",
		TIGERSHARK = "Might be cute if it didn't want to eat me.",
		TOUCAN = "That thing looks shifty.",
		TRAWLNET = "The fishes should swim right into this.",
		TRAWLNETDROPPED =
		{
			GENERIC = "Come to me, fishes!",
			SOON = "Nearly there!",
			SOONISH = "It's on its way down.",
		},
		TREECLUMP = "You're asking for a good chop, bud.",
		TRIDENT = "Get a load of this massive fork, eh?!",
		TRINKET_13 = "Is this safe for consumption?",
		TRINKET_14 = "Is that my face?",
		TRINKET_15 = "This guitar is tiny!",
		TRINKET_16 = "It's just a little sheet of metal, eh?",
		TRINKET_17 = "Not my size.",
		TRINKET_18 = "It's broken.",
		TRINKET_19 = "Who knows what this does?",
		TRINKET_20 = "That's a little too fancy for my liking.",
		TRINKET_21 = "That boat seems a little on the small side.",
		TRINKET_22 = "Not very useful looking.",
		TRINKET_23 = "I got no idea what that is.",
		TROPICAL_FISH = "Are you ready to become fish'n'chips?",
		TUNACAN = "Lucy'll open'er up.",
		TURBINE_BLADES = "Makes my head spin.",
		TURF_SANDY = "Just some ground, eh?",
		TURF_ASH = "Just some ground, eh?",
		TURF_BEACH = "Just some ground, eh?",
		TURF_DESERTDIRT = "Just some ground, eh?",
		TURF_FUNGUS_GREEN = "Just some ground, eh?",
		TURF_FUNGUS_RED = "Just some ground, eh?",
		TURF_JUNGLE = "Just some ground, eh?",
		TURF_MAGMAFIELD = "Just some ground, eh?",
		TURF_MEADOW = "Just some ground, eh?",
		TURF_SNAKESKINFLOOR = "Just some ground, eh?",
		TURF_SWAMP = "Just some ground, eh?",
		TURF_TIDALMARSH = "Just some ground, eh?",
		TURF_VOLCANO = "Just some ground, eh?",
		TWISTER_SEAL = "Cute little fella.",
		VENOMGLAND = "It smells kind of funny.",
		VINE = "Sigh. Not a tree.",
		VOLCANO = "That's a doozy!",
		VOLCANOSTAFF = "The power of the volcano is in my hand.",
		VOLCANO_ALTAR =
		{
			GENERIC = "Nothing to do aboot that.",
			OPEN = "I feel like it wants something from me.",
		},
		VOLCANO_ALTAR_BROKEN = "Thoroughly broke, that.",
		VOLCANO_ALTAR_TOWER = "That's a creepy-lookin' hunk of rock, that.",
		VOLCANO_EXIT = "Time to scoot.",
		VOLCANO_SHRUB = "Well, it's definitely not an evergreen.",
		WALLYINTRO_DEBRIS = "Where am I?",
		WALL_LIMESTONE = "That's a wall.",
		WALL_LIMESTONE_ITEM = "Why build walls when we could build bridges?",
		WATERMELON_SEEDS = "Maybe I could plant them?",
		WATERYGRAVE = "I hope to never end up in one of those.",
		WHALE_BLUE = "Give'r!",
		WHALE_BUBBLES = "I know you're down there, buddy.",
		WHALE_CARCASS_BLUE = "That's a big guy, eh.",
		WHALE_CARCASS_WHITE = "Well, he's dead now.",
		WHALE_TRACK = "I'm hot on the trail.",
		WHALE_WHITE = "It's strong, and very free.",
		WILBUR_CROWN = "Luxurious.",
		WILBUR_UNLOCK = "I made a new buddy.",
		WILDBORE = "Looks like a total hoser.",
		WILDBOREHEAD = "Tough luck, buddy.",
		WILDBOREHOUSE = "Looks like a house fulla hosers.",
		WOODLEGSBOAT = "Fancy, but it seems a little slow.",
		WOODLEGSHAT = "Could do with a pair of woolly earflaps.",
		WOODLEGSSAIL = "Pretty stylish sail, that.",
		WOODLEGS_KEY1 = "What might this open?",
		WOODLEGS_KEY2 = "Key to what?",
		WOODLEGS_KEY3 = "I should hold on to this, eh?",
		WRECK = "A waste of good wood.",
		CALIFORNIAROLL = "I feel like a regular Vancouverite.",

	},
	DESCRIBE_GENERIC = "What's that, eh?",
	DESCRIBE_TOODARK = "It's dark!",
	DESCRIBE_SMOLDERING = "It's aboot to go up in flames, eh?",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "Lil ripe. Or not ripe enough?",
	},
}
