return {
	ACTIONFAIL =
	{
		SHAVE =
		{
			AWAKEBEEFALO = "I don't think she'd take kindly to that.",
			GENERIC = "To what end?",
			NOBITS = "But it's already as smooth as a baby's rear end.",
		},
		STORE =
		{
			GENERIC = "It wouldn't fit.",
			NOTALLOWED = "That can't go in there.",
		},
		WRITE =
        {
            GENERIC = "I'm unable to do that right now.",
        },
		RUMMAGE =
		{	
			GENERIC = "Curses.",	
		},
		COOK =
        {
            GENERIC = "Nothing ever goes as planned.",
            TOOFAR = "I must get closer.",
        },
        CHANGEIN =
        {
            GENERIC = "How could you improve on perfection?",
            BURNING = "Oh. There go all my good pocket squares.",
        },
        GIVE =
        {
            DEAD = "The dead have no need of such things.",
            SLEEPING = "It's thoroughly unconscious.",
            BUSY = "It's busy, currently.",
        },
        TEACH =
        {
            KNOWN = "I am far too advanced for this.",
            CANTLEARN = "There's a lesson to be learned about tampering with secret knowledge.",
        },
		REPAIRBOAT =
		{
			GENERIC = "Not right now.",
		},

	},
	ACTIONFAIL_GENERIC = "That didn't work.",
	ANNOUNCE_MAGIC_FAIL = "Such magic does not belong here.",
    ANNOUNCE_NOSLEEPONFIRE = "That might not be the best idea.",
	ANNOUNCE_NODANGERSIESTA = "They're hot on my heels!",
	ANNOUNCE_NONIGHTSIESTA = "It's sleep time, not siesta time.",
	ANNOUNCE_NONIGHTSIESTA_CAVE = "It's a bit too creepy out for that.",
	ANNOUNCE_NOHUNGERSIESTA = "Traditionally a siesta comes after eating, not before.",
	ANNOUNCE_SHELTER = "Protect me, wretched tree!",
	ANNOUNCE_BURNT = "It burns!",
	ANNOUNCE_TOOL_SLIP = "Drat.",
	ANNOUNCE_DAMP = "Damp is not dapper.",
	ANNOUNCE_WORMS = "Something terrible cometh.",
	ANNOUNCE_WET = "Water'll ruin a good suit, you know?",
	ANNOUNCE_WETTER = "I don't think I'll ever be dry again.",
	ANNOUNCE_SOAKED = "Wetter than water itself.",
	ANNOUNCE_ADVENTUREFAIL = "I of all people should be able to do this.",
	ANNOUNCE_BEES = "Killing me won't bring back your honey!",
	ANNOUNCE_BOOMERANG = "Ow! Blasted... clumsy hands!",
	ANNOUNCE_CHARLIE = "Charlie? It's me! Maxwell!",
	ANNOUNCE_CHARLIE_ATTACK = "Ow! Charlie, that hurt!",
	ANNOUNCE_COLD = "My heart grows cold.",
	ANNOUNCE_HOT = "My heart can't stand the heat!",
	ANNOUNCE_CRAFTING_FAIL = "Er... I can't do that.",
	ANNOUNCE_DEERCLOPS = "I hear one of them coming.",
	ANNOUNCE_DUSK = "It'll be dark soon. Charlie will be waking up.",
	ANNOUNCE_EAT =
	{
		GENERIC = "(Gulp!)",
		PAINFUL = "Ow! That hurt my mouth!",
		SPOILED = "That was putrid.",
		STALE = "That was past its due-date.",
		INVALID = "I won't let that anywhere near my mouth.",
		YUCKY = "A civilized man does not eat such things.",  
	},
	ANNOUNCE_ENTER_DARK = "It's dark! I can't see!",
	ANNOUNCE_ENTER_LIGHT = "The light is back.",
	ANNOUNCE_FREEDOM = "Freedom, at last!",
	ANNOUNCE_HIGHRESEARCH = "My brain swells with power!",
	ANNOUNCE_HOUNDS = "The hounds are growing restless.",
	ANNOUNCE_HUNGRY = "I am empty inside.",
	ANNOUNCE_HUNT_BEAST_NEARBY = "I smell dung and beast sweat.",
	ANNOUNCE_HUNT_LOST_TRAIL = "Drat! It got away.",
	ANNOUNCE_HUNT_LOST_TRAIL_SPRING = "I can't follow it in these conditions!",
	ANNOUNCE_INV_FULL = "My pockets are full.",
	ANNOUNCE_KNOCKEDOUT = "Ugh. My head hurts.",
	ANNOUNCE_LOWRESEARCH = "That wasn't very informative.",
	ANNOUNCE_MOSQUITOS = "What annoying little bugs.",
	ANNOUNCE_NODANGERSLEEP = "Not while there's danger afoot!",
	ANNOUNCE_NODAYSLEEP = "I can't sleep during daylight hours.",
	ANNOUNCE_NODAYSLEEP_CAVE = "Sleeping now would mess up my sleep schedule!",
	ANNOUNCE_NOHUNGERSLEEP = "I'm too hungry. I can't sleep.",
	ANNOUNCE_NO_TRAP = "Odd. They forgot to set it.",
	ANNOUNCE_PECKED = "Have patience!",
	ANNOUNCE_QUAKE = "That rumbling can't be good.",
	ANNOUNCE_RESEARCH = "Knowledge is power. And power is... well, power.",
	ANNOUNCE_THORNS = "I scratched my arms up doing that.",
	ANNOUNCE_TORCH_OUT = "Curses. Another light down.",
	ANNOUNCE_FAN_OUT = "There goes my respite.",
	ANNOUNCE_COMPASS_OUT = "The compass has fallen to pieces.",
	ANNOUNCE_TRAP_WENT_OFF = "Ack!",
	ANNOUNCE_UNIMPLEMENTED = "Hmm, not quite done.",
	ANNOUNCE_WORMHOLE = "Yech. It's horrible in there.",
	ANNOUNCE_CANFIX = "\nI think I can fix this!",
	ANNOUNCE_NOSANITY = "I have the worst headache!",
	ANNOUNCE_NOFUEL = "I need some nightmare fuel.",
	ANNOUNCE_NOWARDROBEONFIRE = "You're kidding right?",
	ANNOUNCE_ACCOMPLISHMENT= "I need to pass the time somehow.",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "That kinda makes it all worthwhile.",	
	ANNOUNCE_INSUFFICIENTFERTILIZER = "It perked up just a tiny bit.",
	ANNOUNCE_LIGHTNING_DAMAGE_AVOIDED = "Can't touch this!",
	ANNOUNCE_OTHER_WORLD_PLANT = "I can't possibly plant this here.",
	ANNOUNCE_MESSAGEBOTTLE =
	{
		"The penmanship is atrocious. I can't make it out.",
	},
	ANNOUNCE_BOAT_DAMAGED = "My vessel is sustaining damage.",
	ANNOUNCE_BOAT_SINKING = "I fear I've sprung a leak.",
	ANNOUNCE_BOAT_SINKING_IMMINENT = "After everything, is this how it ends?!",
	ANNOUNCE_CRAB_ESCAPE = "Crafty crustacean...",
	ANNOUNCE_MAPWRAP_LOSECONTROL = "I am consumed by the abyss!",
	ANNOUNCE_MAPWRAP_RETURN = "Thank goodness.",
	ANNOUNCE_MAPWRAP_WARN = "I want nothing to do with mists and fogs.",
	ANNOUNCE_MORETREASURE = "Ah. Another guide to a lost treasure.",
	ANNOUNCE_OTHER_WORLD_TREASURE = "I don't believe this treasure is located nearby.",
	ANNOUNCE_SHARX = "It seems I'm being pursued.",
	ANNOUNCE_TRAWL_FULL = "The net is full to bursting!",
	ANNOUNCE_TREASURE = "It appears I can follow this to some sort of... treasure.",
	ANNOUNCE_VOLCANO_ERUPT = "There's no need for such outbursts.",
	ANNOUNCE_WAVE_BOOST = "Truly!",
	ANNOUNCE_WHALE_HUNT_BEAST_NEARBY = "Pursue the beast!",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL = "Foiled by a fish!",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL_SPRING = "I've lost sight of the whale!",

	BATTLECRY =
	{
		GENERIC = "To arms!",
		PIG = "Brains over brawn!",
		PREY = "You look tasty!",
		SPIDER = "I'll not be made a fool of again!",
		SPIDER_WARRIOR = "You've forced my hand!",
	},
	COMBAT_QUIT =
	{
		GENERIC = "And stay away!",
		PIG = "Next time, pig!",
		PREY = "You're not worth my time!",
		SPIDER = "I won't be made a fool of... next time!",
		SPIDER_WARRIOR = "Next time the gloves come off!",
	},
	
	DESCRIBE =
	{
		LICHEN = "A slow growing cave plant.",
		ICEHOUND = "How quickly they forget...",
		INVENTORYGRAVE = "But who placed the headstone, I wonder?",
		INVENTORYMOUND = "It seems she's claimed another victim.",
		GLOMMER = "A flying goop factory.",
        GLOMMERFLOWER = 
        {
        	GENERIC = "Flower power.",
        	DEAD = "Flower power forever.",
        },
        GLOMMERWINGS = "They're sticky.",
        GLOMMERFUEL = "Well, that's rank.",
        BELL = "More bell.",
        STATUEGLOMMER = 
        {	
        	GENERIC = "Hey, that's not a statue of me!",
        	EMPTY = "That'll teach it to not be me.",
    	},
		WEBBERSKULL = "Don't think you'll be able to escape that easily.",
		MOLE =
		{
			HELD = "End of the line.",
			UNDERGROUND = "Are you picking up what I'm putting down? Do you dig it?",
			ABOVEGROUND = "I'll take that as a \"yes\".",
		},
		MOLEHILL = "Burrow deep, I'm coming for you.",
		MOLEHAT = "No wonder they can dig for hours.",
		NIGHTSTICK = "Good morning.",
		RABBITHOUSE=
		{
			GENERIC = "Oh, isn't that clever.",
			BURNT = "Cleverness killed the carrot.",
		},
		TURF_DECIDUOUS = "Turf.",
		TURF_SANDY = "Turf.",
		TURF_BADLANDS = "Turf.",
		BEARGER = "Take anything you want.",
		BEARGERVEST = "See my vest.",
		ICEPACK = "Its contents are hibernating.",
		BEARGER_FUR = "This would make a nice rug.",
		BIGFOOT = "Now that is surely fuel for nightmares.",
		BONESHARD = "Grind them bones.",
		BUZZARD = "Carrion connoisseur.",
		CACTUS = 
		{
			GENERIC = "Puffer plant.",
			PICKED = "Cactus? More like flat-tus!",
		},
		CACTUS_MEAT_COOKED = "Cactus comestible.",
		CACTUS_MEAT = "It would be unwise to put that in my mouth.",
		CACTUS_FLOWER = "This part of the cactus is always nice.",
		COLDFIRE =
		{
			EMBERS = "I'm going to lose it.",
			GENERIC = "How comforting.",
			HIGH = "That will keep Charlie away for now.",
			LOW = "It needs fuel.",
			NORMAL = "Cold and fiery.",
			OUT = "That's not coming back.",
		},
		CATCOON = "Catty vermin.",
		CATCOONDEN = 
		{
			GENERIC = "Vermin housing.",
			EMPTY = "Well, I guess that's that.",
		},
		CATCOONHAT = "Dead head.",
		COONTAIL = "Tale of tails.",
		COOKPOT =
		{
			COOKING_LONG = "Wait for it...",
			COOKING_SHORT = "Here it comes!",
			DONE = "Finally, some quality grub.",
			EMPTY = "Just the thought makes my mouth water.",
			BURNT = "A bit overdone for my tastes.",
		},
		EYEBRELLAHAT =	"Eye to the sky.",
		ARMORDRAGONFLY = "That's some fly mail.",
		DRAGON_SCALES = "Fiery.",
		DRAGONFLYCHEST = "Those scales sure are nifty.",
		DECIDUOUSTREE = 
		{
			BURNING = "Oops.",
			BURNT = "Bathed in fire.",
			POISON = "Shut your maw!",
			CHOPPED = "That's not about to grow back.",
			GENERIC = "I've heard them described as \"leafy\".",
		},
		ACORN_COOKED = "Over an open fire.",
		BIRCHNUTDRAKE = "A nut with legs! How terrifying!",
		FARMPLOT =
		{
			GENERIC = "Do I look like a farmer?",
			GROWING = "I have better things to do than watch plants grow.",
			NEEDSFERTILIZER = "It needs to be... refreshed.",
			BURNT = "A harvest of ashes.",
		},
		COLDFIREPIT =
		{
			EMBERS = "I should attend to that.",
			GENERIC = "A fire pit.",
			HIGH = "A cold, roaring fire.",
			LOW = "It's getting low.",
			NORMAL = "It's cold.",
			OUT = "It's gone warm.",
		},
		FIRESUPPRESSOR = 
		{	
			ON = "Begone, fire!",
			OFF = "Quiet before the storm.",
			LOWFUEL = "Not much fuel left.",
		},
		ICEHAT = "Strap some ice to your head.",
		LIGHTNINGGOAT = 
		{
			GENERIC = "What's it always chewing on?",
			CHARGED = "Chaaarge!",
		},
		LIGHTNINGGOATHORN = "It'd make a nice horn.",
		GOATMILK = "It's charged with nutrients.",
		MEATRACK =
		{
			DONE = "Like the desert.",
			DRYING = "Still moist.",
			DRYINGINRAIN = "Moist and staying that way.",
			GENERIC = "It can dry meats so that they last longer.",
			BURNT = "It's too brittle to hang meat on now.",
		},
		MERMHEAD = 
		{
			GENERIC = "The eyes follow you around.",
			BURNT = "Roasted merm head. Delicious.",
		},
		MERMHOUSE = 
		{
			GENERIC = "They copied the pigs, but they're even less intelligent.",
			BURNT = "It burns just as well as the pigs' version.",
		},
		FLOWERSALAD = "Leafy goodness.",
        ICECREAM = "Sundae, sundae, sundae!",
        BANANAPOP = "Hm... I don't know what I was expecting.",
        BISQUE = "Excellent food, but the ambiance could be improved.",
        CEVICHE = "A delightful, cultured dish.",
        SEAFOODGUMBO = "It looks passable.",
        SURFNTURF = "A very balanced meal, I suppose.",
        SHARKFINSOUP = "My refined palate relishes the taste of endangerment.",
        LOBSTERDINNER = "And here I forgot my bib.",
        LOBSTERBISQUE = "Ah, I do enjoy the finer things.",
        JELLYOPOP = "Hm... I don't think this meshes well with my cultivated look.",
        WATERMELONICLE = "The case is cold on the melon.",
        TRAILMIX = "Nuts and berries. No bolts.",
        HOTCHILI = "Hot as heck!",
        GUACAMOLE = "There's a mole in the mix.",
		MOOSE = "It's definitely from the North, whatever it is.",
		MOOSEEGG = "Ride the lightning, you big egg.",
		MOSSLING = "That's a fluffy... thing.",
		FEATHERFAN = "Is it windy out or is it just my fan?",
		TROPICALFAN = "Is it windy out or is it just my fan?",
		GOOSE_FEATHER = "I could use a pillow filled with these.",
		STAFF_TORNADO = "Wind power.",
		PIGHEAD = 
		{	
			GENERIC = "Er... charming.",
			BURNT = "Pig roast!",
		},
		PIGHOUSE =
		{
			FULL = "I'd go inside too, if I was him.",
			GENERIC = "It is not a sound structure.",
			LIGHTSOUT = "I'll huff and I'll puff!",
			BURNT = "Let's see you hide in there now.",
		},
		FERTILIZER = "It's not gentlemanly to carry manure in one's hands.",
		RAINOMETER = 
		{	
			GENERIC = "I could just look up and learn the same thing.",
			BURNT = "The rain did not come in time.",
		},
		RAINCOAT = "Out, out, rain!",
		RAINHAT = "Not the most dapper of hats, but quite necessary.",
		RESEARCHLAB = 
		{	
			GENERIC = "I can't believe I forgot how to build those things.",
			BURNT = "The fire learned how to burn it down.",
		},
		RESEARCHLAB2 = 
		{
			GENERIC = "It unlocks recipes of middling utility.",
			BURNT = "Flames have swallowed it whole.",
		},
		RESEARCHLAB3 = 
		{
			GENERIC = "This is where I do my own personal research.",
			BURNT = "Research complete.",
		},
		RESEARCHLAB4 = 
		{
			GENERIC = "Quite a dapper machine.",
			BURNT = "It was too hot to handle.",
		},
		RESURRECTIONSTATUE = 
		{
			GENERIC = "I'm not above using this.",
			BURNT = "I won't be using it any longer.",
		},
		ROCK_ICE = 
		{
			GENERIC = "I could get a chip of ice off the old block.",
			MELTED = "It's just a puddle.",
		},
		ROCK_ICE_MELTED = "It's just a puddle.",
		ICE = "Baby glaciers.",
        REFLECTIVEVEST = "Safety before dapperness.",
		HAWAIIANSHIRT = "The dapperest of them all.",
		TENT = 
		{
			GENERIC = "That's a bit rustic for my taste.",
			BURNT = "That's a bit burned for my taste.",
		},
		SIESTAHUT = 
		{
			GENERIC = "Rustic, but excellent shade.",
			BURNT = "So much for the whole \"shade\" thing.",
		},
		TRANSISTOR = "I don't understand how it works, but it does.",
		TREASURECHEST = 
		{
			GENERIC = "A place to store loot.",
			BURNT = "It won't store anything now.",
		},
		TUMBLEWEED = "Tumble on, weed.",
		GRASS_UMBRELLA = "It's more \"pretty\" than \"dapper\".",
		PALMLEAF_UMBRELLA = "It serves its purpose.",
		UNIMPLEMENTED = "Mysterious! Let's not touch it.",
		WALL_HAY = 
		{	
			GENERIC = "It's a tinderbox.",
			BURNT = "I told you so.",
		},
		WALL_WOOD = 
		{
			GENERIC = "Moderately tough, but flammable.",
			BURNT = "Not tough, nor flammable.",
		},
		WARG = "The alpha!",
		WATERMELON = "It's mostly water. Fibrous, sweet water.",
		WATERMELON_COOKED = "Grillermelon.",
		WATERMELONHAT = "This is one way to keep cool. And sticky.",
		WINTEROMETER = 
		{
			GENERIC = "Not the most useful invention, is it?",
			BURNT = "Who cares?",
		},
		LIVINGTREE = "It's got a face.",
		ICESTAFF = "Cool staff.",
		WAXWELLJOURNAL = "I'm so sorry Charlie.",
		WORMLIGHT = "What a neat trick.",
		WORM =
		{
		    PLANT = "You aren't fooling me, plant.",
		    DIRT = "Something stirs.",
		    WORM = "Well that's new!",
		},
		EEL = "They only exist in the depths.",
		EEL_COOKED = "It slithers all the way down.",
		UNAGI = "It will have to do.",
		EYETURRET = "Some of my better work.",
		EYETURRET_ITEM = "Now I just have to set it up.",
		MINOTAURHORN = "I'm sorry I had to do that, old friend.",
		MINOTAURCHEST = "It's almost like he's still alive.",
		THULECITE_PIECES = "I could combine several piles to make a bigger piece.",
		POND_ALGAE = "It's some algae.",
		GREENSTAFF = "I must rely on focusing tools in this form.",
		POTTEDFERN = "How quaint.",

		THULECITE = "An exceedingly rare but useful material.",
		ARMORRUINS = "Thulecite meshes so well with nightmare fuel.",
		RUINS_BAT = "The fuel runs deep in this.",
		RUINSHAT = "Fuel must flow.",
		NIGHTMARE_TIMEPIECE = --Keeps track of the nightmare cycle
		{
			CALM = "The heart of the city is still.",	--calm phase
			WARN = "It beats once again.",	--Before nightmare
			WAXING = "The pulse is quickening.", --Nightmare Phase first 33%
			STEADY = "The pulse is holding steady.", --Nightmare 33% - 66%
			WANING = "The pulse is waning.", --Nightmare 66% +
			DAWN = "It calms once more.", --After nightmare
			NOMAGIC = "The pulse has no influence here.", --Place with no nightmare cycle.
		},
		BISHOP_NIGHTMARE = "They degrade without proper upkeep.",
		ROOK_NIGHTMARE = "The builders have left it in a state of abandonment.",
		KNIGHT_NIGHTMARE = "It looks beyond repair.",
		MINOTAUR = "My my, the fuel has changed you.",	--Monster in labyrinth
		SPIDER_DROPPER = "Creatures in this world evolve at a terrifying rate.",	--White spider that comes from the roof
		NIGHTMARELIGHT = "The overuse of fuel was their downfall.",	--Lights that activate during nightmare.
		RELIC = "They were all dead when I got here.",	--Fixed relic
		RUINS_RUBBLE = "The earthquakes have taken their toll.",	--Broken relic
		MULTITOOL_AXE_PICKAXE = "I don't know why I didn't think of this.",	--Works as axe and pickaxe
		GREENGEM = "The nightmare fuel will unlock its true potential.",
		ORANGESTAFF = "I must rely on focusing tools in this form.",	--Teleports player.
		YELLOWAMULET = "This will make me stand out.",	--Emits light, player walks faster.
		GREENAMULET = "I swear I don't normally need this.",	--Reduce cost of crafting

		LIGHTER = "It does the job, I suppose.",
		BOOK_BIRDS = "What a wasteful misuse of magic.",
		BOOK_TENTACLES = "Shall I summon horrors from the depths?",
		BOOK_GARDENING = "It's not wise to toy with forces beyond your comprehension.",
		BOOK_SLEEP = "I haven't slept in... ages.",
		BOOK_BRIMSTONE = "It's a novel, er... novel.",
		LUCY = "Ah. How have you been, Lucy.",
		BALLOONS_EMPTY = "Those look much too jovial for my liking.",
		SPEAR_WATHGRITHR = "I can appreciate a finely crafted weapon.",

		ABIGAIL_FLOWER = 
		{ 
			GENERIC = "Hm? What a familiar presence.",
			LONG = "I can sense strong magic within it.",
			MEDIUM = "This enchantment is not of my doing.",
			SOON = "Whatever it is will be arriving soon.",
			HAUNTED_POCKET = "I should quit toying with this now.",
			HAUNTED_GROUND = "It demands a sacrifice.",

		},

		SLURPER = "Simple creatures. They exist only to sleep and feed.",
		SLURPER_PELT = "In death, this creature will serve me!",
		ARMORSLURPER = "Wet, soggy, and oddly filling.",
		ORANGEAMULET = "Simple magic is often the best.",
		YELLOWSTAFF = "With a bigger gem it would be so much more powerful.",
		YELLOWGEM = "I can feel the magic in this.",
		ORANGEGEM = "This will be quite powerful with some fuel.",
		TELEBASE = 
		{
			VALID = "That should do the trick.",
			GEMS = "The fuel needs more focal points.",
		},
		GEMSOCKET = 
		{
			VALID = "This one's ready.",
			GEMS = "The fuel needs a focus.",
		},
		STAFFLIGHT = "That should chase the shadows away.",
       	ANCIENT_ALTAR =
        {
        	WORKING = "Where are their gods now?",
        	BROKEN = "This can be partially restored.",
        },
        ANCIENT_ALTAR = "Where are their gods now?",
        ANCIENT_ALTAR_BROKEN = "This can be partially restored.",

        ANCIENT_STATUE = "A once proud race.",

		CAVE_BANANA = "Like ashes in my mouth.",
		CAVE_BANANA_COOKED = "Even worse than raw.",
		CAVE_BANANA_TREE = "It looks like a banana, but I'm not buying it.",
		ROCKY = "I banished these guys for a reason.",
		
		HOUNDSTOOTH="It could be used for fashion.",
		ARMORSNURTLESHELL="That is not dapper at all.",
		BAT="Ugh. Ugly beasts.",
		BATBAT = "Violence has never felt better.",
		BATWING="I'm not eating that.",
		BATWING_COOKED="I'm still not eating that.",
		BEDROLL_FURRY="At least they're good for something.",
		BUNNYMAN="It reminds me of my old act.",
		FLOWER_CAVE="It's so dark down here.",
		FLOWER_CAVE_DOUBLE="It's so dark down here.",
		FLOWER_CAVE_TRIPLE="It's so dark down here.",
		GUANO="Disgusting!",
		LANTERN="I hope this keeps Them away.",
		LIGHTBULB="It will run out eventually.",
		MANRABBIT_TAIL="Silly rabbit.",
		MUSHTREE_TALL="It smells of rot and failure.",
		MUSHTREE_MEDIUM="Where's Waldo?",
		MUSHTREE_SMALL="Ugh, it smells bad.",
		SLURTLE="I don't remember those...",
		SLURTLE_SHELLPIECES="They don't fit back together.",
		SLURTLEHAT="This will keep me standing, if I need to fight.",
		SLURTLEHOLE="That's revolting.",
		SLURTLESLIME="There must be a better way.",
		SNURTLE="That's strange. They must be new.",
		SPIDER_HIDER="It's a tricky one.",
		SPIDER_SPITTER="Aggressive little thing, isn't it?",
		SPIDERHOLE="How did that get down here?",
		STALAGMITE="Rocks. How dull.",
		STALAGMITE_FULL="Rocks. How dull.",
		STALAGMITE_LOW="Rocks. How dull.",
		STALAGMITE_MED="Rocks. How dull.",
		STALAGMITE_TALL="Stalagmite. How dull.",
		STALAGMITE_TALL_FULL="Stalagmite. How dull.",
		STALAGMITE_TALL_LOW="Stalagmite. How dull.",
		STALAGMITE_TALL_MED="Stalagmite. How dull.",

		POWCAKE = "What foul manifestation of evil is this?",
		CAVE_ENTRANCE = 
		{
			GENERIC= "I plugged it a long time ago.",
			OPEN = "That was not a good idea!",
		},
        CAVE_EXIT = "Get me out of here!",

		MAXWELLPHONOGRAPH = "That accursed thing!",
		BOOMERANG = "Beats getting your hands dirty.",
		PIGGUARD = "Blech. Disgusting brute.",
		ABIGAIL = "Why won't these mortals just stay dead?",
		ADVENTURE_PORTAL = "So that's where I left that thing!",
		AMULET = "It channels the darkest energies of the universe.",
		ANIMAL_TRACK = "Some dumb beast passed through here.",
		ARMORGRASS = "Direct confrontation is quite gauche.",
		ARMORMARBLE = "That really isn't my style.",
		ARMORWOOD = "Ugh. I'm not typically one for vulgar fisticuffs.",
		ARMOR_SANITY = "Time to wrap myself in nightmares.",
		ASH =
		{
			GENERIC = "A fine powder that smells of destruction.",
			REMAINS_GLOMMERFLOWER = "There's always another Glommer.",
			REMAINS_EYE_BONE = "Don't worry. There will be more Chesters.",
			REMAINS_THINGIE = "My trip through the portal made it unrecognizable.",
		},
		AXE = "Sometimes the direct approach is best.",
		BABYBEEFALO = "They're even ugly as children.",
		BACKPACK = "I wish there were porters around here.",
		BACONEGGS = "Now that is a proper breakfast.",
		BANDAGE = "Sticky and gooey and good for putting on booboos.",
		BASALT = "I made a rock so heavy that even I cannot lift it.",
		BEARDHAIR = "Hirsute.",
		BEDROLL_STRAW = "I don't like sleeping rough.",
		BEE =
		{
			GENERIC = "They work so hard, the fools.",
			HELD = "Now what do I do with it?",
		},
		BEEBOX =
		{
			FULLHONEY = "So tempting, but so full of bees.",
			GENERIC = "It holds my bees.",
			NOHONEY = "My bees are not working hard enough.",
			SOMEHONEY = "I should wait a bit longer.",
			BURNT = "Honey roasted.",
		},
		BEEFALO =
		{
			FOLLOWER = "Aw nuts, it's following me.",
			GENERIC = "Just look at that stupid beast.",
			NAKED = "Now it looks dumb AND pathetic.",
			SLEEPING = "It's only marginally less stupid when it's asleep.",
		},
		BEEFALOHAT = "How unfashionable.",
		BEEFALOWOOL = "It smells like a barn.",
		BEEHAT = "I'll wear it if I have to.",
		BEEHIVE = "Not the bees!",
		BEEMINE = "They wait so patiently.",
		BEEMINE_MAXWELL = "Maybe I shouldn't have put that there.",
		BERRIES = "Sigh. If I have to.",
		BERRIES_COOKED = "A little more refined, at least.",
		BERRYBUSH =
		{
			BARREN = "It needs manure.",
			WITHERED = "Too hot for that little bush.",
			GENERIC = "Reduced to eating berries. Sigh.",
			PICKED = "And now we wait.",
		},
		BIRDCAGE =
		{
			GENERIC = "You'll never get me behind bars again.",
			OCCUPIED = "I feel for ya, feathers.",
			SLEEPING = "You'll still be in there when you wake up.",
			HUNGRY = "What's all the fuss about, feathers?",
			STARVING = "Oh, come on. I fed you last week.",
			DEAD = "That's a deep sleep.",
			SKELETON = "Maybe he wasn't sleeping.",
		},
		BIRDTRAP = "They keep falling for it!",
		BIRD_EGG = "I like to think of it as baby bird prison.",
		BIRD_EGG_COOKED = "Sunny side up.",
		BISHOP = "I'm especially proud of that piece.",
		BLOWDART_FIRE = "Just make sure to breathe out.",
		BLOWDART_SLEEP = "Call me \"Mr. Sandman\".",
		BLOWDART_PIPE = "A glorious tube of pain!",
		BLUEAMULET = "It's frosted over.",
		BLUEGEM = "Blue brings ice.",
		BLUEPRINT = "I know all about that. I just forgot.",
		BELL_BLUEPRINT = "I know all about that. I just forgot.",
		BLUE_CAP = "What could go wrong?",
		BLUE_CAP_COOKED = "Umami!",
		BLUE_MUSHROOM =
		{
			GENERIC = "The blue ones are good for something.",
			INGROUND = "It's not ready.",
			PICKED = "Another time, maybe?",
		},
		BOARDS = "Roughly hewn.",
		BOAT = "It's not going anywhere.",
		BONESTEW = "Leave no scrap unused.",
		BUGNET = "Good for capturing defenseless insects.",
		BUSHHAT = "There's room in there for me.",
		BUTTER = "Some puns are irresistible.",
		BUTTERFLY =
		{
			GENERIC = "It's a flying flower.",
			HELD = "It would be a shame if someone ripped the wings off of it.",
		},
		BUTTERFLYMUFFIN = "That should stop its incessant flapping.",
		BUTTERFLYWINGS = "Ha ha ha. I got him!",
		CAMPFIRE =
		{
			EMBERS = "I'm going to lose it.",
			GENERIC = "How comforting.",
			HIGH = "That will keep Charlie away for now.",
			LOW = "It needs fuel.",
			NORMAL = "Fiery.",
			OUT = "That's not coming back.",
		},
		CANE = "It has pictures of fast things carved into it.",
		CARROT = "I'm not a fan of vegetables.",
		CARROT_COOKED = "A little more refined, at least.",
		CARROT_PLANTED = "How mundane.",
		CARROT_SEEDS = "Such labor is beneath me.",
		CAVE_FERN = "I'd like to step on it.",
		CHARCOAL = "Nothing will steal my carbon!",
        CHESSJUNK1 = "There's a reason I never finished that.",
        CHESSJUNK2 = "That one was a jerk.",
        CHESSJUNK3 = "Didn't like that one's face.",
		CHESTER = "Annoying little monster. Has his uses, though.",
		CHESTER_EYEBONE =
		{
			GENERIC = "Stop looking at me!",
			WAITING = "What is it waiting for?",
		},
		COOKEDMANDRAKE = "It has lost a lot of its power.",
		COOKEDMEAT = "It smells less like a barnyard now.",
		COOKEDMONSTERMEAT = "I'll eat it if I have to.",
		COOKEDSMALLMEAT = "Well, at least it's not moving anymore.",
		CORN = "High in fructose.",
		CORN_COOKED = "A little more refined, at least.",
		CORN_SEEDS = "Such labor is beneath me.",
		CROW =
		{
			GENERIC = "I don't know how they got here.",
			HELD = "Shhhh... My pretty.",
		},
		LICHEN = "This fungus survived the downfall.",
		CUTLICHEN = "Dry, crumbly, sustaining.",
		CUTGRASS = "The mundane stuff of the earth.",
		CUTREEDS = "I think I could build something useful from this.",
		CUTSTONE = "The building blocks of civilization.",
		DEADLYFEAST = "It smells... noxious.",
		DEERCLOPS = "Even I'm afraid of that guy.",
		DEERCLOPS_EYEBALL = "Deerclops are so myopic.",
		DEPLETED_GRASS =
		{
			GENERIC = "That's not doing anyone any good.",
		},
		DIRTPILE = "That looks out of place.",
		DIVININGROD =
		{
			COLD = "Mostly just background noise.",
			GENERIC = "I can use this to find my missing parts.",
			HOT = "It must be right under my nose!",
			WARM = "This is the right direction.",
			WARMER = "I should keep my eyes peeled.",
		},
		DIVININGRODBASE =
		{
			GENERIC = "It's the starting mechanism.",
			READY = "I need to insert the divining rod.",
			UNLOCKED = "Progress!",
		},
		DIVININGRODSTART = "The portals lead to the next rod.",
		DRAGONFLY = "A fiery fly.",
		LAVASPIT = 
		{
			HOT = "Spitfire.",
			COOL = "It's cold and dry now.",
		},
		DRAGONFRUIT = "Exotic and delicious.",
		DRAGONFRUIT_COOKED = "A little more refined, at least.",
		DRAGONFRUIT_SEEDS = "Such labor is beneath me.",
		DRAGONPIE = "Simply exquisite.",
		DRUMSTICK = "It tastes strangely like berries.",
		DRUMSTICK_COOKED = "Still tastes like berries.",
		DUG_BERRYBUSH = "Do I look like a gardener?",
		DUG_GRASS = "Do I look like a gardener?",
		DUG_MARSH_BUSH = "Do I look like a gardener?",
		DUG_SAPLING = "I can't believe I'm reduced to this.",
		DURIAN = "It's an acquired taste.",
		DURIAN_COOKED = "A little more refined, at least.",
		DURIAN_SEEDS = "Such labor is beneath me.",
		EARMUFFSHAT = "They're warm, at least.",
		EGGPLANT = "Just another boring plant.",
		EGGPLANT_COOKED = "A little more refined, at least.",
		EGGPLANT_SEEDS = "Such labor is beneath me.",
		ACORN = 
		{
		    GENERIC = "A more outdoorsy type might be able to make something of this.",
		    PLANTED = "Huh, it seems to belong in the ground.",
		},
		EVERGREEN =
		{
			BURNING = "Oops.",
			BURNT = "Bathed in fire.",
			CHOPPED = "That's not about to grow back.",
			GENERIC = "I've heard them described as \"piney\".",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "Oops.",
			BURNT = "Dust to dust.",
			CHOPPED = "I put it out of its misery.",
			GENERIC = "It looks sickly.",
		},
		EYEPLANT = "The Meat Bulb's pawns.",
		FEATHERHAT = "I will lure them in with my plumage.",
		FEATHER_CROW = "Black is the color of sleep.",
		FEATHER_ROBIN = "Red is the color of fire.",
		FEATHER_ROBIN_WINTER = "Grey is the color of pain.",
		FEM_PUPPET = "Better her than me.",
		FIREFLIES =
		{
			GENERIC = "How pretty.",
			HELD = "I could squish them if I wanted to.",
		},
		FIREHOUND = "I put fire gems in there as a joke.",
		FIREPIT =
		{
			EMBERS = "I should attend to that.",
			GENERIC = "A fire pit.",
			HIGH = "A roaring fire.",
			LOW = "It's getting low.",
			NORMAL = "It's hot.",
			OUT = "It's gone cold.",
		},
		FIRESTAFF = "A basic enchantment, but effective.",
		FISH = "Fresh from the murky depths.",
		FISHINGROD = "I will eat for a lifetime.",
		FISHSTICKS = "These should tide me over.",
		FISHTACOS = "Cooked fish in a crunchy shell.",
		FISH_MED = "Stay.",
		FISH_MED_COOKED = "It still stinks.",
		FISH_COOKED = "It still stinks.",
		FLINT = "Ow! I cut my finger!",
		FLOWER = "I am filled with the irrational urge to stomp upon it.",
		FLOWERHAT = "Definitely not my style.",
		FLOWER_EVIL = "I like that flower.",
		FOLIAGE = "A meal fit for a peasant.",
		FOOTBALLHAT = "Now I am ready for the scrimmage.",
		FROG =
		{
			DEAD = "It croaked.",
			GENERIC = "It jumps and licks things.",
			SLEEPING = "It looks tired.",
		},
		FROGGLEBUNWICH = "Has a bit of a kick to it.",
		FROGLEGS = "Muscular.",
		FROGLEGS_COOKED = "Stringy.",
		FRUITMEDLEY = "This would pair great with a simple cheese plate.",
		GEARS = "My pets! What has become of you?",
		GHOST = "It remembers me!",
        GHOST_SAILOR = "He reminds me of someone...",
		GOLDENAXE = "It gets sharper with every cut.",
		GOLDENPICKAXE = "This must be game logic.",
		GOLDENPITCHFORK = "I'm not sure this was a good investment.",
		GOLDENSHOVEL = "This shovel is worth a princely sum.",
		GOLDNUGGET = "This was important to me once.",
		GRASS =
		{
			BARREN = "Needs manure.",
			WITHERED = "You'd think grass could withstand this heat...",
			BURNING = "Oops.",
			GENERIC = "Tufty.",
			PICKED = "Nothing to harvest.",
		},
		GREEN_CAP = "I should eat it.",
		GREEN_CAP_COOKED = "Salty!",
		GREEN_MUSHROOM =
		{
			GENERIC = "Green fungus.",
			INGROUND = "When do those ones come up?",
			PICKED = "Been there. Done that.",
		},
		GUNPOWDER = "Now this I like.",
		HAMBAT = "An undignified weapon for a less refined time.",
		HAMMER = "It feels good to undo the work of others.",
		HEALINGSALVE = "Just a bit of venom and some dirty old ash.",
		HEATROCK =
		{	
			FROZEN = "It's almost too cold to hold.",
			COLD = "Pleasantly cool.",
			GENERIC = "A pocketful of stone and temperature.",
			WARM = "Comfortably lukewarm.",
			HOT = "It's almost too hot to hold.",
		},
		HOME = "There's no place like it.",
		HOMESIGN = 
		{
			GENERIC = "It says... nothing.",
			BURNT = "Somehow, it says even less now.",
		},
		HONEY = "Sticky and sweet.",
		HONEYCOMB = "It's full of bee maggots.",
		HONEYHAM = "Tender.",
		HONEYNUGGETS = "These look childish, but they're delicious.",
		HORN = "Call forth the beasts!",
		HOUND = "They don't recognize me!",
		HOUNDBONE = "Hungry devils, aren't they?",
		HOUNDMOUND = "It's a tunnel down to the hounds' nest.",
		ICEBOX = "A little piece of winter in a box.",
		INSANITYROCK =
		{
			ACTIVE = "I can see its true nature now!",
			INACTIVE = "It only half-exists on this plane.",
		},
		JAMMYPRESERVES = "It's soiled my good gloves.",
		KABOBS = "Cooked to perfection.",
		KILLERBEE =
		{
			GENERIC = "What is that bee so angry about?",
			HELD = "I've caught a tiger by the tail.",
		},
		KNIGHT = "Such quality workmanship!",
		KOALEFANT_SUMMER = "A distant cousin of the beefalo.",
		KOALEFANT_WINTER = "It has its winter coat on.",
		KRAMPUS = "You won't catch me!",
		KRAMPUS_SACK = "It's really light.",
		LEIF = "Disgusting creature!",
		LEIF_SPARSE = "Disgusting creature!",
		LIGHTNING_ROD =
		{
			CHARGED = "Energy flows through it.",
			GENERIC = "A little bit of protection.",
		},
		LITTLE_WALRUS = "A chip off the old block.",
		LIVINGLOG = "I like the noise they make when you burn them.",
		LOCKEDWES = "He displeased me.",
		LOG =
		{
			BURNING = "Well. That was fun while it lasted.",
			GENERIC = "It's a piece of wood. What more is there to say?",
		},
		LUREPLANT = "A vicious plant.",
		LUREPLANTBULB = "Perhaps I can use this to my advantage.",
		MALE_PUPPET = "Better him than me.",
		MANDRAKE =
		{
			DEAD = "My ears are still ringing.",
			GENERIC = "Oh shut UP, will you?",
			PICKED = "What a disturbing root.",
		},
		MANDRAKESOUP = "There'll be no more crying out of you.",
		MANDRAKE_COOKED = "Looks like I got the last meep.",
		MARBLE = "It's strong stuff.",
		MARBLEPILLAR = "I've always wondered who built those.",
		MARBLETREE = "How whimsical.",
		MARSH_BUSH =
		{
			BURNING = "I should ask it questions.",
			GENERIC = "It's twisted and thorny, just like me!",
			PICKED = "That was painful.",
		},
		MARSH_PLANT = "What a generic little plant.",
		MARSH_TREE =
		{
			BURNING = "There it goes.",
			BURNT = "It's no use to anyone now.",
			CHOPPED = "Tree 0, Maxwell 1.",
			GENERIC = "A tree with a foul demeanor.",
		},
		MAXWELL = "Looking good!",
		MAXWELLHEAD = "Hey, handsome.",
		MAXWELLLIGHT = "Aw, it remembers me.",
		MAXWELLLOCK = "It keeps the master in the chair.",
		MAXWELLTHRONE = "It's less painful than it looks. Barely.",
		MEAT = "I'm used to much finer fare.",
		MEATBALLS = "My compliments to the chef!",
		MEAT_DRIED = "My teeth are getting too old for this.",
		MERM = "They were already here when I arrived.",
		MINERHAT = "Eventually the firefly will starve.",
		MONKEY = "I don't have time for you!",
		MONKEYBARREL = "What a disgusting home.",
		MONSTERLASAGNA = "It would be unwise to ingest this.",
		MONSTERMEAT = "How revolting.",
		MONSTERMEAT_DRIED = "My teeth are getting too old for this.",
		MOSQUITO =
		{
			GENERIC = "Bloody bloodsucking bloodsuckers.",
			HELD = "I got him.",
		},
		MOSQUITOSACK = "A bloody sack. With blood in it.",
		MOUND =
		{
			DUG = "Already got that one.",
			GENERIC = "What lies beneath?",
		},
		NIGHTLIGHT = "It burns with a beautiful glow.",
		NIGHTMAREFUEL = "Ahhh. Refreshing.",
		NIGHTSWORD = "Snicker-snack!",
		NITRE = "One third of the way there...",
		ONEMANBAND = "It has a good beat, and you can dance to it.",
		PANDORASCHEST = "It's a trap.",
		PANFLUTE = "I'm going to sing a song of madness.",
		PAPYRUS = "A blank canvas.",
		PENGUIN = "Nice tux.",
		PERD = "It is addicted to fermented berries.",
		PEROGIES = "I made it, so you know it's good.",
		PETALS = "I've a habit of destroying beautiful things, don't I?",
		PETALS_EVIL = "It's dripping with nightmare essence.",
		PICKAXE = "Everybody loves a little mining.",
		PIGGYBACK = "Oh, that's just demeaning.",
		PIGKING = "That's a man with his priorities in order!",
		PIGMAN =
		{
			DEAD = "I dub thee \"Bacon\".",
			FOLLOWER = "He's simple, but he's mine.",
			GENERIC = "What a slobbering fool.",
			GUARD = "They're starting to organize.",
			WEREPIG = "That one's gone feral.",
		},
		PIGSKIN = "It was him or me.",
		PIGTENT = "That's just nasty.",
		PIGTORCH = "Great. Now they have fire.",
		PINECONE = 
		{
		    GENERIC = "A more outdoorsy type might be able to make something of this.",
		    PLANTED = "Huh, it seems to belong in the ground.",
		},
		PITCHFORK = "The tool of choice for perfectionists.",
		PLANTMEAT = "A feeble attempt to trick the weak minded.",
		PLANTMEAT_COOKED = "The heat has made this a suitable meal.",
		PLANT_NORMAL =
		{
			GENERIC = "That is a generic plant.",
			GROWING = "It's growing.",
			READY = "It's ready.",
			WITHERED = "It wasn't hardy enough for the heat.",
		},
		POMEGRANATE = "Usually I'd get someone to seed this for me.",
		POMEGRANATE_COOKED = "A little more refined, at least.",
		POMEGRANATE_SEEDS = "Such labor is beneath me.",
		POND = "I can see my face reflected off the top.",
		POOP = "It's the way of all mortal life.",
		PUMPKIN = "Hallowe'en was always my favorite.",
		PUMPKINCOOKIE = "It's been eons since I had a good biscuit.",
		PUMPKIN_COOKED = "A little more refined, at least.",
		PUMPKIN_LANTERN = "Why hello, Mr. Crane.",
		PUMPKIN_SEEDS = "Such labor is beneath me.",
		PURPLEAMULET = "It speaks with the shadow.",
		PURPLEGEM = "Purple brings great power.",
		RABBIT =
		{
			GENERIC = "I've been here too long... it actually looks tasty.",
			HELD = "Don't worry, rabbit. Everything is under control.",
		},
		RABBITHOLE = 
		{
			GENERIC = "There's a world going on under there.",
			SPRING = "The entrance has collapsed in on itself.",
		},
		RATATOUILLE = "Roughage.",
		RAZOR = "If only the world had a single neck.",
		REDGEM = "Red brings fire.",
		RED_CAP = "I forget what this one does.",
		RED_CAP_COOKED = "Kind of bitter.",
		RED_MUSHROOM =
		{
			GENERIC = "It's a red mushroom.",
			INGROUND = "It'll have to come back for it.",
			PICKED = "It's all used up.",
		},
		REEDS =
		{
			BURNING = "Oops.",
			GENERIC = "There's wind in them there willows.",
			PICKED = "No more tubes.",
		},
        RELIC = 
        {
            GENERIC = "Remnants of an extinct civilization.",
            BROKEN = "Just bits and pieces of rock.",
        },
        RUINS_RUBBLE = "A broken relic.",
        RUBBLE = "Just bits and pieces of rock.",
		RESURRECTIONSTONE = "There's a story behind that...",
		ROBIN =
		{
			GENERIC = "The redbird comes from the fire lands.",
			HELD = "Silence, bird!",
		},
		ROBIN_WINTER =
		{
			GENERIC = "I don't recognize that one.",
			HELD = "Quiet, you.",
		},
		ROBOT_PUPPET = "Better it than me.",
		ROCK_LIGHT =
		{
			GENERIC = "The top of this lava pit has cooled into a fine crust.",
			OUT = "It looks harmless.",
			LOW = "The fires are cooling.",
			NORMAL = "It's hot.",
		},
		ROCK = "It's a rock.",
		ROCKS = "Hmmm. Now what do I do with them?",
        ROOK = "A castle for my home.",
		ROPE = "You'd think this would have more uses.",
		ROTTENEGG = "Disgusting. Why am I keeping this around?",
		SANITYROCK =
		{
			ACTIVE = "I can see its true nature now!",
			INACTIVE = "There are two ways to see that obstacle.",
		},
		SAPLING =
		{
			BURNING = "Oops.",
			WITHERED = "Nothing survives in this heat.",
			GENERIC = "A supple, woody stem.",
			PICKED = "It'll grow back.",
		},
		SEEDS = "I suppose these won't plant themselves.",
		SEEDS_COOKED = "I broiled the life out of 'em.",
		SEWING_KIT = "A fine and noble endeavor.",
		SHOVEL = "This is some real advanced technology.",
		SILK = "Despite its origin, it could make some fine garments.",
		SKELETON = "Ha! I remember that one.",
		SKELETON_PLAYER = "The master becomes the student.",
		SKULLCHEST = "That's one snazzy chest.",
		SMALLBIRD =
		{
			GENERIC = "What!? What do you want?",
			HUNGRY = "You want some food?",
			STARVING = "He's so hungry!",
		},
		SMALLMEAT = "This is barely a mouthful.",
		SMALLMEAT_DRIED = "My teeth are getting too old for this.",
		SPEAR = "It's a spear. Yup.",
		SPIDER =
		{
			DEAD = "Splat.",
			GENERIC = "It's mostly digestive system.",
			SLEEPING = "Shhhh! It will wake up hungry.",
		},
		SPIDERDEN = "They grow big here.",
		SPIDEREGGSACK = "Squishy.",
		SPIDERGLAND = "Distasteful.",
		SPIDERHAT = "Spiders have such malleable wills.",
		SPIDERQUEEN = "Maybe I'll just get out of her way.",
		SPIDER_WARRIOR =
		{
			DEAD = "Splat.",
			GENERIC = "It's a specialized form.",
			SLEEPING = "I don't want to wake that one.",
		},
		SPOILED_FOOD = "That used to be food until I wasted it.",
		STATUEHARP = "Not my best work.",
		STATUEMAXWELL = "Now that's a fine statue.",
		STINGER = "It's dripping with venom.",
		STEELWOOL = "Someone should use this to clean something.",
		STRAWHAT = "A hat fit for a peasant.",
		STUFFEDEGGPLANT = "A meal fit for a king... or at least someone with a throne.",
		SUNKBOAT = "That's not how you use a boat!",
		SWEATERVEST = "It's no three-piece, but it's dapper enough.",
		TAFFY = "It's almost entirely sugar.",
		TALLBIRD = "These were a failed experiment.",
		TALLBIRDEGG = "Tallbirds are territorial because of these things.",
		TALLBIRDEGG_COOKED = "It tastes like broken dreams.",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "It's getting tepid.",
			GENERIC = "We've got a live one here.",
			HOT = "Hot enough for ya?",
			LONG = "It's going to be a while.",
			SHORT = "Any moment now...",
		},
		TALLBIRDNEST =
		{
			GENERIC = "Well. That's tempting.",
			PICKED = "It's made of dirty beefalo hair.",
		},
		TEENBIRD =
		{
			GENERIC = "It's less cute now that it's grown up.",
			HUNGRY = "They sure do eat a lot.",
			STARVING = "A hungry beast is a dangerous beast.",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "It's alive!",
			GENERIC = "My beautiful machine is in pieces!",
			LOCKED = "Now to turn it on.",
			PARTIAL = "It is still incomplete.",
		},
		TELEPORTATO_BOX = "This is a box full of sadness and woe.",
		TELEPORTATO_CRANK = "This is used to agitate the humors.",
		TELEPORTATO_POTATO = "The gears in here are so small they turn the fabric of reality.",
		TELEPORTATO_RING = "This is the quantum field guard band.",
		TELESTAFF = "Magic can do amazing things, when funneled through the right channels.",
		TENTACLE = "I'm glad the rest of it is still down there.",
		TENTACLESPIKE = "Ugh. This is so revolting.",
		TENTACLESPOTS = "This is how they reproduce.",
		TENTACLE_PILLAR = "How deep does this go?",
		TENTACLE_GARDEN = "This one is odd.",
        TENTACLE_PILLAR_ARM = "Babies?",
		TOPHAT = "Some fine haberdashery.",
		TORCH = "It keeps Charlie at bay.",
		TRAP = "Only the dumbest animals will fall for this.",
		TRAP_TEETH = "This one packs a wallop.",
		TRAP_TEETH_MAXWELL = "I'm sure I had my reasons when I placed this.",
		TREASURECHEST_TRAP = "Hmmm. Looks suspicious.",
		TREECLUMP = "I can't get through there.",
		TRINKET_1 = "These must have been heated to an incredible temperature.",
		TRINKET_10 = "These are gross, and that's the tooth.",
		TRINKET_11 = "I'm not listening.",
		TRINKET_12 = "I'm not touching that without several pairs of gloves.",
		TRINKET_2 = "This was important to someone once.",
		TRINKET_3 = "A tangled mess. Like life.",
		TRINKET_4 = "Don't look at me like that.",
		TRINKET_5 = "A toy for a child's mind.",
		TRINKET_6 = "Just useless old wires.",
		TRINKET_7 = "Not something a grown man should be caught playing with.",
		TRINKET_8 = "I'd prefer a pocketwatch on a chain.",
		TRINKET_9 = "My suits don't deserve to be defaced with these tacky atrocities.",
		TRUNKVEST_SUMMER = "It's more of a fall vest.",
		TRUNKVEST_WINTER = "It's so hard to look fashionable in the winter.",
		TRUNK_COOKED = "At least the mucus burned off.",
		TRUNK_SUMMER = "Full of summer mucus.",
		TRUNK_WINTER = "The trunk thickens in the winter to hold more mucus.",

		TURF_CARPETFLOOR = "That's a quality, high-pile carpet sample!",
		TURF_CHECKERFLOOR = "That's my natural habitat.",
		TURF_DIRT = "Dusty.",
		TURF_FOREST = "Smells like mud.",
		TURF_GRASS = "Scratchy.",
		TURF_MARSH = "It's dripping all over.",
		TURF_ROAD = "At least this one is useful.",
		TURF_ROCKY = "Kinda rough.",
		TURF_SAVANNA = "Dirty.",
		TURF_WOODFLOOR = "I prefer hardwoods.",

		TURF_CAVE="Turf.",
		TURF_FUNGUS="Turf.",
		TURF_SINKHOLE="Turf.",
		TURF_UNDERROCK="Turf.",
		TURF_MUD="Turf.",

		TURKEYDINNER = "How festive.",
		TWIGS = "Common, but useful.",
		UMBRELLA = "It's crooked!",
		WAFFLES = "An excellent start to the morning. Or evening.",
		WALL_HAY_ITEM = "Pocket-sized wall pieces. Yup.",
		WALL_STONE = "This will keep the riff-raff out.",
		WALL_STONE_ITEM = "Pocket-sized wall pieces. Yup.",
		WALL_WOOD_ITEM = "Pocket-sized wall pieces. Yup.",
		WALL_RUINS = "An ancient wall.",
		WALL_RUINS_ITEM = "Pocket-sized wall pieces. Yup.",
		WALRUS = "Don't you recognize me?",
		WALRUSHAT = "Made in Scotland.",
		WALRUS_CAMP =
		{
			EMPTY = "I best not linger when winter comes.",
			GENERIC = "The Walrusser can't be far.",
		},
		WALRUS_TUSK = "I'll put this to better use.",
		WASPHIVE = "That looks dangerous.",
		WETGOOP = "How uncultured.",
		WINTERHAT = "How disappointingly rustic.",
		WORMHOLE =
		{
			GENERIC = "It's worse knowing what the other part looks like.",
			OPEN = "I assure you that it smells worse than it looks.",
		},
		WORMHOLE_LIMITED = "It looks ill.",
		ACCOMPLISHMENT_SHRINE = "Even THEY couldn't build something so devious.",

		AERODYNAMICHAT = "Quite sleek, if not elegant.",
		ANTIVENOM = "A cure to what ails you.",
		ARMORCACTUS = "Nothing says \"stay away\" quite like this.",
		ARMORLIMESTONE = "It renders me... sluggish.",
		ARMOROBSIDIAN = "I've bent the flame to my will.",
		ARMORSEASHELL = "Perhaps not the sturdiest, but it will conceal my vulnerabilities.",
		ARMOR_LIFEJACKET = "Sadly my cultured countenance must take a backseat to sensibility.",
		ARMOR_SNAKESKIN = "Quite dapper!",
		ARMOR_WINDBREAKER = "Sigh.",
		ARMOUREDBOAT = "This boat knows how to take a hit like a champion.",
		BABYOX = "Stop chewing my cufflinks, wretched cur.",
		BALLPHIN = "They're much craftier than they appear at first glance.",
		BAMBOO = "I have several ideas in mind for this.",
		BAMBOOTREE =
		{
			BURNT = "It will not be returning.",
			CHOPPED = "It needs time to replenish.",
			GENERIC = "It can grow through just about anything.",
		},
		BERMUDATRIANGLE = "It's calling to me to dive in.",
		BIGFISHINGROD = "Perhaps I'll have better luck with the swimming meat now.",
		BIOLUMINESCENCE = "Quite otherworldly, no?",
		BLOWDART_FLUP = "This is quite a stunning contraption.",
		BLOWDART_POISON = "I've turned the venom of this world against itself.",
		BLUBBER = "I believe I can... eat it...",
		BLUBBERSUIT = "This is undignified.",
		BOATCANNON = "It's about time I got my hands on one of these.",
		BOATREPAIRKIT = "It will hold off my vessel's inevitable decay.",
		BOAT_LANTERN = "It lends an eerie glow to all around it.",
		BOAT_TORCH = "Sailing at night seems unsafe, but this makes it somewhat better.",
		BOTTLELANTERN = "Their lives have found purpose in servitude.",
		BRAINJELLYHAT = "I feel inspired.",
		BUOY = "It floats with ease.",
		BURIEDTREASURE = "Ah, what's this then?",
		BUSH_VINE =
		{
			BURNT = "It's met its end.",
			CHOPPED = "Used up, for now.",
			GENERIC = "These have taken over the island.",
		},
		CAPTAINHAT = "It makes me feel commanding.",
		CARGOBOAT = "Ah, plenty of room to breathe.",
		CHIMINEA = "Safe keeping for my hard earned fires.",
		CLOTHSAIL = "It will aid in my travels.",
		COCONADE =
		{
			BURNING = "I may want to take cover.",
			GENERIC = "I foresee death in the future.",
		},
		COCONUT = 
		{
		    GENERIC = "Could do considerable damage to a person's noggin.",
		    PLANTED = "It can't hurt anyone anymore.",
		},
		COCONUT_COOKED = "It will last me for now.",
		COCONUT_HALVED = "I made one coconut into two... Magic!",
		COFFEE = "I look forward to this.",
		COFFEEBEANS = "It's strange to see them this color.",
		COFFEEBEANS_COOKED = "Better than raw, but perhaps there's a better way to prepare them?",
		COFFEEBOT = "It will do my coffee-related bidding.",
		COFFEEBUSH =
		{
			BARREN = "Barren.",
			GENERIC = "Delightful coffee beans.",
			PICKED = "I've picked them all.",
			WITHERED = "Decay has overtaken it.",
		},
		COMPASS =
		{
			GENERIC="Hm. I'm unable to get a reading.",
			N = "North.",
			S = "South.",
			E = "East.",
			W = "West.",
			NE = "Northeast.",
			SE = "Southeast.",
			NW = "Northwest.",
			SW = "Southwest.",
		},
		CORAL = "It's quite lovely.",
		CORALREEF = "This could likely support a wide array of life.",
		CORAL_BRAIN = "Now I can harness its thoughtpower for myself.",
		CORAL_BRAIN_ROCK = "I wonder what it's thinking?",
		CRAB =
		{
			GENERIC = "An edible crustacean.",
			HIDDEN = "The crabbit is hiding.",
		},
		CRABHOLE = "It can't hide forever.",
		CRATE = "Perhaps I could pry it open.",
		CUTLASS = "A gentleman's weapon.",
		DEAD_SWORDFISH = "Perhaps it should have taken more fencing lessons.",
		DEPLETED_BAMBOOTREE = "It's gone.",
		DEPLETED_BUSH_VINE = "No more.",
		DEPLETED_GRASS_WATER = "That was all there was.",
		DEVTOOL = "How odd.",
		DEVTOOL_NODEV = "I fear I cannot grasp it.",
		DOUBLE_UMBRELLAHAT = "This looks silly.",
		DOYDOY = "This sad creature has no hope of survival.",
		DOYDOYBABY = "Now there will be more of them.",
		DOYDOYEGG = "Hmm, propagate a dying species or enjoy a light snack?",
		DOYDOYEGG_COOKED = "A light snack is always the best option.",
		DOYDOYEGG_CRACKED = "Whoops.",
		DOYDOYFEATHER = "It would look dashing tucked in a Sunday hat.",
		DOYDOYNEST = "What are their chances, you think?",
		DRAGOON = "Don't you know who I am?",
		DRAGOONDEN = "I see no reason to disturb them.",
		DRAGOONEGG = "It radiates an oppressive heat.",
		DRAGOONHEART = "Hearts only bring pain anyway.",
		DRAGOONSPIT = "Quite uncouth.",
		DUBLOON = "The clinking sound when they rub together is intensely satisfying.",
		DUG_BAMBOOTREE = "I suppose I should find a place for this.",
		DUG_BUSH_VINE = "I should find a proper place for this.",
		DUG_COFFEEBUSH = "This is worth replanting.",
		DUG_ELEPHANTCACTUS = "I'd better not run with it.",
		EARRING = "I would look quite dashing in it, were my ear pierced.",
		ELEPHANTCACTUS = "It won't be shooting anyone like this.",
		ELEPHANTCACTUS_ACTIVE = "Take cover!",
		ELEPHANTCACTUS_STUMP = "Good riddance.",
		FABRIC = "I've fashioned the bamboo into something useful.",
		FEATHERSAIL = "I suppose it's better than paddling.",
		FISHINHOLE = "They would be much more content in my stomach.",
		FISH_RAW = "Could use a touch of fire.",
		FISH_RAW_SMALL = "Have I been reduced to this?",
		FISH_RAW_SMALL_COOKED = "...Bottoms up.",
		FLAMEGEYSER = "That puts on quite a spectacle.",
		FLOTSAM = "Perhaps I could reel it in somehow.",
		FLUP = "That thing is quite beneath me.",
		FRESHFRUITCREPES = "Deserves to be eaten with fine silverware. Sadly, I've just my hands.",
		FROG_POISON = "I had better teach it some manners.",
		GASHAT = "Cleans the stench away.",
		GOLDENMACHETE = "I've always wanted to hack things in luxury.",
		GRASS_WATER = "It is partially submerged.",
		HAIL_ICE = "Slightly chilly.",
		HOUNDFIRE = "A biting flame!",
		ICEMAKER =
		{
			HIGH = "It's working hard to make ice for me.",
			LOW = "I'd better fill it up.",
			NORMAL = "It appears to be doing its job.",
			OUT = "It's not doing its job.",
			VERYLOW = "It's on its last legs.",
		},
		IRONWIND = "Thank goodness, I have places to be!",
		JELLYFISH = "What a strange little creature.",
		JELLYFISH_COOKED = "It will do, I suppose.",
		JELLYFISH_DEAD = "I like it better dead.",
		JELLYFISH_PLANTED = "It's quite shocking.",
		JELLYJERKY = "I actually don't mind this?",
		JUNGLETREE =
		{
			BURNING = "It is not long for this world.",
			BURNT = "In another lifetime, perhaps.",
			CHOPPED = "I have used it for my own purposes.",
			GENERIC = "I believe it wants me to chop it down.",
		},
		JUNGLETREESEED =
        {
            GENERIC = "I could replant this, theoretically.",
            PLANTED = "Good. I was right.",
        },
		KNIGHTBOAT = "Obey me, fool!",
		KRAKEN = "You will bow to me.",
		KRAKENCHEST = "Now for my reward.",
		KRAKEN_TENTACLE = "How dare you touch me?",
		LAVAPOOL = "Exceptionally toasty.",
		LIMESTONE = "Perhaps this sealife's death will find use after all.",
		LIMPETROCK =
		{
			GENERIC = "Could be used as a food source in a pinch.",
			PICKED = "Just a rock now.",
		},
		LIMPETS = "Slimy and vaguely ingestible.",
		LIMPETS_COOKED = "A delicacy? Really?",
		LIVINGJUNGLETREE = "Nothing out of the ordinary here.",
		TREEGUARD = "Cease this nonsense.",
		LOBSTER = "Now that looks like a proper meal.",
		LOBSTERHOLE = "Show yourself, delicious critters.",
		LOBSTER_DEAD = "Excellent.",
		LOBSTER_DEAD_COOKED = "I forgot my bib.",
		LOGRAFT = "It seems like there should be regulations against this.",
		LUGGAGECHEST = "Quite a dapper briefcase if I do say so.",
		MACHETE = "Truthfully I was always a hack.",
		MAGIC_SEAL = "I sense a powerful force within it.",
		MAGMAROCK = "Well, it's a rock.",
		MAGMAROCK_FULL = "Well, it's a rock.",
		MAGMAROCK_GOLD = "This rock is much more luxurious.",
		MAGMAROCK_GOLD_FULL = "This rock is much more luxurious.",
		MANGROVETREE = "A tree like any other... but wet.",
		MANGROVETREE_BURNT = "It has been destroyed.",
		MARSH_PLANT_TROPICAL = "Not of much use to me.",
		MERMFISHER = "I have no quarrel with him.",
		MERMHOUSE_FISHER = "I suppose everyone needs to live somewhere...",
		MESSAGEBOTTLE = "What is this primitive communication?",
		MESSAGEBOTTLEEMPTY = "Given enough time I could build a ship inside.",
		MONKEYBALL = "What am I supposed to do with this?",
		MONSTERTARTARE = "It's less than appetizing.",
		MOSQUITOSACK_YELLOW = "I'll be taking that blood back, thank you.",
		MOSQUITO_POISON = "I would like to avoid being bitten by this one.",
		MUSSEL = "They're a delicacy... somewhere.",
		MUSSELBOUILLABAISE = "I truly look forward to a full meal.",
		MUSSEL_COOKED = "Looks to be less of a health hazard now.",
		MUSSEL_FARM =
		{
			GENERIC = "It appears to be a convenient gathering of food.",
			STICKPLANTED = "They're oblivious to their approaching death.",
		},
		MUSSEL_STICK = "The mussels won't be able to resist.",
		MYSTERYMEAT = "Rather disgusting.",
		NEEDLESPEAR = "Exceedingly sharp.",
		OBSIDIAN = "What a delightful color.",
		OBSIDIANAXE = "It seems to work best when alight.",
		OBSIDIANCOCONADE = "This is definitely overkill.",
		OBSIDIANFIREPIT =
		{
			EMBERS = "I should attend to that.",
			GENERIC = "The stone was born for this.",
			HIGH = "A roaring fire.",
			LOW = "It's getting low.",
			NORMAL = "It's burning in style.",
			OUT = "It's gone cold.",
		},
		OBSIDIANMACHETE = "This seems like a dangerous thing to farm with.",
		OBSIDIANSPEARGUN = "Projectile flame. I quite like it.",
		OBSIDIAN_WORKBENCH = "This workstation ignites a spark of creativity in my heart...",
		OCTOPUSCHEST = "It looks... rotten.",
		OCTOPUSKING = "I could use his generosity to my advantage.",
		OX = "It is smelly and very stupid.",
		OXHAT = "Sometimes one must sacrifice form for function.",
		OX_FLUTE = "Goodness. It's been awhile since I played.",
		OX_HORN = "The beast stood no chance.",
		PACKIM = "His irritating appearance is tempered by his usefulness and willing servitude.",
		PACKIM_FISHBONE = "I think I should hold onto it.",
		PALMLEAF = "Now I just need servants to fan my glorious self!",
		PALMLEAF_HUT = "Phew.",
		PALMTREE =
		{
			BURNING = "It is not long for this world.",
			BURNT = "In another lifetime, perhaps.",
			CHOPPED = "I have used it for my own purposes.",
			GENERIC = "How luxurious.",
		},
		PARROT = "Hm. Colorful.",
		PARROT_PIRATE = "Perhaps I can shut him up.",
		PEACOCK = "This creature understands showmanship.",
		PEG_LEG = "Good for whacking.",
		PIKE_SKULL = "Drab.",
		PIRATEGHOST = "I'll not be meeting the same fate!",
		PIRATEHAT = "Is this amusing?",
		PIRATEPACK = "I suppose it will do.",
		PIRATIHATITATOR =
		{
			BURNT = "Ashes to ashes.",
			GENERIC = "Such a fascinating device.",
		},
		POISONHOLE = "I can see it just fine from here... No need to get closer.",
		PORTAL_SHIPWRECKED = "Useless!",
		PRIMEAPE = "This pitiful creature possesses only a modicum of intelligence.",
		PRIMEAPEBARREL = "Keep me away from that.",
		RAFT = "Much too precarious for my liking.",
		RAWLING = "Oh good. A talking sack of stuffing.",
		REDBARREL = "It's bursting with potential.",
		ROCK_CHARCOAL = "I can't help but admire the natural formations.",
		ROCK_OBSIDIAN = "It refuses to bend to my tools.",
		ROWBOAT = "Manually operated. A pity.",
		SAIL = "It will be smooth sailing with this at my back.",
		SAIL_STICK = "A stick, presumably for sailing.",
		SAND = "Rocks so thoroughly beaten down they are no longer recognizable.",
		SANDBAG = "A bag of dirt that keeps water out.",
		SANDBAGSMALL = "A bag of dirt that keeps water out.",
		SANDBAGSMALL_ITEM = "A bag of dirt I can carry.",
		SANDBAG_ITEM = "A bag of dirt I can carry.",
		SANDHILL = "A little mound of yellow sand.",
		SAND_CASTLE =
		{
			GENERIC = "I found that wholly unenjoyable. I swear.",
			SAND = "Decorative sand.",
		},
		SEAGULL = "It is loud and irritating.",
		SEAGULL_WATER = "Rather uncivil.",
		SEASACK = "It won't make me stronger, but it'll give me more pockets.",
		SEASHELL = "Holding it makes me feel like a tourist.",
		SEASHELL_BEACHED = "A little kitschy for my taste.",
		SEATRAP = "The curiosity will get the best of you eventually.",
		SEAWEED = "Sea garbage.",
		SEAWEED_COOKED = "I'm loathe to eat this.",
		SEAWEED_DRIED = "Ugh.",
		SEAWEED_PLANTED = "It thrives here.",
		SHADOWSKITTISH_WATER = "Oh dear.",
		SHARKITTEN = "A charming monstrosity.",
		SHARKITTENSPAWNER =
		{
			GENERIC = "The pile stirs when I mention treats.",
			INACTIVE = "An ordinary pile of sand.",
		},
		SHARK_FIN = "A trophy from a most excellent kill.",
		SHARK_GILLS = "I suppose they're worth hanging on to.",
		SHARK_TEETHHAT = "I respect this fashion choice.",
		SHARX = "It's not a question of \"if\" I will conquer it, but when.",
		SHIPWRECKED_ENTRANCE = "I hope you're prepared.",
		SHIPWRECKED_EXIT = "Farewell.",
		SLOTMACHINE = "I admittedly have a penchant for tempting fate.",
		SLURPERPELT = "A fine pelt.",
		SNAKE = "A cruel yet elegant beastie.",
		SNAKEDEN =
		{
			BURNT = "It's met its end.",
			CHOPPED = "Used up, for now.",
			GENERIC = "These have taken over the island.",
		},
		SNAKEOIL = "Perhaps I could turn a profit with this.",
		SNAKESKIN = "The texture is delectable.",
		SNAKESKINHAT = "Quite dashing, actually.",
		SNAKESKINSAIL = "For ease of travel.",
		SNAKE_FIRE = "Something's got that snake heated.",
		SNAKE_POISON = "Perhaps I'll give that one a wide berth.",
		SOLOFISH = "It smells like wet dog.",
		SPEARGUN = "This projectile flinger may come in handy.",
		SPEARGUN_POISON = "I've made sure it packs an extra wallop.",
		SPEAR_LAUNCHER = "This projectile flinger may come in handy.",
		SPEAR_OBSIDIAN = "I've made sure it packs a fiery wallop.",
		SPEAR_POISON = "I've made sure it packs an extra wallop.",
		SPOILED_FISH = "I believe I should dispose of this.",
		STUNGRAY = "It smells quite atrocious.",
		SUNKEN_BOAT =
		{
			ABANDONED = "It's ferociously guarded.",
			GENERIC = "It will never sail again.",
		},
		SUNKEN_BOAT_BURNT = "All things are doomed in time.",
		SUNKEN_BOAT_TRINKET_1 = "Exactly what it looks like. Err... What does it look like?",
		SUNKEN_BOAT_TRINKET_2 = "I feel as though it is mocking my situation.",
		SUNKEN_BOAT_TRINKET_3 = "It has no apparent function.",
		SUNKEN_BOAT_TRINKET_4 = "An advanced little gadget.",
		SUNKEN_BOAT_TRINKET_5 = "It was probably hideous before soaking in bilgewater.",
		SUPERTELESCOPE = "This may help me get the lay of the land.",
		SWEETPOTATOSOUFFLE = "Why, this looks halfway palatable!",
		SWEET_POTATO = "Ready for cooking.",
		SWEET_POTATO_COOKED = "Storebought just doesn't taste the same.",
		SWEET_POTATO_PLANTED = "I've eaten worse things. Much worse.",
		SWEET_POTATO_SEEDS = "Perhaps something will grow if I shove these in the ground.",
		SWIMMINGHORROR = "I've had enough of your kind, fiend.",
		SWORDFISH = "Ah, a sparring partner!",
		TELEPORTATO_SW_BASE = "I see the makings of something quite handsome.",
		TELEPORTATO_SW_BOX = "Another piece of the puzzle.",
		TELEPORTATO_SW_CRANK = "Excellent. Not long now.",
		TELEPORTATO_SW_POTATO = "I do admit it's a little ridiculous.",
		TELEPORTATO_SW_RING = "Ah, another piece.",
		TELESCOPE = "This may help me get the lay of the land.",
		THATCHPACK = "Not much, but the extra space is better than nothing.",
		TIDALPOOL = "Much deeper than it lets on.",
		TIDAL_PLANT = "It's a bit of a runt.",
		TIGEREYE = "Not something a gentleman handles without gloves.",
		TIGERSHARK = "Aptly named.",
		TOUCAN = "Colorful vermin.",
		TRAWLNET = "I see no downside to using this.",
		TRAWLNETDROPPED =
		{
			GENERIC = "Just think of the meals I'll make.",
			SOON = "Into the depths...",
			SOONISH = "It's working its way down.",
		},
		TRIDENT = "A fork fit for ocean royalty.",
		TRINKET_13 = "A welcome change from seawater.",
		TRINKET_14 = "This seems like bad voodoo.",
		TRINKET_15 = "It only has four strings.",
		TRINKET_16 = "Letters and numbers... some sort of secret code?",
		TRINKET_17 = "It was probably hideous before soaking in bilgewater.",
		TRINKET_18 = "A little superglue and it would make a lovely centerpiece.",
		TRINKET_19 = "Neither red nor blue.",
		TRINKET_20 = "Exactly what it looks like. Err... What does it look like?",
		TRINKET_21 = "Might be nice in a hot bath...",
		TRINKET_22 = "Looks like something one would find at a backwater flea market.",
		TRINKET_23 = "It's not communicating with anyone now.",
		TROPICAL_FISH = "It belongs on a skewer.",
		TUNACAN = "Fish is presumably contained inside.",
		TURBINE_BLADES = "It appears expertly engineered.",
		TURF_ASH = "It appears to be some turf.",
		TURF_BEACH = "It appears to be some turf.",
		TURF_DESERTDIRT = "It appears to be some turf.",
		TURF_FUNGUS_GREEN = "It appears to be some turf.",
		TURF_FUNGUS_RED = "It appears to be some turf.",
		TURF_JUNGLE = "It appears to be some turf.",
		TURF_MAGMAFIELD = "It appears to be some turf.",
		TURF_MEADOW = "It appears to be some turf.",
		TURF_SNAKESKINFLOOR = "It appears to be some turf.",
		TURF_SWAMP = "It appears to be some turf.",
		TURF_TIDALMARSH = "It appears to be some turf.",
		TURF_VOLCANO = "It appears to be some turf.",
		TWISTER = "I would rather not get sucked into that.",
		TWISTER_SEAL = "It's, uh... cute?",
		VENOMGLAND = "Could this be the cure?",
		VINE = "It's twisted and gnarled.",
		VOLCANO = "I respect its power.",
		VOLCANOSTAFF = "It feels at home in my hands.",
		VOLCANO_ALTAR =
		{
			GENERIC = "It appears to be a place of offering.",
			OPEN = "Do I dare play with more forces beyond my control?",
		},
		VOLCANO_ALTAR_BROKEN = "A true pity.",
		VOLCANO_ALTAR_TOWER = "What a captivating structure.",
		VOLCANO_EXIT = "I must take my leave.",
		VOLCANO_SHRUB = "Had I any pity, I would give it to this tree.",
		WALLYINTRO_DEBRIS = "What nonsense is this now?",
		WALL_LIMESTONE = "It will hold.",
		WALL_LIMESTONE_ITEM = "Where should I begin building my fortress?",
		WATERMELON_SEEDS = "I could probably plant these.",
		WATERYGRAVE = "Not all find a final resting place.",
		WHALE_BLUE = "Surrender to me.",
		WHALE_BUBBLES = "You've given yourself away, pal.",
		WHALE_CARCASS_BLUE = "Size truly doesn't matter!",
		WHALE_CARCASS_WHITE = "I triumphed over it!",
		WHALE_TRACK = "I'm in hot pursuit!",
		WHALE_WHITE = "We meet again.",
		WILBUR_CROWN = "The inside is filthy.",
		WILBUR_UNLOCK = "Well I suppose there's no sending you back now.",
		WILDBORE = "I'll easily dispose of that swinish brute.",
		WILDBOREHEAD = "Lovely ambiance.",
		WILDBOREHOUSE = "Is this what passes for architecture around here?",
		WIND_CONCH = "Beautiful on the outside, destructive on the inside.",
		WOODLEGSBOAT = "Seems dependable.",
		WOODLEGSHAT = "Swashbuckling...",
		WOODLEGSSAIL = "A fine sail.",
		WOODLEGS_CAGE = "We are all trapped, in one way or another.",
		WOODLEGS_KEY1 = "Brittle.",
		WOODLEGS_KEY2 = "A key of fine gold.",
		WOODLEGS_KEY3 = "Just common iron.",
		WRECK = "It stood no chance.",
		CALIFORNIAROLL = "We meet again, crabbit.",
	},
	DESCRIBE_GENERIC = "You tell me.",
	DESCRIBE_TOODARK = "I can't see in the dark!",
	DESCRIBE_SMOLDERING = "Won't be long before it lights on fire.",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "That was unwise.",
	},
}
