return {
	ACTIONFAIL =
	{
		SHAVE =
		{
			AWAKEBEEFALO = "I'll prune him once he slumbers.",
			GENERIC = "Unshaveworthy.",
			NOBITS = "But there's nothing to trim!",
		},
		STORE =
		{
			GENERIC = "It is already brimming with goods.",
			NOTALLOWED = "I fear that does not go there.",
		},
		RUMMAGE =
        {   
            GENERIC = "If I can't do it, it can't be done!",   
        },
		COOK =
        {
            GENERIC = "Alas! Bested by cookware!",
            TOOFAR = "I must close the gap between us!",
        },
        WRITE =
        {
            GENERIC = "I fear I cannot!",
        },
        GIVE =
        {
            DEAD = "They'll have better things in Valhalla.",
            SLEEPING = "Such sweet slumber... Maybe later.",
            BUSY = "I'll try once more when it's done.",
        },
        CHANGEIN =
        {
            GENERIC = "That's where I keep all my favorite furs and pelts.",
            BURNING = "Gasp! My furs!",
        },
        TEACH =
        {
            KNOWN = "I already wield such knowledge.",
            CANTLEARN = "That knowledge is forbidden by the gods.",
        },
		REPAIRBOAT =
		{
			GENERIC = "My vessel is renewed!",
		},
	},
	ACTIONFAIL_GENERIC = "If I can't do it, it can't be done.",
	ANNOUNCE_MAGIC_FAIL = "Its magicks have weakened!",
	ANNOUNCE_ADVENTUREFAIL = "Back to the Otherworld. Victory is nigh!",
	ANNOUNCE_BEES = "Back, wee speared creatures!",
	ANNOUNCE_BOOMERANG = "Urg! I must master the curved weapon.",
	ANNOUNCE_CHARLIE = "Reveal yourself!",
	ANNOUNCE_CHARLIE_ATTACK = "Coward!",
	ANNOUNCE_COLD = "Brrr! Where are my furs!",
	ANNOUNCE_HOT = "The hot sun tires me.",
	ANNOUNCE_CRAFTING_FAIL = "I lack the required provisions.",
	ANNOUNCE_DEERCLOPS = "A worthy foe approaches!",
	ANNOUNCE_DUSK = "The sun is setting. Darkness waits nearby.",
	ANNOUNCE_EAT =
	{
		GENERIC = "Meat makes my heart sing!",
		PAINFUL = "Ohh, I don't feel well.",
		SPOILED = "Ugh. Fresh would be better.",
		STALE = "That was stale beast.",
		INVALID = "That is not food fit for a warrior!",
		YUCKY = "That food is not fit for a warrior!",
	},
	ANNOUNCE_ENTER_DARK = "And the curtain falls.",
	ANNOUNCE_ENTER_LIGHT = "I step into the light!",
	ANNOUNCE_FREEDOM = "Freedom! The saga continues!",
	ANNOUNCE_HIGHRESEARCH = "I am an excellent craftswoman.",
	ANNOUNCE_HOUNDS = "The beasts are approaching...",
	ANNOUNCE_HUNGRY = "How I long for a feast!",
	ANNOUNCE_HUNT_BEAST_NEARBY = "Hush... The creature is near.",
	ANNOUNCE_HUNT_LOST_TRAIL = "I've lost the tracks.",
	ANNOUNCE_HUNT_LOST_TRAIL_SPRING = "It's too muddy for trailing.",
	ANNOUNCE_INV_FULL = "I'm carrying all I can!",
	ANNOUNCE_KNOCKEDOUT = "Ugh, my head.",
	ANNOUNCE_LOWRESEARCH = "That wasn't very exciting.",
	ANNOUNCE_MOSQUITOS = "Away, tiny demons!",
	ANNOUNCE_NODANGERSLEEP = "It's not safe to sleep. Use the spear!",
	ANNOUNCE_NODAYSLEEP = "The sun is high, journey on!",
	ANNOUNCE_NODAYSLEEP_CAVE = "I won't be resting yet.",
	ANNOUNCE_NOHUNGERSLEEP = "I'll starve overnight! Feast first.",
	ANNOUNCE_NOSLEEPONFIRE = "I won't sleep in the flames.",
	ANNOUNCE_NODANGERSIESTA = "Battle is upon us, there'll be no rest!",
	ANNOUNCE_NONIGHTSIESTA = "No napping in the moonlight.",
	ANNOUNCE_NONIGHTSIESTA_CAVE = "This doesn't feel like the time for a nap.",
	ANNOUNCE_NOHUNGERSIESTA = "I'd like a meat snack first.",
	ANNOUNCE_NO_TRAP = "Thankfully, I am light of foot.",
	ANNOUNCE_PECKED = "Away, feisty beaker!",
	ANNOUNCE_QUAKE = "The world shudders!",
	ANNOUNCE_RESEARCH = "The power of knowledge is great.",
	ANNOUNCE_SHELTER = "Aha! Shelter!",
	ANNOUNCE_THORNS = "Arg, I've been poked!",
	ANNOUNCE_TORCH_OUT = "My light is quenched!",
	ANNOUNCE_TRAP_WENT_OFF = "That wasn't part of the plan.",
	ANNOUNCE_UNIMPLEMENTED = "It is not of this world.",
	ANNOUNCE_WORMHOLE = "That was a sloppy adventure.",
	ANNOUNCE_CANFIX = "\nI can repair this.",
	ANNOUNCE_FAN_OUT = "I've lost another fan!",
	ANNOUNCE_ACCOMPLISHMENT = "May I return to battle now?",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "Victory! All right, let's go.",	
	ANNOUNCE_INSUFFICIENTFERTILIZER = "More droppings for you?",
	ANNOUNCE_TOOL_SLIP = "Slippery devil!",
	ANNOUNCE_LIGHTNING_DAMAGE_AVOIDED = "I rode in on a bolt lightning.",

	ANNOUNCE_DAMP = "Slick for battle.",
	ANNOUNCE_WET = "I am a wet warrior.",
	ANNOUNCE_WETTER = "Does this count as a bath?",
	ANNOUNCE_SOAKED = "I'm nearly drowned!",
	
	ANNOUNCE_OTHER_WORLD_PLANT = "Such a plant could never thrive in this realm!",

	ANNOUNCE_BOAT_DAMAGED = "My vessel is wounded!",
	ANNOUNCE_BOAT_SINKING = "The sea pulls me toward Hel!",
	ANNOUNCE_BOAT_SINKING_IMMINENT = "These black depths will soon claim me!",
	ANNOUNCE_BURNT = "Owwee!",
	ANNOUNCE_CRAB_ESCAPE = "It has vanished!",
	ANNOUNCE_MAPWRAP_LOSECONTROL = "The currents are my master!",
	ANNOUNCE_MAPWRAP_RETURN = "I hath emerged from the fog!",
	ANNOUNCE_MAPWRAP_WARN = "I hath reached the edges of the world!",
	ANNOUNCE_MORETREASURE = "I am smiled upon this day!",
	ANNOUNCE_OTHER_WORLD_TREASURE = "This map describes another land.",
	ANNOUNCE_SHARX = "Foes from the froth!",
	ANNOUNCE_TRAWL_FULL = "My net has been filled with a marvelous bounty.",
	ANNOUNCE_TREASURE = "The map tells of treasure!",
	ANNOUNCE_VOLCANO_ERUPT = "Is Ragnarok upon me?!",
	ANNOUNCE_WAVE_BOOST = "Carry me forth!",
	ANNOUNCE_WHALE_HUNT_BEAST_NEARBY = "A beast lurks beneath the waves...",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL = "I have lost the beast's trail...",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL_SPRING = "I cannot read these rough waters...",

	BATTLECRY =
	{
		GENERIC = "Valhalla awaits!",
		PIG = "I'm having pig tonight!",
		PREY = "Die bravely, feeble foe!",
		SPIDER = "Spider, meet my spear!",
		SPIDER_WARRIOR = "Prepare to be slain!",
	},
	COMBAT_QUIT =
	{
		GENERIC = "Odin will have you yet!",
		PIG = "I'll be back, pigskin!",
		PREY = "I let you go this time!",
		SPIDER = "Leggy coward.",
		SPIDER_WARRIOR = "Flee, monster! I will return.",
	},

	DESCRIBE =
	{		
		BIGFISHINGROD = "I will ensnare delicious fish meat.",
		BIGFOOT = "That's something completely different!",
		COFFEEBOT = "The best machine under the sun.",
		DEPLETED_GRASS_WATER = "It is thoroughly vanquished.",
		HOUNDFIRE = "It burns with eternal passion!",
		INVENTORYGRAVE = "I will see thee in Valhalla!",
		INVENTORYMOUND = "I will see thee in Valhalla!",
		LIMPETS_COOKED = "Let us feast!",
		WOODLEGSBOAT = "I would prefer a longship.",
		WOODLEGSHAT = "Pales in comparison to my helm.",
		WOODLEGSSAIL = "A fearsome sheet.",
		GLOMMER = "A majestic goober.",
        GLOMMERFLOWER = 
        {
        	GENERIC = "A wonder of the woods.",
        	DEAD = "It was once a wonder of the woods.",
        },
        GLOMMERWINGS = "Ohh, look what the goober left for me.",
        GLOMMERFUEL = "This slop could be useful.",
        BELL = "I prefer the ringing resonance of clashing blades.",
        STATUEGLOMMER = 
        {	
        	GENERIC = "A curious homage to the gods.",
        	EMPTY = "That wasn't very respectful of me.",
        },

		WEBBERSKULL = "He fought boldly, but his burial will not be that of a Viking.",
		WORMLIGHT = "Glowing treasure, I can't resist!",
		WORMLIGHT_LESSER = "Glow! Glow with all your might!",
		WORM =
		{
		    PLANT = "I smell a trap.",
		    DIRT = "What's under that dirt?",
		    WORM = "A snake beast from the depths!",
		},
		WORMLIGHT_PLANT = "I smell a trap.",
		MOLE =
		{
			HELD = "A friend for my pocket.",
			UNDERGROUND = "Who's under there?",
			ABOVEGROUND = "He burrows with reckless abandon.",
		},
		MOLEHILL = "Something fiendish lives down there.",
		MOLEHAT = "It's best to use every part of the animal.",

		EEL = "Delicious, slimy snake fish.",
		EEL_COOKED = "Hot eel!",
		UNAGI = "No need for food to be so fancy.",
		EYETURRET = "The eye of the laser god stares into my soul.",
		EYETURRET_ITEM = "An ancient eyeball of protection!",
		MINOTAURHORN = "Can I add this to my helmet?",
		MINOTAURCHEST = "The conquest chest!",
		THULECITE_PIECES = "Looks like shiny popped corn.",
		POND_ALGAE = "Ancient flora.",
		GREENSTAFF = "Twirly green power.",
		POTTEDFERN = "What am I meant to do with such a thing?",

		THULECITE = "This material possesses gargantuan strength!",
		ARMORRUINS = "Armor fit for Odin himself!",
		RUINS_BAT = "A warrior's wand!",
		RUINSHAT = "A crown, that fights!",
		NIGHTMARE_TIMEPIECE =
		{
			CALM = "Nothing stirs.",
			WARN = "It's starting...",
			WAXING = "The magic is heightening!",
			STEADY = "The magic power holds steady.",
			WANING = "It's starting to retreat!",
			DAWN = "Barely any magic remains.",
			NOMAGIC = "The magic slumbers far from here.",
		},
		BISHOP_NIGHTMARE = "Be wary of his blasts!",
		ROOK_NIGHTMARE = "You don't frighten me!",
		KNIGHT_NIGHTMARE = "I don't think I'd ride that horse.",
		MINOTAUR = "What wonders. Let us duel!",
		SPIDER_DROPPER = "You are so sneaky!",
		NIGHTMARELIGHT = "It harnesses dark powers from beneath.",
		NIGHTSTICK = "A weapon worthy of Thor.",
		GREENGEM = "An emerald stone.",
		RELIC = "Old bits of a dwelling.",
		RUINS_RUBBLE = "I'm quite crafty. I could repair that.",
		MULTITOOL_AXE_PICKAXE = "A warrior tool!",
		ORANGESTAFF = "A staff of magical movement.",
		YELLOWAMULET = "A star, captured within an amulet.",
		GREENAMULET = "Enhanced emerald crafting skills!",
		SLURPERPELT = "I do love furs.",	

		SLURPER = "The fur foe thinks she's a hat!",
		SLURPER_PELT = "I do love furs.",
		SLURPERPELT = "I do love furs.",
		ARMORSLURPER = "She ebbs the ache of hunger. Good fur.",
		ORANGEAMULET = "Gathering has never been so easy.",
		YELLOWSTAFF = "It summons stars!",
		YELLOWGEM = "A yellow beaut.",
		ORANGEGEM = "A stone of orange.",
		TELEBASE = 
		{
			VALID = "Prepare yourselves for the power of purple!",
			GEMS = "There's still gems missing.",
		},
		GEMSOCKET = 
		{
			VALID = "Ready!",
			GEMS = "It's empty.",
		},
		STAFFLIGHT = "Behold! A gift from Wotan!",
	
        ANCIENT_ALTAR = "These crafts had better be good.",

        ANCIENT_ALTAR_BROKEN = "This one is not in working order.",

        ANCIENT_STATUE = "Treasure with a mysterious aura.",

        LICHEN = "Sky blue nonsense plant.",
		CUTLICHEN = "I picked it. But I won't eat it.",

		CAVE_BANANA = "Monkey food.",
		CAVE_BANANA_COOKED = "Warmed monkey food.",
		CAVE_BANANA_TREE = "A flimsy monkey tree.",
		ROCKY = "He may be a worthy combat comrade.",
		
		COMPASS =
		{
			GENERIC= "A reading cannot be gleaned.",
			N = "North.",
			S = "South.",
			E = "East.",
			W = "West.",
			NE = "Northeast.",
			SE = "Southeast.",
			NW = "Northwest.",
			SW = "Southwest.",
		},

		NIGHTMARE_TIMEPIECE =
		{
			WAXING = "The magic is heightening!",
			STEADY = "The magic power holds steady.",
			WANING = "It's starting to retreat!",
			DAWN = "Barely any magic remains.",
			WARN = "It's starting...",
			CALM = "Nothing stirs.",
			NOMAGIC = "The magic slumbers far from here.",
		},

		HOUNDSTOOTH="A token of my conquest.",
		ARMORSNURTLESHELL="A shield of sorts.",
		BAT="Dark winged meat.",
		BATBAT = "Winged spear!",
		BATWING="Like the wings of my helm, only meatier.",
		BATWING_COOKED="Cooked dark wing.",
		BEDROLL_FURRY="A luxurious fur bed!",
		BUNNYMAN="I will eat you.",
		FLOWER_CAVE="And it lit up the night, upon the darkest hour.",
		FLOWER_CAVE_DOUBLE="And it lit up the night, upon the darkest hour.",
		FLOWER_CAVE_TRIPLE="And it lit up the night, upon the darkest hour.",
		GUANO="Hmm, dark wing turds.",
		LANTERN="A lantern for the darkness.",
		LIGHTBULB="Glow!",
		MANRABBIT_TAIL="The fuzzy trophy of a successful battle.",
		MUSHTREE_TALL  ="What is this magic?",
		MUSHTREE_MEDIUM="I do like its glow.",
		MUSHTREE_SMALL ="I don't care for mushrooms.",
		RABBITHOUSE=
		{
			GENERIC = "What am I to do with a carrot that big?",
			BURNT = "Good riddance, giant carrot.",
		},
		SLURTLE="You are an angel. Of nasty.",
		SLURTLE_SHELLPIECES="They're smashed up good.",
		SLURTLEHAT="A new battle helm for my collection!",
		SLURTLEHOLE="Not where I'd choose to hang my helm.",
		SLURTLESLIME="Yes. Slime.",
		SNURTLE="I like his helmet.",
		SPIDER_HIDER="I'll smash you!",
		SPIDER_SPITTER="This one's feisty.",
		SPIDERHOLE="Webbing. Never a good sign.",
		STALAGMITE="A cave boulder.",
		STALAGMITE_FULL="A cave boulder.",
		STALAGMITE_LOW="A cave boulder.",
		STALAGMITE_MED="A cave boulder.",
		STALAGMITE_TALL="A pointy rock of sorts.",
		STALAGMITE_TALL_FULL="A pointy rock of sorts.",
		STALAGMITE_TALL_LOW="A pointy rock of sorts.",
		STALAGMITE_TALL_MED="A pointy rock of sorts.",

		TURF_CARPETFLOOR = "It soaks up the blood of battle.",
		TURF_CHECKERFLOOR = "Fancy floor.",
		TURF_DIRT = "A piece of the battlefield.",
		TURF_FOREST = "A piece of the battlefield.",
		TURF_GRASS = "A piece of the battlefield.",
		TURF_MARSH = "A piece of the battlefield.",
		TURF_ROAD = "The road to battle leads wherever I choose.",
		TURF_ROCKY = "A piece of the battlefield.",
		TURF_SAVANNA = "A piece of the battlefield.",
		TURF_WOODFLOOR = "Wooden flooring, a fine surface for mortal combat.",

		TURF_CAVE="A piece of the battlefield.",
		TURF_FUNGUS="A piece of the battlefield.",
		TURF_SINKHOLE="A piece of the battlefield.",
		TURF_UNDERROCK="A piece of the battlefield.",
		TURF_MUD="A piece of the battlefield.",

		POWCAKE = "What in the name of the unicorn is this?",
        CAVE_ENTRANCE = 
        {
            GENERIC="What treasures lie beneath?",
            OPEN = "To the underworld!",
        },
        CAVE_EXIT = "Back to the open skies!",
		MAXWELLPHONOGRAPH = "A mechanical songstress.",
		BOOMERANG = "For flinging at foes!",
		PIGGUARD = "He's battle ready, I can tell.",
		ABIGAIL = "A lady ghost.",
		ADVENTURE_PORTAL = "Adventure is calling.",
		AMULET = "It's red, and a fighter. Just like me!",
		ANIMAL_TRACK = "Oh! I love a good hunt.",
		ARMORGRASS = "Grass protection. It won't last long.",
		ARMORMARBLE = "Nearly impenetrable!",
		ARMORWOOD = "A borrowed tree vest.",
		ARMOR_SANITY = "Strong, but I find my mind wanders...",
		ASH =
		{
			GENERIC = "The flames' remains.",
			REMAINS_GLOMMERFLOWER = "The flower must remain in its homeworld.",
			REMAINS_EYE_BONE = "The eyebone could not pass to this world.",
			REMAINS_THINGIE = "It's burnt. Gone.",
		},
		AXE = "To chop and destroy!",
		BABYBEEFALO = "Mini beastie.",
		BACKPACK = "A portable armory.",
		BANDAGE = "To heal my battle wounds.",
		BASALT = "A thousand mortals couldn't break through this stone.",
		BATBAT = "Wing spear!",
		BEARDHAIR = "Fur of the crazies.",
		BEDROLL_STRAW = "A tool for my naps.",
		BEARGER = "Beast or bear-serker?",
		BEARGERVEST = "I am berserker!",
		ICEPACK = "The backpack of the beast.",
		BEARGER_FUR = "It fought bravely, but I have claimed its hide.",
		BEE =
		{
			GENERIC = "Wee warriors! I don't know if I like them.",
			HELD = "Easy now!",
		},
		BEEBOX =
		{
			FULLHONEY = "It's a honey treasure trove!",
			GENERIC = "A sweet box of wee warriors.",
			NOHONEY = "Where's the honey?",
			SOMEHONEY = "Some honey. Patience is needed.",
			BURNT = "My hive is silent.",
		},
		BEEFALO =
		{
			FOLLOWER = "Come along beastie.",
			GENERIC = "Ancient woolen beasts!",
			NAKED = "Are you cold without your wools?",
			SLEEPING = "Sounds like Aunt Hilda.",
		},
		BEEFALOHAT = "This is going to look good on me, I can tell.",
		BEEFALOWOOL = "I do love woolly things.",
		BEEHAT = "My bee helm, of course.",
		BEEHIVE = "Always buzzing, always plotting.",
		BEEMINE = "It sounds suspicious.",
		BEEMINE_MAXWELL = "Watch your step!",
		BERRIES = "Fruits. I don't like 'em.",
		BERRIES_COOKED = "Warm red mush.",
		BERRYBUSH =
		{
			BARREN = "Should I put some turds on it?",
			WITHERED = "It's too hot to grow.",
			GENERIC = "A fruit bush.",
			PICKED = "The fruits have been snatched.",
		},
		BIFOOT = "Stompy foot.",
		BIRDCAGE =
		{
			GENERIC = "A home for my ravens!",
			OCCUPIED = "Are you having a nice time?",
			SLEEPING = "Sweet dreams, raven friend.",
		},
		BIRDTRAP = "I'm a cunning raven catcher!",
		BIRD_EGG = "Eggy.",
		BIRD_EGG_COOKED = "Hot egg.",
		BISHOP = "This one needs a good smack.",
		BLOWDART_FIRE = "Like the breath of a dragon.",
		BLOWDART_SLEEP = "Goodnight to my foes.",
		BLOWDART_PIPE = "Projectile weaponry!",
		BLUEAMULET = "Cold jewelery.",
		BLUEGEM = "An icy blue sapphire.",
		BLUEPRINT = "Oh, a map! No, wait. That's wrong.",
		BELL_BLUEPRINT = "Oh, a map! No, wait. That's wrong.",
		BLUE_CAP = "Hmm, a blue one.",
		BLUE_CAP_COOKED = "I still don't want to eat it.",
		BLUE_MUSHROOM =
		{
			GENERIC = "It's mold, really.",
			INGROUND = "Good, it's hiding.",
			PICKED = "I hope it doesn't grow again.",
		},
		BOARDS = "Grandfather logs.",
		BOAT = "Is that how I got here?",
		BONESHARD = "Bits of my enemies.",
		BONESTEW = "Delicious!",
		BUGNET = "To snatch insects from the air.",
		BUSHHAT = "For the hunt.",
		BUTTER = "Butter. Might it be good on steak?",
		BUTTERFLY =
		{
			GENERIC = "It is sort of nice.",
			HELD = "Caught!",
		},
		BUTTERFLYMUFFIN = "Muffin, smuffin.",
		BUTTERFLYWINGS = "A pretty souvenir.",
		BUZZARD = "You and I, we meat feast together.",
		CACTUS = 
		{
			GENERIC = "It does have admirable armor.",
			PICKED = "It will return.",
		},
		CACTUS_MEAT_COOKED = "Toasted sword plant meat.",
		CACTUS_MEAT = "Sword plant meat.",
		CACTUS_FLOWER = "Beauty from brawn.",
		COLDFIRE =
		{
			EMBERS = "The fire's nearly dead.",
			GENERIC = "A cold comfort.",
			HIGH = "The fire roars!",
			LOW = "The fire's slowly dying.",
			NORMAL = "A cold comfort.",
			OUT = "And the light flickers out.",
		},
		CAMPFIRE =
		{
			EMBERS = "The fire's nearly dead.",
			GENERIC = "Warm fire, warm Wigfrid.",
			HIGH = "The fire roars!",
			LOW = "The fire's slowly dying.",
			NORMAL = "Warm fire, warm Wigfrid.",
			OUT = "And the light flickers out.",
		},
		CANE = "Turns \"walk\" to \"trot\".",
		CATCOON = "Oh! Cute meat with fur.", 
		CATCOONDEN = 
		{
			GENERIC = "Cute meat lives there.",
			EMPTY = "She fought bravely. Alas, she is gone.",
		},
		CATCOONHAT = "A furry cap! Blessings to you, cute meat.",
		COONTAIL = "It is the tail of cute meat.",
		CARROT = "Where's the protein?",
		CARROT_COOKED = "Sad cooked carrots.",
		CARROT_PLANTED = "A wee root vegetable.",
		CARROT_SEEDS = "Tiny nature bits.",
		CAVE_FERN = "Foliage from the dark ages.",
		CHARCOAL = "Loot from Loge the demigod.",
        CHESSJUNK1 = "It's only a pile of fallen warriors.",
        CHESSJUNK2 = "More fallen mechanical warriors.",
        CHESSJUNK3 = "Someone should really clean this place up.",
		CHESTER = "Don't worry, I won't eat him.",
		CHESTER_EYEBONE =
		{
			GENERIC = "Who are you?",
			WAITING = "The eyeball is tired.",
		},
		COOKEDMANDRAKE = "She's definitely dead.",
		COOKEDMEAT = "Meeeat!",
		COOKEDMONSTERMEAT = "Monster beast steak.",
		COOKEDSMALLMEAT = "Yum, yum, meat snacks.",
		COOKPOT =
		{
			COOKING_LONG = "Might as well do something whilst I wait.",
			COOKING_SHORT = "Shouldn't be long now!",
			DONE = "What have we got here?",
			EMPTY = "Nothing in there.",
			BURNT = "The fire reigned supreme.",
		},
		CORN = "A vegetable sword!",
		CORN_COOKED = "Popped corn smells good.",
		CORN_SEEDS = "Tiny nature bits.",
		CROW =
		{
			GENERIC = "Raven friend!",
			HELD = "Together again.",
		},
		CUTGRASS = "A craftwoman's most elemental resource.",
		CUTREEDS = "I cleaned all the bugs out! Then I ate them.",
		CUTSTONE = "Solid stone!",
		DEADLYFEAST = "A most potent dish.",
		DEERCLOPS = "Rays will shine through my spear and poke out your eyeball!",
		DEERCLOPS_EYEBALL = "Hmm, shall I eat it?",
		EYEBRELLAHAT = "Don't get rain in your eye!",
		DEPLETED_GRASS =
		{
			GENERIC = "It's probably a tuft of grass.",
		},
		DEVTOOL = "It smells of bacon!",
		DEVTOOL_NODEV = "I'm not strong enough to wield it.",
		DIRTPILE = "A small hill of earth.",
		DIVININGROD =
		{
			COLD = "All is quiet.",
			GENERIC = "A mechanical hunting hound. For the hunt.",
			HOT = "Sound the horns! We've arrived!",
			WARM = "We've got the scent!",
			WARMER = "The hound is excited. We're getting closer.",
		},
		DIVININGRODBASE =
		{
			GENERIC = "What cryptic ruins.",
			READY = "Seems I'm missing a piece...",
			UNLOCKED = "Ready! The saga continues!",
		},
		DIVININGRODSTART = "This mysterious sword feels important.",
		DRAGONFLY = "Ah, dragon! At last we meet!",
		ARMORDRAGONFLY = "Excellent armor for the heat of battle.",
		DRAGON_SCALES = "Mystical scales.",
		DRAGONFLYCHEST = "This chest is worthy of my weapons.",
		LAVASPIT = 
		{
			HOT = "Your fiery pools are no match for me!",
			COOL = "It's not very scary now, is it?",
		},
		DRAGONFRUIT = "It's very fancy.",
		DRAGONFRUIT_COOKED = "Grilled fancy fruit.",
		DRAGONFRUIT_SEEDS = "Tiny nature bits.",
		DRAGONPIE = "Why isn't this a meat pie? Meat, meeeat!",
		DRUMSTICK = "Leg of beastie, in my belly.",
		DRUMSTICK_COOKED = "Hooooot meat!",
		DUG_BERRYBUSH = "I think I'll return this to the earth goddess.",
		DUG_GRASS = "I think I'll return this to the earth goddess.",
		DUG_MARSH_BUSH = "I think I'll return this to the earth goddess.",
		DUG_SAPLING = "I think I'll return this to the earth goddess.",
		DURIAN = "Smells like my battle boots.",
		DURIAN_COOKED = "Why did I cook this again?",
		DURIAN_SEEDS = "Tiny nature bits.",
		EARMUFFSHAT = "Yes, most practical!",
		EGGPLANT = "Purple and bulbous.",
		EGGPLANT_COOKED = "Food for the weak.",
		EGGPLANT_SEEDS = "Tiny nature bits.",
		DECIDUOUSTREE = 
		{
			BURNING = "The wood's ablaze!",
			BURNT = "Loge took that one.",
			CHOPPED = "Chopped by the warrior of the woods!",
			POISON = "I've got to work a bit harder for this firewood.",
			GENERIC = "Future firewood!",
		},
		ACORN = 
		{
		    GENERIC = "There's a tree hiding within.",
		    PLANTED = "Grow strong, young twigs!",
		},
		ACORN_COOKED = "I cooked the young tree.",
		BIRCHNUTDRAKE = "A young tree warrior!",
		EVERGREEN =
		{
			BURNING = "The wood's ablaze!",
			BURNT = "Loge took that one.",
			CHOPPED = "Chopped by the warrior of the woods!",
			GENERIC = "I feel at home in the woods.",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "The wood's ablaze!",
			BURNT = "Loge took that one.",
			CHOPPED = "Chopped by the warrior of the woods!",
			GENERIC = "A good, sturdy tree.",
		},
		EYEPLANT = "Don't point your eyeball at me, foliage!",
		FARMPLOT =
		{
			GENERIC = "I can't grow meat, what's the point?",
			GROWING = "They're growing stronger.",
			NEEDSFERTILIZER = "It wants a turd feast.",
			BURNT = "Serves you right for not growing meats!",
		},
		FEATHERHAT = "Seems a bit flashy for battle.",
		FEATHER_CROW = "A token from the ravens!",
		FEATHER_ROBIN = "Red as my hair.",
		FEATHER_ROBIN_WINTER = "Winter's feather.",
		FEM_PUPPET = "She looks unhappy upon her throne.",
		FIREFLIES =
		{
			GENERIC = "Tiny fairy lights aglow!",
			HELD = "I hold the light!",
		},
		FIREHOUND = "The flamed one has no mercy.",
		FIREPIT =
		{
			EMBERS = "The fire's nearly dead.",
			GENERIC = "Warm fire, warm Wigfrid.",
			HIGH = "The fire roars!",
			LOW = "The fire's slowly dying.",
			NORMAL = "Warm fire, warm Wigfrid.",
			OUT = "And the light flickers out.",
		},
		COLDFIREPIT =
		{
			EMBERS = "The fire's nearly dead.",
			GENERIC = "A cold comfort.",
			HIGH = "The fire roars!",
			LOW = "That fire's slowly dying.",
			NORMAL = "A cold comfort.",
			OUT = "And the light flickers out.",
		},
		FIRESTAFF = "Wigfrid! Master of fire!",
		FIRESUPPRESSOR = 
		{	
			ON = "Catapult engaged for battle!",
			OFF = "Time to rest, flinging warrior.",
			LOWFUEL = "The catapult grows weak and tired.",
		},

		FISH = "Meat of the sea!",
		FISHINGROD = "I'm a ruthless fisherwoman.",
		FISHSTICKS = "Spears of sea meat.",
		FISHTACOS = "Fish in a blanket!",
		FISH_MED = "Rest easy in Valhalla.",
		FISH_MED_COOKED = "Joy!",
		FISH_COOKED = "Joy!",
		FLINT = "Vital for spear construction.",
		FLOWER = "A flower from Freya.",
		FLOWERHAT = "Flimsy for the fight, lovely for my head.",
		FLOWER_EVIL = "A terrible evil plagues this flora.",
		FOLIAGE = "A collection of ferns.",
		FOOTBALLHAT = "A pig's bottom made my helmet.",
		FROG =
		{
			DEAD = "You're a bit slimy for Valhalla.",
			GENERIC = "I'd like frog boots someday.",
			SLEEPING = "It sleeps.",
		},
		FROGGLEBUNWICH = "What a treat!",
		FROGLEGS = "Filled with rubbery protein!",
		FROGLEGS_COOKED = "I like when I can see the bones sticking out.",
		FRUITMEDLEY = "Ugh! Putting it into a cup doesn't fool me.",
		GEARS = "These might look nice glued to my helm.",
		GHOST = "A spirit trapped between worlds.",
        GHOST_SAILOR = "He must have been a valiant warrior.",
		GOLDENAXE = "A tool of gold!",
		GOLDENPICKAXE = "Gold for gold.",
		GOLDENPITCHFORK = "Why did I even make a pitchfork this fancy?",
		GOLDENSHOVEL = "Digging like a king!",
		GOLDNUGGET = "I am pleased with this gold piece.",

		GRASS =
		{
			BARREN = "The life has gone from it.",
			WITHERED = "The heat has defeated this plant.",
			BURNING = "Loge looks upon you!",
			GENERIC = "That could be useful.",
			PICKED = "It fell to my might.",
		},
		GREEN_CAP = "Terrible!",
		GREEN_CAP_COOKED = "Charred by flame or not, it will not touch my lips!",
		GREEN_MUSHROOM =
		{
			GENERIC = "It has risen!",
			INGROUND = "Hide, coward.",
			PICKED = "I see fungal spores.",
		},
		GUNPOWDER = "Such energy!",
		HAMBAT = "A weapon fit for the great dining halls!",
		HAMMER = "More fit for labor than battle.",
		HEALINGSALVE = "Fill me with life!",
		HEATROCK =
		{
			FROZEN = "Cold teeth bite at me!",
			COLD = "The stone has taken on cold!",
			GENERIC = "A stone of great use!",
			WARM = "The stone has taken on warmth!",
			HOT = "Loge would be proud.",
		},
		HOMESIGN = 
		{
			GENERIC = "A most well placed sign.",
			UNWRITTEN = "I shall write a tale of triumph!",
			BURNT = "Signs of a battle past.",
		},
		HONEY = "Sticky and gross.",
		HONEYCOMB = "Wouldn't make much of a comb.",
		HONEYHAM = "A hearty feast!",
		HONEYNUGGETS = "A meaty, nuggety feast!",
		HORN = "How I long for battle.",
		HOUND = "Fenrir's spawn!",
		HOUNDBONE = "A fallen foe.",
		HOUNDMOUND = "These hounds are truly warriors.",
		ICEBOX = "Winter dwells inside!",
		ICEHAT = "A chunk of cold.",
		ICEHOUND = "Teeth of frost!",
		INSANITYROCK =
		{
			ACTIVE = "Woah!",
			INACTIVE = "I suspect nothing of this rock.",
		},
		JAMMYPRESERVES = "Sticky and gross.",
		KABOBS = "Meat jammed on a stick! Yes!",
		KILLERBEE =
		{
			GENERIC = "A challenger!",
			HELD = "A conquered foe.",
		},
		KNIGHT = "I sense battle!",

		KOALEFANT_SUMMER = "Dear creature... I am going to eat you.",
		KOALEFANT_WINTER = "Poor unsuspecting meat beast.",
		KRAMPUS = "You don't scare me, goat!",
		KRAMPUS_SACK = "I can fit everything in here!",
		LEIF = "That is an ancient woodland being.",
		LEIF_SPARSE = "That is an ancient woodland being.",
		LIGHTNING_ROD =
		{
			CHARGED = "Oh, great lightning!",
			GENERIC = "Bring with you lightning, Donner!",
		},
		LIGHTNINGGOAT = 
		{
			GENERIC = "May I call you Unicorn?",
			CHARGED = "The lightning has made you a unicorn warrior!",
		},
		LIGHTNINGGOATHORN = "This could deal a lasting blow.",
		GOATMILK = "This is powerful milk.",
		LITTLE_WALRUS = "A spawn of the evil toothed seal.",
		LIVINGLOG = "Burning such magic would seem a waste.",
		LOCKEDWES = "I'll save you silent mortal!",
		LOG =
		{
			BURNING = "Flaming log!",
			GENERIC = "Wood is always of value.",
		},
		LUREPLANT = "Finally! A useful vegetable.",
		LUREPLANTBULB = "Perhaps I will be a meat farmer after all!",
		MALE_PUPPET = "He looks unhappy upon his throne.",
		MANDRAKE =
		{
			DEAD = "The corpse of the rutabaga still retains its magic.",
			GENERIC = "A rutabaga!",
			PICKED = "She just wants to go on a rutabaga saga.",
		},
		MANDRAKESOUP = "A stew of magic!",
		MANDRAKE_COOKED = "Grilled rutabaga.",
		MARBLE = "The warrior stone!",
		MARBLEPILLAR = "Fit for a palace!",
		MARBLETREE = "Even the winds cannot knock this tree down.",
		MARSH_BUSH =
		{
			BURNING = "Hot log!",
			GENERIC = "A shrub on guard.",
			PICKED = "What a nuisance.",
		},
		MARSH_PLANT = "Pond foliage.",
		MARSH_TREE =
		{
			BURNING = "It's ablaze!",
			BURNT = "Burnt.",
			CHOPPED = "My battleaxe always wins.",
			GENERIC = "A warrior tree.",
		},
		MAXWELL = "Arrg! Is that the antagonist to my saga?!",
		MAXWELLHEAD = "I can see into his pores.",
		MAXWELLLIGHT = "Dark magic lives here.",
		MAXWELLLOCK = "Shall I unlock it?",
		MAXWELLTHRONE = "I prefer to roam free, my unicorn and I.",
		MEAT = "The true fruit of the earth!",
		MEATBALLS = "Tiny feast balls.",
		MEATRACK =
		{
			DONE = "Let's eat!",
			DRYING = "It's being prepared just the way I like it.",
			DRYINGINRAIN = "All this rain isn't helping.",
			GENERIC = "Ah! A dangly rack for my meats!",
			BURNT = "Such a shame.",
		},
		MEAT_DRIED = "Excellent battle provisions.",
		MERM = "Die soggy beast fish!",
		MERMHEAD = 
		{
			GENERIC = "I could smell it from back there!",
			BURNT = "Beheaded. Burnt. Stinky.",
		},
		MERMHOUSE = 
		{
			GENERIC = "Is this dwelling made of fish?",
			BURNT = "I won't miss it.",
		},
		MINERHAT = "A lighted helm! For the darkness.",
		MONKEY = "I don't trust him.",
		MONKEYBARREL = "What horrors dwell within?",
		MONSTERLASAGNA = "Monster casserole.",
		FLOWERSALAD = "Leaves are for animals. Animals are for eating.",
        ICECREAM = "It hurts my teeth.",
        WATERMELONICLE = "You cannot fool me by hiding in frozen fruit, stick.",
        TRAILMIX = "Meat of a nut is not true meat.",
        HOTCHILI = "A test of my willpower.",
        GUACAMOLE = "Yum, creamy!",
		MONSTERMEAT = "Meat of the dark beasts.",
		MONSTERMEAT_DRIED = "All dried up.",
		MOOSE = "I wish I could ride it into battle.",
		MOOSEEGG = "Something is bouncing around inside.",
		MOSSLING = "You are not large enough to be my steed.",
		FEATHERFAN = "The luxuries of camp, on the go.",
		TROPICALFAN = "The luxuries of camp, on the go.",
		GOOSE_FEATHER = "A shieldmaiden deserves a soft bed of dunn.",
		STAFF_TORNADO = "A storm of pain.",
		MOSQUITO =
		{
			GENERIC = "Ugh! These things are useless!",
			HELD = "Settle, demon fury!",
		},
		MOSQUITOSACK = "The blood will make me strong.",
		MOUND =
		{
			DUG = "I wanted the loot!",
			GENERIC = "Are there treasures beneath the gravestones?",
		},
		NIGHTLIGHT = "I'm more comfortable around my own fire.",
		NIGHTMAREFUEL = "The fuel of darkness!",
		NIGHTSWORD = "It takes a brave warrior to wield this sword.",
		NITRE = "It contains explosive components.",
		ONEMANBAND = "Sing with me! We are the guardians of Asgard!",
		PANDORASCHEST = "It contains a mystery.",
		PANFLUTE = "I prefer to face my enemies awake.",
		PAPYRUS = "This will carry forth the record of my saga.",
		PENGUIN = "Birds of the sea, come from afar.",
		PERD = "You cannot run forever!",
		PEROGIES = "Pockets of meat.",
		PETALS = "Thank you Froh for this gift!",
		PETALS_EVIL = "These were not made by Froh.",
		PICKAXE = "I can use it to get precious spear and helm materials.",
		PIGGYBACK = "The pig died with honor, then gave to me this pack.",
		PIGHEAD = 
		{	
			GENERIC = "This is savagery.",
			BURNT = "Normally I like a good roast, but this is not right.",
		},
		PIGHOUSE =
		{
			FULL = "Come out and go to war with me!",
			GENERIC = "I did not think pigs could make houses.",
			LIGHTSOUT = "Do you not hunger for battle, pig?",
			BURNT = "Loge did not smile upon you this day.",
		},
		PIGKING = "Is it pig-Odin?",
		PIGMAN =
		{
			DEAD = "He died with honor.",
			FOLLOWER = "We ride to battle!",
			GENERIC = "Will you fight alongside me, pig?",
			GUARD = "That pig looks brave.",
			WEREPIG = "It has been tainted by Fenrir.",
		},
		PIGSKIN = "The hide of a pig creature.",
		PIGTORCH = "Do these pigs worship Loge?",
		PINECONE = 
		{
		    GENERIC = "This baby tree is well protected by spiky armor.",
		    PLANTED = "It has shed its armor. Grow, baby tree!",
		},
		PITCHFORK = "A weapon for farmers.",
		PLANTMEAT = "I suppose it's close enough.",
		PLANTMEAT_COOKED = "Still green, but it'll do.",
		PLANT_NORMAL =
		{
			GENERIC = "A plant.",
			GROWING = "I am a shieldmaiden, not a farmer!",
			READY = "Ugh, vegetables. I'm not sure what I expected...",
			WITHERED = "Bested by the sun.",
		},
		POMEGRANATE = "Fruity flesh.",
		POMEGRANATE_COOKED = "Seared fruit flesh.",
		POMEGRANATE_SEEDS = "Tiny nature bits.",
		POND = "Something lurks in the deep.",
		POOP = "If only I could use it as camouflage from predators.",
		FERTILIZER = "Its stench could raise the fallen.",
		PUMPKIN = "It might make a good bludgeon, at least.",
		PUMPKINCOOKIE = "Baked all the life out of it.",
		PUMPKIN_COOKED = "Piping hot orange mush.",
		PUMPKIN_LANTERN = "Do you wish to fight, vegetable?",
		PUMPKIN_SEEDS = "Tiny nature bits.",
		PURPLEAMULET = "An amulet of dark powers.",
		PURPLEGEM = "It is cloudy with a mysterious energy.",
		RABBIT =
		{
			GENERIC = "Jump into my mouth!",
			HELD = "There is no escape!",
		},
		RABBITHOLE = 
		{
			GENERIC = "Showtime, rabbits!",
			SPRING = "It must be intermission for the rabbits.",
		},
		RAINOMETER = 
		{	
			GENERIC = "It foretells the coming of rains.",
			BURNT = "Its prophecy days are done.",
		},
		RAINCOAT = "Armor for rain.",
		RAINHAT = "We will fight in the rain.",
		RATATOUILLE = "A pile of vegetables. No thanks.",
		RAZOR = "A small blade, but a blade nonetheless.",
		REDGEM = "It is hot to the touch.",
		RED_CAP = "Umami or not, I don't want it.",
		RED_CAP_COOKED = "I won't eat it, but it was fun to put in the fire.",
		RED_MUSHROOM =
		{
			GENERIC = "At least it's got a nice color.",
			INGROUND = "And stay down there!",
			PICKED = "Good riddance.",
		},
		REEDS =
		{
			BURNING = "See you in Asgard, reeds!",
			GENERIC = "Those are some hardy reeds.",
			PICKED = "Cut down in their prime.",
		},
        RELIC = 
        {
            GENERIC = "Fit for Asgard.",
            BROKEN = "It has been reduced to smithereens.",
        },
        RUINS_RUBBLE = "Its days are not done.",
        RUBBLE = "A pile of ancient rocks.",
		RESEARCHLAB = 
		{	
			GENERIC = "I prefer battle to science.",
			BURNT = "Ashes to ashes.",
		},
		RESEARCHLAB2 = 
		{
			GENERIC = "Perhaps science can enhance my combat skills.",
			BURNT = "Dust to dust.",
		},
		RESEARCHLAB3 = 
		{
			GENERIC = "A mystical thing.",
			BURNT = "Its strange power did not protect it from the fire.",
		},
		RESEARCHLAB4 = 
		{
			GENERIC = "It is an absurd machine that makes meat.",
			BURNT = "No more meat will come from here!",
		},
		RESURRECTIONSTATUE = 
		{
			GENERIC = "I do not know why I made this.",
			BURNT = "Valhalla, I come!",
		},
		RESURRECTIONSTONE = "It holds me back from Valhalla.",
		ROBIN =
		{
			GENERIC = "Red like blood.",
			HELD = "I prefer your black brethren.",
		},
		ROBIN_WINTER =
		{
			GENERIC = "This bird knows about the cold.",
			HELD = "Such fluffy feathers.",
		},
		ROBOT_PUPPET = "A prisoner!",
		ROCK_LIGHT =
		{
			GENERIC = "The lava crust is firm.",
			OUT = "Looks delicate.",
			LOW = "The lava crust is reforming.",
			NORMAL = "Beautiful light!",
		},
		ROCK = "Smash!",
		ROCK_ICE = 
		{
			GENERIC = "A miniature frozen mountain.",
			MELTED = "Poor glacier!",
		},
		ROCK_ICE_MELTED = "Poor glacier!",
		ICE = "Reminds me of home.",
		ROCKS = "Some pretty normal rocks.",
        ROOK = "Chaaaarge!",
		ROPE = "Strong enough to bind the sails of my longship.",
		ROTTENEGG = "Ruined for eating, but primed for battle.",
		SANITYROCK =
		{
			ACTIVE = "I do not think I can best this rock in combat.",
			INACTIVE = "Clever rock, you cannot surprise a warrior!",
		},
		SAPLING =
		{
			BURNING = "Nooo! My spears!",
			WITHERED = "It has been shriveled by the heat.",
			GENERIC = "I will make it into a spear.",
			PICKED = "I have slain the small tree!",
		},
		SEEDS = "Tiny nature bits.",
		SEEDS_COOKED = "Tiny nature bits, cooked to death.",
		SEWING_KIT = "I am no seamstress, but repairs are sometimes necessary.",
		SHOVEL = "I'd prefer a ship burial, though this might have its uses.",
		SILK = "Useful for binding, and for remembering victories past.",
		SKELETON = "Rest easy in Valhalla.",
		SKELETON_PLAYER = "This fight is not yet over.",
		SKULLCHEST = "Ah, that was a good battle.",
		SMALLBIRD =
		{
			GENERIC = "You are not fierce yet, bird.",
			HUNGRY = "You must eat to grow strong.",
			STARVING = "The small bird looks famished.",
		},
		SMALLMEAT = "A nice meaty snack.",
		SMALLMEAT_DRIED = "A small provision for a long campaign.",
		SPEAR = "It is not my favored spear, but it will do the trick.",
		SPIDER =
		{
			DEAD = "Felled by my spear, like so many before it.",
			GENERIC = "Eight legs and still no match for me!",
			SLEEPING = "I will allow it a fair fight and wait til it awakes.",
		},
		SPIDERDEN = "Crush them at the source!",
		SPIDEREGGSACK = "I could squash these but I'd miss out on more battles.",
		SPIDERGLAND = "Ripped from the abdomen of a slain spider.",
		SPIDERHAT = "A perfect way to infiltrate the enemy camp.",
		SPIDERQUEEN = "Finally, a true test of my abilities.",
		SPIDER_WARRIOR =
		{
			DEAD = "Victory for Wigfrid once again!",
			GENERIC = "The champion of the spiders. To battle!",
			SLEEPING = "It is cowardly to attack a sleeping enemy.",
		},
		SPOILED_FOOD = "Age has only made this food gross, not wise.",
		STATUEHARP = "It must be Gunnar. The snakes took his head.",
		STATUEMAXWELL = "Fie, demon!",
		STINGER = "The sword on the back of a bee.",
		STRAWHAT = "A hat for cooling after a raucous battle.",
		STUFFEDEGGPLANT = "Filling the vegetable does not make it meat.",
		SUNKBOAT = "No wonder it sank. It is not a longship.",
		SWEATERVEST = "It is a handsome vest, but it offers no protection.",
		REFLECTIVEVEST = "Ha! The sun is no warrior if it cannot penetrate this.",
		HAWAIIANSHIRT = "Flowers cannot stop a spear.",
		TAFFY = "Long will the saga of this taffy be told.",
		TALLBIRD = "A fearsome bird! But I am not afraid.",
		TALLBIRDEGG = "It will grow into a formidable foe.",
		TALLBIRDEGG_COOKED = "It was you or me, bird.",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "This egg would not survive a Norse winter.",
			GENERIC = "Fight your way out, bird!",
			HOT = "Borne of flame! Unless it cooks to death.",
			LONG = "A time remains before this bird is to be born.",
			SHORT = "It will soon wake to this world.",
		},
		TALLBIRDNEST =
		{
			GENERIC = "A feathered warrior lurks inside.",
			PICKED = "A young bird of war will soon be born.",
		},
		TEENBIRD =
		{
			GENERIC = "You are not yet ready for battle, bird.",
			HUNGRY = "I hope you like vegetables... the meat is for me.",
			STARVING = "To enter battle with me is your choice, bird.",
		},
		TELEBASE =
		{
			VALID = "It will harness my awesome speed.",
			GEMS = "It requires purple gems.",
		},
		GEMSOCKET = 
		{
			VALID = "Showtime!",
			GEMS = "It lacks its gem.",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "To Asgard!",
			GENERIC = "A bridge to another world.",
			LOCKED = "The bridge is unstable yet.",
			PARTIAL = "The bridge is incomplete.",
		},
		TELEPORTATO_BOX = "Perhaps this holds the secret to this land's Bifrost.",
		TELEPORTATO_CRANK = "A sturdy crank.",
		TELEPORTATO_POTATO = "No decency. It's not even metal meat.",
		TELEPORTATO_RING = "It appears similar to the Bifrost.",
		TELESTAFF = "I ride through the air and the sea!",
		TENT = 
		{
			GENERIC = "Sleep this night, and prepare for battle on the morrow.",
			BURNT = "It has been razed.",
		},
		SIESTAHUT = 
		{
			GENERIC = "A place to rest my battle-weary head.",
			BURNT = "It has been razed.",
		},
		TENTACLE = "It looks fierce. Into the fray!",
		TENTACLESPIKE = "Gooey, but dangerous. I like it.",
		TENTACLESPOTS = "A tough hide.",
		TENTACLE_PILLAR = "A towering tentacled foe.",
		TENTACLE_PILLAR_ARM = "A gross, grasping appendage.",
		TENTACLE_GARDEN = "I will thrust my spear into that mass of tentacles!",
		TOPHAT = "It doesn't match my costume.",
		TORCH = "Perfect for a nighttime assault.",
		TRANSISTOR = "A marvel of science.",
		TRAP = "A well constructed trap. I will have my meal.",
		TRAP_TEETH = "A treacherous trap.",
		TRAP_TEETH_MAXWELL = "An excellent mace wasted, buried in the ground.",
		TREASURECHEST = 
		{
			GENERIC = "A place to store my helm and spear whilst I rest.",
			BURNT = "Its walls were torn down by fire.",
		},
		TREASURECHEST_TRAP = "I am always ready.",
		TREECLUMP = "A dead end! I must stand and fight.",
		TRINKET_1 = "Toys do not interest a great warrior such as I.",
		TRINKET_10 = "A token of victory.",
		TRINKET_11 = "A warrior encased in fine armor.",
		TRINKET_12 = "Shorn from a hideous monster.",
		TRINKET_2 = "Accompaniment for the song of my triumphs.",
		TRINKET_3 = "Even my spear cannot undo this knot.",
		TRINKET_4 = "A small, peculiar man.",
		TRINKET_5 = "Will it take me to Asgard?",
		TRINKET_6 = "Useless technology.",
		TRINKET_7 = "No time for games! There is battle at hand!",
		TRINKET_8 = "It would make an okay weapon in a pinch.",
		TRINKET_9 = "No decent armor can be made with these.",
		TRUNKVEST_SUMMER = "It will not suffice in the frozen wastes.",
		TRUNKVEST_WINTER = "The warm pelt of a bested creature. A fine garment.",
		TRUNK_COOKED = "A juicy reward after a hard battle.",
		TRUNK_SUMMER = "The powerful trunk of a fallen not-so-hairy beast.",
		TRUNK_WINTER = "The powerful trunk of a fallen hairy beast.",
		TUMBLEWEED = "Flee, bouncing coward!",
		TURKEYDINNER = "A true feast.",
		TWIGS = "Good for making spears.",
		UMBRELLA = "Rain protection made from the trophy of a hunt.",
		GRASS_UMBRELLA = "I dislike flowers, but I dislike wet armor more.",
		PALMLEAF_UMBRELLA = "I dislike plants, but I dislike wet armor more.",
		UNIMPLEMENTED = "A mysterious relic, sure to contain great power.",
		WAFFLES = "Waffles are no way to prepare for battle!",
		WALL_HAY = 
		{	
			GENERIC = "A minor deterrent to attackers.",
			BURNT = "That won't do at all.",
		},
		WALL_HAY_ITEM = "Perhaps my foes will get lost in this hay.",
		WALL_STONE = "My enemies will dash themselves on these rocks.",
		WALL_STONE_ITEM = "A sturdy wall, fashioned from the earth.",
		WALL_RUINS = "Nigh impenetrable.",
		WALL_RUINS_ITEM = "Only the finest barriers for my fort.",
		WALL_WOOD = 
		{
			GENERIC = "It may impale a foe.",
			BURNT = "Fire, wood's only weakness!",
		},
		WALL_WOOD_ITEM = "A mediocre fortification.",
		WALRUS = "Those tusks could pierce even the finest armor.",
		WALRUSHAT = "Highland filth!",
		WALRUS_CAMP =
		{
			EMPTY = "They have departed for a great journey.",
			GENERIC = "A proper winter camp.",
		},
		WALRUS_TUSK = "Rended from the mouth of the sea beast.",
		WARG = "Be that you, Fenrir?",
		WASPHIVE = "Bees of war!",
		WATERMELON = "It makes a good sound when you hit it.",
		WATERMELON_COOKED = "Warm and red, but it doesn't flow.",
		WATERMELONHAT = "It's almost like wearing a pelt.",
		WETGOOP = "Slop.",
		WINTERHAT = "Warm, but not suitable for combat.",
		WINTEROMETER = 
		{
			GENERIC = "If only it measured the heat of battle.",
			BURNT = "The measuring device has been slain by Loge.",
		},
		WORMHOLE =
		{
			GENERIC = "Does it swallow those fallen in battle?",
			OPEN = "Its maw welcomes me.",
		},
		WORMHOLE_LIMITED = "It is sickly and weak.",
		ACCOMPLISHMENT_SHRINE = "My victories shall be remembered!",        
		LIVINGTREE = "A tree of life, but it is not Yggdrasil.",
		ICESTAFF = "A gift from Ullr!",
		WATHGRITHRHAT = "The power of the unicorn is great.",
		SPEAR_WATHGRITHR = "My comrade in arms!",

		--- CAPY DLC ------------------------------------------------------------------------------------------------

		BACONEGGS = "Pig and eggs!",
		BANANAPOP = "I've somehow found a way to make it even LESS appealing!",
		BISQUE = "Not a bad dish.",
		CEVICHE = "Fancy for my taste, but it'll do.",
		SEAFOODGUMBO = "A meal fit for a queen.",
		SURFNTURF = "Yuck! Turf!",
		SHARKFINSOUP = "Delicious!",
		LOBSTERDINNER = "I triumphed over my wobster foe.",
		LOBSTERBISQUE = "That's more like it.",
		JELLYOPOP = "I could go berserk on these!",
		CALIFORNIAROLL = "That's just a morsel of fish food.",

		AERODYNAMICHAT = "My head shall cut the air!",
		ANTIVENOM = "No venom shall flow through my veins!",
		ARMOR_LIFEJACKET = "Adventure offers no true safety!",
		ARMOR_SNAKESKIN = "Rain is bested!",
		ARMOR_WINDBREAKER = "I shall break the wind with every step!",
		ARMORLIMESTONE = "It's heft is reassuring on my bones.",
		ARMOROBSIDIAN = "Come at me now, fiends!",
		ARMORSEASHELL = "I shall not wash up on the shores of Valhalla wearing this!",
		ARMOUREDBOAT = "Now this is a vessel fit for a Viking!",
		BABYOX = "When you grow up you will become even more meat, meat.",
		BALLPHIN = "A blow struck may simply bounce off.",
		BALLPHINPOD = "A raiding party!",
		BAMBOO = "Sticks of great versatility.",
		BAMBOOTREE = "A very hearty weed.",
		BERMUDATRIANGLE = "Is this a plaything of Loki?",
		BIOLUMINESCENCE = "What magic is this?",
		BLOWDART_POISON = "To weaken from a distance. Odin forgive me...",
		BOAT_INDICATOR = "I shall launch my craft.",
		BOAT_LANTERN = "See me, foul beasts of the shadow seas!",
		BOATCANNON = "It smites mine enemies for me!?",
		BOATREPAIRKIT = "Most sensible cargo.",
		BOTTLELANTERN = "A most curious torch.",
		BURIEDTREASURE = "May luck smile on me this day.",
		SNAKEDEN = "You skulking wretch!",
		CANNONSHOT = "Sound and fury!",
		CAPTAINHAT = "It would be better with horns.",
		CARGOBOAT = "A boat fit for a long journey.",
		CHIMINEA = "What kind of fire hides in a hole?",
		CIRCLINGSEAGULL = "Sky filth!",
		CLOTHSAIL = "A fine sail.",
		COCONADE = "Fire that can be thrown.",
		COCONUT = 
		{
		    GENERIC = "The hardest of fruits.",
		    PLANTED = "The hard fruit gave way to a flimsy tree.",
		},
		COFFEE = "Bitter and pulse-pounding.",
		COFFEEBEANS = "I take mine black.",
		
		COFFEEBUSH = "Just add water?",
		CORAL = "The sea bequeaths such strange gifts.",
		CORALREEF = "A hard and brittle place. I like it.",
		CRAB = "Your armor cannot protect you, meat!",
		CRABHOLE = "Does shame drive them to this hole?",
		CUTLASS = "Oh, great sword of piscean death. I shall swing you with honor.",
		DEAD_SWORDFISH = "Onward to Valhalla, brave fish.",
		DEPLETED_BAMBOOTREE = "Have some respect for yourself.",
		DEPLETED_BUSH_VINE = "Not so viney now are you?",
		DOYDOY = "It shows no trace of fear for me!",
		DOYDOYBABY = "I honor you, young warrior of the DoyDoys.",
		DOYDOYEGG = "Within this egg grows a Viking of another feather.",
		
		DOYDOYFEATHER = "The treasured feather of a fallen bird warrior.",
		DOYDOYNEST = "The nest where more brave ones will hatch!",
		DUBLOON = "The spoils of the fallen!",
		DUG_BAMBOOTREE = "If I plant you, will you repay me?",
		DUG_BERRYBUSH2 = "My own personal fount of berries!",
		DUG_BUSH_VINE = "To vine or not to vine?",
		DUG_COFFEEBUSH = "Coffee to go.",
		EARRING = "This is not of my ear.",
		FABRIC = "Sewing is not warrior's work...",
		FEATHERSAIL = "The brave birds gift me their swift feathers!",
		FIRERAIN = "True warrior's weather!",
		FIRERAINSHADOW = "By Odin!",
		FISHINHOLE = "Do you wish to surrender, fish?",
		FROG_POISON = "Back, foul reptilian scourge!",
		GASHAT = "Armor of sorts for my nose and throat!",
		GOLDENMACHETE = "I shall swing you with pride.",
		ICEMAKER = "Reminds me of home.",
		IRONWIND = "This contraption runs on Odin's steeds!",
		JELLYFISH = "You are much too small to be a sea monster.",
		JELLYFISH_COOKED = "The sea monster cooks up well!",
		JELLYFISH_DEAD = "The sea monster rides to Valhalla!",
		JELLYFISH_PLANTED = "I expected sea monsters to be bigger.",
		JELLYJERKY = "My teeth shall do battle with you.",
		JUNGLETREE = "A mighty tree!",
		JUNGLETREE_BURNT = "Goodbye, giant.",
		JUNGLETREE_STUMP = "I will see you in Valhalla, tree.",
		JUNGLETREESEED =
        {
            GENERIC = "The strength of the tree, in a seed.",
            PLANTED = "It will grow mightily.",
        },
		LAVAPOOL = "A puddle of fire!",
		LIMESTONE = "Hard as an unripe fruit.",
		LIMPETS = "Rock meat!",
		
		LOBSTER = "You are dressed for battle, sea-dweller.",
		LOBSTERHOLE = "The armored ones dwell here...",
		LOGRAFT = "You will not carry me far, but you will carry me.",
		MACHETE = "A fine length of blade.",
		MESSAGEBOTTLE = "A message from Valhalla?",
		MESSAGEBOTTLEEMPTY = "Empty of both messages and drink. Pity.",
		MOSQUITO_POISON = "Poison! The work of a coward!",
		MUSSEL = "You don't look strong.",
		MUSSEL_STICK = "The foolish mussels shall climb this stick.",
		OBSIDIAN = "Pebbles from the fire mountain!",
		OBSIDIAN_WORKBENCH = "Fire forge!",
		OBSIDIANAXE = "Now THIS is an axe!",
		OBSIDIANCOCONADE = "Throwing fire is the coward's way. But such fun!",
		OBSIDIANFIREPIT =
		{
			EMBERS = "The fire's nearly dead.",
			GENERIC = "A fire fit for a Viking!",
			HIGH = "The fire roars!",
			LOW = "The fire's slowly dying.",
			NORMAL = "Warm fire, warm Wigfrid.",
			OUT = "And the light flickers out.",
		},
		OBSIDIANMACHETE = "A tool for cutting. A tool for burning.",
		SPEAR_OBSIDIAN = "Feel the burn.",
		OBSIDIANSPEARGUN = "I normally prefer to set fires up close.",
		OX = "Praise Odin for this bountiful hoofed feast!",
		PACKIM = "Will you follow me to Valhalla?",
		PACKIM_FISHBONE = "A curious bauble.",
		PALMLEAF = "A Viking-sized leaf!",
		PALMTREE =
		{
			BURNING = "The wood's ablaze!",
			BURNT = "Loge took that one.",
			CHOPPED = "Chopped by the warrior of the woods!",
			GENERIC = "Do you forsake branches, tree?",
		},
		PALMTREE_BURNT = "I smell burnt coconut.",
		PALMTREE_STUMP = "You will be fueling my hearth in Valhalla.",
		PARROT = "Hold your tongue, bird!",
		PEACOCK = "It will be a shame to ruin those feathers, meat.",
		PIRATEHAT = "This hat confuses my character... I mean, my soul.",
		PIRATIHATITATOR = "This contraption has the smell of Loki about it...",
		POISONHOLE = "The ground belches with sickness!",
		RAFT = "A Viking fears not dampness!",
		ROWBOAT = "Rowing is in my blood.",
		SAIL = "A curious sail, but it shall do.",
		SAND = "You are a very clean dirt.",
		SAND_CASTLE = "A scale model of my future keep.",
		SANDBAG = "Bagged sand.",
		SANDBAG_ITEM = "Keeps the floods at bay.",
		SANDHILL = "I will not make a mountain out of a sandhill.",
		SEAGULL = "Vile bird!",
		SEAGULL_WATER = "You foul the water you float upon!",
		SEASACK = "Disgusting, but useful in its way.",
		SEASHELL = "The currency of the sea.",
		SEASHELL_BEACHED = "A tiny elf shield?",
		SEATRAP = "Bring me spoils of the sea!",
		SEAWEED = "Watery plant filth!",
		
		SEAWEED_PLANTED = "A weed I cannot crush under my boot.",
		SHARK_FIN = "A token from a fallen warrior.",
		SHARX = "Ah, a worthy sea opponent!",
		SLOTMACHINE = "A machine of fate and misery.",
		SNAKE = "Never trust those who slither.",
		SNAKE_FIRE = "They speak with the volcano's mouth!",
		SNAKE_POISON = "Keep your foul fangs from my hide!",
		SNAKESKIN = "A snake has slipped its skin. With a little help...",
		SNAKESKINHAT = "Shall I wear the serpent?",
		SOLOFISH = "It seems the sea is offering me a feast.",
		SPEAR_POISON = "This spear awards a coward's victory.",
		SPEARGUN = "A coward's weapon.",
		SPEARGUN_POISON = "I am not some sneak hiding in the shadows! Am I?",
		SPOILED_FISH = "You smell of your failure.",
		STUNGRAY = "Have you no honor, stinky ones?",
		SUPERTELESCOPE = "Odin has lent me his eye!",
		SWORDFISH = "Now you are a fish after my heart!",
		TELESCOPE = "What trickery is this?",
		TIGERSHARK = "Take me to Valhalla, devil of the sea!",
		TIGERSHARKSHADOW = "The shadow of the beast!",
		TORNADO = "The wind has taken furious form!",
		TOUCAN = "Fight with me, long-nosed bird! Together we shall dine in Valhalla!",
		TRAWLNET = "I shall ransack the sea!",
		TRAWLNETDROPPED = "And now to see about my loot!",
		TRIDENT = "A weapon fit for a god!",
		TRINKET_13 = "What foul mead is this?",
		TRINKET_14 = "The toy of a babe. Or is it?",
		TRINKET_15 = "A weapon of annoyance.",
		TRINKET_16 = "A piece of armor?",
		TRINKET_17 = "A warrior walks to Valhalla barefoot...",
		TRINKET_18 = "I don't recognize the craftsmanship.",
		TRINKET_19 = "It is always clear skies for a righteous warrior.",
		TURBINE_BLADES = "What sort of strange sword is this?",
		TURF_BEACH = "Feels good between my toes.",
		TURF_JUNGLE = "You could lose yourself in this...",
		TWISTER = "You hide beneath wind, villain!",
		VENOMGLAND = "The source of the fevers.",
		VINE = "What can you do for me?",
		VOLCANO = "A mountain of fire!",
		VOLCANO_ALTAR = "I must appease the fire god that lives inside this mountain.",
		VOLCANO_ALTAR_BROKEN = "Senseless destruction of a weapon forge...",
		VOLCANO_EXIT = "I weary of this infernal realm.",
		VOLCANOSTAFF = "Call down the wrath of fire mountain!",
		WALL_LIMESTONE = "Fine work.",
		WALL_LIMESTONE_ITEM = "Will you stand with me?",
		WHALE_BLUE = "I will end your moping, giant!",
		WHALE_CARCASS_BLUE = "I will toast you in Valhalla.",
		WHALE_CARCASS_WHITE = "Oh, how the mighty stink.",
		WHALE_WHITE = "It would be an honor to kill you.",
		NEEDLESPEAR = "Tis truly a wondrous war lance!",
		ARMORCACTUS = "It will make of me a friend to the cactus.",
		BAMBOOTREE =
		{
			BURNT = "Your hollow sorcery could not save you from fire.",
			CHOPPED = "You could not hack it!",
			GENERIC = "What sorcery is this? Wood that is hollow?",
		},
		BLOWDART_FLUP = "A coward's weapon, dropped by a pitiful, sneaking creature.",
		BLUBBER = "This is much prized by my people!",
		BLUBBERSUIT = "Rue my suit of fat, moisture!",
		BOAT_TORCH = "The night sea is alight!",
		BRAINJELLYHAT = "My brain has the might of my sword!",
		BUOY = "It buoys my spirits to see it above the waves.",
		BUSH_VINE =
		{
			BURNT = "It's burnt. No sense vine-ing about it.",
			CHOPPED = "It needed a haircut.",
			GENERIC = "This bush has helm head.",
		},
		COCONADE =
		{
			BURNING = "The nut will spew its fire soon!",
			GENERIC = "This is no ordinary nut!",
		},
		COCONUT_COOKED = "I shall feast on this large nut.",
		COCONUT_HALVED = "I have cleaved the nut and it has shown me its insides!",
		COFFEEBEANS_COOKED = "It smells energizing.",
		COFFEEBUSH =
		{
			BARREN = "Did you even put up a fight?",
			GENERIC = "It bears strange volcano fruits.",
			PICKED = "Its fruits must be reborn.",
			WITHERED = "Weakling bush!",
		},
		CORAL_BRAIN = "If I eat of it will I gain its knowledge?",
		CORAL_BRAIN_ROCK = "A mystical, all-knowing water rock!",
		CRAB =
		{
			GENERIC = "Do battle with me, armored one!",
			HIDDEN = "Un-bury thyself, coward!",
		},
		CRATE = "Yield your secrets, box!",
		DOUBLE_UMBRELLAHAT = "What kind of strange helm is this?",
		DOYDOYEGG_COOKED = "I shall eat of this fearless bird's bounty.",
		DOYDOYEGG_CRACKED = "Its fearlessness leaks out.",
		DRAGOON = "A fellow berserker whose belly is full of fire!",
		DRAGOONDEN = "A berserker has to live somewhere.",
		DRAGOONEGG = "I can hear the beating heart of a warrior within!",
		DRAGOONHEART = "My fallen foe has given me a gift!",
		DRAGOONSPIT = "I wish I could spit fire...",
		DUG_ELEPHANTCACTUS = "I shall get to the point. You belong to me now.",
		ELEPHANTCACTUS = "I sense the spirit of a berserker within you, plant.",
		ELEPHANTCACTUS_ACTIVE = "Finally the earth sprouts a worthy adversary!",
		ELEPHANTCACTUS_STUMP = "Coward!",
		FISH_RAW = "This sea meat will serve me well.",
		FISH_RAW_SMALL = "This sea meat will serve me well.",
		FISH_RAW_SMALL_COOKED = "This meat will swim in my belly!",
		FLAMEGEYSER = "The ground belches fire!",
		FLOTSAM = "I must fish it from the sea if I'm to learn its secrets.",
		FLUP = "You cowardly mudlurker!",
		FRESHFRUITCREPES = "So light and airy!",
		GRASS_WATER = "Grass I can pick from my longship!",
		HAIL_ICE = "The sky is throwing ice!",
		HOME = "Someone must dwell here.",
		ICEMAKER =
		{
			HIGH = "The machine is fired up!",
			LOW = "It is spitting considerably less ice forth.",
			NORMAL = "Ice from fire!",
			OUT = "It needs more fire!",
			VERYLOW = "Its fire is about to go out.",
		},
		JUNGLETREE =
		{
			BURNING = "The tree burns.",
			BURNT = "The tree is no more.",
			CHOPPED = "A strong tree, but not so strong as my axe.",
			GENERIC = "There are no trees like this where I sail from.",
		},
		KNIGHTBOAT = "My longship speeds me to war!",
		KRAKEN = "I'll return you to Hel herself!",
		KRAKENCHEST = "Spoils of war!",
		KRAKEN_TENTACLE = "The arm of the beast!",
		LIMPETROCK =
		{
			GENERIC = "The meat stone!",
			PICKED = "The stone is meatless for now...",
		},
		TREEGUARD = "To arms!",
		LIVINGJUNGLETREE = "I do not like your face, tree!",
		LOBSTER_DEAD = "Sleep in Valhalla, armored one.",
		LOBSTER_DEAD_COOKED = "Your armor hides tasty meat.",
		LUGGAGECHEST = "I hope I am spoiled by these spoils of the sea!",
		MAGIC_SEAL = "I shall wield this with proper respect for the mighty warrior wizard that left it.",
		MAGMAROCK = "What can I use to roll these rocks?",
		MAGMAROCK_FULL = "What can I use to roll these rocks?",
		MAGMAROCK_GOLD = "It shimmers...",
		MAGMAROCK_GOLD_FULL = "It shimmers...",
		MANGROVETREE = "I have never felled a tree from my longship before!",
		MANGROVETREE_BURNT = "Everything above the water is char.",
		MARSH_PLANT_TROPICAL = "A meager plant.",
		MERMFISHER = "I quarrel not with fisherfolk, so long as they do not take up arms.",
		MERMHOUSE_FISHER = "The fisherfolk dwell here.",
		MONKEYBALL = "A bit of monkey merriment.",
		MONSTERTARTARE = "Still quivering.",
		MOSQUITOSACK_YELLOW = "The pest dropped its sack of sickness.",
		MUSSELBOUILLABAISE = "Thin, but warming.",
		MUSSEL_COOKED = "Strong taste.",
		MUSSEL_FARM =
		{
			GENERIC = "It builds mussels.",
			STICKPLANTED = "Become one with the stick...",
		},
		MYSTERYMEAT = "The food of my enemy's children is... what to me?",
		OCTOPUSCHEST = "The chest holds offerings.",
		OCTOPUSKING = "He seems open to bartering.",
		OXHAT = "This helm will keep my scalp dry.",
		OX_FLUTE = "I have no rhythm...",
		OX_HORN = "Ah, a fine mug it would make!",
		PALMLEAF_HUT = "Keeps the rain off my helm.",
		PARROT_PIRATE = "You talk too much!",
		PEG_LEG = "This leg will make a fine basher!",
		PIGTENT = "It smells of breakfast!",
		PIKE_SKULL = "Reminds me of home.",
		PIRATEGHOST = "To Hel, spirit!",
		PIRATEPACK = "Builds chest muscles.",
		PIRATIHATITATOR =
		{
			BURNT = "Its magic has floated away as embers.",
			GENERIC = "What awkward sorcery is this?",
		},
		PORTAL_SHIPWRECKED = "This longship looks unfit for a warrior.",
		PRIMEAPE = "You are as amusing as you are hairy.",
		PRIMEAPEBARREL = "By this mess I would say a Viking lives here.",
		RAWLING = "Finally! Someone to rehearse with.",
		REDBARREL = "This cask packs a punch!",
		ROCK_CHARCOAL = "Rocks burn?",
		ROCK_OBSIDIAN = "Lava stone!",
		SAIL_STICK = "I command the wind!",
		SANDBAGSMALL = "This bag of sand battles the water!",
		SANDBAGSMALL_ITEM = "Water crashes against it feebly!",
		SAND_CASTLE =
		{
			GENERIC = "I want to pretend I'm a giant and crush it!",
			SAND = "Time has crushed it.",
		},
		SEAWEED_COOKED = "Sea snack.",
		SEAWEED_DRIED = "It is chewy...",
		SHADOWSKITTISH_WATER = "An enemy looms!",
		SHARKITTEN = "It is your momma I want...",
		SHARKITTENSPAWNER =
		{
			GENERIC = "Something lies in wait!",
			INACTIVE = "Just sand... for now...",
		},
		SHARK_GILLS = "Shark gills!",
		SHARK_TEETHHAT = "A helm after my warriors heart!",
		SHIPWRECKED_ENTRANCE = "A new land to plunder and pillage!",
		SHIPWRECKED_EXIT = "Off to a new land...",
		SNAKEDEN =
		{
			BURNT = "It's burnt. No sense vine-ing about it.",
			CHOPPED = "It needed a haircut.",
			GENERIC = "This bush has helm head.",
		},
		SNAKEOIL = "What powerful properties does this bestow?",
		SNAKESKINSAIL = "A sail made of murder!",
		SPEAR_LAUNCHER = "A gift from Odin!",
		SUNKEN_BOAT =
		{
			ABANDONED = "The sea claims another!",
			GENERIC = "He has something to say!",
		},
		SUNKEN_BOAT_BURNT = "A Viking funeral has taken place...",
		SUNKEN_BOAT_TRINKET_1 = "Some kind of crude weapon?", 
		SUNKEN_BOAT_TRINKET_2 = "A child's longship.", 
		SUNKEN_BOAT_TRINKET_3 = "Soggy candle.", 
		SUNKEN_BOAT_TRINKET_4 = "Sea sorcery.", 
		SUNKEN_BOAT_TRINKET_5 = "Not my size.",
		SWEETPOTATOSOUFFLE = "It is filled with delicious air!",
		SWEET_POTATO = "I have never heard of a potato that is sweet! ...Gross!",
		SWEET_POTATO_COOKED = "I won't eat it, but I appreciate the color.",
		SWEET_POTATO_PLANTED = "There are inedible plantsweets in the ground!",
		SWEET_POTATO_SEEDS = "These will grow sweetly.",
		SWIMMINGHORROR = "Are you here to give me a Viking's funeral?",
		TELEPORTATO_SW_BASE = "It is missing things.",
		TELEPORTATO_SW_BOX = "It is part of something.",
		TELEPORTATO_SW_CRANK = "It cranks. But for what?",
		TELEPORTATO_SW_POTATO = "What strange contraption is this?",
		TELEPORTATO_SW_RING = "Is it valuable?",
		THATCHPACK = "I hope my spear doesn't poke a hole in it.",
		TIDALPOOL = "A tiny lake!",
		TIDAL_PLANT = "Soggy plant.",
		TIGEREYE = "I've got the eye of the tigershark!",
		TRAWLNETDROPPED =
		{
			GENERIC = "Plunderful!",
			SOON = "The plunder will sink soon.",
			SOONISH = "I think my plunder will sink soon.",
		},
		TRINKET_20 = "Some kind of crude weapon?", 
		TRINKET_21 = "A child's longship.",
		TRINKET_22 = "Soggy candle.", 
		TRINKET_23 = "A broken something.", 
		TROPICAL_FISH = "Inside it is the color of meat!",
		TUNACAN = "Food that can survive a voyage!",
		TURF_SANDY = "A piece of the battlefield.",
		TURF_ASH = "A piece of the battlefield.",
		TURF_BADLANDS = "A piece of the battlefield.",
		TURF_DECIDUOUS = "A piece of the battlefield.",
		TURF_DESERTDIRT = "A piece of the battlefield.",
		TURF_FUNGUS_GREEN = "A piece of the battlefield.",
		TURF_FUNGUS_RED = "A piece of the battlefield.",
		TURF_MAGMAFIELD = "A piece of the battlefield.",
		TURF_MEADOW = "A piece of the battlefield.",
		TURF_SNAKESKINFLOOR = "My enemy's hide feels good beneath my feet!",
		TURF_SWAMP = "A piece of the battlefield.",
		TURF_TIDALMARSH = "A piece of the battlefield.",
		TURF_VOLCANO = "A piece of the battlefield.",
		TWISTER_SEAL = "You were the little guy doing all that huffing and puffing?!?",
		VOLCANO_ALTAR =
		{
			GENERIC = "The altar of the fire gods sleeps.",
			OPEN = "It is ready to receive sacrifice!",
		},
		VOLCANO_ALTAR_TOWER = "An altar to the fire gods!",
		VOLCANO_SHRUB = "You look burnt out.",
		WALLYINTRO_DEBRIS = "Is this the wreckage of my longship?",
		WATERMELON_SEEDS = "Seedy.",
		WATERYGRAVE = "Plunder under!",
		WHALE_BUBBLES = "Something lurks beneath.",
		WHALE_TRACK = "I shall whale on you!",
		WILBUR_CROWN = "I plunder what this is?",
		WILBUR_UNLOCK = "I kneel to no king, even adorable ones!",
		WILDBORE = "I sense a kindred spirit!",
		WILDBOREHEAD = "Save a mug in Valhalla for me.",
		WILDBOREHOUSE = "A terrible place to live!",
		WIND_CONCH = "I feel a breeze...",
		WOODLEGS_CAGE = "A locked cage!",
		WOODLEGS_KEY1 = "What might this open?",
		WOODLEGS_KEY2 = "Another key!",
		WOODLEGS_KEY3 = "A strange key!",
		WRECK = "Longships litter the path to Valhalla.",
	},
	DESCRIBE_GENERIC = "It is an artifact of this realm.",
	DESCRIBE_TOODARK = "Too dark even for battle.",
	DESCRIBE_SMOLDERING = "The flames will soon consume it.",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "The freshest of meats!",
	},
}
