return {
	ACTIONFAIL =
	{
		SHAVE =
		{
			AWAKEBEEFALO = "It's hairy like us, but I don't think it likes shaving.",
			GENERIC = "It's not shaving time!",
			NOBITS = "Clean as a whistle.",
		},
		STORE =
		{
			GENERIC = "All full!",
			NOTALLOWED = "That's against the rules.",
		},
		WRITE =
        {
            GENERIC = "We can't write on that now.",
        },
		RUMMAGE =
        {   
            GENERIC = "That's off-limits.",  
        },
		COOK =
        {
            GENERIC = "I don't want to. Mom always said the kitchen was dangerous!",
            TOOFAR = "Let's scurry closer!",
        },
        GIVE =
        {
            DEAD = "Um. We should probably keep it.",
            SLEEPING = "Aww... It's sleepy-snoozy right now!",
            BUSY = "We can try again when it's finished.",
        },
        CHANGEIN =
        {
            GENERIC = "Not right now, we're comfy.",
            BURNING = "Woah! Hot fashions!",
        },
        TEACH =
        {
            KNOWN = "I'm pretty sure one of us knows that one.",
            CANTLEARN = "We don't get it...",
        },
		REPAIRBOAT =
		{
			GENERIC = "No need. It already floats our boat.",
		},
	},
	ACTIONFAIL_GENERIC = "Mom told me never to do that.",
	ANNOUNCE_MAGIC_FAIL = "I don't think this thing likes it here.",
	ANNOUNCE_ADVENTUREFAIL = "Play time is over.",
	ANNOUNCE_BEES = "Flying ouchies!",
	ANNOUNCE_BOOMERANG = "It hurts us when we don't catch it.",
	ANNOUNCE_CHARLIE = "Is somebody there?!",
	ANNOUNCE_CHARLIE_ATTACK = "Aah! Monsters in the dark!",
	ANNOUNCE_COLD = "Brrr... spider hair isn't very warm.",
	ANNOUNCE_HOT = "Hot as heck!",
	ANNOUNCE_CRAFTING_FAIL = "We're missing something.",
	ANNOUNCE_DEERCLOPS = "That sounded like a big meanie.",
	ANNOUNCE_DUSK = "Almost time for bed.",

	ANNOUNCE_EAT =
	{
		GENERIC = "Yummy in our tummy!",
		PAINFUL = "Our tummy hurts.",
		SPOILED = "Past its date.",
		STALE = "Stale like mum's leftovers.",
		INVALID = "That doesn't look like food to us.",
		YUCKY = "We can't, we won't, we refuse to eat that.",
	},
	ANNOUNCE_ENTER_DARK = "We can't see! I want my nightlight.",
	ANNOUNCE_ENTER_LIGHT = "Phew, light!",
	ANNOUNCE_FREEDOM = "We made it!",
	ANNOUNCE_HIGHRESEARCH = "I'm learning so much!",
	ANNOUNCE_HOUNDS = "Doggies are coming!",
	ANNOUNCE_HUNGRY = "It's time for a snack!",
	ANNOUNCE_HUNT_BEAST_NEARBY = "Fresh tracks!",
	ANNOUNCE_HUNT_LOST_TRAIL = "Animal went bye-bye.",
	ANNOUNCE_HUNT_LOST_TRAIL_SPRING = "It's too muddy to track.",
	ANNOUNCE_INV_FULL = "Our pockets are full!",
	ANNOUNCE_KNOCKEDOUT = "Ow, our head!",
	ANNOUNCE_LOWRESEARCH = "That might've taught a toddler something.",
	ANNOUNCE_MOSQUITOS = "Suck someone else's blood!",
	ANNOUNCE_NODANGERSLEEP = "Can't sleep with monsters nearby!",
	ANNOUNCE_NODAYSLEEP = "It's daytime, not bedtime.",
	ANNOUNCE_NODAYSLEEP_CAVE = "We're not ready for bed.",
	ANNOUNCE_NOHUNGERSLEEP = "Our tummy is rumbling, we can't sleep.",
	ANNOUNCE_NOSLEEPONFIRE = "Mum always said, \"Don't sleep in a burning building.\"",
	ANNOUNCE_NODANGERSIESTA = "Can't nap with monsters nearby!",
	ANNOUNCE_NONIGHTSIESTA = "We can't take a nap, it's nighttime!",
	ANNOUNCE_NONIGHTSIESTA_CAVE = "No naps til daybreak!",
	ANNOUNCE_NOHUNGERSIESTA = "Won't be able to nap with a rumbling tummy.",
	ANNOUNCE_NO_TRAP = "Easy peasy.",
	ANNOUNCE_PECKED = "Bad bird!",
	ANNOUNCE_QUAKE = "I don't think that was our tummy.",
	ANNOUNCE_RESEARCH = "It's almost like being back in school.",
	ANNOUNCE_SHELTER = "Protect us, tree!",
	ANNOUNCE_THORNS = "Yowch!",
	ANNOUNCE_BURNT = "Jeepers, that was hot!",
	ANNOUNCE_TORCH_OUT = "Waah, our light went out!",
	ANNOUNCE_FAN_OUT = "Aaw, the twirly is gone.",
    ANNOUNCE_COMPASS_OUT = "Uh oh, I broke it.",
	ANNOUNCE_TRAP_WENT_OFF = "Eek!",
	ANNOUNCE_UNIMPLEMENTED = "Gah! It needs more time.",
	ANNOUNCE_WORMHOLE = "That was a scary hole!",
	ANNOUNCE_CANFIX = "\nWe can repair it.",
	ANNOUNCE_ACCOMPLISHMENT = "We're so capable!",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "We're a super hero!",	
	ANNOUNCE_INSUFFICIENTFERTILIZER = "Not good enough for you, plant?",
	ANNOUNCE_TOOL_SLIP = "Hey! We were using that!",
	ANNOUNCE_LIGHTNING_DAMAGE_AVOIDED = "We're invincible!",

	ANNOUNCE_DAMP = "Splishy splashy.",
	ANNOUNCE_WET = "We're unpleasantly moist.",
	ANNOUNCE_WETTER = "Wet as a bathtub we can't crawl out of.",
	ANNOUNCE_SOAKED = "We're drenched!",
	ANNOUNCE_MESSAGEBOTTLE =
	{
		"Eight eyes isn't enough to read this.",
	},
	ANNOUNCE_OTHER_WORLD_PLANT = "We can't grow this here.",
	ANNOUNCE_BOAT_DAMAGED = "Our boat's hurt!",
	ANNOUNCE_BOAT_SINKING = "Down, down, down we go!",
	ANNOUNCE_BOAT_SINKING_IMMINENT = "Help! We can't swim!",
	ANNOUNCE_CRAB_ESCAPE = "You slippery snail... er, crabbit!",
	ANNOUNCE_MAPWRAP_LOSECONTROL = "We're trembling in our pantaloons!",
	ANNOUNCE_MAPWRAP_RETURN = "That was scary!",
	ANNOUNCE_MAPWRAP_WARN = "I don't like this...",
	ANNOUNCE_MORETREASURE = "Yay! Another treasure hunt!",
	ANNOUNCE_OTHER_WORLD_TREASURE = "I don't think I can find this treasure here.",
	ANNOUNCE_SHARX = "Mean sea hounds! Leave us alone!",
	ANNOUNCE_TRAWL_FULL = "Let's pull'er up!",
	ANNOUNCE_TREASURE = "A map! We should follow it!",
	ANNOUNCE_VOLCANO_ERUPT = "It's raining fire!",
	ANNOUNCE_WAVE_BOOST = "Weee!",
	ANNOUNCE_WHALE_HUNT_BEAST_NEARBY = "We're on the trail!",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL = "It went home...",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL_SPRING = "It's so choppy!",


	BATTLECRY =
	{
		GENERIC = "En garde!",
		PIG = "We hate it! Horrible pig!",
		PREY = "We will put you in our web!",
		SPIDER = "Hey, wanna play?",
		SPIDER_WARRIOR = "Why can't we just get along?!",
	},
	COMBAT_QUIT =
	{
		GENERIC = "Well, we would have won!",
		PIG = "Another day, pig.",
		PREY = "Speedy thing!",
		SPIDER = "We didn't actually want to hurt you.",
		SPIDER_WARRIOR = "Simmer down, friend.",
	},
	
	DESCRIBE_GENERIC = "Can we play with it?",
	DESCRIBE_TOODARK = "All our eyes stopped working!",
	DESCRIBE_SMOLDERING = "Uh-oh. I smell burning!",
	
	DESCRIBE =
	{
        INVENTORYGRAVE = "They're just sleeping.",
		INVENTORYMOUND = "They're just sleeping.",

		LAVA_POND_ROCK = "Wow! A rock!",
		LAVA_POND_ROCK2 = "Wow! A rock!",
		LAVA_POND_ROCK3 = "Wow! A rock!",
		LAVA_POND_ROCK4 = "Wow! A rock!",
		LAVA_POND_ROCK5 = "Wow! A rock!",
		LAVA_POND_ROCK6 = "Wow! A rock!",
		LAVA_POND_ROCK7 = "Wow! A rock!",

		SPIDER_WARRIOR =
		{
			GENERIC = "Can you teach us to fight good?",
			SLEEPING = "Night-night.",
			DEAD = "Forgive us.",
		},
        GLOMMER = "Nice eyes.",
        GLOMMERFLOWER = 
        {
        	GENERIC = "It doesn't smell very nice.",
        	DEAD = "I spoke too soon. It smells worse now.",
        },
        GLOMMERWINGS = "I wish I'd at least ended up with wings. Sigh.",
        GLOMMERFUEL = "Yucky muck!",
        BELL = "Exactly the right amount of bell.",
        STATUEGLOMMER = 
        {	
        	GENERIC = "A statue of some weird bug.",
        	EMPTY = "Take that, rock bug!",
    	},

		WEBBERSKULL = "How did this get here?",
		WORMLIGHT = "It's gushing with light.",
		WORMLIGHT_LESSER = "I dare you to eat it!",
		WORM =
		{
		    PLANT = "What could possibly go wrong?",
		    DIRT = "Some dirt, big whoop.",
		    WORM = "Creepy crawly!",
		},
		WORMLIGHT_PLANT = "What could possibly go wrong?",
		MOLE =
		{
			HELD = "Are you comfy?",
			UNDERGROUND = "Come out and play!",
			ABOVEGROUND = "Hello little guy!",
		},
		MOLEHILL = "Hidey-hole.",
		MOLEHAT = "I can see for miles and miles.",
		MOONROCKNUGGET = "Neat!",
		ROCK_MOON = "Neat!",

		EEL = "Fresh water-snake.",
		EEL_COOKED = "We could slurp this down.",
		UNAGI = "It was easy to make with all our arms.",
		EYETURRET = "Stop looking at me!",
		EYETURRET_ITEM = "Wakey wakey!",
		MINOTAURHORN = "It's quite tender.",
		MINOTAURCHEST = "What a big treasure box!",
		THULECITE_PIECES = "Small bits of fancy rock.",
		POND_ALGAE = "Just a normal pond plant.",
		GREENSTAFF = "Magic taker-apart-er.",
		POTTEDFERN = "Mum would like this nice fern.",

		THULECITE = "Fancy rocks!",
		ARMORRUINS = "Nice and lightweight.",
		RUINS_BAT = "We will, we will, smash you!",
		RUINSHAT = "And now we are king.",
		BISHOP_NIGHTMARE = "Bishop of bad dreams.",
		ROOK_NIGHTMARE = "You can't rook us.",
		KNIGHT_NIGHTMARE = "Goodnight, good knight.",
		MINOTAUR = "Wear that frown upside down.",
		SPIDER_DROPPER = "Our friends live up there.",
		NIGHTMARELIGHT = "Not exactly my kind of nightlight.",
		NIGHTSTICK = "Night light, night bright!",
		GREENGEM = "I'm absolutely green with envy.",
		RELIC = "Reminds me of home, if I had lived in ancient times.",
		RUINS_RUBBLE = "We can repair it!",
		MULTITOOL_AXE_PICKAXE = "Double duty.",
		ORANGESTAFF = "Teleportation gives us a chance to rest all our feet.",
		YELLOWAMULET = "Nice and glowy.",
		GREENAMULET = "Time to build!",
		SLURPERPELT = "It's like a tiny rug.",	

		SLURPER = "Hairy tongue thing!",
		SLURPER_PELT = "It's like a tiny rug.",
		ARMORSLURPER = "Squeeze our tummy tight!",
		ORANGEAMULET = "Many legs make light work, and so does this.",
		YELLOWSTAFF = "We summon you, warm ball of light!",
		YELLOWGEM = "Yellow-bellied gem.",
		ORANGEGEM = "Orange you glad we found you, gem?",
		TELEBASE = 
		{
			VALID = "Teleportation, away!",
			GEMS = "It needs s'more purple gems.",
		},
		GEMSOCKET = 
		{
			VALID = "Looks prepped.",
			GEMS = "Still needs a gem.",
		},
		STAFFLIGHT = "Cozy.",
	
        ANCIENT_ALTAR = "Old and full of mysteries.",

        ANCIENT_ALTAR_BROKEN = "It's been busted up.",

        ANCIENT_STATUE = "It's throbbing strangely.",

        LICHEN = "It likes it down here.",
		CUTLICHEN = "I like me a lichen.",

		CAVE_BANANA = "A bundle of bananas.",
		CAVE_BANANA_COOKED = "Hot mush.",
		CAVE_BANANA_TREE = "It's a tropical cave tree, of course.",
		ROCKY = "Snip snap!",
		
		COMPASS =
		{
			GENERIC= "We can't get a reading!",
			N = "North!",
			S = "South!",
			E = "East!",
			W = "West!",
			NE = "Northeast!",
			SE = "Southeast!",
			NW = "Northwest!",
			SW = "Southwest!",
		},

		NIGHTMARE_TIMEPIECE =
		{
			CALM = "Everything's dandy.",
			WARN = "Something's brewing.",
			WAXING = "It's getting magickier!",
			STEADY = "Stable, for now.",
			WANING = "Magic go down the hole.",
			DAWN = "Return to us, day!",
			NOMAGIC = "Not much magic here.",
		},

		HOUNDSTOOTH="Our very own tooth to gnash.",
		ARMORSNURTLESHELL="We're a giant spider! Wearing a shell!",
		BAT="Screechy mean guy!",
		BATBAT = "Flap that bat like you were born to do it.",
		BATWING="This thing drives me batty.",
		BATWING_COOKED="Tastes like chicken.",
		BATCAVE= "Oooh they're hiding in there!",
		BEDROLL_FURRY="I miss being able to properly feel a nice bedroll.",
		BUNNYMAN="Hop along, lil bunny.",
		FLOWER_CAVE="Oooh, a glowing ball of flower!",
		FLOWER_CAVE_DOUBLE="Oooh, a glowing ball of flower!",
		FLOWER_CAVE_TRIPLE="Oooh, a glowing ball of flower!",
		GUANO="Bat doodoo.",
		LANTERN="We have captured the sun.",
		LIGHTBULB="Bright and delicious.",
		MANRABBIT_TAIL="We feel lucky, oh so lucky.",
		MUSHTREE_TALL  ="How did it get so big?",
		MUSHTREE_MEDIUM="It's upsettingly large.",
		MUSHTREE_SMALL ="Bigger than a normal mushroom.",
		MUSHTREE_TALL=
		{
            GENERIC = "How did it get so big?",
            BLOOM = "It sounds so funny!",
        },
		MUSHTREE_MEDIUM=
		{
            GENERIC = "It's upsettingly large.",
            BLOOM = "Hahah! Wow, it smells so bad!",
        },
		MUSHTREE_SMALL=
		{
            GENERIC = "Bigger than a normal mushroom.",
            BLOOM = "It's all round and squishy now!",
        },
        MUSHTREE_TALL_WEBBED = "This one looks friendly!",
        SPORE_TALL = "Catch it! Catch it!",
        SPORE_MEDIUM = "Catch it! Catch it!",
        SPORE_SMALL = "Catch it! Catch it!",
        SPORE_TALL_INV = "If we stare at it we'll turn to stone!",
        SPORE_MEDIUM_INV = "If we lick it we'll turn to wood!",
        SPORE_SMALL_INV = "If we eat it we'll turn to water!",

		RABBITHOUSE=
		{
			GENERIC = "Just like grandpa said, \"You live in what you eat.\"",
			BURNT = "A little overdone and overlarge.",
		},
		SLURTLE="We'll slaughter that slurtle.",
		SLURTLE_SHELLPIECES="We hit it a little too hard.",
		SLURTLEHAT="A solid helmet.",
		SLURTLEHOLE="Slimy and rocky.",
		SLURTLESLIME="Slime-time!",
		SNURTLE="We'll snuff out that snurtle.",
		SPIDER_HIDER="Friends!",
		SPIDER_SPITTER="Lay down some web for us.",
		SPIDERHOLE="We could stand to live there.",
		SPIDERHOLE_ROCK = "We could stand to live there.",
		STALAGMITE="Rocks underground?! Shocking.",
		STALAGMITE_FULL="Rocks underground?! Shocking.",
		STALAGMITE_LOW="Rocks underground?! Shocking.",
		STALAGMITE_MED="Rocks underground?! Shocking.",
		STALAGMITE_TALL="Pointy rocks underground?! Simply stunning.",
		STALAGMITE_TALL_FULL="Pointy rocks underground?! Simply stunning.",
		STALAGMITE_TALL_LOW="Pointy rocks underground?! Simply stunning.",
		STALAGMITE_TALL_MED="Pointy rocks underground?! Simply stunning.",

		LIGHTER = "Lighter than what?",
		BOOK_BIRDS = "This one has pictures!",
		BOOK_TENTACLES = "I'll read it for us!",
		BOOK_GARDENING = "Why should we read about flowers when we can just pick them?",
		BOOK_SLEEP = "It's... beddy-bye time...",
		BOOK_BRIMSTONE = "We don't like how this one ends!",
		LUCY = "If we talks to it will it talk back?",
		BALLOONS_EMPTY = "Is there going to be a party?!",
		SPEAR_WATHGRITHR = "Pointy ouchies!",
		WAXWELLJOURNAL = "I don't think we should play with that...",

		ABIGAIL_FLOWER = 
		{ 
			GENERIC = "Pretty petals!",
			LONG = "I think it's listening to us!",
			MEDIUM = "It's getting creepy!",
			SOON = "It gives us itches and skritches up our spine!",
			HAUNTED_POCKET = "Put it down! Put it down!",
			HAUNTED_GROUND = "Scary blossoms!",
		},

		TURF_CARPETFLOOR = "Soft like our body.",
		TURF_CHECKERFLOOR = "Our feet go click-clack on this.",
		TURF_DIRT = "Some pretty average earth.",
		TURF_FOREST = "Some pretty average earth.",
		TURF_GRASS = "Some pretty average earth.",
		TURF_MARSH = "Some pretty average earth.",
		TURF_ROAD = "Some pretty average earth.",
		TURF_ROCKY = "Some pretty average earth.",
		TURF_SAVANNA = "Some pretty average earth.",
		TURF_WOODFLOOR = "Some pretty average earth.",

		TURF_CAVE="Some pretty average earth.",
		TURF_FUNGUS="Some pretty average earth.",
		TURF_SINKHOLE="Some pretty average earth.",
		TURF_UNDERROCK="Some pretty average earth.",
		TURF_MUD="Some pretty average earth.",

		POWCAKE = "Mum never let me have these.",
        CAVE_ENTRANCE = "It's plugged up.",
        CAVE_ENTRANCE_RUINS = "It's plugged up.",

		CAVE_ENTRANCE_OPEN = 
        {
            GENERIC = "We'd rather visit our spider friends on the surface.",
            OPEN = "I can hear some spider friends down there.",
        },
        CAVE_EXIT = 
        {
            GENERIC = "We like it down here.",
            OPEN = "It leads back to the light.",
        },

		MAXWELLPHONOGRAPH = "We could listen to that forever!",
		BOOMERANG = "Boomerangarangarang!",
		PIGGUARD = "We wouldn't want to cross that one.",
		ABIGAIL = "That's no party poltergeist!",
		ADVENTURE_PORTAL = "Something wicked this way comes.",
		AMULET = "It's a fine necklace, I suppose.",
		ANIMAL_TRACK = "Whatever it is, it travels single file.",
		ARMORGRASS = "It just feels like more hair.",
		ARMORMARBLE = "Marbelous protection!",
		ARMORWOOD = "Wood you like to fight?",
		ARMOR_SANITY = "I'm a bit uneasy wearing this, but it's effective.",
		ASH =
		{
			GENERIC = "Funk to funky.",
			REMAINS_GLOMMERFLOWER = "The flower didn't make it.",
			REMAINS_EYE_BONE = "The eyebone didn't survive the trip.",
			REMAINS_THINGIE = "Whatever it was, it's gone back to the earth.",
		},
		AXE = "Chop and chop.",
		BABYBEEFALO = "Get busy, child.",
		BACKPACK = "It's like a second abdomen we can store things in.",
		BACONEGGS = "I'd rather have sugary cereal. Oh well.",
		BANDAGE = "A bandage for our booboos.",
		BASALT = "Impenetrable.",
		BEARDHAIR = "In another life, I could've grown this.",
		BEARGER = "Run for the hills!",
		BEARGERVEST = "We'll be the hairiest spider ever.",
		ICEPACK = "I can bear this pack!",
		BEARGER_FUR = "It's so thick!",
		FURTUFT = "Fluffy, and not from a spider.",	
		BEDROLL_STRAW = "Musty but relaxing.",
		BEE =
		{
			GENERIC = "Always Be Pollinating.",
			HELD = "Ours now!",
		},
		BEEBOX =
		{
			FULLHONEY = "It's full to brimming.",
			READY = "It's full to brimming.",
			GENERIC = "It's a box with bees in it.",
			NOHONEY = "There's no honey inside.",
			SOMEHONEY = "Work faster, bees!",
			BURNT = "The site of The Great Honey Fire.",
		},
		BEEFALO =
		{
			FOLLOWER = "He seems to want to stick around.",
			GENERIC = "Big big beefalo!",
			NAKED = "Shaved you good!",
			SLEEPING = "Slumber deep, beefalo.",
		},
		BEEFALOHAT = "We'll blend in perfectly.",
		BEEFALOWOOL = "Thick fur.",
		BEEHAT = "A fortress for my face.",
		BEEHIVE = "It's a hive of activity.",
		BEEMINE = "Would you bee mine?",
		BEEMINE_MAXWELL = "I just can't mosquito you.",
		BERRIES = "Juice sacks.",
		BERRIES_COOKED = "Warm juice sacks.",
		BERRYBUSH =
		{
			BARREN = "It's run out of plant food.",
			WITHERED = "Heat too intense for ya?",
			GENERIC = "Ripe for the pickin'.",
			PICKED = "See you soon, berries!",
		},
		BIGFOOT = "AAAAAAAAAAH!",
		BIRDCAGE =
		{
			GENERIC = "It's the jail.",
			OCCUPIED = "Jailbird.",
			SLEEPING = "You have to sleep to survive in the jail.",
			HUNGRY = "He looks hungry.",
			STARVING = "We need to feed him.",
			DEAD = "We weren't very good wardens.",
			SKELETON = "Eww.",
		},
		BIRDTRAP = "Come to our web trap, birds!",
		BIRD_EGG = "A hard shelled egg.",
		PANDORASCHEST = "Stylish storage.",
		SCORCHED_SKELETON = "They're probably fine.",
		CAVE_BANANA_BURNT = "Oopsie doodle.",
		BIRD_EGG_COOKED = "Fried just like mum did.",
		BISHOP = "You don't play by the chess rules grandpa taught me.",
		BLOWDART_FIRE = "One step above blowing hot air.",
		BLOWDART_SLEEP = "Airborne sleeping agent.",
		BLOWDART_PIPE = "Same as blowing bubbles.",
		BLUEAMULET = "I guess it's nice.",
		BLUEGEM = "Glittering and cool.",
		BLUEPRINT = "\"Follow the instructions\", mum always said.",
		BELL_BLUEPRINT = "\"Follow the instructions\", mum always said.",
		BLUE_CAP = "You'd have to be crazy...",
		BLUE_CAP_COOKED = "Good thing we're feeling healthy.",
		BLUE_MUSHROOM =
		{
			GENERIC = "Vroom vroom, mushroom.",
			INGROUND = "Hiding, are we?",
			PICKED = "Maybe it will regrow.",
		},
		BOARDS = "Logs, but flat.",
		BOAT = "All these legs, but we don't row.",
		BONESHARD = "Boney bits.",
		BONESTEW = "Smells like Sunday supper.",
		BUGNET = "It's like a portable web!",
		BUSHHAT = "Spider in the bushes.",
		BUTTER = "Butter is better.",
		BUTTERFLY =
		{
			GENERIC = "Look at it, flitting around happily.",
			HELD = "Not so happy now, are we?",
		},
		BUTTERFLYMUFFIN = "Do you know the muffin spider?",
		BUTTERFLYWINGS = "Pick our teeth with butterfly bones.",
		BUZZARD = "You won't find any carrion here. We're stuck like this.",
		CACTUS = 
		{
			GENERIC = "It's got more things coming out of it than we do.",
			PICKED = "It's got no meat left in it.",
		},
		CACTUS_MEAT_COOKED = "Take that, pokey things!",
		CACTUS_MEAT = "Haven't had enough, huh?",
		CACTUS_FLOWER = "This part is nice.",
		COLDFIRE =
		{
			EMBERS = "We should put something on the fire before it goes out.",
			GENERIC = "Sure beats the heat. And darkness.",
			HIGH = "That fire is huge!",
			LOW = "The fire's getting a touch low.",
			NORMAL = "Nice and cool.",
			OUT = "Well, that's done.",
		},
		CAMPFIRE =
		{
			EMBERS = "We should put something on the fire before it goes out.",
			GENERIC = "Sure beats the cold. And darkness.",
			HIGH = "That fire is huge!",
			LOW = "The fire's getting a touch low.",
			NORMAL = "Nice and warm.",
			OUT = "Well, that's done.",
		},
		CANE = "One more point of contact couldn't slow us down.",
		CATCOON = "A bit more feral than grandpa's cat.",
		CATCOONDEN = 
		{
			GENERIC = "Trunk house.",
			EMPTY = "The nine lives thing is true!",
		},
		CATCOONHAT = "Hat of a cat.",
		COONTAIL = "I always liked pulling Whiskers' tail.",
		CARROT = "I sort of miss being forced to eat these.",
		CARROT_COOKED = "Easier for us both.",
		CARROT_PLANTED = "Bury your head, carrot.",
		CARROT_SEEDS = "We could grow something with these.",
		CAVE_FERN = "Swirly plants.",
		CHARCOAL = "Hard and black, like my better half.",
        CHESSJUNK1 = "A mess of chess.",
        CHESSJUNK2 = "A mess of chess.",
        CHESSJUNK3 = "A mess of chess.",
		CHESTER = "Haha. You make all our stuff slobbery.",
		CHESTER_EYEBONE =
		{
			GENERIC = "Peekaboo.",
			WAITING = "We spy a tired eye.",
		},
		COOKEDMANDRAKE = "Cooked to death.",
		COOKEDMEAT = "Can't have any pudding if we don't eat it.",
		COOKEDMONSTERMEAT = "It'll go down, but I won't be happy about it.",
		COOKEDSMALLMEAT = "Meat treat.",
		COOKPOT =
		{
			COOKING_LONG = "It won't be done for a while.",
			COOKING_SHORT = "Almost ready!",
			DONE = "Supper is served.",
			EMPTY = "Food goes in, other food comes out.",
			BURNT = "Someone must have left the fire going.",
		},
		CORN = "Corn in the raw.",
		CORN_COOKED = "Popping corn.",
		CORN_SEEDS = "We could grow something with these.",
		CROW =
		{
			GENERIC = "Oh, you look like you're having a grand time, flying about.",
			HELD = "We all want a bit of freedom.",
		},
		CUTGRASS = "We should be able to weave this, too.",
		CUTREEDS = "Reeds, web, what's the difference.",
		CUTSTONE = "Squared rocks.",
		DEADLYFEAST = "Scent of doom.",
		DEERCLOPS = "He might be able to digest me!",
		DEERCLOPS_EYEBALL = "Yucktastic.",
		EYEBRELLAHAT =	"Disturbing, but it'll keep us dry.",
		DEPLETED_GRASS =
		{
			GENERIC = "It was once grass.",
		},
		DEVTOOL = "Axe me a question!",
		DEVTOOL_NODEV = "I can't wield that.",
		DIRTPILE = "A pile of dirt. I bet it's hiding something.",
		DIVININGROD =
		{
			COLD = "Nothing nearby.",
			GENERIC = "Lead and I shall follow.",
			HOT = "We are close!",
			WARM = "Going the right way.",
			WARMER = "Something must be near.",
		},
		DIVININGRODBASE =
		{
			GENERIC = "It's a mystery.",
			READY = "Looks like there's a hole for an oversized key.",
			UNLOCKED = "It's ready to go.",
		},
		DIVININGRODSTART = "Radical rod!",
		DRAGONFLY = "Oh, don't you just drag on.",
		ARMORDRAGONFLY = "Another creature casing.",
		DRAGON_SCALES = "They don't weigh much for scales.",
		DRAGONFLYCHEST = "It looks like my old toy chest!",
		LAVASPIT = 
		{
			HOT = "Too hot for us!",
			COOL = "Looks safe now.",
		},
		LAVA_POND = "Ouch! Burnies!",
		LAVAE = "Sizzling hot!",
		LAVAE_PET = 
		{
			STARVING = "It looks starving!",
			HUNGRY = "Poor hungry lavae.",
			CONTENT = "Happy lavae!",
			GENERIC = "It's my friend.",
		},
		LAVAE_EGG = 
		{
			GENERIC = "Maybe I can make it hatch?",
		},
		LAVAE_EGG_CRACKED =
		{
			COLD = "Poor egg. It looks cold.",
			COMFY = "The egg seems happy.",
		},
		LAVAE_TOOTH = "What a weird tooth.",

		DRAGONFRUIT = "It looks suspect.",
		DRAGONFRUIT_COOKED = "It looks tastier now.",
		DRAGONFRUIT_SEEDS = "We could grow something with these.",
		DRAGONPIE = "We baked it!",
		DRUMSTICK = "I just want to bang on my drum.",
		DRUMSTICK_COOKED = "We love finger food.",
		DUG_BERRYBUSH = "Into the ground with you!",
		DUG_GRASS = "Into the ground with you!",
		DUG_MARSH_BUSH = "Into the ground with you!",
		DUG_SAPLING = "Into the ground with you!",
		DURIAN = "Pungent.",
		DURIAN_COOKED = "No sir, I don't like it.",
		DURIAN_SEEDS = "We could grow something with these.",
		EARMUFFSHAT = "Strap some rabbits to our head, good idea.",
		EGGPLANT = "Blech, eggplant.",
		EGGPLANT_COOKED = "Mum knew I liked it braised.",
		EGGPLANT_SEEDS = "We could grow something with these.",
		DECIDUOUSTREE = 
		{
			BURNING = "What a senseless waste of firewood.",
			BURNT = "Only we can prevent forest fires.",
			CHOPPED = "Got you good, tree!",
			POISON = "What're you so mad about?",
			GENERIC = "My, what nice foliage you have.",
		},
		ACORN = 
		{
		    GENERIC = "Tree or food, there's something inside.",
		    PLANTED = "May you have a long and free life.",
		},
		ACORN_COOKED = "Roasted on an open fire.",
		BIRCHNUTDRAKE = "So that's what's inside!",
		EVERGREEN =
		{
			BURNING = "What a senseless waste of firewood.",
			BURNT = "Only we can prevent forest fires.",
			CHOPPED = "Got you good, tree!",
			GENERIC = "Pines are always greener on the other side of the fence.",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "What a senseless waste of firewood.",
			BURNT = "Only we can prevent forest fires.",
			CHOPPED = "Got you good, tree!",
			GENERIC = "A dying breed.",
		},
		EYEPLANT = "Ever vigilant.",
		FARMPLOT =
		{
			GENERIC = "I'll have a go at this farming thing.",
			GROWING = "C'mooon, plants!",
			NEEDSFERTILIZER = "The soil is dried up.",
			BURNT = "A razed farm is no farm at all.",
		},
		FEATHERHAT = "Feathers enough to cover our spiderness.",
		FEATHER_CROW = "Feather of black.",
		FEATHER_ROBIN = "Feather of red.",
		FEATHER_ROBIN_WINTER = "Feather of white.",
		FEM_PUPPET = "She's locked up!",
		FIREFLIES =
		{
			GENERIC = "Elusive little buggies.",
			HELD = "Going on an adventure, got some fireflies in our pocket!",
		},
		FIREHOUND = "He's got a fire under his feet. And all inside him.",
		FIREPIT =
		{
			EMBERS = "We should put something on the fire before it goes out.",
			GENERIC = "Sure beats the cold. And darkness.",
			HIGH = "That fire is huge!",
			LOW = "The fire's getting a touch low.",
			NORMAL = "Nice and warm.",
			OUT = "Well, that's done. But not forever!",
		},
		COLDFIREPIT =
		{
			EMBERS = "We should put something on the fire before it goes out.",
			GENERIC = "Sure beats the heat. And darkness.",
			HIGH = "That fire is huge!",
			LOW = "The fire's getting a touch low.",
			NORMAL = "Nice and cool.",
			OUT = "Well, that's done. But not forever!",
		},
		FIRESTAFF = "We didn't start the fire.",
		FIRESUPPRESSOR = 
		{	
			ON = "This would come in handy in a snowball fight.",
			OFF = "It's off.",
			LOWFUEL = "Running low on fuel.",
		},

		FISH = "It could stand to be fried.",
		FISHINGROD = "I miss grandpa's fishing trips.",
		FISHSTICKS = "At least we know how to make fish sticks.",
		FISHTACOS = "Taco Tuesday!",
		FISH_MED = "All dogfish go to heaven, right?",
		FISH_MED_COOKED = "Flaky and moist. Delicious.",
		FISH_COOKED = "Flaky and moist. Delicious.",
		FLINT = "Oh, to feel a sharp edge against my skin.",
		FLOWER = "We agree that flowers are nice.",
		FLOWER_WITHERED = "Aww so sad!",
		FLOWERHAT = "Colorful crown.",
		FLOWER_EVIL = "This flower is decidedly not nice!",
		FOLIAGE = "Soft and leafy.",
		FOOTBALLHAT = "We could be good at football, much better than I was!",
		FROG =
		{
			DEAD = "A hop too far.",
			GENERIC = "Ack! Sticky tongue!",
			SLEEPING = "Oblivious amphibious.",
		},
		FROGGLEBUNWICH = "Sandwich for me, frog legs for him.",
		FROGLEGS = "A fraction of a frog.",
		FROGLEGS_COOKED = "I admit, I've acquired a taste for these.",
		FRUITMEDLEY = "Pile o'fruit.",
		GEARS = "I wish I'd been a robot.",
		GHOST = "That's not a fun ghost!",
        GHOST_SAILOR = "He looks kind of sad.",
		GOLDENAXE = "Life is okay when you've got a golden axe.",
		GOLDENPICKAXE = "The finest pickaxe of them all.",
		GOLDENPITCHFORK = "We can do some fancy forking with this.",
		GOLDENSHOVEL = "We're gonna dig so many holes.",
		GOLDNUGGET = "We definitely like shiny.",
		GRASS =
		{
			BARREN = "It could use some perking up.",
			WITHERED = "The heat wave bested it.",
			BURNING = "Fire, fire, fire!",
			GENERIC = "Grass, next best thing to silk.",
			PICKED = "Picked down to the stems.",
		},
		GREEN_CAP = "Smells really earthy.",
		GREEN_CAP_COOKED = "Heat really brings out the juices.",
		GREEN_MUSHROOM =
		{
			GENERIC = "Ready for harvest.",
			INGROUND = "We can't get at it!",
			PICKED = "It's gone now.",
		},
		GUNPOWDER = "We're getting good at making stuff.",
		HAMBAT = "An interesting way to use food.",
		HAMMER = "Chaos and destruction!",
		HEALINGSALVE = "Soothing.",
		HEATROCK =
		{
			FROZEN = "It's cold to the touch.",
			COLD = "It's getting chilly.",
			GENERIC = "It's a rock.",
			WARM = "It's getting hot!",
			HOT = "It's hot to the touch!",
		},
		HOMESIGN = 
		{
			GENERIC = "We could write on that if only we had a pen!",
			BURNT = "The lettering burnt off.",
		},
		HONEY = "Sticky and sweet.",
		HONEYCOMB = "Honey pods!",
		HORN = "If this makes a mating call we're in trouble.",
		HOUND = "That's an angry puppy!",
		HOUNDBONE = "There isn't much left.",
		HOUNDMOUND = "This place scares us.",
		ICEBOX = "Spoil not, food supplies!",
		ICEHAT = "This should keep us cool.",
		ICEHOUND = "He has a chilling look in his eyes.",
		INSANITYROCK =
		{
			ACTIVE = "Move, stupid rock!",
			INACTIVE = "I wonder what that does.",
		},
		HONEYHAM = "Ooo, tasty!",
		HONEYNUGGETS = "We wish they were shaped like dinosaurs.",
		JAMMYPRESERVES = "Ew... sticky fingies.",
		KABOBS = "Foods on a stick!",
		KILLERBEE =
		{
			GENERIC = "Uh oh, run!",
			HELD = "I hope it doesn't escape.",
		},
		KNIGHT = "Wow! That's complicated clockwork.",
		KOALEFANT_SUMMER = "Maybe it's lost.",
		KOALEFANT_WINTER = "We finally found it!",
		KRAMPUS = "Give us back our things!",
		KRAMPUS_SACK = "We could put more in but we're scared to touch the stuff he left inside.",
		LEIF = "Where did that come from?!",
		LEIF_SPARSE = "Where did that come from?!",
		LIGHTNING_ROD =
		{
			CHARGED = "It looks all glowy!",
			GENERIC = "This might keep us safe.",
		},
		LIGHTNINGGOAT = 
		{
			GENERIC = "My father kept goats.",
			CHARGED = "It's all glowy.",
		},
		LIGHTNINGGOATHORN = "This might make a good weapon.",
		GOATMILK = "A glass of milk with every supper.",
		LITTLE_WALRUS = "He has anger in his eyes.",
		LIVINGLOG = "This log has a face.",
		LOCKEDWES = "Hello? Can you hear me?",
		LOG =
		{
			BURNING = "So much for our arts and crafts!",
			GENERIC = "That's a log of wood.",
		},
		LUREPLANT = "What a colorful plant.",
		LUREPLANTBULB = "I wish we could learn to generate meat.",
		MALE_PUPPET = "He doesn't look like he's having much fun.",
		MANDRAKE =
		{
			DEAD = "The skin is all seared.",
			GENERIC = "That's a funny looking plant.",
			PICKED = "You're a bad friend!",
		},
		MANDRAKESOUP = "We fall asleep in the bath too!",
		MANDRAKE_COOKED = "The meeping had to stop.",
		MARBLE = "Maybe we should take up sculpting.",
		MARBLEPILLAR = "Nothing lasts forever in this world.",
		MARBLETREE = "I hope it doesn't fall on us.",
		MARSH_BUSH =
		{
			BURNING = "It will be gone soon!",
			GENERIC = "Hope we don't fall on that.",
			PICKED = "That hurt our hands.",
		},
		MARSH_PLANT = "That's a thirsty plant.",
		MARSH_TREE =
		{
			BURNING = "It's extra dangerous now!",
			BURNT = "Its growing days are over.",
			CHOPPED = "Axes can solve all tree-related problems!",
			GENERIC = "A harsh tree for harsh conditions.",
		},
		MAXWELL = "That jerk tricked us.",
		MAXWELLLIGHT = "Well, these would've been handy before.",
		MAXWELLLOCK = "It's missing something.",
		MAXWELLTHRONE = "That throne makes our skin crawl.",
		MEAT = "Some fire would spice this up.",
		MEATBALLS = "I used to make these with grandpa!",
		MEATRACK =
		{
			DONE = "Food time!",
			DRYING = "Is it done yet? I'm hungry.",
			DRYINGINRAIN = "It's hard to dry when it's raining.",
			GENERIC = "It's not doing us much good empty!",
			BURNT = "Fire takes all.",
		},

		MEAT_DRIED = "That worked better than expected.",
		MERM = "I would've thought they would bathe more often!",
		MERMHEAD = 
		{
			GENERIC = "A waste of food.",
			BURNT = "I wonder who that was.",
		},
		MERMHOUSE = 
		{
			GENERIC = "Smells fishy.",
			BURNT = "It's in worse shape than before!",
		},
		MINERHAT = "A handy light for our head.",
		MONKEY = "He just wants to learn!",

		MONKEYBARREL = "Did you hear something?",
		MONSTERLASAGNA = "Mmm!",
		FLOWERSALAD = "Five servings a day.",
        ICECREAM = "We dream of ice cream.",
        WATERMELONICLE = "Just the thing for a hot summer day.",
        TRAILMIX = "Crunchy and healthy.",
        HOTCHILI = "Flavor bombs!",
        GUACAMOLE = "Holy moley, this is tasty.",
		MONSTERMEAT = "Smells foul.",
		MONSTERMEAT_DRIED = "It's really chewy.",
		MOOSE = "She doesn't look at all pleased to see us.",
		MOOSEEGG = "That would make a huge breakfast!",
		MOSSLING = "Hungry little guys.",
		FEATHERFAN = "This thing is huge!",
		TROPICALFAN = "This thing is huge!",
		MINIFAN = "It cools us when we run, how nice.",
		GOOSE_FEATHER = "Tickle torture.",
		STAFF_TORNADO = "We'll huff and we'll puff.",
		MOSQUITO =
		{
			GENERIC = "Shoo!",
			HELD = "We have you in our web.",
		},
		MOSQUITOSACK = "Maybe we can put the blood back in?",
		MOUND =
		{
			DUG = "We're sorry about that.",
			GENERIC = "Our loot sense is tingling.",
		},
		NIGHTLIGHT = "It makes our skin crawl.",
		NIGHTMAREFUEL = "It's cold and slippery.",
		NIGHTSWORD = "Are you seeing this too?",
		NITRE = "What are we supposed to do with this?",
		ONEMANBAND = "We need to practice more.",
		PANFLUTE = "A well constructed instrument.",
		PAPYRUS = "We could do our homework.",
		PHLEGM = "It's a boogie!",
		PENGUIN = "Where do they live the rest of the year?",
		PERD = "Come back! I just want to eat you!",
		PEROGIES = "It does not look like pie...",
		PETALS = "How colorful.",
		PETALS_EVIL = "They make our head hurt.",
		PICKAXE = "Rocks will be ours!",
		PIGGYBACK = "It holds so much stuff!",
		PIGHEAD = 
		{	
			GENERIC = "We just wanted to be friends.",
			BURNT = "Gross.",
		},
		PIGHOUSE =
		{
			GENERIC = "A tall skinny house for a short fat pig.",
			FULL = "I can see a pig through the window!",
			LIGHTSOUT = "Why do they hate me?",
			BURNT = "Not so fancy now, pig!",
		},
		PIGKING = "King of the bullies!",
		PIGMAN =
		{
			DEAD = "He won't bully us any more.",
			GENERIC = "Aw, you're no fun.",
			GUARD = "They look angry.",
			WEREPIG = "He's all furry now!",
			FOLLOWER = "Hoist the sails, matey!",
		},
		PIGSKIN = "Take that!",
		PIGTORCH = "If only we could get closer.",
		PINECONE = 
		{
		    GENERIC = "It's bursting with life.",
		    PLANTED = "Grow, grow!",
		},
		PITCHFORK = "A good tool to play in the dirt.",
		PLANTMEAT = "It's all squishy.",
		PLANTMEAT_COOKED = "It smells kind of rotten.",
		PLANT_NORMAL =
		{
			GENERIC = "What will blossom?",
			GROWING = "Is it done yet?",
			READY = "We're master farmers.",
			WITHERED = "It's all dried out and dead.",
		},
		POMEGRANATE = "I didn't expect this to grow.",
		POMEGRANATE_COOKED = "It's good for us!",
		POMEGRANATE_SEEDS = "We could grow something with these.",
		POND = "Water doesn't go well with our fur.",
		POOP = "Doodoo.",
		FERTILIZER = "I saw mum use this in her gardens.",
		PUMPKIN = "That's a huge pumpkin!",
		PUMPKINCOOKIE = "Yum!",
		PUMPKIN_COOKED = "It's all warm now.",
		PUMPKIN_LANTERN = "Just like we used to make at home!",
		PUMPKIN_SEEDS = "We could grow something with these.",
		PURPLEAMULET = "Did you hear something?",
		PURPLEGEM = "I can see knowledge swimming inside.",
		RABBIT =
		{
			GENERIC = "We just want to play!",
			HELD = "He's ours now.",
		},
		RABBITHOLE = 
		{
			GENERIC = "Come out! We just want to be friends.",
			SPRING = "I hope they're okay in there.",
		},
		RAINOMETER = 
		{	
			GENERIC = "It must be powered by magic.",
			BURNT = "I don't think that's accurate.",
		},
		RAINCOAT = "We might look silly, but it'll keep our fur dry.",
		RAINHAT = "It'll keep the water out of our fur.",
		RATATOUILLE = "Do we have to eat our veggies?",
		RAZOR = "I watched my father use one of these.",
		REDGEM = "It feels warm even on the coldest nights.",
		RED_CAP = "It smells funny.",
		RED_CAP_COOKED = "It smells better now.",
		RED_MUSHROOM =
		{
			GENERIC = "Ready for the taking!",
			INGROUND = "We can't get at it like that.",
			PICKED = "I think some spores remain.",
		},
		REEDS =
		{
			BURNING = "Those burn quickly!",
			GENERIC = "Maybe we could use some of those.",
			PICKED = "Only stems remain.",
		},
        RELIC = 
        {
            GENERIC = "These haven't been used in a while.",
            BROKEN = "Smashed beyond repair.",
        },
        RUINS_RUBBLE = "It looks broken.",
        RUBBLE = "Rocks from an old city.",
		RESEARCHLAB = 
		{	
			GENERIC = "It's like a science lab in here!",
			BURNT = "I think it's broken.",
		},
		RESEARCHLAB2 = 
		{
			GENERIC = "Father used to work on something like that.",
			BURNT = "All our work... gone.",
		},
		RESEARCHLAB3 = 
		{
			GENERIC = "We should be careful around that.",
			BURNT = "The fires care not for magic.",
		},
		RESEARCHLAB4 = 
		{
			GENERIC = "Did I just hear a squeak?",
			BURNT = "Smells like cooking.",
		},
		RESURRECTIONSTATUE = 
		{
			GENERIC = "Who is that supposed to be?",
			BURNT = "It will be of no use to us in that state.",
		},
		RESURRECTIONSTONE = "Some sort of religious monument maybe?",
		ROBIN =
		{
			GENERIC = "Red is my favorite color!",
			HELD = "Held snug in our pockets.",
		},
		ROBIN_WINTER =
		{
			GENERIC = "What pretty white feathers.",
			HELD = "We will name it \"Francis\".",
		},
		ROBOT_PUPPET = "I don't think they're having fun.",
		ROCK = "We'll need to mine it before we can use it.",
		ROCK_CHARCOAL = "Big, crumbly rock.",
		MOOSE_NESTING_GROUND = "For its babies' sleepytime.",
		ROCK_LIGHT =
		{
			GENERIC = "This lava's all dried up.",
			LOW = "It's a little less cozy.",
			NORMAL = "Cozy!",
			OUT = "It looks like it might break.",
		},
		ROCK_ICE = 
		{
			GENERIC = "Ice can be useful.",
			MELTED = "Puddle!",
		},
		ROCK_ICE_MELTED = "Puddle!",
		ICE = "Chilling.",
		ROCKS = "None of these look like they would skip well.",
        ROOK = "Who made these things!?",
		ROPE = "We could tie stuff up with this.",
		ROTTENEGG = "Ew!",
		SANITYROCK =
		{
			ACTIVE = "It's in our way.",
			INACTIVE = "Something about this rock feels off.",
		},
		SAPLING =
		{
			BURNING = "So bright!",
			WITHERED = "I think the heat broke it.",
			GENERIC = "These sure grow slowly.",
			PICKED = "We'll make good use of your twigs!",
		},
		SEEDS = "A small life trapped within. My sympathies.",
		SEEDS_COOKED = "Their growing days are over.",
		SEWING_KIT = "Mum used to handle all of our sewing.",
		SHOVEL = "Maybe we can tunnel our way out?",
		SILK = "It's so smooth!",
		SKELETON = "Hello? Are you alright?",
		SKELETON_PLAYER = "Er, where did the spider parts go?",
		SKULLCHEST = "Who knows what could be hiding in there!",
		SMALLBIRD =
		{
			GENERIC = "Could this be a friend for us?",
			HUNGRY = "I can see its tummy rumble.",
			STARVING = "Poor thing. It looks so hungry!",
		},
		SMALLMEAT = "A couple more and we'll have a meal!",
		SMALLMEAT_DRIED = "It'll keep longer this way.",
		SPEAR = "We should stick things with the pointy part.",
		SPIDER =
		{
			DEAD = "Another lost friend.",
			GENERIC = "Spiders understand us.",
			SLEEPING = "Aww! I think it's having a dream.",
		},
		SPIDERDEN = "Looks cozy in there.",
		SPIDEREGGSACK = "A portable friendship pod!",
		SPIDERGLAND = "This might sooth our cuts.",
		SPIDERHAT = "What have I done?",
		SPIDERQUEEN = "Mommy-Longlegs?",
		SPOILED_FOOD = "Blech!",
		STATUEHARP = "Someone took the head.",
		STATUEMAXWELL = "That's the guy who said he could help us.",
		STINGER = "We should be careful, we could poke an eye out!",
		STRAWHAT = "This might keep the sun out of our eyes.",
		STUFFEDEGGPLANT = "We will stuff ourself with eggyplants!",
		SWEATERVEST = "It itches and fits funny.",
		REFLECTIVEVEST = "Safety first!",
		HAWAIIANSHIRT = "Grandpa's style, definitely.",
		TAFFY = "Candy!",
		TALLBIRD = "Look at those legs!",
		TALLBIRDEGG = "Did I hear a meep?",
		TALLBIRDEGG_COOKED = "Smells great!",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "It's shivering!",
			GENERIC = "I think it's hatching!",
			HOT = "It'll boil if it doesn't cool down soon.",
			LONG = "Looks like an egg.",
			SHORT = "Did that egg just move?",
		},
		TALLBIRDNEST =
		{
			GENERIC = "This could feed us for days!",
			PICKED = "Where is the egg?",
		},
		TEENBIRD =
		{
			GENERIC = "It's getting old so fast!",
			HUNGRY = "It looks hungry!",
			STARVING = "I think it's starving!",
		},
		TELEBASE =
		{
			VALID = "Seems ready to use.",
			GEMS = "It needs something to focus the power.",
		},
		GEMSOCKET = 
		{
			VALID = "Looks good.",
			GEMS = "Looks empty.",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "We could use this to visit new worlds!",
			GENERIC = "I can hear the sounds of another world!",
			LOCKED = "It still won't work!",
			PARTIAL = "I don't think we're done yet!",
		},
		TELEPORTATO_BOX = "The power in this box is unimaginable.",
		TELEPORTATO_CRANK = "A crank that will stand up to punishment.",
		TELEPORTATO_POTATO = "It looks like this goes with something...",
		TELEPORTATO_RING = "I think there are more parts.",
		TELESTAFF = "It makes my brain feel fuzzy.",
		TENT = 
		{
			GENERIC = "It's way past our bedtime!",
			BURNT = "The fire destroyed it.",
		},
		SIESTAHUT = 
		{
			GENERIC = "Is it nap time?",
			BURNT = "We can't take a nap in that!",
		},
		TENTACLE = "We would be mad if something stepped on us, too.",
		TENTACLESPIKE = "We could hit stuff with the pointy bits!",
		TENTACLESPOTS = "Spotty!",
		TENTACLE_PILLAR = "It's huge!",
		TENTACLE_PILLAR_HOLE = "Oooh let's jump in!",
		TENTACLE_PILLAR_ARM = "Aw, it's just a baby!",
		TENTACLE_GARDEN = "It's huge!",
		TOPHAT = "Like father used to wear.",
		TORCH = "This should keep us safe.",
		TRANSISTOR = "We are getting good at crafting!",
		TRAP = "Now we can catch some food!",
		TRAP_TEETH = "This will hurt our enemies.",
		TRAP_TEETH_MAXWELL = "Who would put this here? We could get hurt!",
		TREASURECHEST = 
		{
			GENERIC = "We could keep our toys in it!",
			BURNT = "It won't be very useful to us now.",
		},
		TRINKET_1 = "We could've had some fun if they weren't all melted.",
		TRINKET_2 = "A voiceless instrument.",
		TRINKET_3 = "It won't come undone!",
		TRINKET_4 = "It's watching us.",
		TRINKET_5 = "Yay, a new toy!",
		TRINKET_6 = "Maybe we'll find a use for these.",
		TRINKET_7 = "Another toy!",
		TRINKET_8 = "I miss bath toys.",
		TRINKET_9 = "None of them match!",
		TRINKET_10 = "Just like grandpa wears!",
		TRINKET_11 = "Beep boop!",
		TRINKET_12 = "Feels leathery.",
		TRUNKVEST_SUMMER = "It's so puffy!",
		TRUNKVEST_WINTER = "It'll keep us from catching a cold.",
		TRUNK_COOKED = "Looks filling!",
		TRUNK_SUMMER = "We took his nose!",
		TRUNK_WINTER = "He blue his nose.",
		TUMBLEWEED = "Who knows what that tumbleweed has picked up.",
		TURF_CARPETFLOOR = "Carpets! Just like in our old house.",
		TURF_CHECKERFLOOR = "Fancy.",
		TURF_DIRT = "Some ground that we dug up.",
		TURF_FOREST = "Some ground that we dug up.",
		TURF_GRASS = "Some ground that we dug up.",
		TURF_MARSH = "Some ground that we dug up.",
		TURF_ROAD = "Some ground that we dug up.",
		TURF_ROCKY = "Some ground that we dug up.",
		TURF_SAVANNA = "Some grassy dirt.",
		TURF_DRAGONFLY = "Warm and cozy ground!",
		TURF_BADLANDS = "Some ground that we dug up.",
		TURF_DECIDUOUS = "Some ground that we dug up.",
		TURF_DESERTDIRT = "Some ground that we dug up.",
		TURF_FUNGUS_GREEN = "Some ground that we dug up.",
		TURF_FUNGUS_RED = "Some ground that we dug up.",
		TURF_SANDY = "Some ground that we dug up.",
		TURF_WOODFLOOR = "If we put these on the ground we'll have a floor!",

		STEELWOOL = "Scratchy, like father's beard!",
		SPAT = "Maybe it just needs a cuddle!",
		BISHOP_CHARGE_HIT = "Owie!",
		TURKEYDINNER = "Like mother used to make before this happened!",
		TWIGS = "Wish we had a friend to play stick swords with.",
		UMBRELLA = "This should keep some of the rain off of us.",
		GRASS_UMBRELLA = "It won't keep us from playing in puddles!",
		PALMLEAF_UMBRELLA = "It won't keep us from playing in puddles!",
		UNIMPLEMENTED = "What a crummy item.",
		WAFFLES = "Yummy!",
		WALL_HAY = 
		{	
			GENERIC = "This will keep all sorts of things out!",
			BURNT = "It didn't keep the fire out.",
		},
		WALL_HAY_ITEM = "Some grass tied together.",
		WALL_STONE = "We're base-building masters!",
		WALL_STONE_ITEM = "These should come in handy.",
		WALL_RUINS = "Looks sturdy.",
		WALL_RUINS_ITEM = "Wow, these are really heavy.",
		WALL_WOOD = 
		{
			GENERIC = "Like a pillow fort, but wood!",
			BURNT = "Turns out wood burns really well.",
		},
		WALL_WOOD_ITEM = "They won't keep us safe if we keep holding them.",
		WALL_MOONROCK = "We feel safe behind this wall... it makes us sleepy...",
		WALL_MOONROCK_ITEM = "We thought \"moon\" meant something totally different!",
		WALRUS = "I don't think he wants to be friends with us.",
		WALRUSHAT = "Reminds me of grandpa.",
		WALRUS_CAMP =
		{
			EMPTY = "I think someone was here.",
			GENERIC = "Maybe they'll invite us in?",
		},
		WALRUS_TUSK = "Maybe we can use it for arts and crafts.",
		WARDROBE = 
		{
			GENERIC = "We like to hide in it.",
            BURNING = "Fire fire fire!",
			BURNT = "We can't hide in there any more.",
		},
		WARG = "I don't think that puppy is very happy.",
		WASPHIVE = "Sounds like anger!",
		WATERMELON = "Looks tasty!",
		WATERMELON_COOKED = "We can cook anything!",
		BANANAPOP = "Yaaay! Popsicle, popsicle!",
		BISQUE = "We lift our pinkies when we eat it.",
		CEVICHE = "Yucky!",
		SEAFOODGUMBO = "We could eat it forever!",
		SURFNTURF = "Eww, healthy!",
		SHARKFINSOUP = "Yum, yum, soup!",
		LOBSTERDINNER = "We have to eat it with our eyes closed. Too many legs!",
		LOBSTERBISQUE = "We want to pour it all over our tongues!",
		JELLYOPOP = "Yummy!",
		WATERMELONHAT = "This is the best idea we have ever had.",
		WETGOOP = "Experimenting is fun!",
		WINTERHAT = "Mum always said I should take a cap with me.",
		WHIP = "Oooh, it makes so much noise!",
		WINTEROMETER = 
		{
			GENERIC = "How hot is it, Mr. Thermal Measurer?",
			BURNT = "Another dead friend.",
		},
		WORMHOLE =
		{
			GENERIC = "I think that thing is alive.",
			OPEN = "I've been in worse.",
		},
		WORMHOLE_LIMITED = "Gross, that one looks sick!",
		ACCOMPLISHMENT_SHRINE = "It gives me a goal in life.",        
		LIVINGTREE = "Hello, Mr. Tree!",
		ICESTAFF = "It makes me feel funny.",



----------------------------capy---------------------------------------

		AERODYNAMICHAT = "We feel light on our feet.",
		ANTIVENOM = "This is medicine?",
		ARMOR_LIFEJACKET = "It pays to be safe.",
		ARMOR_SNAKESKIN = "Rain will bead off this reptilian coat.",
		ARMOR_WINDBREAKER = "Wind can't hold us back!",
		ARMORLIMESTONE = "Our back hurts...",
		ARMOROBSIDIAN = "Our enemies will feel the heat!",
		ARMORSEASHELL = "We feel like a knight in not-so-shiny armor.",
		ARMOUREDBOAT = "It provides peace of mind at sea.",
		BABYOX = "Hey lil fella!",
		BALLPHIN = "Playful rubber blobs. We'll watch from afar.",
		BALLPHINPOD = "Why don't they like us!",
		BAMBOO = "Such a useful stick-type thing.",
		BAMBOOTREE = "Such a small but helpful tree.",
		BERMUDATRIANGLE = "How unsettling!",
		BERRYBUSH2_SNAKE = "Ripe for the pickin'.",
		BERRYBUSH_SNAKE = "Ripe for the pickin'.",
		BIOLUMINESCENCE = "Wooow! Pretty water lights!",
		BLOWDART_POISON = "A sneaky weapon...",
		BOAT_LANTERN = "Seeing where we're going is sure handy!",
		BOATCANNON = "With this we can make a warship!",
		BOATREPAIRKIT = "Never leave home without one.",
		BOTTLELANTERN = "Hey in there, thanks for the light!",
		BURIEDTREASURE = "Treasure, treasure, treasure!",
		BUSH_VINE = "What a crazy looking plant.",
		CAPTAINHAT = "Just like a real boatguy!",
		CARGOBOAT = "Ah, we can stretch all our legs...",
		CHIMINEA = "Our fires can stay safe from the wind's clutches.",
		CIRCLINGSEAGULL = "Don't poop on us!",
		CLOTHSAIL = "Now we can harness the wind!",
		COCONADE = "We should throw this very much far away from ourselves.",
		COCONUT = 
		{
		    GENERIC = "Food! From a tree!",
		    PLANTED = "Aw. It's so little.",
		},
		COFFEE = "Bitter.",
		COFFEEBEANS = "These smell very... adult.",
		
		COFFEEBUSH = "These don't look tasty.",
		CORAL = "Pretty colors.",
		CORALREEF = "A coral party!",
		CRABHOLE = "The sixlegger lives underground.",
		CUTLASS = "There's something fishy about this sword.",
		DEAD_SWORDFISH = "Should we eat it or use it?",
		DEPLETED_BAMBOOTREE = "Come back, bamboos.",
		DEPLETED_BUSH_VINE = "Will the vines come back?",
		DOYDOY = "Nothing behind the eyes...",
		DOYDOYBABY = "Aww, it's a lil dummy.",
		DOYDOYEGG = "Where dumb life begins.",
		
		DOYDOYFEATHER = "Hmmm, it dropped this.",
		DOYDOYNEST = "The lil dummies come from these.",
		DUBLOON = "Shiny coins!",
		DUG_BAMBOOTREE = "We're a gardening expert!",
		DUG_BUSH_VINE = "Where should we put this?",
		DUG_COFFEEBUSH = "With a little love it could grow again.",
		EARRING = "This belonged to a pirate!",
		FABRIC = "We could make a new blankie. Or not.",
		FEATHERSAIL = "A feathery sail makes for swift travel.",
		FIRERAIN = "It's raining fire!",
		FIRERAINSHADOW = "Duck and cover!",
		FISHINHOLE = "Fishies for the taking!",
		FROG_POISON = "If we get licked by those we'll get sick.",
		GASHAT = "We are protected from sick smells.",
		GOLDENMACHETE = "What a beautiful blade!",
		ICEMAKER = "Ice is useful in this heat.",
		IRONWIND = "Who needs a sail!",
		TREEGUARD = "Mean tree!",
		JELLYFISH = "That blob is alive!",
		JELLYFISH_COOKED = "We hoped it would be more... solid.",
		JELLYFISH_DEAD = "It's not jelly or fish. It's also not alive.",
		JELLYJERKY = "We'll try anything once.",
		JELLYFISH_PLANTED = "The sea is full of such weird junk.",
		JUNGLETREE =
	    {
			BURNING = "What a senseless waste of firewood.",
			BURNT = "That's one less place for snakes to slither from.",
			CHOPPED = "Bye-bye, big tree.",
			GENERIC = "Oh neat, a big tree.",
		},
		JUNGLETREESEED =
        {
            GENERIC = "Hard to believe such a big tree comes from this!",
            PLANTED = "Grow, grow, grow!",
        },
		LAVAPOOL = "Blazing hot!",
		LIMESTONE = "So bumpy!",
		LIMPETROCK =
		{
			GENERIC = "This rock is covered in food things!",
			PICKED = "Come back, yumyums.",
		},
		LIMPETS = "Do we have to eat these?",
		LIMPETS_COOKED = "Tastes like ocean.",
		
		LOBSTER = "This meat wears armor!",
		LOBSTERHOLE = "That is where the armored meat goes during the day.",
		LOGRAFT = "This does not look swift.",
		MACHETE = "Hyah! Hyah!",
		MESSAGEBOTTLE = "Maybe there's a comic book in here!",
		MESSAGEBOTTLEEMPTY = "We wish it was filled with soda pop.",
		MOSQUITO_POISON = "These ones leave a gift when they bite.",
		
		MUSSEL = "Maybe one day I'll have big mussels.",
		MUSSEL_STICK = "The mussels do pull-ups on this.",
		OBSIDIAN = "Volcano rocks rock!",
		OBSIDIAN_WORKBENCH = "We forge the fire items here!",
		OBSIDIANAXE = "We'll be unstoppable!",
		OBSIDIANCOCONADE = "The weather will be bomb-y!",
		OBSIDIANFIREPIT =
		{
			EMBERS = "We should put something on the fire before it goes out.",
			GENERIC = "We made the fire stones into a fire home!",
			HIGH = "That fire is huge!",
			LOW = "The fire's getting a touch low.",
			NORMAL = "The toastiest of fires.",
			OUT = "Well, that's done. But not forever!",
		},
		OBSIDIANMACHETE = "It cooks with each cut!",
		SPEAR_OBSIDIAN = "One jab makes'em burn up!",
		OBSIDIANSPEARGUN = "Like shooting fireworks!",
		OX = "Cool horns.",
		PACKIM = "Hello, large-mouthed friend!",
		PACKIM_FISHBONE = "We wonder what this is?",
		PALMLEAF = "Big leaf.",
		PALMTREE = 
		{
			BURNING = "What a senseless waste of firewood.",
			BURNT = "It's dropped its last coconut.",
			CHOPPED = "Goodbye, Tree of Palms.",
			GENERIC = "This tree has presents!",
		},
		PARROT = "Aren't you a chatty fellow!",
		PEACOCK = "Such pretty feathers!",
		PIRATEHAT = "Aaargh, we feel so salty!",
		PIRATIHATITATOR = "With this pirate hat we'll harness dark, cursed stuff.",
		POISONHOLE = "Yikes! The ground is farting!",
		RAFT = "Do we think this is sturdy enough?",
		ROWBOAT = "How's that old song go?",
		SAIL = "This'll give us a push!",
		SAND = "It's nice to feel it beneath our many feet.",
		SAND_CASTLE = "Look what we built!",
		SANDBAG = "Sand pillows!",
		SANDHILL = "Wish we had a bucket and a shovel.",
		SEAGULL = "We want to throw something at you.",
		SEAGULL_WATER = "It must be nice to fly... and eat garbage.",
		SEASACK = "Eww, it's wet and squishy.",
		SEASHELL = "Sea litter.",
		SEATRAP = "Things swim in. Dinner comes out.",
		SEAWEED = "The salad of the sea.",
		
		SEAWEED_PLANTED = "We should weed that out, maybe.",
		SHARK_FIN = "Do we touch it?",
		SHARX = "Sh...Sh...SHARK!!!!!",
		SLOTMACHINE = "I think I'm too young for this.",
		SNAKE = "We should keep our distance from those ones.",
		SNAKE_FIRE = "Aaaah, fire-breathing volcano thingies!",
		SNAKE_POISON = "These ones have a sick bite!",
		SNAKESKIN = "The skin of a snake!",
		SNAKESKINHAT = "Does snakeskin make us look tough?",
		SOLOFISH = "Say, there's a lot of meat on you!",
		SPEAR_POISON = "One jab'll do ya.",
		SPEARGUN = "We shoot it!",
		SPEARGUN_POISON = "I better point this away from myself.",
		STUNGRAY = "Aren't you cute! Hey, what's that smell...",
		SUPERTELESCOPE = "Helps us see better than with all our eyes, combined!",
		SWORDFISH = "We like your sword face, fish!",
		TELESCOPE = "I can see so far!",
		TIGERSHARK = "Out of the water!",
		TIGERSHARKSHADOW = "We're scared...",
		TORNADO = "We don't like this...",
		TOUCAN = "What a colorful beak you have!",
		TRAWLNET = "I wonder what we'll drag up.",
		TRAWLNETDROPPED = "What goodies are inside!",
		TRIDENT = "We feel like a god with this in our hands!",
		TRINKET_13 = "Is it our birthday!",
		TRINKET_14 = "Reminds me of Teddy.",
		TRINKET_15 = "I wonder if it's in tune.",
		TRINKET_16 = "Where's the automobile?",
		TRINKET_17 = "Too big for us.",
		TRINKET_18 = "This is a lot older than we are.",
		TRINKET_19 = "What's a brain cloud?",
		TURBINE_BLADES = "Weird.",
		TURF_BEACH = "Some ground we dug up.",
		TURF_JUNGLE = "Some ground we dug up.",
		TWISTER = "Nature hates us!",
		VENOMGLAND = "The key to feeling better if we get sick.",
		VINE = "This stuff is wild.",
		VOLCANO = "Is that a... oh my...",
		VOLCANO_ALTAR = "We can feed the hungry volcano! But what does it like to eat?",
		VOLCANO_ALTAR_BROKEN = "That is a burning shame.",
		VOLCANO_EXIT = "We can escape the heat here.",
		VOLCANOSTAFF = "The volcano does our bidding!",
		WALL_LIMESTONE = "Is this wall made of limes?",
		WALL_LIMESTONE_ITEM = "Why is it called limestone? It's not even green.",
		WHALE_BLUE = "Buck up, big fella!",
		WHALE_CARCASS_BLUE = "Its suffering is over now.",
		WHALE_CARCASS_WHITE = "This is a very big dead thing.",
		WHALE_WHITE = "His eyes burn with hatred!",
	
		ARMORCACTUS = "Weaponized hugs!",
		BAMBOOTREE =
		{
			BURNT = "It's bamburnt.",
			CHOPPED = "It has a bamboo-boo.",
			GENERIC = "Cute little bamboo.",
		},
		BIGFISHINGROD = "Perhaps we'll hook something good.",
		BLOWDART_FLUP = "I can't imagine this would hurt very much.",
		BLUBBER = "Fat and happy.",
		BLUBBERSUIT = "A boy inside a spider inside a whale.",
		BOAT_TORCH = "It will light my way!",
		BRAINJELLYHAT = "It feels smart and squishy on our head.",
		BUOY = "I'm a little buoy too!",
		BUSH_VINE =
		{
			BURNT = "All burned up.",
			CHOPPED = "We took it all.",
			GENERIC = "It's a nice bush.",
		},
		COCONADE =
		{
			BURNING = "Fire in the hole!",
			GENERIC = "This will be so fun!",
		},
		COCONUT_COOKED = "Just needs a tiny umbrella.",
		COCONUT_HALVED = "Now there's one for each of us.",
		COFFEEBEANS_COOKED = "These make me feel funny.",
		COFFEEBOT = "The machine that makes the hyper juice!",
		COFFEEBUSH =
		{
			BARREN = "No more mean beans.",
			GENERIC = "It's covered in the happy beans.",
			PICKED = "We took them all.",
			WITHERED = "The bean bush looks sad.",
		},
		CORAL_BRAIN = "Yummy headmeats!",
		CORAL_BRAIN_ROCK = "I want to poke it, but I'm afraid our hand will get stuck.",
		CRAB =
		{
			CRAB = "One, two... s-six legs. Aw, we thought maybe you were a friend.",
			HIDDEN = "Come out, come out, wherever you are!",
		},
		CRATE = "Wow, a crate.",
		DEPLETED_GRASS_WATER = "All gone.",
		DOUBLE_UMBRELLAHAT = "One for each of us!",
		DOYDOYEGG_COOKED = "To make an omelette you have to endanger a few species.",
		DOYDOYEGG_CRACKED = "It cracked under the pressure.",
		DRAGOON = "It's a trailblazer!",
		DRAGOONDEN = "Maybe we'll leave that alone.",
		DRAGOONEGG = "Will it hatch soon?",
		DRAGOONHEART = "It's strangely hot.",
		DRAGOONSPIT = "Keep your bodily fluids to yourself!",
		DUG_ELEPHANTCACTUS = "Now I can use it.",
		ELEPHANTCACTUS = "It's withered, but still hurts to touch.",
		ELEPHANTCACTUS_ACTIVE = "It's made of hurt!",
		ELEPHANTCACTUS_STUMP = "Are you sleeping in there?",
		FISH_RAW = "It would probably be better cooked.",
		FISH_RAW_SMALL = "It's a little fishy.",
		FISH_RAW_SMALL_COOKED = "Boney.",
		FLAMEGEYSER = "The ground is angry.",
		FLOTSAM = "There must be a way to grab it.",
		FLUP = "Why is it so aggressive!",
		FRESHFRUITCREPES = "Cripes! We can't wait for these crepes!",
		GRASS_WATER = "It's going for a swim.",
		HAIL_ICE = "Brrr!",
		HOME = "Hellooo? We're here!",
		HOUNDFIRE = "It's gonna burn away all our spider hair!",
		ICEMAKER =
		{
			HIGH = "It's running pretty good!",
			LOW = "I think it needs our help.",
			NORMAL = "Looks alright to us.",
			OUT = "Dead.",
			VERYLOW = "This thing's on its last legs. Maybe it can borrow some of ours?",
		},
		JUNGLETREE =
		{
			BURNING = "Too hot!",
			BURNT = "It's not green anymore.",
			CHOPPED = "We cut it up!",
			GENERIC = "Not a bad tree.",
		},
		KNIGHTBOAT = "It's mean!",
		KRAKEN = "Run away!",
		KRAKENCHEST = "Let's open it!",
		KRAKEN_TENTACLE = "Leave me alone!",
		LIMPETROCK =
		{
			GENERIC = "It's covered in limpets.",
			PICKED = "All gone.",
		},
		LIVINGJUNGLETREE = "Nothing out of the ordinary here.",
		LOBSTER_DEAD = "It's not moving anymore.",
		LOBSTER_DEAD_COOKED = "Yum, yum, yum!",
		LUGGAGECHEST = "Better finish packing.",
		MAGIC_SEAL = "Woah, magic-y!",
		MAGMAROCK = "It's a bunch of stony stones.",
		MAGMAROCK_FULL = "It's a bunch of stony stones.",
		MAGMAROCK_GOLD = "It's a bunch of shiny stones.",
		MAGMAROCK_GOLD_FULL = "It's a bunch of shiny stones.",
		MANGROVETREE = "It would be a cool place for a treehouse.",
		MANGROVETREE_BURNT = "So no treehouse, then.",
		MARSH_PLANT_TROPICAL = "It looks like a weed.",
		MAXWELLHEAD = "Imagine the trouble he has buying hats!",
		MERMFISHER = "Half-human, half-animal. Too weird.",
		MERMHOUSE_FISHER = "Can I come in?",
		MONKEYBALL = "We've made a friend!",
		MONSTERTARTARE = "Looks amazing!",
		MOSQUITOSACK_YELLOW = "The backside of a mosquito.",
		MUSSELBOUILLABAISE = "About as appetizing as they get.",
		MUSSEL_COOKED = "Still kind of gross.",
		MUSSEL_FARM =
		{
			GENERIC = "Yuck.",
			STICKPLANTED = "Is it done yet?",
		},
		MYSTERYMEAT = "It's a big goopy mess.",
		NEEDLESPEAR = "This could really hurt someone.",
		OCTOPUSCHEST = "Let's look inside!",
		OCTOPUSKING = "It looks friendly.",
		OXHAT = "How do we look?",
		OX_FLUTE = "It's just begging to be played!",
		OX_HORN = "We could put these on something to make it sharp.",
		PALMLEAF_HUT = "Almost as good as a spider nest.",
		PANDORASCHEST = "Stylish storage.",
		PARROT_PIRATE = "As far as birds go, this one's very fashionable.",
		PEG_LEG = "This be our smackin' leg.",
		PIGTENT = "Little pig, little pig, let me in!",
		PIKE_SKULL = "We don't like that!",
		PIRATEGHOST = "As if normal pirates weren't scary enough!",
		PIRATEPACK = "A booty bundle.",
		PIRATIHATITATOR =
		{
			BURNT = "All burned up!",
			GENERIC = "This is definitely a thing. A magic pirate thing.",
		},
		PORTAL_SHIPWRECKED = "No one's going through this.",
		PRIMEAPE = "My best frenemy.",
		PRIMEAPEBARREL = "Too many monkeys.",
		RAWLING = "We like the wild ball man.",
		REDBARREL = "Boom-material!",
		ROCK_OBSIDIAN = "This rock is pretty tough.",
		SAIL_STICK = "It's a stick!",
		SANDBAGSMALL = "Keeps the wet stuff out.",
		SANDBAGSMALL_ITEM = "Remember to lift with your legs... all eight of them!",
		SANDBAG = "Remember to lift with your legs... all eight of them!",
		SANDBAG_ITEM = "Remember to lift with your legs... all eight of them!",
		SAND_CASTLE =
		{
			GENERIC = "That was fun!",
			SAND = "We wish we could live inside.",
		},
		SEASHELL_BEACHED = "We can hear the ocean with these. We can also hear it without them.",
		SEAWEED_COOKED = "Very salty.",
		SEAWEED_DRIED = "It sticks to the roof of our mouth!",
		SHADOWSKITTISH_WATER = "Eep!",
		SHARKITTEN = "Here kitty, kitty!",
		SHARKITTENSPAWNER =
		{
			GENERIC = "Maybe some kitties will come out and play?",
			INACTIVE = "Bland sand.",
		},
		SHARK_GILLS = "A big fish's breathing bits.",
		SHARK_TEETHHAT = "A smile to wear on our forehead!",
		SHIPWRECKED_ENTRANCE = "Let the adventure begin!",
		SHIPWRECKED_EXIT = "Bye-bye!",
		SNAKEDEN =
		{
			BURNT = "All burned up.",
			CHOPPED = "We took it all.",
			GENERIC = "It's a nice bush.",
		},
		SNAKEOIL = "It really works!",
		SNAKESKINSAIL = "With our sheet of gross skins, we're ready for adventure.",
		SPEAR_LAUNCHER = "Why would anyone launch a spear? Someone might get hurt.",
		SPOILED_FISH = "It's no good to anyone now.",
		SUNKBOAT = "So close, so far away.",
		SUNKEN_BOAT =
		{
			ABANDONED = "Maybe it's time to abandon ship, birdie.",
			GENERIC = "It's not much to look at.",
		},
		SUNKEN_BOAT_BURNT = "Hard to believe this thing was ever seaworthy.",
		SUNKEN_BOAT_TRINKET_1 = "It's very shiny.",
		SUNKEN_BOAT_TRINKET_2 = "Yaaaay!",
		SUNKEN_BOAT_TRINKET_3 = "We probably can't light that.",
		SUNKEN_BOAT_TRINKET_4 = "Is this a toy?",
		SUNKEN_BOAT_TRINKET_5 = "We'll boil this if we get desperate.",
		SWEETPOTATOSOUFFLE = "It's so dainty.",
		SWEET_POTATO = "You say \"po-tat-o\", I say \"dinner\"!",
		SWEET_POTATO_COOKED = "Orange foodmush.",
		SWEET_POTATO_PLANTED = "We want to eat that!",
		SWEET_POTATO_SEEDS = "We could plant these to grow more sweet potatoes.",
		SWIMMINGHORROR = "AHH!",
		TELEPORTATO_SW_BASE = "Can we eat off this?",
		TELEPORTATO_SW_BOX = "Someone's got a screw loose.",
		TELEPORTATO_SW_CRANK = "It's weird!",
		TELEPORTATO_SW_POTATO = "Aw, it's not even edible.",
		TELEPORTATO_SW_RING = "Maybe it's for hulahooping?",
		THATCHPACK = "Helps carry goodies!",
		TIDALPOOL = "It's like a fishbowl... without the bowl!",
		TIDAL_PLANT = "A little shrub.",
		TIGEREYE = "What're you looking at?",
		TRAWLNETDROPPED =
		{
			GENERIC = "What a tangled web we weave!",
			SOON = "It's going down!",
			SOONISH = "It's going down. Slowly.",
		},
		TREASURECHEST_TRAP = "Nice and easy.",
		TREECLUMP = "It's in our way!",
		TRINKET_20 = "It's very shiny.",
		TRINKET_21 = "Yaaaay!",
		TRINKET_22 = "What was in the bottle?",
		TRINKET_23 = "Where did the words go?",
		TROPICAL_FISH = "It's pretty!",
		TUNACAN = "We left our can opener at home.",
		TURF_SANDY = "Some ground that we dug up.",
		TURF_ASH = "Some ground that we dug up.",
		TURF_BADLANDS = "Some ground that we dug up.",
		TURF_DECIDUOUS = "Some ground that we dug up.",
		TURF_DESERTDIRT = "Some ground that we dug up.",
		TURF_FUNGUS_GREEN = "Some ground that we dug up.",
		TURF_FUNGUS_RED = "Some ground that we dug up.",
		TURF_MAGMAFIELD = "Some ground that we dug up.",
		TURF_MEADOW = "Some ground that we dug up.",
		TURF_SNAKESKINFLOOR = "Some ground that we dug up.",
		TURF_SWAMP = "Some ground that we dug up.",
		TURF_TIDALMARSH = "Some ground that we dug up.",
		TURF_VOLCANO = "Some ground that we dug up.",
		TWISTER_SEAL = "Its cheeks look so pinchable!",
		VOLCANO_ALTAR =
		{
			GENERIC = "We can't use it right now.",
			OPEN = "The altar is ready for presents!",
		},
		VOLCANO_ALTAR_TOWER = "It's big!",
		VOLCANO_SHRUB = "I think it's speaking to me.",
		WALLYINTRO_DEBRIS = "Where's the rest of the ship?",
		WATERMELON_SEEDS = "If we eat these will they grow inside us?",
		WATERYGRAVE = "Blub blub.",
		WHALE_BUBBLES = "Which end are those coming from?",
		WHALE_TRACK = "Follow that whale!",
		WILBUR_CROWN = "We want to wear it.",
		WILBUR_UNLOCK = "He will make a nice friend.",
		WILDBORE = "I don't think he's friendly.",
		WILDBOREHEAD = "He doesn't look too happy.",
		WILDBOREHOUSE = "Muffled oinking is coming from inside.",
		WIND_CONCH = "A nice ocean breeze waits inside this shell. Well, maybe not so nice.",
		WOODLEGSBOAT = "Ready for the open seas!",
		WOODLEGSHAT = "Yarr! Haha.",
		WOODLEGSSAIL = "One fancy piece of cloth.",
		WOODLEGS_CAGE = "He needs our help!",
		WOODLEGS_KEY1 = "What will it open?",
		WOODLEGS_KEY2 = "This key's probably worth more than what it unlocks.",
		WOODLEGS_KEY3 = "A thing for opening other things.",
		WRECK = "A reminder to respect the sea.",
		CALIFORNIAROLL = "Hmm, something smells fishy about this!",
	},
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "What if it hatches in our belly?",
	},
}