return {
	ACTIONFAIL =
	{
		REPAIRBOAT =
		{
			GENERIC = "It doesn't need any work.",
		},
		SHAVE =
		{
			AWAKEBEEFALO = "Woah, slow down. She's awake.",
			GENERIC = "Nah.",
			NOBITS = "My work here is done.",
		},
		STORE =
		{
			GENERIC = "It's holding all it can.",
			NOTALLOWED = "I could jam it in there I guess. Might get smushed.",
		},
		RUMMAGE =
		{	
			GENERIC = "Haha, nah.",	
		},
        COOK =
        {
            GENERIC = "Ughh, no.",
            TOOFAR = "I just need to walk over there to use it... Ughhh, I'm going to starve!",
        },
        GIVE =
        {
            DEAD = "Poor guy's dead.",
            SLEEPING = "Aw. Let it sleep.",
            BUSY = "It's doing something else right now.",
        },
        WRITE =
        {
            GENERIC = "Nah. Don't wanna.",
        },
        CHANGEIN =
        {
            GENERIC = "What's wrong with what I'm wearing?",
            BURNING = "Yeah, I think I'll pass.",
        },
		TEACH =
        {
            KNOWN = "I already know that, y'know?",
            CANTLEARN = "Looks boring.",
        },
	},
	ACTIONFAIL_GENERIC = "Well that didn't work.",
	ANNOUNCE_MAGIC_FAIL = "It won't work. Me either! Haha.",
	ANNOUNCE_ACCOMPLISHMENT = "Busywork.",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "Well, that's finished.",
	ANNOUNCE_ADVENTUREFAIL = "All that work for nothing.",
	ANNOUNCE_BEES = "Relax your thorax!",
	ANNOUNCE_BOAT_DAMAGED = "My floater's been dinged!",
	ANNOUNCE_BOAT_SINKING = "This thing is letting on water.",
	ANNOUNCE_BOAT_SINKING_IMMINENT = "I won't be floating much longer...",
	ANNOUNCE_BOOMERANG = "Ow! Stop hitting yourself, Walani!",
	ANNOUNCE_BURNT = "OUCH! That's burnin' my digits!",
	ANNOUNCE_CANFIX = "\nI should probably repair that. Maybe later.", 
	ANNOUNCE_CHARLIE = "Who's there?! Leave me alone!",
	ANNOUNCE_CHARLIE_ATTACK = "ACHK! I SAID GO AWAY!",
	ANNOUNCE_COLD = "Way too cold!",
	ANNOUNCE_CRAB_ESCAPE = "I thought it was right here...",
	ANNOUNCE_CRAFTING_FAIL = "Haha. I really messed that up.",
	ANNOUNCE_DEERCLOPS = "Something big is headed this way!",
	ANNOUNCE_DUSK = "Darkness will be here soon!",
	ANNOUNCE_EAT =
	{
		GENERIC = "Not too bad. Heh heh.",
		INVALID = "I'll take a pass on that one.",
		PAINFUL = "Ish my tongue shupposed t'shwell up like that?",
		SPOILED = "Gnarly! I think I'm gonna hurl...",
		STALE = "I mean, I guess that was food.",
		YUCKY = "Haha, wow, no.",
	},
	ANNOUNCE_ENTER_DARK = "H-holy geez, it's dark! HELP! Help me!",
	ANNOUNCE_ENTER_LIGHT = "Sweet crispy light! I missed you!",
	ANNOUNCE_FREEDOM = "Hooray, I'm free! Time for a nap?",
	ANNOUNCE_HIGHRESEARCH = "Woah, I think that, like, expanded my mind!",
	ANNOUNCE_HOT = "This heat is unbearable.",
	ANNOUNCE_HOUNDS = "Junkyard dogs incomin'.",
	ANNOUNCE_HUNGRY = "I'm crashing like a sick wave! Gimme food!",
	ANNOUNCE_HUNT_BEAST_NEARBY = "I hear rustling nearby.",
	ANNOUNCE_HUNT_LOST_TRAIL = "Ugh, it got away.",
	ANNOUNCE_HUNT_LOST_TRAIL_SPRING = "The water washed the tracks away. Oh well.",
	ANNOUNCE_INSUFFICIENTFERTILIZER = "I think it wants something. Hey! What do you want?",
	ANNOUNCE_INV_FULL = "What am I, a pack animal?",
	ANNOUNCE_KNOCKEDOUT = "Woah. What happened?",
	ANNOUNCE_LIGHTNING_DAMAGE_AVOIDED = "Not today, nature!",
	ANNOUNCE_LOWRESEARCH = "Radical! Knowledge!",
	ANNOUNCE_MAPWRAP_LOSECONTROL = "Uhhhm. Where am I?",
	ANNOUNCE_MAPWRAP_RETURN = "The fog is clearing!",
	ANNOUNCE_MAPWRAP_WARN = "Looks pretty foggy over there.",
	ANNOUNCE_MESSAGEBOTTLE =
	{
		"Reading's boring anyway.",
	},
	ANNOUNCE_MORETREASURE = "My luck continues!",
	ANNOUNCE_MOSQUITOS = "Rude! Make your own blood!",
	ANNOUNCE_NODANGERSIESTA = "Sleeping right now seems kinda dangerous.",
	ANNOUNCE_NODANGERSLEEP = "Sleeping right now seems kinda dangerous.",
	ANNOUNCE_NODAYSLEEP = "You know I'm always down for a nap but... not right now.",
	ANNOUNCE_NODAYSLEEP_CAVE = "Are you nuts? I'm not sleepin' in a cave!",
	ANNOUNCE_NOHUNGERSIESTA = "Foooooooooooooood...",
	ANNOUNCE_NOHUNGERSLEEP = "Fooooooooooooooood...",
	ANNOUNCE_NONIGHTSIESTA = "That would be improper napping form.",
	ANNOUNCE_NONIGHTSIESTA_CAVE = "It's a bit too cavey around here for a siesta.",
	ANNOUNCE_NOSLEEPONFIRE = "Uhh... That's on fire right now.",
	ANNOUNCE_NO_TRAP = "Worst trap ever.",
	ANNOUNCE_OTHER_WORLD_TREASURE = "I don't think this is anywhere around here.",
	ANNOUNCE_OTHER_WORLD_PLANT = "Can't do that, the poor thing wouldn't grow here.",
	ANNOUNCE_PECKED = "Hey! Stop that!",
	ANNOUNCE_QUAKE = "The ground is shaking.",
	ANNOUNCE_RESEARCH = "I feel smarter.",
	ANNOUNCE_SHARX = "Something smells sharky.",
	ANNOUNCE_SHELTER = "Ah. I'm in my element when I'm out of the elements.",
	ANNOUNCE_THORNS = "Ow! It bit me!",
	ANNOUNCE_TOOL_SLIP = "You're not making this any more fun!",
	ANNOUNCE_TORCH_OUT = "WHERE DID MY LIGHT GO?!",
	ANNOUNCE_TRAP_WENT_OFF = "My bad.",
	ANNOUNCE_TRAWL_FULL = "My work has paid off!",
	ANNOUNCE_TREASURE = "Woohoo! Treasure!",
	ANNOUNCE_UNIMPLEMENTED = "Looks kinda half-baked.",
	ANNOUNCE_VOLCANO_ERUPT = "The volcano speaks!",
	ANNOUNCE_WAVE_BOOST = "Surf's up!",
	ANNOUNCE_WHALE_HUNT_BEAST_NEARBY = "Whale, whale, whale!",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL = "It must've dove deeper.",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL_SPRING = "The waters are way too rough.",
	ANNOUNCE_WORMHOLE = "...Where am I?",
	ANNOUNCE_DAMP = "A little water never hurt no one.",
	ANNOUNCE_WET = "I'll need to towel off soon.",
	ANNOUNCE_WETTER = "My clothes are all soggy... Haha.",
	ANNOUNCE_SOAKED = "I am thoroughly soaked.",
	BATTLECRY =
	{
		GENERIC = "I'M A FORCE TO BE RECKONED WITH!",
		PIG = "DESTRUCTION!",
		PREY = "YOU WILL NOT WIN!",
		SPIDER = "YOU WILL REGRET THIS DAY!",
		SPIDER_WARRIOR = "I WILL END YOU!",
	},
	COMBAT_QUIT =
	{
		GENERIC = "Oh man, you shoulda seen the look on your face.",
		PIG = "Haha, gotcha.",
		PREY = "Nah, I was just messin' with you.",
		SPIDER = "Pssh, nah, we're good.",
		SPIDER_WARRIOR = "Haha, nah. We're cool.",
	},
	DESCRIBE =
	{
		BERRYBUSH =
		{
			GENERIC = "How lush!",
			PICKED = "Thanks for the snack, dude.",
			WITHERED = "I can nurse it back to health.",
		},
		INVENTORYGRAVE = "Surf that big wave in the sky, dude.",
		INVENTORYMOUND = "Surf that big wave in the sky, dude.",
		ACCOMPLISHMENT_SHRINE = "Well, that looks like a lot of busywork.",
		ACORN =
		{
			GENERIC = "Come on out, nature!",
			PLANTED = "Grow strong little dude.",
		},
		ACORN_COOKED = "Sorry, tree baby.",
		ADVENTURE_PORTAL = "Why would I want to go in there?",
		AERODYNAMICHAT = "Aerodynamic. Choka.",
		AMULET = "Looks great, feels great.", --Red
		ANCIENT_ALTAR = "This is giving me major jeepers.",
		ANCIENT_ALTAR_BROKEN = "Maybe it still works?",
		ANCIENT_STATUE = "How depressing.",
		ANIMAL_TRACK = "Friends are near!",
		ANTIVENOM = "This'll make the sickness go away.",
		ARMORDRAGONFLY = "This armor is so hot right now.",
		ARMORGRASS = "Doesn't seem all that sturdy.",
		ARMORLIMESTONE = "Seems maybe, like, *too* sturdy.",
		ARMORMARBLE = "That's just overkill.",
		ARMOROBSIDIAN = "It kinda pokes my butt.",
		ARMORRUINS = "It's so fancy!",
		ARMORSEASHELL = "The ocean will protect me!",
		ARMORSLURPER = "So efficient!",
		ARMORSNURTLESHELL = "Protection from nature, by nature.",
		ARMORWOOD = "I hope the attacker doesn't have an axe.",
		ARMOR_LIFEJACKET = "In case the waves get all gnar'.",
		ARMOR_SANITY = "Eyuk! It makes my skin crawl.",
		ARMOR_SNAKESKIN = "I guess snakes aren't so bad.",
		ARMOR_WINDBREAKER = "The wind slips right around me!",
		ARMOUREDBOAT = "What a clunky looking board.",
		ASH =
		{
			GENERIC = "I must've missed the party.",
			REMAINS_EYE_BONE = "Huh. I guess it didn't like traveling?",
			REMAINS_GLOMMERFLOWER = "Huh. I guess it didn't like traveling?",
			REMAINS_THINGIE = "Huh. I guess it didn't like traveling?",
		},
		AXE = "I could cut trees with this... But I'd rather not.",
		BABYBEEFALO = "Growing up is a trap... don't do it!",
		BABYOX = "Stay young forever!",
		BACKPACK = "To haul my stuff around.",
		BACONEGGS = "Turn that frown upside down!",
		BALLPHIN = "My surfing buddies!",
		BAMBOO = "This looks pretty float-atious.",
		BAMBOOTREE =
		{
			BURNT = "I think it's dead.",
			CHOPPED = "Hurry up and grow already!",
			GENERIC = "I guess I could cut that down.",
		},
		BANDAGE = "I can patch myself up with this!",
		BAT = "Go flap somewhere else!",
		BATBAT = "Maybe I could bat some bats with this.",
		BATWING = "A couple more of these and I'll be flyin'!",
		BATWING_COOKED = "Looks a bit leathery.",
		BEARDHAIR = "Someone is probably missing these.",
		BEARGER = "Things don't have to get hairy, dude.",
		BEARGERVEST = "Made of real bearger chest!",
		BEARGER_FUR = "Now I can hibernate in comfort.",
		BANANAPOP = "The best way to keep cool. And very little preparation!",
		BISQUE = "This actually might've been worth the effort!",
		CEVICHE = "All I need is sunshine and some good food.",
		SEAFOODGUMBO = "My favorite!",
		SURFNTURF = "Can I eat it on my surfboard?",
		SHARKFINSOUP = "I could shove my face right in this.",
		LOBSTERDINNER = "Hey wobster, what's eatin' you? Oh, me!",
		LOBSTERBISQUE = "Looks fancy. And delicious.",
		JELLYOPOP = "Is this junk food or health food? I can't tell.",
		BEDROLL_FURRY = "For a more comfortable nap time!",
		BEDROLL_STRAW = "For nap time!",
		BEE =
		{
			GENERIC = "Well \"bzz bzz\" to you, too!",
			HELD = "You're probably safer here than out there, honestly.",
		},
		BEEBOX =
		{
			BURNT = "Maybe the bees did some redecorating?",
			FULLHONEY = "It's overflowing with sweet, sweet honey!",
			GENERIC = "That box has bees in and around it.",
			NOHONEY = "Would it be hypocritical to tell the bees to get to work?",
			SOMEHONEY = "Looks like the bees made me some honey! Thanks!",
		},
		BEEFALO =
		{
			FOLLOWER = "Aww, he loves me!",
			GENERIC = "I love these things!",
			NAKED = "Beautiful beach bod, bud.",
			SLEEPING = "Blissfully unaware of the terrors of night.",
		},
		BEEFALOHAT = "It smells like beefalo.",
		BEEFALOWOOL = "It looks more like hair to me.",
		BEEHAT = "Stops the bee kisses.",
		BEEHIVE = "The bees must sleep in there.",
		BEEMINE = "It's like a confetti bomb. But bees.",
		BELL = "Summons the big stomper.",
		BELL_BLUEPRINT = "A recipe for disaster.",
		BERMUDATRIANGLE = "Take me to a new surf spot!",
		BERRIES = "These are the edible kind, right?",
		BERRIES_COOKED = "They're all sticky now. Heh heh, gross.",
		BERRYBUSH =
		{
			BARREN = "It needs a little love.",
			GENERIC = "Awesome! That bush has berries!",
			PICKED = "It's kinda just a regular bush now.",
			WITHERED = "That bush isn't looking very good.",
		},
		BIOLUMINESCENCE = "Pretty glowy goop!",
		BIRDCAGE =
		{
			GENERIC = "I need to get a birdy buddy.",
			OCCUPIED = "I hope my birdy buddy is happy.",
			SLEEPING = "My birdy buddy's super sleepy.",
			HUNGRY = "My birdy buddy's belly's empty!",
			STARVING = "My birdy buddy's all bones!",
			DEAD = "My birdy buddy breathed his last...",
			SKELETON = "I have a lot of regrets in life.",
		},
		BIRDTRAP = "I can catch myself a birdy buddy with this.",
		BIRD_EGG = "There is a tiny birdy buddy in here!",
		BIRD_EGG_COOKED = "...I'm sorry, birdy buddy.",
		BISHOP = "Don't get any bright ideas.",
		BLUBBER = "If I had enough of this I could surf in any weather!",
		BLUBBERSUIT = "Gross, but effective.",
		BOARDS = "Not much surf in these boards.",
		BOATCANNON = "Can't we find a peaceful solution?",
		BOATREPAIRKIT = "Surfboard maintenance is essential!",
		BOAT_LANTERN = "Night-surfing. I love it!",
		BOAT_TORCH = "Night-surfing. I love it!",
		BOOMERANG = "They say if you love something, you should let it go.",
		BOTTLELANTERN = "This will keep the dark away.",
		BURIEDTREASURE = "Hope this is worth the work.",
		BUSHHAT = "This makes me feel at one with nature.",
		BUSH_VINE =
		{
			BURNT = "Not much use to anyone now.",
			CHOPPED = "Those vines are mine.",
			GENERIC = "Looks a little tangled.",
		},
		BUTTER = "Haha. Slippery!",
		BUTTERFLY =
		{
			GENERIC = "What a pretty pattern!",
			HELD = "You're my pretty pocket pal.",
		},
		BUTTERFLYMUFFIN = "What a pretty muffin!",
		BUTTERFLYWINGS = "I feel pretty bad about that.",
		CAMPFIRE =
		{
			EMBERS = "I need fuel for my fire!",
			GENERIC = "My cozy campfire!",
			HIGH = "Uhh... I hope this doesn't spread.",
			LOW = "I think it needs some energy!",
			NORMAL = "My cozy campfire!",
			OUT = "Well, that's that.",
		},
		CANE = "I cane, I saw.",
		CAPTAINHAT = "If only the boss could see me now.",
		CARGOBOAT = "This surfboard sure has a lot of pockets.",
		CARROT = "They must've named these after oranges.",
		CARROT_COOKED = "Smells good!",
		CARROT_PLANTED = "Ooo, that's a good find!",
		CARROT_SEEDS = "I could grow a carrot with these.",
		CAVE_BANANA = "Potassium!",
		CAVE_BANANA_COOKED = "Cooked potassium!",
		CHARCOAL = "The remains of something burnt.",
		CHESSJUNK1 = "Lots of potential here!",
		CHESSJUNK2 = "I hope someone makes something out of that.",
		CHESSJUNK3 = "Look at all those parts.",
		CHESTER = "The best kind of friend... one who works for free.",
		CHESTER_EYEBONE =
		{
			GENERIC = "I get the feeling I'm being watched.",
			WAITING = "Nap time!",
		},
		CHIMINEA = "Stay safe from the howling winds, precious light!",
		CLOTHSAIL = "I'll flow with the wind.",
		COCONADE =
		{
			BURNING = "This will make a big splash!",
			GENERIC = "Just holding it makes me feel powerful.",
		},
		COCONUT = 
		{
		    GENERIC = "Imagine getting conked on the head by one of these!",
		    PLANTED = "Hey little tree dude.",
		},
		COCONUT_COOKED = "Hmmm. Yep. It's cooked now.",
		COFFEE = "Smells amazing!",
		COFFEEBEANS = "Come to mama!",
		COFFEEBEANS_COOKED = "Peppy!",
		COFFEEBUSH =
		 {
		 	BARREN = "Nooo, I need my java!",
		 	GENERIC = "Java!",
		 	PICKED = "Hurry up and grow back!",
		 	WITHERED = "If it grew on the volcano...",
		 },
		COLDFIRE =
		{
			EMBERS = "Don't leave me, light!",
			GENERIC = "I'm not really sure how this thing works.",
			HIGH = "Chillin'.",
			LOW = "That fire is slacking off.",
			NORMAL = "The fire is doing it's job.",
			OUT = "The fire is taking a break.",
		},
		COLDFIREPIT =
		{
			EMBERS = "Don't leave me, light!",
			GENERIC = "I'm not really sure how this thing works.",
			HIGH = "Chillin'.",
			LOW = "That fire is slacking off.",
			NORMAL = "The fire is doing it's job.",
			OUT = "The fire is taking a break.",
		},
		COMPASS =
		{
			GENERIC = "How do I use this thing again?",
			N = "North-ish?",
			S = "South-ish?",
			E = "East-ish?",
			W = "West-ish?",
			NE = "Northeast-ish?",
			SE = "Southeast-ish?",
			NW = "Northwest-ish?",
			SW = "Southwest-ish?",
		},
		COOKEDMEAT = "Surfing fuel!",
		COOKEDMONSTERMEAT = "This still looks awful.",
		COOKEDSMALLMEAT = "A tasty morsel.",
		COOKPOT =
		{
			BURNT = "The food might taste a bit burnt.",
			COOKING_LONG = "If I watch it it'll never boil.",
			COOKING_SHORT = "Food incoming!",
			DONE = "I cooked something. Yum!",
			EMPTY = "My kind of cooking... Just dump everything in and wait!",
		},
		CORAL = "I need a fish tank to put this in!",
		CORALREEF = "What a pretty coral reef.",
		CORAL_BRAIN = "I get an uneasy feeling of despair near this.",
		CORAL_BRAIN_ROCK = "That is an impressive piece of coral.",
		CORN = "Aw, shucks.",
		CORN_COOKED = "I'll need a toothpick soon.",
		CORN_SEEDS = "I could grow some corn of my own with these.",
		CRAB =
		{
			GENERIC = "If I was on my surfboard I could catch you.",
			HIDDEN = "He's taking a break from running.",
		},
		CRABHOLE = "A beachfront home. Nice.",
		CUTGRASS = "It makes a swishing sound when I walk.",
		DEAD_SWORDFISH = "Woah, that fish is HUGE!",
		DEPLETED_GRASS =
		{
			GENERIC = "That grass looks pretty dead.",
		},
		DEVTOOL = "Useful!",
		DIRTPILE = "Well, would you look at that. A pile of dirt.",
		DIVININGROD =
		{
			COLD = "This rod isn't doing all that much.",
			GENERIC = "What a silly looking device.",
			HOT = "This rod is going crazy!",
			WARM = "I think the rod is trying to tell me something!",
			WARMER = "Woah, the rod is really going now.",
		},
		DOUBLE_UMBRELLAHAT = "This should keep me at least twice as dry.",
		DRAGONFRUIT_SEEDS = "I could grow a dragonfruit with these.",
		DRAGONPIE = "Delicious pie!",
		DUBLOON = "It's my lucky day!",
		DUG_BAMBOOTREE = "Planting this sounds like hard work.",
		DUG_BERRYBUSH = "Planting this sounds like hard work.",
		DUG_COFFEEBUSH = "Planting this sounds like hard work.",
		DUG_ELEPHANTCACTUS = "Planting this sounds like hard work.",
		DUG_GRASS = "Planting this sounds like hard work.",
		DUG_MARSH_BUSH = "Planting this sounds like hard work.",
		DUG_SAPLING = "Planting this sounds like hard work.",
		DURIAN = "Looks pretty difficult to eat.",
		DURIAN_COOKED = "Woah! That smells awful!",
		DURIAN_SEEDS = "I could grow a stink-fruit with these.",
		EARMUFFSHAT = "Keeps my ears fluffy and warm.",
		EARRING = "I hope someone didn't lose this...",
		EGGPLANT_SEEDS = "I could grow an eggplant with these.",
		ELEPHANTCACTUS = "Looking sharp!",
		ELEPHANTCACTUS_ACTIVE = "Ouch!",
		ELEPHANTCACTUS_STUMP = "It's taking a nap.",

		-----------------------------------------------------

		EVERGREEN =
		{
			BURNING = "That's not cool.",
			BURNT = "I know the feeling.",
			CHOPPED = "Sliced and diced.",
			GENERIC = "Reminds me of winter. Yuck.",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "That's not cool.",
			BURNT = "He's a burnout.",
			CHOPPED = "Cut down in its prime.",
			GENERIC = "Looks like the diet version.",
		},
		EYEBRELLAHAT = "My third eye will protect me.",
		EYEPLANT = "Made you look!",
		EYETURRET = "It's looking out for me.",
		EYETURRET_ITEM = "It's got my back.",
		FABRIC = "Where did my sticks go? I've been bamboozled!",
		FARMPLOT =
		{
			BURNT = "It's toast!",
			GENERIC = "Looks like manual labor to me.",
			GROWING = "I hope it's organic.", --Earth is having a ground-child
			NEEDSFERTILIZER = "That shrub could use some grub.",
		},
		FEATHERFAN = "An artificial ocean breeze.",
		FEATHERHAT = "I'm at one with my feathered friends.",
		FEATHERSAIL = "For smooth and swift sailing!",
		FEATHER_CROW = "A real softy.",
		FEATHER_ROBIN = "I'm tickled by the color of this.",
		FEATHER_ROBIN_WINTER = "A portable reminder of the beauty of nature.",
		FEM_PUPPET = "Bummer.",
		FERTILIZER = "Ground food.",
		FIREFLIES =
		{
			GENERIC = "My kind of insects.",
			HELD = "My glowy little pocket pals.",
		},
		FIREHOUND = "This one seems angrier somehow.",
		FIREPIT =
		{
			EMBERS = "This fire is tired.",
			GENERIC = "Oh, sweet enemy of darkness.",
			HIGH = "Heh, woah! Hot stuff!",
			LOW = "It's barely doing its job.",
			NORMAL = "Could be better... could be worse.",
			OUT = "It's taking a break.",
		},
		FIRESTAFF = "It's a hot commodity.",
		FIRESUPPRESSOR =
		{
			LOWFUEL = "It needs some juice.",
			OFF = "It's out cold.",
			ON = "Fling it on!",
		},
		FISHINGROD = "Have rod, will travel.",
		FISHINHOLE = "Looks like a good place to get lunch.",
		FISHSTICKS = "Looks like these fish are gonna be stickin' around.",
		FISHTACOS = "All times are taco times.",
		FISH_COOKED = "From my own personal recipe.",
		FISH_MED = "Sorry, lil dude.",
		FISH_MED_COOKED = "Is it snacktime?",
		FISH_RAW = "Needs more fire.",
		FISH_RAW_SMALL = "Small fish from a big pond.",
		FISH_RAW_SMALL_COOKED = "Is it snacktime?",
		FLAMEGEYSER = "It's got a hot temper.",
		FLINT = "This rock doesn't roll.",
		FLOTSAM = "Maybe I can fish it out.",
		FLOWER = "I'm very picky when it comes to these. Heh heh heh.",
		FLOWERHAT = "That's a happy looking headpiece!",
		FLOWERSALAD = "Now that's what I call health food.",
		FLOWER_EVIL = "Flowers shouldn't be that scary.",
		FLUP = "It's rude to stare, dude!",
		FOLIAGE = "It's all natural.",
		FOOTBALLHAT = "I feel like I could tackle anything.",
		FRUITMEDLEY = "A sweet treat!",
		GASHAT = "Protection from stink.",
		GEARS = "Looks like robot guts.",
		GOLDENAXE = "That's one treasury tool.",
		GOLDENMACHETE = "I can hack in style.",
		GOLDENPICKAXE = "I picked a good one.",
		GOLDENPITCHFORK = "It makes work feel shiny!",
		GOLDENSHOVEL = "I'm digging this fancy shovel.",
		GOLDNUGGET = "It's shiny and useful!",
		GRASS =
		{
			BARREN = "It needs help to grow.",
			BURNING = "That won't last.",
			GENERIC = "For all your grassy needs.",
			PICKED = "It will be back.",
			WITHERED = "It looks tired.",
		},
		GRASS_UMBRELLA = "This should keep me almost dry.",
		GREEN_CAP = "Looks sort of tasty.",
		GREEN_CAP_COOKED = "Fried fungus.",
		GREEN_MUSHROOM =
		{
			GENERIC = "Funky fungi.",
			INGROUND = "It's taking a nap.",
			PICKED = "Maybe it's thirsty.",
		},
		GUACAMOLE = "A total snack attack.",
		GUNPOWDER = "It goes boom.",
		HAIL_ICE = "From the freezer in the sky.",
		HAMBAT = "I can fight food with food.",
		HAMMER = "Smashing stuff *sounds* like work, but it's pretty fun.",
		HAWAIIANSHIRT = "This shirt is so me.",
		HEALINGSALVE = "It helps me live a little.",
		HEATROCK =
		{
			COLD = "It's icy!",
			FROZEN = "Refreshing.",
			GENERIC = "It's rock temperature.",
			HOT = "It's warm and glowing.",
			WARM = "It's a little toasty.",
		},
		HOMESIGN =
		{
			BURNT = "I know the feeling.",
			GENERIC = "Hang ten!",
		},
		HONEY = "Sticky, sweet and good to eat!",
		HOUND = "This dog is a real drag!",
		ICEMAKER =
		{
			HIGH = "Super chillin'.",
			LOW = "Not so chillin'.",
			NORMAL = "Just chillin'.",
			OUT = "Illin'.",
			VERYLOW = "Little bit of illin'.",
		},
		ICEPACK = "Keeps my snacks as cool as I am.",
		ICESTAFF = "Too cold to hold.",
		INSANITYROCK =
		{
			ACTIVE = "Ouch. My thoughts are hurting.",
			INACTIVE = "That's one dark tower.",
		},
		JAMMYPRESERVES = "Preserve those jams.",
		JELLYFISH = "Don't step on one in bare feet!!",
		JELLYFISH_COOKED = "I hope it doesn't sting on the way down.",
		JELLYFISH_DEAD = "It might still sting me.",
		JELLYFISH_PLANTED = "I hate these things.",
		JELLYJERKY = "Looks extra chewy.",
		JUNGLETREE =
		{
			BURNING = "That's not cool.",
			BURNT = "I know the feeling.",
			CHOPPED = "Sliced and diced.",
			GENERIC = "It's like nature's canopy.",
		},
		JUNGLETREESEED =
        {
            GENERIC = "A tree yee shall be.",
            PLANTED = "Ugh, planting that got me all sweaty. Gross.",
        },
		KABOBS = "It's like a meatsicle!",
		KILLERBEE =
		{
			GENERIC = "It's badly BEEhaved.",
			HELD = "This bee needs to relax.",
		},
		KNIGHTBOAT = "What a horrible knight to have a curse.",
		KRAMPUS = "Stealing isn't cool!",
		KRAMPUS_SACK = "A bag of stolen goods.",
		LANTERN = "It really lightens the mood.",
		LAVAPOOL = "It's like a gooey campfire!",
		LAVASPIT =
		{
			COOL = "All dried up.",
			HOT = "Looks a little spicy.",
		},
		LIGHTNING_ROD =
		{
			CHARGED = "It's fully energized!",
			GENERIC = "It's powered by electricity.",
		},
		LIMESTONE = "That's some tough stuff.",
		LIMPETROCK =
		{
			GENERIC = "Just look at all these Barneys.",
			PICKED = "Nothing to eat here.",
		},
		LIMPETS = "They're free from the hustle and bustle of daily life.",
		LIMPETS_COOKED = "Still a bit slimy.",
		LIVINGJUNGLETREE = "That tree would make a great board.",
		TREEGUARD = "Wanna be a board?!",
		LIVINGLOG = "It looks bummed.",
		LOBSTER = "Yummy sea bug.",
		LOBSTERHOLE = "I can wait as long as it takes.",
		LOBSTER_DEAD = "Soon to be good eats.",
		LOBSTER_DEAD_COOKED = "Now that's good eats!",
		LOG =
		{
			BURNING = "Waste of a good board.",
			GENERIC = "There's a board in there.",
		},
		LOGRAFT = "Seriously?",
		LUGGAGECHEST = "This trunk is a little steamy.",
		LUREPLANT = "It's so attractive.",
		LUREPLANTBULB = "Get meat, the easy way.",
		MACHETE = "What a hack job.",
		MAGMAROCK = "It's warm to the touch.",
		MAGMAROCK_GOLD = "It's warm to the touch.",
		MALE_PUPPET = "Sorry dude.",
		MANDRAKE =
		{
			DEAD = "I was rooting for it.",
			GENERIC = "A mystical plant.",
			PICKED = "You're messing up my chill vibes, dude.",
		},
		MANDRAKESOUP = "Mystical soup.",
		MANDRAKE_COOKED = "Not as mystical as I thought.",
		MANGROVETREE = "This tree really likes water.",
		MANGROVETREE_BURNT = "How?",
		MARSH_BUSH =
		{
			BURNING = "The spikes are burning. Good.",
			GENERIC = "I don't need spikes.",
			PICKED = "Yeoch!",
		},
		MARSH_PLANT = "Planty.",
		MARSH_PLANT_TROPICAL = "Tropical planty.",
		MARSH_TREE =
		{
			BURNING = "I've never seen such a spiky fire.",
			BURNT = "Still spiky.",
			CHOPPED = "Not so spiky now.",
			GENERIC = "Me and spikes don't get along.",
		},
		MEAT = "Five second rule!",
		MEATBALLS = "Saucy.",
		MEATRACK =
		{
			BURNT = "Your days of jerkying are over.",
			DONE = "That's some good looking jerky.",
			DRYING = "See you later, water.",
			DRYINGINRAIN = "Water doesn't make things dry.",
			GENERIC = "This rack could use some meat.",
		},
		MEAT_DRIED = "Boy, this meat is jerky.",
		MERM = "Go dunk your head, guy.",
		MERMFISHER = "You don't mind working for a living.",
		MERMHEAD =
		{
			BURNT = "I like it better burnt.",
			GENERIC = "As if the pigs didn't smell bad enough.",
		},
		MERMHOUSE =
		{
			BURNT = "This house has char-acter.",
			GENERIC = "I could have sworn this was an outhouse.",
		},
		MERMHOUSE_FISHER = "Where the workers take five.",
		MESSAGEBOTTLE = "There must be a better way to send a message...",
		MESSAGEBOTTLEEMPTY = "I could whistle a tune with you.",
		MINERHAT = "Another job I hope to never do.",
		MONSTERLASAGNA = "Still smells monstery...",
		MONSTERMEAT = "Am I really hungry enough?",
		MONSTERMEAT_DRIED = "Tough to chew AND crazy-making!",
		MOSQUITOSACK_YELLOW = "Ewwww.",
		MOSQUITO_POISON = "Get lost!",
		MULTITOOL_AXE_PICKAXE = "I'm picky when it comes to tools.",
		MUSHTREE_MEDIUM = "Medium mushness.",
		MUSHTREE_SMALL = "Grow tree! Mush! Mush!",
		MUSHTREE_TALL = "That's a whole lot of mushtree!",
		MUSSEL = "I could eat a hundred of these.",
		MUSSEL_COOKED = "Needs shallots.",
		MUSSEL_FARM =
		{
			GENERIC = "There's food hanging out down there.",
			STICKPLANTED = "That's it mussels, do some pull ups.",
		},
		MUSSEL_STICK = "The mussels glop to it.",
		NIGHTLIGHT = "Lights the night with 'mares.",
		NIGHTMAREFUEL = "The stuff of nightmares.",
		NIGHTSWORD = "Wield the dark.",
		NITRE = "Not just any old dumb rock.",
		OBSIDIAN = "Ouch, you're hot!",
		OBSIDIANAXE = "I gotta work to make you work...",
		OBSIDIANCOCONADE = "Beware of the boom!",
		OBSIDIANFIREPIT =
		{
			EMBERS = "This fire is tired.",
			GENERIC = "Oh, sweet enemy of darkness.",
			HIGH = "So much bright!",
			LOW = "It's barely doing its job.",
			NORMAL = "This fire keeps on lickin' and tickin'.",
			OUT = "It's taking a break.",
		},
		OBSIDIANMACHETE = "This blade's as hot as it is cool.",
		OBSIDIANSPEARGUN = "Oh, I like you.",
		OBSIDIAN_WORKBENCH = "For playing with fire.",
		OCTOPUSCHEST = "Booty-ya!",
		OCTOPUSKING = "You seem chill.",
		ONEMANBAND = "Let's get this jam sesh rollin'!",
		OX = "You smell like wet hair.",
		PACKIM = "You got a big mouth, fella.",
		PACKIM_FISHBONE = "I'll hold onto this.",
		PALMLEAF = "Would make a radical skirt.",
		PALMLEAF_HUT = "It's like indoors, but outdoors.",
		PALMLEAF_UMBRELLA = "My own pint-sized palm tree.",
		PALMTREE =
		{
			BURNING = "That's not cool.",
			BURNT = "I know the feeling.",
			CHOPPED = "Sliced and diced.",
			GENERIC = "Cool hair, tree.",
		},
		PANFLUTE = "Plays hypnotic tunes.",
		PAPYRUS = "Bet this burns good.",
		PARROT = "Will you ever stop squawking?",
		PEACOCK = "A tropical turkey!",
		PEROGIES = "Comfort food!",
		PETALS = "Flowers totally get me.",
		PETALS_EVIL = "These smell like bad karma.",
		PICKAXE = "My back hurts just looking at it.",
		PIGSKIN = "Not by the hair of his rumpy rump rump.",
		PIRATEHAT = "High fashion for the high seas.",
		PIRATEPACK = "Booty in the back.",
		PIRATIHATITATOR =
		{
			BURNT = "Fire always wins.",
			GENERIC = "It holds many sea-crets.",
		},
		PITCHFORK = "Looks like some kind of trident.",
		PLANTMEAT = "It's got all two food groups.",
		PLANTMEAT_COOKED = "Hey, you're not a REAL steak!",
		PLANT_NORMAL =
		{
			GENERIC = "Farming is so hard!",
			GROWING = "It's still just a child.",
			READY = "Can I get to the eating part now?",
			WITHERED = "Something made it all... gross.",
		},
		POISONHOLE = "Gag!",
		POMEGRANATE = "Seedy.",
		POMEGRANATE_COOKED = "Hot'n'juicy.",
		POMEGRANATE_SEEDS = "Ugh, these should go in the ground I guess...",
		POOP = "Surf sewage!",
		PORTAL_SHIPWRECKED = "I wonder what this does...",
		POWCAKE = "I'll eat whatever.",
		PRIMEAPE = "This guy's a major beach leech.",
		PRIMEAPEBARREL = "Gnarly domicile, man...",
		PURPLEAMULET = "This thing drives me nuts!",
		PURPLEGEM = "Shiny!",
		---------------------------------------------------------

		RAFT = "Worst. Surfboard. Ever.",
		RAINOMETER =
		{
			BURNT = "Guess you didn't see that coming.",
			GENERIC = "Tells me when to paddle in.",
		},
		RATATOUILLE = "I'd rather get curvy than scurvy.",
		RAZOR = "You're not coming near my legs!",
		REDBARREL = "Hmm, was I in charge of keeping these stowed?",
		REDGEM = "Booty-ful!",
		RED_CAP_COOKED = "I'm not THAT hungry.",
		REEDS =
		{
			BURNING = "Whoa. Heavy.",
			GENERIC = "More grass. Righteous.",
			PICKED = "Catch you on the flip flop.",
		},
		REFLECTIVEVEST = "Even sun worshipers need a break.",
		RESEARCHLAB =
		{
			BURNT = "Ugh, do I have to build you all over again now?",
			GENERIC = "I wish you were a do-all-the-work-for-me machine.",
		},
		RESEARCHLAB2 =
		{
			BURNT = "Ugh, do I have to build you all over again now?",
			GENERIC = "I still feel like I'm doing most of the work here.",
		},
		RESEARCHLAB3 =
		{
			BURNT = "Couldn't you have manipulated yourself into not getting burnt?",
			GENERIC = "Manipulating shadows sounds tough, glad I don't have to.",
		},
		RESURRECTIONSTATUE =
		{
			BURNT = "Up in smoke...",
			GENERIC = "You better work.",
		},
		RESURRECTIONSTONE = "Hope I never need you, weird wood dude...",
		ROCK = "I like you much better on land.",
		ROCKS = "Not flat. Won't skip.",
		ROCK_LIGHT =
		{
			GENERIC = "Gnarly!",
			LOW = "The lava is cooling.",
			NORMAL = "Gnarly!",
			OUT = "This fire is cooked.",
		},
		ROPE = "Good for a lot of boring stuff.",
		ROTTENEGG = "Smells like a ship cabin.",
		ROWBOAT = "Awww, rowing? Ugh.",
		RUINSHAT = "Fit for the queen boss!",
		RUINS_BAT = "Know a few scallywags I'd like to introduce this to.",
		SAIL = "A blow boater's best friend.",
		SAND = "I like it between my toes and nowhere else.",
		SANDBAG = "Heavy lifting...",
		SANDBAGSMALL = "Heavy lifting...",
		SANDBAG_ITEM = "Heavy lifting...",
		SANDHILL = "If this was bigger I could sand board.",
		SAND_CASTLE =
		{
			GENERIC = "I feel like a kid again!",
			SAND = "I like it between my toes and nowhere else.",
		},
		SAPLING =
		{
			BURNING = "Not much to burn.",
			GENERIC = "Board material?",
			PICKED = "Looks noodled.",
			WITHERED = "Looks like I feel.",
		},
		SEAGULL = "Poop hawk!",
		SEAGULL_WATER = "Ewww, its nethers are touching my waves...",
		SEASACK = "Squishy.",
		SEASHELL = "No two are alike. Well, except those two. And, uh... that one.",
		SEASHELL_BEACHED = "A gift from the sea.",
		SEATRAP = "Wobster goes in. Dinner comes out.",
		SEAWEED = "Name says it all.",
		SEAWEED_COOKED = "A little better I guess...",
		SEAWEED_DRIED = "It's better with some crunch.",
		SEAWEED_PLANTED = "Gets caught on my board.",
		SEEDS = "Ugh, do I have to like, plant these?",
		SEEDS_COOKED = "They get stuck in my teeth.",
		SEWING_KIT = "I'm not really the \"sewing\" kind.",
		SHARKITTEN = "You're pretty cute for my worst nightmare.",
		SHARK_FIN = "The only kind of fin I wanna see.",
		SHARK_GILLS = "It won't be needing these.",
		SHARK_TEETHHAT = "Feels wrong having these on my head...",
		SHARX = "Shoo! Shoo! Shoo!",
		SHOVEL = "Ugh, digging...",
		SIESTAHUT =
		{
			BURNT = "Rest in peace.",
			GENERIC = "I could use a snooze.",
		},
		SILK = "Spider gunk...",
		SKELETON = "Surfing the beyond...",
		SKELETON_PLAYER = "Surfing the beyond...",
		SKULLCHEST = "This won't Kramp my style.",
		SLOTMACHINE = "Should I push my luck?",
		SMALLBIRD =
		{
			GENERIC = "Eye see you.",
			HUNGRY = "Hope your stomach is as big as your eye.",
			STARVING = "Blink twice if you're hungry.",
		},
		SMALLMEAT = "Mmmmmeat!",
		SMALLMEAT_DRIED = "A treat that travels well.",
		SNAKE = "I hope you can't swim.",
		SNAKEOIL = "I wasn't born yesterday.",
		SNAKESKIN = "I could make a scaly bikini out of this!",
		SNAKESKINHAT = "Raindrops keep falling on my hat.",
		SNAKE_POISON = "My buddy has a bodacious bite!",
		SOLOFISH = "Bring me my slippers.",
		SPEAR = "For stabbing problems.",
		SPEARGUN = "Point. Shoot.",
		SPEARGUN_POISON = "Highly contagious.",
		SPEAR_OBSIDIAN = "Ready. Aim. Fire-y.",
		SPEAR_POISON = "Want to take a sick day?",
		SPIDER =
		{
			DEAD = "I wonder if it will rain now?",
			GENERIC = "Crawly creep.",
			SLEEPING = "Aww, it's so peaceful and disgusting.",
		},
		SPIDERDEN = "They don't like trespassers.",
		SPIDEREGGSACK = "Starts a spider farm.",
		SPIDERGLAND = "Why does health food taste so bad?",
		SPIDERHAT = "Ha! I'm your boss now, spiders!",
		SPIDERQUEEN = "I don't bow to royalty.",
		SPIDER_WARRIOR =
		{
			DEAD = "Now I can rest in peace.",
			GENERIC = "Back off, you're germy!",
			SLEEPING = "Hope you're having a nightmare.",
		},
		SPOILED_FISH = "Gag material!",
		SPOILED_FOOD = "What a waste.",
		STINGER = "Glad I don't have to pick this out of my skin.",
		STRAWHAT = "Keeps my face from getting freckly.",
		STUFFEDEGGPLANT = "Health grub.",
		STUNGRAY = "I thought shark farts were bad...",
		SUNKBOAT = "Surfboards don't sink!",
		SUNKEN_BOAT =
		{
			ABANDONED = "Surfboards don't sink!",
			GENERIC = "Surfboards don't sink!",
		},
		SUPERTELESCOPE = "I can super sea!!",
		SURFBOARD = "My love for you is deeper than the ocean.",
		SURFBOARD_ITEM = "My pride and joy!",
		SWEET_POTATO = "Dessert!",
		SWEET_POTATO_COOKED = "Hmm, it's not that sweet actually...",
		SWEET_POTATO_PLANTED = "Dessert grows in the ground!",
		SWEET_POTATO_SEEDS = "Ugh, I guess I should plant these?",
		SWORDFISH = "I've resolved to be more of a lover than a fighter.",
		TAFFY = "Maybe I could wax my board with this stuff.",
		TALLBIRD = "I'm glad it can't fly.",
		TALLBIRDEGG = "There's a little dude relaxin' inside.",
		TALLBIRDEGG_COOKED = "Now if I could only get giant toast.",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "Gelatinous...",
			GENERIC = "Raw...",
			HOT = "Hope it doesn't hard boil.",
			LONG = "It's growing...",
			SHORT = "C'mon squirt.",
		},
		TALLBIRDNEST =
		{
			GENERIC = "Bunch of future pecky jerks.",
			PICKED = "The eggs have flown the coop.",
		},
		TEENBIRD =
		{
			GENERIC = "It's got a ton of acne under those feathers. Haha, gross.",
			HUNGRY = "They're always hungry!",
			STARVING = "You've eaten me out of base and camp!",
		},
		TELEPORTATO_SW_BASE = "I sense its power...",
		TELEPORTATO_SW_BOX = "This thing attaches to the other thing?",
		TELEPORTATO_SW_CRANK = "I hope this isn't a broom 'cause I hate sweeping.",
		TELEPORTATO_SW_POTATO = "Tubular...",
		TELEPORTATO_SW_RING = "Doesn't look suited for hula-hooping...",
		TELESCOPE = "You can't hide from me, islands!",
		TENT =
		{
			BURNT = "Great! Just great...",
			GENERIC = "A cool, dry place to catch some Zzz's.",
		},
		THATCHPACK = "For when my pockets are full.",
		TIDALPOOL = "Wonder how deep it goes...",
		TIDAL_PLANT = "Stuff can grow anywhere I guess...",
		TIGERSHARK = "I'll never complain about regular sharks again!",
		TOPHAT = "Not quite my style...",
		TORCH = "Take that, night!",
		TOUCAN = "You could catch waves with a nose like that!",
		TRAILMIX = "Protein!",
		TRANSISTOR = "Thing-y what does the science stuff!",
		TRAP = "Catch me a beach breakfast!",
		TRAP_TEETH = "Ooh, that looks nasty!",
		TRAP_TEETH_MAXWELL = "Must avoid...",
		TRAWLNET = "Lootin' and cruisin'.",
		TRAWLNETDROPPED =
		{
			GENERIC = "A sack of sea goodies!",
			SOON = "Just a little more trawlin'...",
			SOONISH = "I wonder what it grabbed up...",
		},
		TREASURECHEST =
		{
			BURNT = "Nooooo! Goodbye shiny, shiny treasure...",
			GENERIC = "Treasure!",
		},
		TREASURECHEST_TRAP = "Tricky treasure!",
		TRIDENT = "I feel like the god of...something!",
		TRINKET_1 = "Gross.",
		TRINKET_10 = "I might need these if I ever take a gnarly wipeout.",
		TRINKET_11 = "Hey there lil dude. Wanna come with me?",
		TRINKET_12 = "Desse-what?",
		TRINKET_13 = "Slammable soda!",
		TRINKET_14 = "If I only had a pin...",
		TRINKET_15 = "Choka! A Ukulele!",
		TRINKET_16 = "An odd shaped plate...",
		TRINKET_17 = "Too big...",
		TRINKET_18 = "Old timey craftsmanship.",
		TRINKET_19 = "I only take herbals...",
		TRINKET_2 = "Aww, but I like real kazooing...",
		TRINKET_23 = "Too much work to figure out what this does...",
		TRINKET_3 = "Gord only knows what this is good for.",
		TRINKET_4 = "Gnome thanks, that thing's creepy.",
		TRINKET_5 = "Zzzzzzzoooooom!",
		TRINKET_6 = "Don't wanna touch this with wet hands...",
		TRINKET_7 = "Ooh, I'm good at this!",
		TRINKET_8 = "Hardened what?",
		TRINKET_9 = "I don't care if things are matchy.",
		TROPICALFAN = "Sweet relief.",
		TROPICAL_FISH = "Such tasty colors!",
		TRUNKVEST_SUMMER = "Lets my skin breath.",
		TUNACAN = "Whoa! Righteous non-spoilage!",
		TURBINE_BLADES = "Twirly!",
		TURF_ASH = "Ashy...",
		TURF_BEACH = "Take the beach to go.",
		TURF_CARPETFLOOR = "Make fists with your toes.",
		TURF_JUNGLE = "Gnarled-ly.",
		TURF_MARSH = "Goopy...",
		TURF_MEADOW = "Nice underfoot.",
		TURF_MUD = "Squelchy.",
		TURF_SINKHOLE = "I have a sinking feeling about this.",
		TURF_UNDERROCK = "Crunchy.",
		TURKEYDINNER = "I am thankful for this.",
		TWIGS = "Very useful.",
		UMBRELLA = "Keep off, elements!",
		UNAGI = "Ten more, please!",
		VENOMGLAND = "What a terrible gland.",
		VINE = "Good for lashing stuff down.",
		VOLCANO = "Mount gnarly!",
		VOLCANOSTAFF = "I'm the volcano's boss now!",
		VOLCANO_ALTAR =
		{
			GENERIC = "The volcano asks its price...",
			OPEN = "Ready to receive...",
		},
		VOLCANO_ALTAR_BROKEN = "Won't be taking any items now.",
		VOLCANO_EXIT = "Time to split this scene.",
		WAFFLES = "Brunch!",
		WALLYINTRO_DEBRIS = "Boat chunks...",
		WALL_HAY =
		{
			BURNT = "Not surprising... it was made out of hay...",
			GENERIC = "Better than no wall...",
		},
		WALL_HAY_ITEM = "Better than no wall...",
		WALL_LIMESTONE = "Now THIS is a wall!",
		WALL_LIMESTONE_ITEM = "Now THIS is a wall!",
		WALL_RUINS = "Why wall yourself off from the world?",
		WALL_RUINS_ITEM = "I could build a wall with this. But why bother?",
		WALL_STONE = "Seems strong...",
		WALL_STONE_ITEM = "Seems strong...",
		WALL_WOOD =
		{
			BURNT = "It was wood, after all...",
			GENERIC = "Knock on wood this keeps stuff out.",
		},
		WALL_WOOD_ITEM = "Knock on wood this keeps stuff out.",
		WASPHIVE = "The worst kind of hive!",
		WATERMELON = "Nothing better on a hot day!",
		WATERMELONHAT = "Next best thing to a watermelon bikini.",
		WATERMELONICLE = "Eat it before it melts!",
		WATERMELON_COOKED = "Hot watermelon...",
		WATERMELON_SEEDS = "I love watermelon... but I hate farm work...",
		WEBBERSKULL = "Not your run of the mill skull.",
		WETGOOP = "Is there dry goop?",
		WHALE_BLUE = "What's got ya down, fella?",
		WHALE_BUBBLES = "Something's down there...",
		WHALE_CARCASS_BLUE = "You don't have to be sad anymore...",
		WHALE_CARCASS_WHITE = "Vengeance is mine.",
		WHALE_WHITE = "Do ye spout black blood and roll fin out?",
		WILDBORE = "I'm not wild about it.",
		WILDBOREHOUSE = "Bores live in houses? Wild!",
		VOLCANO_SHRUB = "Rubs off on my hands.",
		ROCK_OBSIDIAN = "It'd be too much work to get you open...",
		ROCK_CHARCOAL = "Burnt, but good!",
		DRAGOONDEN = "Work out? Why bother.",

		ABIGAIL = "Hang ten, ectobuddy.",
		ARMORCACTUS = "How will I hug trees in this?",
		BASALT = "The strong, silent type.",
		BEEMINE_MAXWELL = "Sometimes I dance to the buzzing beat.",
		BIGFISHINGROD = "I'm ready to find a nice spot to relax with this.",
		BIGFOOT = "Just look at that goofy footed weirdo!",
		BIRCHNUTDRAKE = "Chillax, little dude.",
		BISHOP_NIGHTMARE = "This is why I don't play board games!",
		BLOWDART_FIRE = "A real quick way of lighting a firepit when no one's looking.",
		BLOWDART_FLUP = "It makes a wet squelch when it hits stuff.",
		BLOWDART_PIPE = "Do I have to shoot someone with it?",
		BLOWDART_POISON = "Not good for party tricks. I learned the hard way.",
		BLOWDART_SLEEP = "(Sometimes I use it for naps.)",
		BLUEAMULET = "I like to put it on when I'm feeling a little too steamed.",
		BLUEGEM = "The color of the ocean!",
		BLUEPRINT = "It's making my brain hurt just looking at it.",
		BLUE_CAP = "I didn't know mushrooms came in blue.",
		BLUE_CAP_COOKED = "Did I make it better or worse?",
		BLUE_MUSHROOM =
		{
			GENERIC = "Cooked or raw, I could eat a ton of these.",
			INGROUND = "It likes to sleep during the day. Just like me!",
			PICKED = "It needs time to unwind.",
		},
		BOAT = "The second best way to travel.",
		BOATCANNON = "Shooting it into the water can make some pretty sweet waves.",
		BONESHARD = "I don't think a cast will help now.",
		BONESTEW = "It looks like a pretty hearty meal.",
		BRAINJELLYHAT = "It's, like, blowing my mind!",
		BUGNET = "Maybe I could pass an afternoon catching butterflies.",
		BUNNYMAN = "Do you give good hugs?",
		BUOY = "It's just hanging out.",
		BUZZARD = "Not dead yet, friend!",
		CACTUS =
		{
			GENERIC = "It's fine if you just leave it alone.",
			PICKED = "Ouch! I got prickled.",
		},
		CACTUS_FLOWER = "You ever seen anything as pretty?",
		CACTUS_MEAT = "Cactus flesh... d'you think that's vegetarian?",
		CACTUS_MEAT_COOKED = "Looks pretty tasty now.",
		CATCOON = "It's very independent and loves garbage. Me too!",
		CATCOONDEN =
		{
			EMPTY = "Anyone there?",
			GENERIC = "Looks like a nice place to crash.",
		},
		CATCOONHAT = "I can feel the spirits of catcoons that made it.",
		CAVE_BANANA_TREE = "That's not a real banana!",
		CAVE_ENTRANCE =
		{
			GENERIC = "How much effort will it take to get in there?",
			OPEN = "I've always wanted to try spelunking.",
		},
		CAVE_EXIT = "Time to bail!",
		CAVE_FERN = "Nature finds a way, even here.",
		COCONUT_HALVED = "You get two for the price of one. Pfft.",
		COFFEEBOT = "I could go for a cup of joe.",
		COOKEDMANDRAKE = "Might as well eat it now.",
		COONTAIL = "This would make a stylish hat.",
		CRATE = "Wonder what's inside.",
		CROW =
		{
			GENERIC = "Akaw!",
			HELD = "Are we best friends now?",
		},
		CUTLASS = "It's been awhile since I held one of these.",
		CUTLICHEN = "Can I get something to eat now?",
		CUTREEDS = "It was hard work cutting those. Nap time!",
		CUTSTONE = "I don't have to build something now, do I?",
		DEADLYFEAST = "My gut can't handle that!",
		DECIDUOUSTREE =
		{
			BURNING = "Senseless.",
			BURNT = "Saying sorry won't bring it back.",
			CHOPPED = "Thanks for the logs. Sorry about, like, your body.",
			GENERIC = "It comes in so many colors!",
			POISON = "I said I was sorry!",
		},
		DEERCLOPS = "Yikes! We're in the impact zone now!",
		DEERCLOPS_EYEBALL = "Aw. Kind of reminds me of the boss.",
		DEPLETED_BAMBOOTREE = "It's gone for now.",
		DEPLETED_BUSH_VINE = "No more here.",
		DEPLETED_GRASS_WATER = "That was all it had to offer.",
		DEVTOOL_NODEV = "I couldn't possibly use that.",
		DIVININGRODBASE =
		{
			GENERIC = "What is that?",
			READY = "Maybe it wants a key?",
			UNLOCKED = "Let's get going!",
		},
		DIVININGRODSTART = "I can't wait to find a cool Thing!",
		DOYDOY = "Well hey there little guy.",
		DOYDOYBABY = "Aw! You look like you want a cuddle!",
		DOYDOYEGG = "Could be a doydoy. Or could be dinner.",
		DOYDOYEGG_COOKED = "You can taste the endangerment.",
		DOYDOYEGG_CRACKED = "I didn't touch it, I swear.",
		DOYDOYFEATHER = "It's soft to the touch.",
		DOYDOYNEST = "Looks like a great place to nap. For a doydoy.",
		DRAGONFLY = "I'd never have to put up with this on the open ocean!",
		DRAGONFLYCHEST = "What did I get?!",
		DRAGONFRUIT = "Decadent, and decorative!",
		DRAGONFRUIT_COOKED = "It tastes pretty.",
		DRAGON_SCALES = "I need a suit of these, immediately.",
		DRAGOON = "Woah, tone it down, my guy.",
		DRAGOONEGG = "I licked one once. It burned my tongue.",
		DRAGOONHEART = "It must have been in love. It's still crazy hot.",
		DRAGOONSPIT = "My brother used to do the same thing.",
		DRUMSTICK = "Does someone want to cook it for me?",
		DRUMSTICK_COOKED = "I feel like a warrior.",
		DUG_BUSH_VINE = "Do I really have to replant it?",
		EEL = "If you squint it's actually kind of cute.",
		EEL_COOKED = "I'm not gonna eat just an eel old thing!",
		EGGPLANT = "I've never seen an egg that shade of purple.",
		EGGPLANT_COOKED = "Is this, like, an omelette?",
		FEATHER_ROBIN_WINTER = "I would love a necklace made of these.",
		FISH = "Blub blub, little chum.",
		FLOWER_CAVE = "I want a whole wreath of them!",
		FLOWER_CAVE_DOUBLE = "I want a whole wreath of them!",
		FLOWER_CAVE_TRIPLE = "I want a whole wreath of them!",
		FRESHFRUITCREPES = "Score!",
		FROG =
		{
			DEAD = "It was too good for this world.",
			GENERIC = "Keep your tongue to yourself, bucko.",
			SLEEPING = "Sweet dreams.",
		},
		FROGGLEBUNWICH = "Not a bad afternoon snack.",
		FROGLEGS = "I don't really like touching them.",
		FROGLEGS_COOKED = "Tastes like doydoy.",
		FROG_POISON = "Best to just leave it alone.",
		GEMSOCKET =
		{
			GEMS = "I think it wants me to jam rocks in it.",
			VALID = "Lookin' good!",
		},
		GHOST = "You deserve a rest.",
		GLOMMER = "Looks like a friend.",
		GLOMMERFLOWER =
		{
			DEAD = "Poor lil thing.",
			GENERIC = "Wouldn't it look great in my hair?",
		},
		GLOMMERFUEL = "I'll make sure it goes to good use.",
		GLOMMERWINGS = "Sigh. Fly no more, friend.",
		GOATMILK = "It feels tingly going down.",
		GOOSE_FEATHER = "It's soft but... a bit grimy.",
		GRASS_WATER = "This grass is well hydrated!",
		GREENAMULET = "This necklace is a creative force. I'm feelin' it.",
		GREENGEM = "The color of nature!",
		GREENSTAFF = "This staff only destroys.",
		GUANO = "It's batilisk poop.",
		HOME = "Is it time for a nap?",
		HONEYCOMB = "It's sweet and full of bee babies.",
		HONEYHAM = "Is it a special occasion?",
		HONEYNUGGETS = "I'll just be lying here, shoving these into my mouth.",
		HORN = "It's a big animal horn.",
		HOTCHILI = "Yow! Burns my tongue SO GOOD.",
		HOUNDBONE = "It's a bunch of bones. How comforting.",
		HOUNDFIRE = "Hot! Too hot!",
		HOUNDMOUND = "I think there are some angry pups lurking nearby.",
		HOUNDSTOOTH = "Highlights the importance of regular dental checkups.",
		ICE = "It knows how to chill.",
		ICEBOX = "A constant reminder to keep it cool.",
		ICECREAM = "Perfect treat to pair with a hammock in the sun.",
		ICEHAT = "Keeps my head cold. And wet.",
		ICEHOUND = "What a chilly pup.",
		IRONWIND = "Uh... I'll stick to my board, thanks.",
		KNIGHT = "He looks like he could use a nap.",
		KNIGHT_NIGHTMARE = "He should go to sleep... and not wake up.",
		KOALEFANT_SUMMER = "Hang ten, big guy.",
		KOALEFANT_WINTER = "Hang ten, big snowy guy.",
		KRAKEN = "Surf's up!",
		KRAKENCHEST = "Treasure awaits me!",
		KRAKEN_TENTACLE = "It's much too floppy!",
		LEIF = "Step off, grey belly!",
		LEIF_SPARSE = "Step off, grey belly!",
		LICHEN = "This moss makes me sad.",
		LIGHTBULB = "Naturally bright. Just like me!",
		LIGHTNINGGOAT =
		{
			CHARGED = "Majestic!",
			GENERIC = "Do you think it would let me snuggle it?",
		},
		LIGHTNINGGOATHORN = "I feel a little bad about the dead goat.",
		LITTLE_WALRUS = "How ya doin', tiny?",
		LIVINGTREE = "There's a board in there just begging to get out.",
		LOCKEDWES = "You probably want me to like, free you or something, huh.",
		MAGIC_SEAL = "Why would anyone need this much power?",
		MAGMAROCK_FULL = "It's a big rock.",
		MAGMAROCK_GOLD_FULL = "Is that one sparkling?",
		MANRABBIT_TAIL = "Fluffy!",
		MARBLE = "Pretty fancy material.",
		MARBLEPILLAR = "What was it meant to hold up?",
		MARBLETREE = "Super weird.",
		MAXWELL = "He seems like kind of a jerk.",
		MAXWELLHEAD = "Woah, did I eat some bad berries?",
		MAXWELLLIGHT = "Weird.",
		MAXWELLLOCK = "Gives me the heebie jeebies.",
		MAXWELLPHONOGRAPH = "Jaunty, but grating.",
		MAXWELLTHRONE = "Woah. That's rough.",
		MINOTAUR = "Holy horns.",
		MINOTAURCHEST = "Whatcha got for me, magic chest?",
		MINOTAURHORN = "It was an ordeal to get this.",
		MOLE =
		{
			ABOVEGROUND = "Welcome to the surface!",
			HELD = "Are you comfy in there, buddy?",
			UNDERGROUND = "Who's down there?",
		},
		MOLEHAT = "I CAN SEE ALL!",
		MOLEHILL = "Nice hole, mole.",
		MONKEY = "You think he can surf?",
		MONKEYBALL = "What's that little dude? You want me to throw you?",
		MONKEYBARREL = "Neat abode, guys.",
		MONSTERTARTARE = "I'm not too keen on putting that in my mouth.",
		MOOSE = "You're a big one, huh!",
		MOOSEEGG = "It will one day hatch into a moo... a goo... a thing.",
		MOSQUITO =
		{
			GENERIC = "Filthy bloodsucker!",
			HELD = "Don't think this means we're friends.",
		},
		MOSQUITOSACK = "Makes an okay pillow if you plug your nose.",
		MOSSLING = "Don't you just want to pick it up and squeeze it?",
		MOUND =
		{
			DUG = "Thanks for the loot, dude.",
			GENERIC = "Seems rude to mess with it.",
		},
		MUSSELBOUILLABAISE = "Seafood, my favorite.",
		MYSTERYMEAT = "Total mushburger.",
		NEEDLESPEAR = "Eh. I don't get the point.",
		NIGHTMARELIGHT = "I don't care how weird it is, as long as it keeps darkness away.",
		NIGHTMARE_TIMEPIECE =
		{
			CALM = "I can breathe easy.",
			DAWN = "It's almost over...!",
			NOMAGIC = "I'm not getting anything.",
			STEADY = "I think it's keeping consistent.",
			WANING = "It's leaving...",
			WARN = "Woah! Things are really heating up!",
			WAXING = "It's gaining strength!",
		},
		NIGHTSTICK = "That's one gnarly-lookin' whacker.",
		ORANGEAMULET = "Finally, jewelry that gets me.",
		ORANGEGEM = "The world looks fractured when I peer through it!",
		ORANGESTAFF = "Ah, this staff was made for me!",
		OXHAT = "I hope it doesn't mess up my ponytails.",
		OX_FLUTE = "I'm gonna play some sweet jams on this baby.",
		OX_HORN = "I'm glad it's not attached to anything.",
		PANDORASCHEST = "Maybe I'll get something nice?",
		PARROT_PIRATE = "He's a squawkbuckler.",
		PEG_LEG = "Is it weird to just have one?",
		PENGUIN = "Hey little dude.",
		PERD = "He's a doofy little guy.",
		PIGGUARD = "Take it easy, big guy.",
		PIGGYBACK = "Was it worth it?",
		PIGHEAD =
		{
			BURNT = "Wasn't it bad enough already?",
			GENERIC = "Tough break, dude.",
		},
		PIGHOUSE =
		{
			BURNT = "Hope they had insurance.",
			FULL = "How do they all fit in there?",
			GENERIC = "Where the pigs kick back and relax.",
			LIGHTSOUT = "Turn it back on! PLEASE!",
		},
		PIGKING = "Haha. Am I supposed to curtsy or something?",
		PIGMAN =
		{
			DEAD = "Bad luck, dude.",
			FOLLOWER = "Let's hit the waves!",
			GENERIC = "Lookin' fine, swine.",
			GUARD = "Wow, you're really loyal. That's admirable.",
			WEREPIG = "Haha! What even is that?",
		},
		PIGTENT = "Doesn't smell too great.",
		PIGTORCH = "It's kind of cute.",
		PIKE_SKULL = "Well that's not very nice.",
		PINECONE =
		{
			GENERIC = "It's a tree baby.",
			PLANTED = "Grow on, little bud.",
		},
		PIRATEGHOST = "Aw. He could've had an eternal nap, but he came back.",
		POND = "It's kind of hard to look at myself these days.",
		POND_ALGAE = "It makes me miss the open sea.",
		POTTEDFERN = "It can no longer grow free.",
		PUMPKIN = "You look nice today, pumpkin.",
		PUMPKINCOOKIE = "Score!",
		PUMPKIN_COOKED = "Smells autumn-y.",
		PUMPKIN_LANTERN = "Spooky!",
		PUMPKIN_SEEDS = "They're fine like this. No need to do any farming.",
		RABBIT =
		{
			GENERIC = "Look at its little ears!",
			HELD = "No need to be scared.",
		},
		RABBITHOLE =
		{
			GENERIC = "It's rabbit-shaped.",
			SPRING = "I guess they needed Me Time.",
		},
		RABBITHOUSE =
		{
			BURNT = "Aw. The bunnies lost their home.",
			GENERIC = "A decent enough place to live.",
		},
		RAINCOAT = "The surf can't touch me now!",
		RAINHAT = "High and dry.",
		RAWLING = "This dude cracks me up!",
		RED_CAP = "It might be a bad idea to just eat stuff I find on the ground.",
		RED_MUSHROOM =
		{
			GENERIC = "Now that's a mushroom!",
			INGROUND = "Hiding, little dude?",
			PICKED = "It might grow back on its own.",
		},
		RELIC =
		{
			BROKEN = "I'm not cleaning that up.",
			GENERIC = "Where's the ancient bed?",
		},
		RESEARCHLAB4 =
		{
			BURNT = "Guess I don't get to pull the lever anymore.",
			GENERIC = "That lever's calling to me.",
		},
		ROBIN =
		{
			GENERIC = "A song given wing.",
			HELD = "How are you doing, little guy?",
		},
		ROBIN_WINTER =
		{
			GENERIC = "You have a lovely voice!",
			HELD = "You're not too squished, are you?",
		},
		ROBOT_PUPPET = "Sorry about your existence.",
		ROCKY = "No need to fight!",
		ROCK_ICE =
		{
			GENERIC = "At least someone around here knows how to chill!",
			MELTED = "I didn't bring my puddle stompin' boots!",
		},
		ROCK_ICE_MELTED = "I didn't bring my puddle stompin' boots!",
		ROOK = "Check, mate!",
		ROOK_NIGHTMARE = "Is that thing real?!",
		RUBBLE = "A big ol' pile of rocks.",
		RUINS_RUBBLE = "A big ol' pile of old, old rocks.",
		SAIL_STICK = "Probably more useful than a regular stick.",
		SANDBAGSMALL_ITEM = "Remind me not to swim while carrying these!",
		SANITYROCK =
		{
			ACTIVE = "Go off!",
			INACTIVE = "See ya.",
		},
		SHADOWSKITTISH_WATER = "Hey!",
		SHARKITTENSPAWNER =
		{
			GENERIC = "There are kitties jammin' inside.",
			INACTIVE = "Just sand?",
		},
		SHIPWRECKED_ENTRANCE = "Aloha, world!",
		SHIPWRECKED_EXIT = "Aloha, world!",
		SLURPER = "It's a little gross, but who am I to judge?",
		SLURPERPELT = "Maybe it doubles as a blanket.",
		SLURPER_PELT = "Maybe it doubles as a blanket.",
		SLURTLE = "It tastes with its feet. Gross.",
		SLURTLEHAT = "I'm a little embarrassed to wear it in public.",
		SLURTLEHOLE = "The snail things come out of there.",
		SLURTLESLIME = "It's hard to hold on to.",
		SLURTLE_SHELLPIECES = "Holding on to these doesn't even seem worth it.",
		SNAKEDEN =
		{
			BURNT = "Not much use to anyone now.",
			CHOPPED = "Those vines are mine.",
			GENERIC = "Looks a little tangled.",
		},
		SNAKESKINSAIL = "Why bother when I have my board?",
		SNAKE_FIRE = "Too hot to handle!",
		SNURTLE = "It tastes with its feet. Gross.",
		SPEAR_LAUNCHER = "Seems a little aggressive.",
		SPIDERHOLE = "It's a hole. Full of SPIDERS.",
		SPIDER_DROPPER = "How rude of you to drop in!",
		SPIDER_HIDER = "I see you over there!",
		SPIDER_SPITTER = "No thank you!",
		STAFFLIGHT = "Isn't starlight bad for the skin?",
		STAFF_TORNADO = "I'm glad I'm not on the receiving end.",
		STALAGMITE = "A pretty cool rock.",
		STALAGMITE_FULL = "A pretty cool rock.",
		STALAGMITE_LOW = "A pretty cool rock.",
		STALAGMITE_MED = "A pretty cool rock.",
		STALAGMITE_TALL = "A pretty cool rock.",
		STALAGMITE_TALL_FULL = "A pretty cool rock.",
		STALAGMITE_TALL_LOW = "This rock seems uncool.",
		STALAGMITE_TALL_MED = "A pretty cool rock.",
		STATUEGLOMMER =
		{
			EMPTY = "Woah, far out.",
			GENERIC = "All messed up now.",
		},
		STATUEHARP = "No shoes, no... head... no service!",
		STATUEMAXWELL = "Guy's got an ego problem.",
		SUNKEN_BOAT_BURNT = "An admirer of the sea, burned to ash. What injustice!",
		SUNKEN_BOAT_TRINKET_1 = "I have no idea how to use that.",
		SUNKEN_BOAT_TRINKET_2 = "Where's the toy surf board?",
		SUNKEN_BOAT_TRINKET_3 = "A wet candle in a bottle. Mega-genius!",
		SUNKEN_BOAT_TRINKET_4 = "So how much is the sea worth?",
		SUNKEN_BOAT_TRINKET_5 = "I've already got a pair of boots.",
		SWEATERVEST = "I hope none of my surfer buds see me in this.",
		SWEETPOTATOSOUFFLE = "Good enough to eat!",
		SWIMMINGHORROR = "AH! I'm losin' it!",
		TELEBASE =
		{
			GEMS = "I think it likes purple gems.",
			VALID = "Good to go!",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "Do I really want to go through that?",
			GENERIC = "Get your weird face out of here, dude!",
			LOCKED = "It still won't let me through.",
			PARTIAL = "It'd take a lot of effort to put this back together.",
		},
		TELEPORTATO_BOX = "This looks important.",
		TELEPORTATO_CRANK = "You wanna come with me, huh?",
		TELEPORTATO_POTATO = "Heh heh.",
		TELEPORTATO_RING = "I think I should hold on to it.",
		TELESTAFF = "It shows me things I never knew I could see.",
		TENTACLE = "Hands off, bucko!",
		TENTACLESPIKE = "It's pretty flimsy. I can't see it doing much damage.",
		TENTACLESPOTS = "These might help me out of a tight spot.",
		TENTACLE_GARDEN = "This has no right to exist.",
		TENTACLE_PILLAR = "It's all slimed up.",
		TENTACLE_PILLAR_ARM = "Much too slimy!",
		THULECITE = "It's otherworldly.",
		THULECITE_PIECES = "Weird.",
		TIGEREYE = "Nasty.",
		TREECLUMP = "I didn't want to get through anyway.",
		TRINKET_20 = "I have no idea how to use that.",
		TRINKET_21 = "Is there a toy surf board?",
		TRINKET_22 = "A candle in a bottle. Genius.",
		TRUNKVEST_WINTER = "I could fall asleep in this.",
		TRUNK_COOKED = "Seems edible, as far as noses go.",
		TRUNK_SUMMER = "It's a meaty-looking trunk.",
		TRUNK_WINTER = "It's a cold, meaty-looking trunk.",
		TUMBLEWEED = "It's on a journey called \"life\".",
		TURF_SANDY = "It's getting in my shoes!",
		TURF_BADLANDS = "Keeps me grounded.",
		TURF_CAVE = "It's ground.",
		TURF_CHECKERFLOOR = "It's ground.",
		TURF_DECIDUOUS = "Keeps me grounded.",
		TURF_DESERTDIRT = "Keeps me grounded.",
		TURF_DIRT = "Dirt.",
		TURF_FOREST = "Keeps me grounded.",
		TURF_FUNGUS = "Keeps me grounded.",
		TURF_FUNGUS_GREEN = "Keeps me grounded.",
		TURF_FUNGUS_RED = "Keeps me grounded.",
		TURF_GRASS = "Grassy.",
		TURF_MAGMAFIELD = "Keeps me grounded.",
		TURF_ROAD = "Keeps me grounded.",
		TURF_ROCKY = "Rocky.",
		TURF_SAVANNA = "Keeps me grounded.",
		TURF_SNAKESKINFLOOR = "Keeps me grounded.",
		TURF_SWAMP = "Swampy.",
		TURF_TIDALMARSH = "Marshy.",
		TURF_VOLCANO = "Keeps me grounded.",
		TURF_WOODFLOOR = "Hardwood. Fancy.",
		TWISTER = "This thing needs to relax!",
		TWISTER_SEAL = "I just wanna squish its face into my face.",
		UNIMPLEMENTED = "If it was my job, it'd never get finished.",
		VOLCANO_ALTAR_TOWER = "A blatantly unnatural structure.",
		WALRUS = "Hey grey belly! How's life treatin' ya?",
		WALRUSHAT = "This plaid ain't bad.",
		WALRUS_CAMP =
		{
			EMPTY = "No one home.",
			GENERIC = "Sweet digs.",
		},
		WALRUS_TUSK = "That's a pretty impressive tooth.",
		WARG = "What's your deal, man?",
		WATERYGRAVE = "That wound's a little too fresh.",
		WHALE_TRACK = "Seems like a lot of effort to follow it.",
		WILBUR_CROWN = "I dig the style.",
		WILBUR_UNLOCK = "Welcome aboard, bud!",
		WILDBOREHEAD = "That's what happens when you lose your head.",
		WIND_CONCH = "Get those waves cranking!",
		WINTERHAT = "It's like a hug for my head.",
		WINTEROMETER =
		{
			BURNT = "Not much use to me now.",
			GENERIC = "Why put numbers on what you can feel?",
		},
		WOODLEGSBOAT = "I'd still rather board.",
		WOODLEGSHAT = "Nautical.",
		WOODLEGSSAIL = "An acceptable alternative to surfing... I guess.",
		WOODLEGS_CAGE = "Whoever invented cages had a cruel heart.",
		WOODLEGS_KEY1 = "It's a boney key.",
		WOODLEGS_KEY2 = "Fancy.",
		WOODLEGS_KEY3 = "An iron key. What's it open?",
		WORM =
		{
			DIRT = "Something's taking a dirt nap.",
			PLANT = "Nothing to see here.",
			WORM = "That dude can pull off some sweet aerials.",
		},
		WORMHOLE =
		{
			GENERIC = "Is that its front end, or back?",
			OPEN = "Well, I see no reason not to jump in.",
		},
		WORMHOLE_LIMITED = "I don't think it's feeling well.",
		WORMLIGHT = "I find myself strangely attracted to it.",
		WRECK = "Probably won't be sailing on that anytime soon.",
		YELLOWAMULET = "I absolutely glow when I wear it!",
		YELLOWGEM = "It's got a nice energy.",
		YELLOWSTAFF = "Isn't starlight bad for the skin?",
		CALIFORNIAROLL = "I could eat a boat load of that stuff.",
},
	DESCRIBE_GENERIC = "Yup, that's definitely a thing.",
	DESCRIBE_SMOLDERING = "It's getting too hot to handle.",
	DESCRIBE_TOODARK = "HELP! I'm freakin' out here!",
		EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "Sorry, lil guy.",
	},
}