return{
	ACTIONFAIL = 
	{
		REPAIRBOAT =
		{
			GENERIC = "It will not work.",
		},
		SHAVE =
		{
			AWAKEBEEFALO = "It would be unwise to attempt this while the animal is awake.",
			GENERIC = "Not a shaveable beast.",
			NOBITS = "Nothing to shave.",
		},
		STORE =
		{
			GENERIC = "It is too full.",
			NOTALLOWED = "This is not the place for it.",
		},
		RUMMAGE =
		{	
			GENERIC = "I cannot right now.",	
		},
        COOK =
        {
            GENERIC = "I'm not quite ready yet.",
            TOOFAR = "I'll need to get a little closer to cook with that.",
        },
        GIVE =
        {
            DEAD = "Oh dear...",
            SLEEPING = "It's sleeping.",
            BUSY = "Goodness, it seems busy.",
        },
        WRITE =
        {
            GENERIC = "Maybe later. My hands are covered in cooking oil.",
        },
        CHANGEIN =
        {
            GENERIC = "I guess it never occurred to me I'd need to change.",
            BURNING = "It, oh, it appears to be on fire.",
        },
		TEACH =
        {
            KNOWN = "Ah. I already knew that.",
            CANTLEARN = "That might be a bit beyond me.",
        },
	},
	ACTIONFAIL_GENERIC = "I cannot do that.",
	ANNOUNCE_MAGIC_FAIL = "Sadly, I can not make it work.",
	ANNOUNCE_ACCOMPLISHMENT = "I am triumphant!",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "I hope this feeling lasts forever...",
	ANNOUNCE_ADVENTUREFAIL = "I shall have to attempt that again.",
	ANNOUNCE_BEES = "The honeymakers are upon me!",
	ANNOUNCE_BOAT_DAMAGED = "The vessel is damaged...",
	ANNOUNCE_BOAT_SINKING = "Oh no... I can't die on an empty stomach!",
	ANNOUNCE_BOAT_SINKING_IMMINENT = "Into the soup!",
	ANNOUNCE_BOOMERANG = "Ouch! Damnable thing!",
	ANNOUNCE_BURNT = "Charred...",
	ANNOUNCE_CANFIX = "\nI believe I could repair that.",
	ANNOUNCE_CHARLIE = "What the devil!",
	ANNOUNCE_CHARLIE_ATTACK = "Gah! I do believe something bit me!",
	ANNOUNCE_COLD = "I'm... getting freezerburn...",
	ANNOUNCE_CRAB_ESCAPE = "I was going to make you into a beautiful dinner!",
	ANNOUNCE_CRAFTING_FAIL = "I am lacking the required ingredients.",
	ANNOUNCE_DAMP = "I've been lightly spritzed.",
	ANNOUNCE_WET = "I am getting positively drenched.",
	ANNOUNCE_WETTER = "I fear I may be water soluble!",
	ANNOUNCE_DEERCLOPS = "I do not like that sound one bit!",
	ANNOUNCE_DUSK = "The dinner hour approaches.",
	ANNOUNCE_EAT =
	{
		GENERIC = "Magnifique!",
		INVALID = "Clearly inedible.",
		PAINFUL = "Aarg! My stomach...",
		SPOILED = "Blech! Why did I allow that to cross my lips?",
		STALE = "That was past its best-by date...",
		PREPARED = "Delectable!",
		SAME_OLD_1 = "I'd prefer some variety.",
		SAME_OLD_2 = "So bland.",
		SAME_OLD_3 = "I want to eat something different.",
		SAME_OLD_4 = "I can't stand this food.",
		SAME_OLD_5 = "Enough already!",
		TASTY = "Tres magnifique!",
		COOKED = "Not very palatable.",
		DRIED = "A bit dry.",
		RAW = "Blech. Completely lacking in every way.",
		YUCKY = "I'm frankly offended by the mere suggestion.",
	},
	ANNOUNCE_OTHER_WORLD_PLANT = "What are you doing so far from home?",
	ANNOUNCE_ENTER_DARK = "Darkness, darkness.",
	ANNOUNCE_ENTER_LIGHT = "A new day comes with the dawning light.",
	ANNOUNCE_FREEDOM = "Freeeeeeee!",
	ANNOUNCE_HIGHRESEARCH = "My brain is tingling!",
	ANNOUNCE_HOT = "I'm baking like a souffle here...",
	ANNOUNCE_HOUNDS = "I recognize that sound. Hunger.",
	ANNOUNCE_HUNGRY = "I need food...",
	ANNOUNCE_HUNT_BEAST_NEARBY = "Game is close at hand...",
	ANNOUNCE_HUNT_LOST_TRAIL = "I have lost the trail.",
	ANNOUNCE_HUNT_LOST_TRAIL_SPRING = "The trail has been washed out.",
	ANNOUNCE_INSUFFICIENTFERTILIZER = "It requires more manure.",
	ANNOUNCE_INV_FULL = "I cannot carry another stitch.",
	ANNOUNCE_KNOCKEDOUT = "My head... spinning...",
	ANNOUNCE_LIGHTNING_DAMAGE_AVOIDED = "That was much too close!",
	ANNOUNCE_LOWRESEARCH = "I did not learn any new tricks from that.",
	ANNOUNCE_MAPWRAP_LOSECONTROL = "Oh dear me, I have reached the point of no return.",
	ANNOUNCE_MAPWRAP_RETURN = "I have emerged from the edge of the world.",
	ANNOUNCE_MAPWRAP_WARN = "The implications of this are murky.",
	ANNOUNCE_MESSAGEBOTTLE =
	{
		"The ink is smudged...",
	},
	ANNOUNCE_MORETREASURE = "And yet more treasure!",
	ANNOUNCE_MOSQUITOS = "Disease with wings!",
	ANNOUNCE_NODANGERSIESTA = "This is no time to close my eyes!",
	ANNOUNCE_NODANGERSLEEP = "In this particular instance I'd prefer not to die in my sleep!",
	ANNOUNCE_NODAYSLEEP = "It is too bright to sleep.",
	ANNOUNCE_NODAYSLEEP_CAVE = "I'm not tired.",
	ANNOUNCE_NOHUNGERSIESTA = "I could use a nice meal first.",
	ANNOUNCE_NOHUNGERSLEEP = "My hunger trumps my exhaustion.",
	ANNOUNCE_NONIGHTSIESTA = "Siesta in the dark? I think not.",
	ANNOUNCE_NONIGHTSIESTA_CAVE = "This does not strike me as a relaxing place for siesta.",
	ANNOUNCE_NOSLEEPONFIRE = "I think not! That's a hotbed for danger!",
	ANNOUNCE_NO_TRAP = "Went off without a hitch.",
	ANNOUNCE_OTHER_WORLD_TREASURE = "This seems to point to points unknown.",
	ANNOUNCE_PECKED = "Gah! Enough!",
	ANNOUNCE_QUAKE = "That is not a comforting sound...",
	ANNOUNCE_RESEARCH = "Education is a lifelong process.",
	ANNOUNCE_SHARX = "I do believe they wish me harm.",
	ANNOUNCE_SHELTER = "I am thankful for this tree's protective buffer.",
	ANNOUNCE_SOAKED = "I'm wetter than a dish rag!",
	ANNOUNCE_THORNS = "Gah!",
	ANNOUNCE_FAN_OUT = "It fell apart in my hands!",
    ANNOUNCE_COMPASS_OUT = "Oh. I believe it broke.",
	ANNOUNCE_TOOL_SLIP = "Everything is slick...",
	ANNOUNCE_TORCH_OUT = "Come back, light!",
	ANNOUNCE_TRAP_WENT_OFF = "Darn!",
	ANNOUNCE_TRAWL_FULL = "The net is full!",
	ANNOUNCE_TREASURE = "It points to possible riches!",
	ANNOUNCE_UNIMPLEMENTED = "It is not operational yet.",
	ANNOUNCE_VOLCANO_ERUPT = "Incoming!",
	ANNOUNCE_WAVE_BOOST = "Whoaaaa!",
	ANNOUNCE_WHALE_HUNT_BEAST_NEARBY = "The beast is close.",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL = "The beast has slipped by me!",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL_SPRING = "How can I track anything in this deluge!",
	ANNOUNCE_WORMHOLE = "I must be unhinged to travel so...",
	BATTLECRY =
	{
		GENERIC = "I'm also an accomplished butcher!",
		PIG = "No part of you will go to waste, cochon!",
		PREY = "You look delicious!",
		SPIDER = "I hope it does not rain after I kill you!",
		SPIDER_WARRIOR = "You will die, pest!",
	},
	COMBAT_QUIT =
	{
		GENERIC = "There's no shame in running!",
		PIG = "Noooo, those hocks, those chops...",
		PREY = "Whew. I'm out of breath.",
		SPIDER = "I hope it didn't take any bites out of me.",
		SPIDER_WARRIOR = "That could have been worse.",
	},
	DESCRIBE =
	{
		INVENTORYGRAVE = "Here's hoping the next life treats you better.",
		INVENTORYMOUND = "Here's hoping the next life treats you better.",
		ACCOMPLISHMENT_SHRINE = "I always wished to make a name for myself.",
		ACORN =
		{
			GENERIC = "It rattles.",
			PLANTED = "A new beginning...",
		},
		ACORN_COOKED = "This could use something... Anything.",
		ADVENTURE_PORTAL = "What fresh devilment is this?",
		AERODYNAMICHAT = "Speeds me on my way.",
		AMULET = "I wear safety.",
		ANCIENT_ALTAR = "A structure from antiquity.",
		ANCIENT_ALTAR_BROKEN = "It is broken.",
		ANCIENT_STATUE = "It gives off strange vibrations.",
		ANIMAL_TRACK = "These tracks point to fresh game.",
		ANTIVENOM = "Could come in very handy.",
		ARMORDRAGONFLY = "Heavy and hot.",
		ARMORGRASS = "How much protection can grass really provide?",
		ARMORLIMESTONE = "With this I will be a stone man.",
		ARMORMARBLE = "Weighs a ton.",
		ARMOROBSIDIAN = "Heavy and hot.",
		ARMORRUINS = "Ancient armor.",
		ARMORSEASHELL = "Seashell mail.",
		ARMORSLURPER = "Ah. My appetite wanes under its protection.",
		ARMORSNURTLESHELL = "It allows me to turtle.",
		ARMORWOOD = "Sturdy, but quite flammable.",
		ARMOR_LIFEJACKET = "Better safe than sorry.",
		ARMOR_SANITY = "Am I crazy to wear this?",
		ARMOR_SNAKESKIN = "Function, fashion, and four less living snakes.",
		ARMOR_WINDBREAKER = "While it is rude to break wind in public, I will make an exception.",
		ARMOUREDBOAT = "I am comforted by its seaworthiness.",
		ASH =
		{
			GENERIC = "I miss ash covered cheeses. I miss cheeses, period.",
			REMAINS_EYE_BONE = "The eyebone was sacrificed in my travels.",
			REMAINS_GLOMMERFLOWER = "The unusual flower is but ash now.",
			REMAINS_THINGIE = "It is no more.",
		},
		AXE = "A trusty companion in these environs.",
		BABYBEEFALO = "You will fatten up nicely.",
		BABYOX = "You will fatten up nicely, with some proper grazing.",
		BACKPACK = "It has my back.",
		BACONEGGS = "Runny eggs... crisp bacon... I could die happy now...",
		BALLPHIN = "Chipper fellows.",
		BAMBOO = "Bamboo shoots are excellent on a nice bed of rice.",
		BAMBOOTREE =
		{
			BURNT = "A terrible waste.",
			CHOPPED = "More will sprout in time.",
			GENERIC = "Some chefs steam rice in bamboo stocks.",
		},
		BANDAGE = "First aid.",
		BASALT = "Made of strong stuff!",
		BAT = "If I only had a bat...",
		BATBAT = "A gruesome implement.",
		BATWING = "Hmmm, maybe a soup stock of batwings?",
		BATWING_COOKED = "Needs garlic...",
		BEARDHAIR = "Disgusting.",
		BEARGER = "Oh, I don't like you one bit!",
		BEARGERVEST = "Furry refuge from the elements.",
		BEARGER_FUR = "Feels warm.",
		BEDROLL_FURRY = "Cozy.",
		BEDROLL_STRAW = "A little better than bare ground. Scratchy.",
		BEE =
		{
			GENERIC = "Where there are bees, there is honey!",
			HELD = "Hi, honey.",
		},
		BEEBOX =
		{
			BURNT = "Disastrously caramelized.",
			FULLHONEY = "Honey jackpot!",
			GENERIC = "Home of the honeymakers!",
			NOHONEY = "No more honey...",
			SOMEHONEY = "There is a little honey.",
		},
		BEEFALO =
		{
			FOLLOWER = "That's it, my friend. I lead, you follow.",
			GENERIC = "Here's the beef.",
			NAKED = "Chin up, it'll grow back.",
			SLEEPING = "The sirloin slumbers...",
		},
		BEEFALOHAT = "Fits perfectly.",
		BEEFALOWOOL = "The beast's loss is my gain.",
		BEEHAT = "Essential honey harvesting attire.",
		BEEHIVE = "I can hear the activity within.",
		BEEMINE = "Weaponized bees.",
		BEEMINE_MAXWELL = "I pity whoever trips this.",
		BELL = "Should I ring it?",
		BELL_BLUEPRINT = "Fascinating.",
		BERMUDATRIANGLE = "Shouldn't I boat away from these?",
		BERRIES = "Fresh fruit!",
		BERRIES_COOKED = "Could use a pinch of sugar...",
		BERRYBUSH =
		{
			BARREN = "They require care and fertilizer.",
			GENERIC = "Berries!",
			PICKED = "More will return.",
			WITHERED = "The heat has stifled these berries.",
		},
		BIGFOOT = "Please do not squish me!",
		BIOLUMINESCENCE = "Magnifique...",
		BIRCHNUTDRAKE = "What madness is this?",
		BIRDCAGE =
		{
			GENERIC = "Suitable lodgings for a feathered beast.",
			OCCUPIED = "I now have an egg farm!",
			SLEEPING = "Sleep now, lay later.",
			HUNGRY = "Let me cook something nice up for you.",
			STARVING = "Oh, what do birds eat? A nice brisket?",
			DEAD = "Maybe it will wake up.",
			SKELETON = "It is not waking up. Oh dear.",
		},
		BIRDTRAP = "Oh, roast bird! Hm, don't get ahead of yourself, Warly...",
		BIRD_EGG = "Nature's perfect food.",
		BIRD_EGG_COOKED = "Could use a few different herbs...",
		BISHOP = "You don't strike me as particularly spiritual.",
		BISHOP_NIGHTMARE = "You are grinding my gears, dear fellow.",
		BLOWDART_FIRE = "Breathing fire!",
		BLOWDART_FLUP = "How considerate of that dead thing!",
		BLOWDART_PIPE = "They won't know what hit them.",
		BLOWDART_POISON = "A coward's weapon. Suits me fine!",
		BLOWDART_SLEEP = "A sleep aid!",
		BLUBBER = "This lard would feed a hungry fire!",
		BLUBBERSUIT = "Desperate times call for desperate attire.",
		BLUEAMULET = "Brrrrrr!",
		BLUEGEM = "Such a cool blue.",
		BLUEPRINT = "A recipe for technology!",
		BLUE_CAP = "What deliciousness shall you yield?",
		BLUE_CAP_COOKED = "Could use a dash of smoked salt and balsamic vinegar...",
		BLUE_MUSHROOM =
		{
			GENERIC = "Ah, a blue truffle!",
			INGROUND = "It retreats from the light.",
			PICKED = "I hope the truffles are restocked soon.",
		},
		BOARDS = "Sigh. It would be so perfect for grilling salmon.",
		BOAT = "To cross the open water.",
		BOATCANNON = "I cannon wait to use this!",
		BOATREPAIRKIT = "A most sensible traveling companion.",
		BOAT_LANTERN = "To \"sea\" what's coming!",
		BOAT_TORCH = "It's a light so I might \"sea\".",
		BONESHARD = "I could make a hearty stock with these.",
		BONESTEW = "Warms my soul!",
		BOOMERANG = "Oh good. I have separation anxiety.",
		BOTTLELANTERN = "Shine on!",
		BUGNET = "For catching alternative protein.",
		BUNNYMAN = "I have so many good rabbit recipes...",
		BURIEDTREASURE = "What shall I find?",
		BUSHHAT = "Snacks to go?",
		BUSH_VINE =
		{
			BURNT = "That smoky aroma always makes me hungry...",
			CHOPPED = "How divine! It has been de-vined.",
			GENERIC = "I do wish those were grapevines...",
		},
		BUTTER = "I thought I would never see you again, old friend!",
		BUTTERFLY =
		{
			GENERIC = "Your aerial dance is so soothing to behold...",
			HELD = "Don't slip from my butterfingers.",
		},
		BUTTERFLYMUFFIN = "Delectable!",
		BUTTERFLYWINGS = "I wonder what dishes I could create with these?",
		BUZZARD = "If only you were more turkey than vulture...",
		CACTUS =
		{
			GENERIC = "I bet it has a sharp flavor.",
			PICKED = "It will live to prick again.",
		},
		CACTUS_FLOWER = "Such a pretty flower from such a prickly customer!",
		CACTUS_MEAT = "I hope it does not prickle going down.",
		CACTUS_MEAT_COOKED = "Could use some tortillas and melted queso...",
		CAMPFIRE =
		{
			EMBERS = "I should stoke the fire.",
			GENERIC = "To keep the dark at bay.",
			HIGH = "Rivals a grease fire!",
			LOW = "It is getting low.",
			NORMAL = "I should like to sit by you for a moment.",
			OUT = "I will have to light you again.",
		},
		CANE = "Now we are cooking with gas!",
		CAPTAINHAT = "I have been promoted!",
		CARGOBOAT = "For long distance hauls.",
		CARROT = "Fresh picked produce!",
		CARROT_COOKED = "Could use a dash of olive oil and cilantro...",
		CARROT_PLANTED = "Ah, a fresh carrot!",
		CARROT_SEEDS = "Future carrots!",
		CATCOON = "What perky little ears.",
		CATCOONDEN =
		{
			EMPTY = "Vacant of critters.",
			GENERIC = "How many critters can fit in there?",
		},
		CATCOONHAT = "Not quite my style.",
		CAVE_BANANA = "Just the flavor I needed!",
		CAVE_BANANA_COOKED = "Could use some oats and a few chocolate chips...",
		CAVE_BANANA_TREE = "There must be monkeys close by.",
		CAVE_ENTRANCE =
		{
			GENERIC = "I wonder what is underneath that?",
			OPEN = "Dare I?",
		},
		CAVE_EXIT = "Thank goodness.",
		CAVE_ENTRANCE = "I wonder what is underneath that?",
        CAVE_ENTRANCE_RUINS = "What is within?",
       
       	CAVE_ENTRANCE_OPEN = 
        {
            GENERIC = "I wonder what is underneath that?",
            OPEN = "Dare I?",
        },
        CAVE_EXIT = 
        {
            GENERIC = "Thank goodness.",
            OPEN = "I should like to see the surface again.",
        },

		CAVE_FERN = "How does anything grow down here?",
		CHARCOAL = "This, a grill and some meat and I'd have dinner.",
		CHESSJUNK1 = "Broken chess pieces?",
		CHESSJUNK2 = "More broken chess pieces?",
		CHESSJUNK3 = "And yet more broken chess pieces?",
		CHESTER = "You look cute and inedible.",
		CHESTER_EYEBONE =
		{
			GENERIC = "The eye follows me wherever I go...",
			WAITING = "It sleeps.",
		},
		CHIMINEA = "I wonder if this could be converted into a pizza oven?",
		CLOTHSAIL = "Now we're cooking!",
		COCONADE =
		{
			BURNING = "This will only burn for so long before...",
			GENERIC = "Weaponized food.",
		},
		COCONUT = 
		{
		    GENERIC = "Its packaging is tough to open.",
		    PLANTED = "Evidence of a coconut uneaten. Sigh.",
		},
		COCONUT_COOKED = "Could use rice and curry spices...",
		COFFEE = "Magnifique!",
		COFFEEBEANS = "Glorious!",
		COFFEEBEANS_COOKED = "Could use hot water...!",
		--COFFEEBOT = "What a delight!",
		COFFEEBUSH =
		{
			BARREN = "Come back, coffee!",
			GENERIC = "Does that bush grow... coffee beans?!",
			PICKED = "I hope they grow back by tomorrow morning.",
			WITHERED = "Come back, coffee!",
		},
		COLDFIRE =
		{
			EMBERS = "I should stoke the fire.",
			GENERIC = "Fire that cools?",
			HIGH = "The flames climb higher!",
			LOW = "It's getting low.",
			NORMAL = "I should like to sit by you for a moment.",
			OUT = "I will have to light you again.",
		},
		COLDFIREPIT =
		{
			EMBERS = "I should stoke the fire.",
			GENERIC = "Fire that cools?",
			HIGH = "The flames climb higher!",
			LOW = "It's getting low.",
			NORMAL = "I should like to sit by you for a moment.",
			OUT = "I will have to light you again.",
		},

		COMPASS =
		{
			E = "East.",
			GENERIC = "Hmm, no reading.",
			N = "North.",
			NE = "Northeast.",
			NW = "Northwest.",
			S = "South.",
			SE = "Southeast.",
			SW = "Southwest.",
			W = "West.",
		},
		COOKEDMANDRAKE = "Could use horseradish...",
		COOKEDMEAT = "Could use a chimichurri sauce...",
		COOKEDMONSTERMEAT = "Could use... uh... I don't even...",
		COOKEDSMALLMEAT = "Could use sea salt...",
		COOKPOT = 
		{
			BURNT = "Tragique.",
			COOKING_LONG = "A masterpiece takes time.",
			COOKING_SHORT = "Nearly there...",
			DONE = "Ahh, fini!",
			EMPTY = "Empty pot, empty heart.",
		},
		COONTAIL = "Chat noodle.",
		CORAL = "What shall I make with you?",
		CORALREEF = "A rainbow searock.",
		CORAL_BRAIN = "Are these truly brain bits?",
		CORAL_BRAIN_ROCK = "Chewy rock, with a clever finish.",
		CORN = "Corn! Sweet, sweet corn!",
		CORN_COOKED = "Could use miso and lardons...",
		CORN_SEEDS = "The promise of so many more corn dishes!",
		CRAB =
		{
			GENERIC = "Soon you will be a crabcake.",
			HIDDEN = "I can smell you, my sweet!",
		},
		CRABHOLE = "Come out, come out!",
		CROW =
		{
			GENERIC = "Raven stew perhaps?",
			HELD = "Hush, my pet.",
		},
		CUTGRASS = "What shall I craft?",
		CUTLASS = "En garde!",
		CUTLICHEN = "Hmm, odd.",
		CUTREEDS = "Smells like greenery.",
		CUTSTONE = "Compressed stones, nice presentation.",
		DEADLYFEAST = "I would not recommend this.",
		DEAD_SWORDFISH = "The grand poisson!",
		DECIDUOUSTREE =
		{
			BURNING = "Au revoir, tree.",
			BURNT = "Crisp, no?",
			CHOPPED = "Sliced!",
			GENERIC = "A bouquet of leaves.",
			POISON = "No thank you!",
		},
		DEERCLOPS = "I once had a saucier who looked like that.",
		DEERCLOPS_EYEBALL = "Giant eyeball... soup?",
		DEPLETED_GRASS =
		{
			GENERIC = "Well past its expiry date.",
		},
		DEVTOOL = "Efficient, oui?",
		DEVTOOL_NODEV = "No, I am a traditionalist.",
		DIRTPILE = "It's making a bit of a mess, isn't it?",
		DIVININGROD =
		{
			COLD = "Hmm, keep looking.",
			GENERIC = "A finely tuned radar stick.",
			HOT = "I can almost smell it!",
			WARM = "I've caught onto something!",
			WARMER = "Warmer, warmer...!",
		},
		DIVININGRODBASE =
		{
			GENERIC = "Is it a chopping block?",
			READY = "How do I turn it on?",
			UNLOCKED = "Preparation complete!",
		},
		DIVININGRODSTART = "That looks important.",
		DOUBLE_UMBRELLAHAT = "Ridiculous! I want one.",
		DOYDOY = "I see potential in this poultry.",
		DOYDOYBABY = "I should let it grow into more food.",
		DOYDOYEGG = "Hello, breakfast.",
		DOYDOYFEATHER = "A feather from my feathered friend.",
		DOYDOYNEST = "It will become tastier with time.",
		DOYDOYEGG_CRACKED = "Spoiled egg?",
		DRAGONFLY = "I'm not cut out for this.",
		DRAGONFLYCHEST = "Ooh la la, burnproof storage.",
		DRAGONFRUIT = "So exotic!",
		DRAGONFRUIT_COOKED = "Could use a spread of pudding and chia seeds...",
		DRAGONFRUIT_SEEDS = "They hatch dragonfruits.",
		DRAGONPIE = "Flaky crust, tart filling... heavenly!",
		DRAGON_SCALES = "Hot to the touch!",
		DRAGOON = "I wish I could make my own fire!",
		DRUMSTICK = "Dark meat!",
		DRUMSTICK_COOKED = "Could use a light honey garlic glaze...",
		DUBLOON = "Golden ham, golden honey, golden coin.",
		DUG_BAMBOOTREE = "Shall I bring it back to life?",
		DUG_BERRYBUSH = "Shall I bring it back to life?",
		DUG_COFFEEBUSH = "Coffee to go!",
		DUG_ELEPHANTCACTUS = "Shall I bring it back to life?",
		DUG_GRASS = "Shall I bring it back to life?",
		DUG_MARSH_BUSH = "Shall I bring it back to life?",
		DUG_SAPLING = "Shall I bring it back to life?",
		DURIAN = "That odor...",
		DURIAN_COOKED = "Could use onions and chili...",
		DURIAN_SEEDS = "Even these smell...",
		EARMUFFSHAT = "Ahh, fuzzy!",
		EARRING = "Fancy.",
		EEL = "Anguille.",
		EEL_COOKED = "Could use some cajun spices...",
		EGGPLANT = "Aubergine!",
		EGGPLANT_COOKED = "Could use tomato sauce and Parmesan...",
		EGGPLANT_SEEDS = "Hatches more eggplants!",
		ELEPHANTCACTUS = "A big prickly pickle.",
		ELEPHANTCACTUS_ACTIVE = "Sword plant!",
		ELEPHANTCACTUS_STUMP = "The pickle will fruit again.",
		EVERGREEN =
		{
			BURNING = "Au revoir, tree.",
			BURNT = "Crisp, no?",
			CHOPPED = "Sliced!",
			GENERIC = "A soldier of the exotic forest.",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "Au revoir, tree.",
			BURNT = "Crisp, no?",
			CHOPPED = "Sliced!",
			GENERIC = "A coneless arbre.",
		},
		EYEBRELLAHAT = "\"Eye\" like it!",
		EYEPLANT = "Alluring, no?",
		EYETURRET = "This is my friend, Lazer Oeil!",
		EYETURRET_ITEM = "Wake up!",
		FABRIC = "Soft and crisp, all at once.",
		FARMPLOT =
		{
			BURNT = "Stayed in the oven a tad too long.",
			GENERIC = "I can grow my own ingredients!",
			GROWING = "Ah, couldn't be more fresh!",
			NEEDSFERTILIZER = "Needs to be fertilized.",
		},
		FEATHERFAN = "Why is it so big?",
		FEATHERHAT = "What am I supposed to do with this?",
		FEATHERSAIL = "I mostly want to pet it.",
		FEATHER_CROW = "A bird's feather, in truffle black.",
		FEATHER_ROBIN = "A bird's feather, in cherry red.",
		FEATHER_ROBIN_WINTER = "A bird's feather, in tuna blue.",
		FEM_PUPPET = "She's trapped!",
		FERTILIZER = "Sauce for my garden!",
		FIREFLIES =
		{
			GENERIC = "A dash of glow.",
			HELD = "My petit lightbulb pets.",
		},
		FIREHOUND = "Chien, on fire!",
		FIREPIT =
		{
			EMBERS = "That fire's almost out!",
			GENERIC = "To warm my fingers and roast sausages.",
			HIGH = "Maximum heat!",
			LOW = "It's getting low.",
			NORMAL = "Parfait.",
			OUT = "I like when it's warm and toasty.",
		},
		FIRESTAFF = "Oven on a stick!",
		FIRESUPPRESSOR =
		{
			LOWFUEL = "Shall I fuel it up?",
			OFF = "He's sleeping.",
			ON = "Make it snow!",
		},
		FISH = "Poisson!",
		FISHINGROD = "I believe I prefer the fish market.",
		FISHINHOLE = "Shining, sparkling snacks.",
		FISHSTICKS = "Crunchy and golden outside, flaky and moist inside!",
		FISHTACOS = "Takes me south of the border!",
		FISH_MED = "Don't worry, mon amie. I will make you delicious.",
		FISH_MED_COOKED = "Could use fresh herbs and butter...",
		FISH_COOKED = "Could use a squeeze of lemon...",
		FISH_RAW = "Doesn't even smell fishy it's so fresh!",
		FISH_RAW_SMALL = "I will honor this ingredient.",
		FISH_RAW_SMALL_COOKED = "Could use fresh herbs and butter...",
		FLAMEGEYSER = "Watch that flame!",
		FLINT = "Sharp as can be!",
		FLOTSAM = "Could be a piece of the ship...",
		FLOWER = "Charmant.",
		FLOWERHAT = "Who doesn't look good in this?!",
		FLOWERSALAD = "Edible art!",
		FLOWER_CAVE = "Ah, a light in the dark.",
		FLOWER_CAVE_DOUBLE = "Ah, a light in the dark.",
		FLOWER_CAVE_TRIPLE = "Ah, a light in the dark.",
		FLOWER_EVIL = "A terrible omen if I ever saw one.",
		FLUP = "Ack! Away!",
		FOLIAGE = "Feuillage.",
		FOOTBALLHAT = "Made from pork, to protect my melon.",
		FROG =
		{
			DEAD = "I'll eat your legs for dinner!",
			GENERIC = "Frog. A delicacy.",
			SLEEPING = "Bonne nuit, little snack.",
		},
		FROGGLEBUNWICH = "Ah, French cuisine!",
		FROGLEGS = "I am hopping with excitement!",
		FROGLEGS_COOKED = "Could use garlic and clarified butter...",
		FROG_POISON = "A poison hopper.",
		FRUITMEDLEY = "Invigorating!",
		GASHAT = "Anything to keep poison out of my dinner!",
		GEARS = "The insides of those naughty machines.",
		GEMSOCKET =
		{
			GEMS = "Gem it!",
			VALID = "Voila!",
		},
		GHOST = "Could I offer you a ghost pepper?",
		GLOMMER = "I think I like it.",
		GLOMMERFLOWER =
		{
			DEAD = "What a waste.",
			GENERIC = "Tres beau!",
		},
		GLOMMERFUEL = "Looks like bubblegum, tastes like floor.",
		GLOMMERWINGS = "A tiny delicacy.",
		GOATMILK = "Can I make this into cheese?",
		GOLDENAXE = "A golden chopper!",
		GOLDENMACHETE = "Fancy slicer.",
		GOLDENPICKAXE = "That looks nice.",
		GOLDENPITCHFORK = "A golden fork for a giant, oui?",
		GOLDENSHOVEL = "Shiny.",
		GOLDNUGGET = "Yolk yellow, glowing gold!",
		GOOSE_FEATHER = "A plucked goose was here.",
		GRASS =
		{
			BARREN = "Could I get some fertilizer over here?",
			BURNING = "I never burn anything in the kitchen.",
			GENERIC = "A common ingredient for success around here.",
			PICKED = "Plucked clean!",
			WITHERED = "Too hot for you.",
		},
		GRASS_UMBRELLA = "A bit of shade is better than none.",
		GRASS_WATER = "Herbe at sea.",
		GREENAMULET = "For more savvy construction!",
		GREENGEM = "Ahh, a rare attraction!",
		GREENSTAFF = "I probably shouldn't stir soup with this.",
		GREEN_CAP = "Don't crowd the mushrooms.",
		GREEN_CAP_COOKED = "Could use a slathering of butter and chives...",
		GREEN_MUSHROOM =
		{
			GENERIC = "Little champignon!",
			INGROUND = "Did it eat itself...?",
			PICKED = "I eagerly await its rebirth!",
		},
		GUACAMOLE = "More like Greatamole!",
		GUANO = "Poop of the bat.",
		GUNPOWDER = "Boom!",
		HAIL_ICE = "Like icecubes.",
		HAMBAT = "Mmm, ham popsicle!",
		HAMMER = "For tenderizing boeuf!",
		HAWAIIANSHIRT = "When in Rome...",
		HEALINGSALVE = "Soothing.",
		HEATROCK =
		{
			COLD = "Still cold.",
			FROZEN = "Vanilla ice.",
			GENERIC = "A temperature stone.",
			HOT = "Hot!",
			WARM = "It's warming up nicely.",
		},
		HOME = "Who lives here?",
		HOMESIGN =
		{
			BURNT = "Overcooked.",
			GENERIC = "What's the use in a sign around here?",
		},
		HONEY = "Nectar of the gods!",
		HONEYCOMB = "Just add milk!",
		HONEYHAM = "Comfort food!",
		HONEYNUGGETS = "Junk food is my guilty pleasure. Shh!",
		HORN = "There's still some hairs inside.",
		HOTCHILI = "Spice up my life!",
		HOUND = "Angry chien!",
		HOUNDBONE = "Hmm, soup stock...",
		HOUNDFIRE = "Fire in the kitchen!",
		HOUNDMOUND = "It smells wet.",
		HOUNDSTOOTH = "Better to lose a tooth than your tongue!",
		ICE = "That's ice.",
		ICEBOX = "The ice box, my second-most loyal culinary companion.",
		ICECREAM = "The heat is sweetly beat!",
		ICEHAT = "Must I wear it?",
		ICEHOUND = "Away, frozen diable!",
		ICEMAKER =
		{
			HIGH = "Whistle while you work!",
			LOW = "It's still running.",
			NORMAL = "A small luxury.",
			OUT = "It's run dry.",
			VERYLOW = "Nearly out!",
		},
		ICEPACK = "Now this I can use!",
		ICESTAFF = "It flash freezes poulet!",
		INSANITYROCK =
		{
			ACTIVE = "And I'm in!",
			INACTIVE = "Do not lick it. Your tongue will get stuck.",
		},
		IRONWIND = "Zoom zoom!",
		JAMMYPRESERVES = "Simple, sweet, parfait.",
		JELLYFISH = "Electric meduse for dinner?",
		JELLYFISH_COOKED = "Could use sesame oil and chilis...",
		JELLYFISH_DEAD = "Ohh, its petit face.",
		JELLYFISH_PLANTED = "Meduse.",
		JELLYJERKY = "Could use garlic...",
		JUNGLETREE =
		{
			BURNING = "Au revoir, tree.",
			BURNT = "Crisp, no?",
			CHOPPED = "Sliced!",
			GENERIC = "Gigantesque!",
		},
		JUNGLETREESEED =
        {
            GENERIC = "Cute, no?",
            PLANTED = "Even cuter than the seed!",
        },
		KABOBS = "Opa!",
		KILLERBEE =
		{
			GENERIC = "Almost not worth the honey!",
			HELD = "So sassy!",
		},
		KNIGHT = "A tricky cheval!",
		KNIGHTBOAT = "Cannon fire! Time to pirate.",
		KNIGHT_NIGHTMARE = "Effroyable!",
		KOALEFANT_SUMMER = "Ah, you have fattened up nicely!",
		KOALEFANT_WINTER = "You can't get attached to cute cuts of meat.",
		KRAMPUS = "What the devil!",
		KRAMPUS_SACK = "Infinite pocket space!",
		LANTERN = "It is my night light.",
		LAVAPOOL = "Spicy!",
		LAVASPIT =
		{
			COOL = "The top has cooled like a barfy creme brulee!",
			HOT = "A chef-cuisinier never burns his fingers.",
		},
		LEIF = "I'm out of my element!",
		LEIF_SPARSE = "I'm out of my element!",
		LICHEN = "Really scraping the barrel for produce here.",
		LIGHTBULB = "Looks like candy.",
		LIGHTNINGGOAT =
		{
			CHARGED = "Goat milkshake!",
			GENERIC = "I had a goat once.",
		},
		LIGHTNINGGOATHORN = "For kabobs, perhaps?",
		LIGHTNING_ROD =
		{
			CHARGED = "Electricity!",
			GENERIC = "I do feel a bit safer now.",
		},
		LIMESTONE = "Made from petit fishy skeletons.",
		LIMPETROCK =
		{
			GENERIC = "A petit snail farm!",
			PICKED = "I have a soft spot for bivalves!",
		},
		LIMPETS = "They have a salty aroma.",
		LIMPETS_COOKED = "Smooth, salty, scrumptious.",
		LITTLE_WALRUS = "Oh, there's a little one!",
		LIVINGJUNGLETREE = "Pardon, but are you sleeping?",
		TREEGUARD = "Let us not do anything we will regret, uh... sir...",
		LIVINGLOG = "Magic building blocks!",
		LIVINGTREE = "Tres suspicious...",
		LOBSTER = "Come to me, precious!",
		LOBSTERHOLE = "I am waiting for you!",
		LOBSTER_DEAD = "One step closer to my mouth.",
		LOBSTER_DEAD_COOKED = "Could use garlic-butter...",
		LOCKEDWES = "I'll get you out, mon ami!",
		
		LOG =
		{
			BURNING = "Soon it won't be good for much.",
			GENERIC = "An important aspect of my art.",
		},
		LOGRAFT = "These logs might be better suited to a fire...",
		LUGGAGECHEST = "Please have fresh underwear inside!",
		LUREPLANT = "How alluring.",
		LUREPLANTBULB = "Growing meat from the ground? Now I've seen it all...",
		MACHETE = "I could chop many an onion with this!",
		MAGMAROCK = "This rocks.",
		MAGMAROCK_GOLD = "Wonder if I could harvest goldleaf from this?",
		MANDRAKE =
		{
			DEAD = "I should like to get to the root of this mystery...",
			GENERIC = "Have I discovered a new root vegetable?!",
			PICKED = "Do not pick! Do not pick!",
		},
		MANDRAKESOUP = "What an otherworldly flavor!",
		MANDRAKE_COOKED = "Could use... an explanation...",
		MANGROVETREE = "I wonder what its water content is?",
		MANGROVETREE_BURNT = "I'd say its current water content is zero.",
		MARBLE = "Would make a nice counter top.",
		MARBLEPILLAR = "I wonder how many counter tops I could get out of this...",
		MARSH_BUSH =
		{
			BURNING = "It burns like any other bush.",
			GENERIC = "A prickly customer.",
			PICKED = "Not sure I want to do that again.",
		},
		MARSH_PLANT = "I wonder if it is edible.",
		MARSH_PLANT_TROPICAL = "I wonder if it is edible.",
		MARSH_TREE =
		{
			BURNING = "You will not be missed.",
			BURNT = "The wood gives off a unique aroma when burned.",
			CHOPPED = "There. Now you cannot prick anyone.",
			GENERIC = "I am ever so glad I'm not a tree hugger.",
		},
		MAXWELL = "You! You... villain!",
	    MAXWELLHEAD = "He must eat massive sandwiches.",
		MAXWELLLIGHT = "A light is always welcome.",
		MAXWELLLOCK = "But where is the key?",
		MAXWELLPHONOGRAPH = "I wonder what is in his record collection?",
		MAXWELLTHRONE = "Heavy is the bum that sits on the throne...",
		MEAT = "I must remember to cut across the grain.",
		MEATBALLS = "I'm having a ball!",
		MEATRACK =
		{
			BURNT = "Too dry! Too dry!",
			DONE = "Ready to test on my teeth!",
			DRYING = "Not quite dry enough.",
			DRYINGINRAIN = "Now it is more like a rehydrating rack...",
			GENERIC = "Just like the chefs of the stone age!",
		},
		MEAT_DRIED = "Could use chipotle...",
		MERM = "Fishmongers!",
		MERMFISHER = "You bring the sea with you.",
		MERMHEAD =
		{
			BURNT = "I think it needs to burned again! Pee-eew!",
			GENERIC = "Its odor is not improving with time...",
		},
		MERMHOUSE =
		{
			BURNT = "That fire got the smell out.",
			GENERIC = "Fisherfolk live here. I can smell it.",
		},
		MERMHOUSE_FISHER = "Fisherfolk live here. I can smell it.",
		MESSAGEBOTTLE = "I wonder if it is a secret menu?",
		MESSAGEBOTTLEEMPTY = "I wonder what vintage used to be in this bottle...",
		MINERHAT = "Aha! Now that is using my head!",
		MINOTAUR = "Stay away!",
		MINOTAURCHEST = "I appreciate the attention to its aesthetic detail.",
		MINOTAURHORN = "I wonder, if ground up into a powder...",
		MOLE =
		 {
		 	ABOVEGROUND = "Are you spying on me?",
		 	HELD = "Do you \"dig\" your new surroundings?",
		 	UNDERGROUND = "Something dwells beneath.",
		 },
		MOLEHAT = "Neat vision!",
		MOLEHILL = "It is a nice hill, but I won't make a mountain of it.",
		MONKEY = "A new species of irritation.",
		MONKEYBARREL = "An absolute madhouse.",
		MONSTERLASAGNA = "What a wasted effort...",
		MONSTERMEAT = "Hmmm, nice marbling...",
		MONSTERMEAT_DRIED = "Could use... better judgment...",
		MOOSE = "I wish you were a bit less moose-y and a lot more goose-y!",
		MOOSEEGG = "I think I'll leave this egg quite alone!",
		MOSQUITO =
		{
			GENERIC = "We disagree on where my blood is best used.",
			HELD = "I do not care to be this close to it! Vile!",
		},
		MOSQUITOSACK = "Ugh! It can only be filled with one thing.",
		MOSQUITOSACK_YELLOW = "Ugh! It can only be filled with one thing.",
		MOSQUITO_POISON = "You not only take, but you also give? Well, no thanks!",
	    MOSSLING = "Looking for your momma? Apologies, but I hope you do not find her.",
		MOUND =
		{
			DUG = "What have I become?",
			GENERIC = "I cannot help wondering what might be down there.",
		},
		MULTITOOL_AXE_PICKAXE = "Oh, I get it! Kind of like a spork!",
		MUSHTREE_MEDIUM = "I have seen the light. Mushrooms do indeed grow on trees.",
		MUSHTREE_SMALL = "Surely mushrooms do not grow on trees here?",
		MUSHTREE_TALL = "Oh, divine tree of mushrooms... what else can you teach me?",
		MUSSEL = "Into my tummy you go! Good bi, valves.",
		MUSSEL_COOKED = "Could use shallots and lemongrass...",
		MUSSEL_FARM =
		{
			GENERIC = "A delightful seafood dinner dwells there.",
			STICKPLANTED = "Stick with me, mussels. I'll take you places!",
		},
		MUSSEL_STICK = "Mussels aren't strong enough to resist this stick!",
		NEEDLESPEAR = "Who shall I stick it to?",
		NIGHTLIGHT = "And I thought fluorescent tubes were a bad invention!",
		NIGHTMAREFUEL = "Who in their right mind would want to fuel MORE nightmares?",
		NIGHTMARELIGHT = "Am I crazy or is this light not helping my situation?",
		NIGHTMARE_TIMEPIECE =
		 {
		 	CALM = "It appears that all is well.",
		 	DAWN = "This nightmare is almost over!",
		 	NOMAGIC = "Magicless.",
		 	STEADY = "Steady on.",
		 	WANING = "Subsiding.",
		 	WARN = "I feel some magic coming on!",
		 	WAXING = "Magic hour!",
		 },
		NIGHTSTICK = "I feel electric!",
		NIGHTSWORD = "This thing slices like a dream!",
		NITRE = "How curious.",
		OBSIDIAN = "Hot rock!",
		OBSIDIANAXE = "You really build up a head of steam swinging this!",
		OBSIDIANCOCONADE = "These are a blast!",
		OBSIDIANFIREPIT =
		{
			EMBERS = "That fire's almost out!",
			GENERIC = "To warm my fingers and roast sausages.",
			HIGH = "Maximum heat!",
			LOW = "It's getting low.",
			NORMAL = "This fire's on fire!",
			OUT = "I like when it's warm and toasty.",
		},
		OBSIDIANMACHETE = "You could overheat swinging this thing too much.",
		OBSIDIANSPEARGUN = "Ready. Aim. Fire.",
		OBSIDIAN_WORKBENCH = "I believe it churns out volcanic doohickeys!",
		OCTOPUSCHEST = "Any cold drinks in there?",
		OCTOPUSKING = "Try not to think about his delicious tentacles...",
		ONEMANBAND = "What a racket!",
		ORANGEAMULET = "Here one minute, gone the next!",
		ORANGEGEM = "I miss oranges...",
		ORANGESTAFF = "When I hold it it makes the world feel... fast.",
		OX = "Here's the beef!",
		PACKIM = "You have a big mouth, mister.",
		PACKIM_FISHBONE = "Picked clean...",
		PALMLEAF = "These would work well in tamales.",
		PALMLEAF_HUT = "The great indoors!",
		PALMLEAF_UMBRELLA = "Singing, not in the rain!",
		PALMTREE =
		{
			BURNING = "Au revoir, tree.",
			BURNT = "Crisp, no?",
			CHOPPED = "Sliced!",
			GENERIC = "A good leaning tree.",
		},
		PANDORASCHEST = "It's quite magnificent.",
		PANFLUTE = "This will be music to something's ears.",
		PAPYRUS = "I could write down my recipes on this.",
		PARROT = "I can't recall any parrot recipes...",
		PEACOCK = "Pea-ka-boo!",
		PENGUIN = "A cool customer.",
		PEROGIES = "Mmmmm, pockets of palate punching pleasure!",
		PETALS = "Great in salads.",
		PETALS_EVIL = "Not so great in salads.",
		PICKAXE = "For those tough to crack nuts.",
		PIGGUARD = "What are you guarding, besides your own deliciousness?",
		PIGGYBACK = "Cochon bag!",
		PIGHEAD =
		{
			BURNT = "Not even the cheeks are left...",
			GENERIC = "Ooh la la, the things I could do with you!",
		},
		PIGHOUSE =
		{
			BURNT = "Mmmm, barbecue!",
			FULL = "Looks like more than three little piggies in there.",
			GENERIC = "Can I blow this down?",
			LIGHTSOUT = "Yoo hoo! Anybody home?",
		},
		PIGKING = "Well, you've got the chops for it.",
		PIGMAN =
		{
			DEAD = "He wouldn't want himself to go to waste, would he?",
			FOLLOWER = "I do have a magnetic presence, do I not?",
			GENERIC = "Who bred you to walk upright like that? Deuced unsettling...",
			GUARD = "Alright, alright, moving along.",
			WEREPIG = "Aggression spoils the meat.",
		},
		PIGSKIN = "Crackling!",
		PIGTENT = "Sure to deliver sweet dreams.",
		PIGTORCH = "I wonder what it means?",
		PIKE_SKULL = "Yeeouch!",
		PINECONE =
		{
			GENERIC = "Pine-scented!",
			PLANTED = "One day you'll be a tree.",
		},
		PIRATEHAT = "I do not throw in with these scoundrels. But I like the hat.",
		PIRATEPACK = "This will straighten my back out.",
		PIRATIHATITATOR =
		{
			BURNT = "It played its last magic trick.",
			GENERIC = "This reminds me of something...",
		},
		PITCHFORK = "Proper farm gear.",
		PLANTMEAT = "Meaty leaves? I'm so confused...",
		PLANTMEAT_COOKED = "Could use less oxymorons...",
		PLANT_NORMAL =
		{
			GENERIC = "The miracle of life!",
			GROWING = "That is it, just a little more...",
			READY = "Fresh-picked produce!",
			WITHERED = "Oh dear me, the crop has failed...",
		},
		POISONHOLE = "I smell trouble...",
		POMEGRANATE = "Wonderful!",
		POMEGRANATE_COOKED = "Could use tahini and mint...",
		POMEGRANATE_SEEDS = "Seedy seeds!",
		POND = "I can't see the bottom...",
		POND_ALGAE = "I can't see the bottom...",
		POOP = "The end result of a fine meal.",
		PORTAL_SHIPWRECKED = "Looks like a rickety ride to someplace...",
		PORTABLECOOKPOT = 
		{
            BURNT = "Nononononono whyyyyyyyyyyyyyyy!?",
            COOKING_LONG = "The flavors need time to meld.",
            COOKING_SHORT = "I threw that meal together!",
            DONE = "Pickup! Oh, old habits...",
            EMPTY = "I would never leave home without it!",
        },
		PORTABLECOOKPOT_ITEM = "What new culinary adventures shall we undertake, old friend?",
		POTTEDFERN = "Nature. Tamed.",
		POWCAKE = "I would not feed this to my worst enemies. Or would I...",
		PRIMEAPE = "You reek of mischief and other kinds of... reek.",
		PRIMEAPEBARREL = "Someone has a hoarding issue.",
		PUMPKIN = "I'm the pumpking of the world!",
		PUMPKINCOOKIE = "I've outdone myself this time.",
		PUMPKIN_COOKED = "Could use some pie crust and nutmeg...",
		PUMPKIN_LANTERN = "Trick 'r' neat!",
		PUMPKIN_SEEDS = "Seed saver!",
		PURPLEAMULET = "I must be crazy to fool around with this.",
		PURPLEGEM = "It holds deep secrets.",
		RABBIT =
		{
			GENERIC = "I haven't had rabbit in awhile...",
			HELD = "Your little heart is beating so fast.",
		},
		RABBITHOLE =
		{
			GENERIC = "Thump twice if you are fat and juicy.",
			SPRING = "What a pity rabbit season has ended.",
		},
		RABBITHOUSE =
		{
			BURNT = "That was no carrot!",
			GENERIC = "Do my eyes deceive me?",
		},
		RAFT = "Better than swimming, I suppose.",
		RAINCOAT = "For a foggy Paris evening.",
		RAINHAT = "Better than a newspaper.",
		RAINOMETER =
		{
			BURNT = "It measures nothing now...",
			GENERIC = "It measures moisture in the clouds.",
		},
		RATATOUILLE = "A veritable village of vegetables!",
		RAZOR = "If only I had aftershave.",
		REDBARREL = "Skull and cross bones is bad, yes?",
		REDGEM = "A deep fire burns within.",
		RED_CAP = "Could use cream and salt... And less poison.",
		RED_CAP_COOKED = "Perhaps I could make a good soup.",
		RED_MUSHROOM =
		{
			GENERIC = "Can't get fresher than that!",
			INGROUND = "It'll be hard to harvest like that.",
			PICKED = "There's nothing left.",
		},
		REEDS =
		{
			BURNING = "The fire took to those quite nicely.",
			GENERIC = "A small clump of reeds.",
			PICKED = "There's nothing left to pick.",
		},
		REFLECTIVEVEST = "Well, it should be hard to lose.",
		RESEARCHLAB = --Science Machine
		{
			BURNT = "That didn't cook very well.",
			GENERIC = "A centre for learning.",
		},
		RESEARCHLAB2 = --Alchemy Machine
		{
			BURNT = "The fire seemed to find it quite tasty.",
			GENERIC = "Oh, the things I'll learn!",
		},
		RESEARCHLAB3 = --Shadow Manipulator
		{
			BURNT = "The darkness is all burnt up.",
			GENERIC = "It boggles the mind.",
		},
		RESURRECTIONSTATUE =
		{
			BURNT = "It won't be much good now.",
			GENERIC = "Part of my soul is within.",
		},
		RESURRECTIONSTONE = "Looks like some sort of ritual stone.",
		ROBIN =
		{
			GENERIC = "Good afternoon, sir or madam!",
			HELD = "It's soft, and surprisingly calm.",
		},
		ROBIN_WINTER =
		{
			GENERIC = "This little fellow seems quite frigid.",
			HELD = "Let me lend you my warmth, feathered friend.",
		},
		ROBOT_PUPPET = "Surely no one deserves such treatment!",
		ROCK = "Don't you go rolling off on me.",
		ROCKS = "Bite-sized boulders.",
		ROCKY = "Hmm... I would have to be careful to not chip a tooth.",
		ROCK_ICE =
		{
			GENERIC = "Brr!",
			MELTED = "It's just liquid now.",
		},
		ROCK_ICE_MELTED = "It's just liquid now.",
		ROCK_LIGHT =
		{
			GENERIC = "The lava has crusted over.",
			LOW = "Like a pie on a proverbial windowsill, it will soon cool.",
			NORMAL = "Nature's fiery fondue pot.",
			OUT = "It has no heat left to give.",
		},
		ROOK = "What a rude contraption.",
		ROOK_NIGHTMARE = "An utter monstrosity!",
		ROPE = "A bit too thick to tie up a roast.",
		ROTTENEGG = "Pee-eew!",
		ROWBOAT = "Free me from the shackles of this island!",
		RUBBLE = "Delicious destruction.",
		RUINSHAT = "Seems unnecessarily fancy.",
		RUINS_BAT = "I could tenderize some meat with this.",
		RUINS_RUBBLE = "Delicious destruction.",
		SAIL = "This should speed things up.",
		SAND = "Lots of tiny, tiny stones.",
		SANDBAG = "I was hoping it would be full of potatoes.",
		SANDBAGSMALL = "Helps keep my dry environment dry.",
		SANDBAG_ITEM = "No potatoes here. Oh well.",
		SANDBAGSMALL_ITEM = "I'll need to set these up before they do anything.",
		SANDHILL = "The sand has formed a small pile.",
		SAND_CASTLE =
		{
			GENERIC = "How calming.",
			SAND = "It looks at home here.",
		},
		SANITYROCK =
		{
			ACTIVE = "It's tugging on my mind.",
			INACTIVE = "The darkness lurks within.",
		},
		SAPLING =
		{
			BURNING = "Those burn quite dramatically.",
			GENERIC = "Those could be key to my continued survival.",
			PICKED = "There is nothing left for me to grasp!",
			WITHERED = "It could use some love.",
		},
		SEAGULL = "I know you're just after my cooking.",
		SEAGULL_WATER = "I know you're just after my cooking.",
		SEASACK = "Wetter is better.",
		SEASHELL = "There's nothing edible left inside.",
		SEASHELL_BEACHED = "What a pretty shell.",
		SEATRAP = "I can trick some delicious crustaceans into this!",

		SEAWEED = "I do not have much experience with this ingredient.",
		SEAWEED_COOKED = "Could use toasted sesame seeds...",
		SEAWEED_DRIED = "Could use Tamari...",
		SEAWEED_PLANTED = "Sea produce!",
		SEEDS = "You may grow up to be delicious one day.",
		SEEDS_COOKED = "Could use smoked paprika...",
		SEWING_KIT = "Not exactly my specialty.",
		SHARKITTEN = "The veal of the sea.",
		SHARK_FIN = "This looks rather bland.",
		SHARK_GILLS = "It won't be needing these anymore.",
		SHARK_TEETHHAT = "Look upon your king!",
		SHARX = "Don't eat me, I'm not properly seasoned!",
		SHOVEL = "I'm not the landscaping type.",
		SIESTAHUT =
		{
			BURNT = "Overcooked.",
			GENERIC = "Comes in handy after a big lunch.",
		},
		SILK = "Is that sanitary?",
		SKELETON = "I have a bone to pick with you.",
		SKELETON_PLAYER = "I have a bone to pick with... m-me?",
		SKULLCHEST = "What an ominous container.",
		SLOTMACHINE = "Maybe I'll win something tasty?",
		SLURPER = "It is not polite to slurp.",
		SLURPERPELT = "Wear this? What in heavens for?",
		SLURPER_PELT = "Wear this? What in heavens for?",
		SLURTLE = "You would flavor a soup nicely. Your shell could be the bowl!",
		SLURTLEHAT = "Be the snail.",
		SLURTLEHOLE = "Yuck!",
		SLURTLESLIME = "Nature giveth, and nature grosseth.",
		SLURTLE_SHELLPIECES = "If only I had crazy glue.",
		SMALLBIRD =
		{
			GENERIC = "Hello food... uh, friend.",
			HUNGRY = "I suppose I could whip something up for you.",
			STARVING = "You look famished!",
		},
		SMALLMEAT = "Fresh protein!",
		SMALLMEAT_DRIED = "Could use a teriyaki glaze...",
		SNAKE = "Stay back or I'll turn you into something savory!",
		SNAKEDEN =
		{
			BURNT = "That smoky aroma always makes me hungry...",
			CHOPPED = "How divine! It has been de-vined.",
			GENERIC = "I do wish those were grapevines...",
		},
		SNAKEOIL = "Why can't you be olive oil?",
		SNAKESKIN = "Would make a haute apron.",
		SNAKESKINHAT = "Tres cool.",
		SNAKE_FIRE = "Only thing worse than a snake is a snake on fire.",
		SNAKE_POISON = "I'll need to butcher you ever so carefully.",
		SNURTLE = "Escar-goodness gracious!",
		SOLOFISH = "You'll make a fine filet.",
		SPEAR = "For kebab-ing.",
		SPEARGUN = "Long-range kebab-ing.",
		SPEARGUN_POISON = "It would make me sick to use this on good meat.",
		SPEAR_OBSIDIAN = "Pull the trigger and voila! Dinner is done!",
		SPEAR_POISON = "It would make me sick to use this on good meat.",
		SPICEPACK = "My bag of chef's tricks!",
		SPIDER =
		{
			DEAD = "Please no rain!",
			GENERIC = "You are not for eating.",
			SLEEPING = "It should make itself a silk pillow.",
		},
		SPIDERDEN = "A spider has to live somewhere, I suppose.",
		SPIDEREGGSACK = "This is probably a delicacy somewhere.",
		SPIDERGLAND = "Alternative medicine.",
		SPIDERHAT = "Well, it is on my head now. Best make the most of it.",
		SPIDERHOLE = "I have no reason to investigate any further.",
		SPIDERQUEEN = "I will not bend the knee to the likes of you!",
		SPIDER_DROPPER = "Ah, the old \"drop from the ceiling and commit violent acts\" act.",
		SPIDER_HIDER = "A spider that turtles!",
		SPIDER_SPITTER = "So many spiders!",
		SPIDER_WARRIOR =
		{
			DEAD = "It knew the risks.",
			GENERIC = "Does this mean you are even more warlike than the others?",
			SLEEPING = "It is having a flashback to the spider war...",
		},
		SPOILED_FISH = "Such a shame...",
		SPOILED_FOOD = "It is a sin to waste food...",
		STAFFLIGHT = "Too much power to hold in one hand.",
		STAFF_TORNADO = "Does nature like being tamed?",
		STALAGMITE = "I always get you upside down with stalactites...",
		STALAGMITE_FULL = "Rocks to be had.",
		STALAGMITE_LOW = "Rocks to be had.",
		STALAGMITE_MED = "Rocks to be had.",
		STALAGMITE_TALL = "Rocks to be had.",
		STALAGMITE_TALL_FULL = "Rocks to be had.",
		STALAGMITE_TALL_LOW = "Rocks to be had.",
		STALAGMITE_TALL_MED = "Rocks to be had.",
		STATUEGLOMMER =
		{
			EMPTY = "Oops.",
			GENERIC = "Must have been a pretty important, uh, thingy...",
		},
		STATUEHARP = "Headless harpsmen.",
		STATUEMAXWELL = "He is literally made of stone.",
		STINGER = "It would really sting to not have a use for this.",
		STRAWHAT = "Now I am on island time.",
		STUFFEDEGGPLANT = "Slightly smoky flesh, savory filling. Ah!",
		STUNGRAY = "Ew, smells like its insides have gone bad.",
		SUNKBOAT = "The sea claims all and does not bargain.",
		SUNKEN_BOAT =
		{
			ABANDONED = "Where did he go?",
			GENERIC = "Hey fella, need a wing?",
		},
		SUNKEN_BOAT_BURNT = "Yikes! That boat had baaaad luck.",
		SUNKEN_BOAT_TRINKET_1 = "Excuse me?",
		SUNKEN_BOAT_TRINKET_2 = "It cannot help me.",
		SUNKEN_BOAT_TRINKET_3 = "Not much of a candle then, is it?",
		SUNKEN_BOAT_TRINKET_4 = "Sea-what?",
		SUNKEN_BOAT_TRINKET_5 = "Not my size.",
		SUPERTELESCOPE = "I knew sharks had an exceptional sense of smell, but their vision!",
		SWEATERVEST = "I feel so much better all of the sudden.",
		SWEET_POTATO = "Starch never tasted so sweet.",
		SWEET_POTATO_COOKED = "Could use touch of curry and creme freche...",
		SWEET_POTATO_PLANTED = "Starch never tasted so sweet.",
		SWEET_POTATO_SEEDS = "People often confuse yams and sweet potatoes. They're very different!",
		SWORDFISH = "A deluxe, but dangerous ingredient!",
		TAFFY = "I hope it never dislodges from my teeth!",
		TALLBIRD = "Leggy.",
		TALLBIRDEGG = "I wonder what its incubation period is?",
		TALLBIRDEGG_COOKED = "Could use sliced fried tomatoes and beans...",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "Oh, you poor egg, you are so cold!",
			GENERIC = "There is activity!",
			HOT = "I hope you don't hardboil.",
			LONG = "This is going to take some dedication.",
			SHORT = "A hatching is in the offing!",
		},
		TALLBIRDNEST =
		{
			GENERIC = "No vacancy here.",
			PICKED = "Empty nest syndrome is setting in.",
		},
		TEENBIRD =
		{
			GENERIC = "You are sort of tall, I guess...",
			HUNGRY = "Teenagers, always hungry!",
			STARVING = "Are you trying to eat me out of base and home?",
		},
		TELEBASE =
		{
			GEMS = "It requires more purple gems.",
			VALID = "It is operational.",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "Where shall we go, thing?",
			GENERIC = "It leads somewhere. And that is what I am afraid of.",
			LOCKED = "It denies my access.",
			PARTIAL = "It requires something additional.",
		},
		TELEPORTATO_BOX = "\"This\" likely connects to a \"that.\"",
		TELEPORTATO_CRANK = "Definitely for a cranking action of some kind.",
		TELEPORTATO_POTATO = "This, I do not even...",
		TELEPORTATO_RING = "One ring to teleport them all!",
		TELEPORTATO_SW_BASE = "It leads somewhere. And that is what I am afraid of.",
		TELEPORTATO_SW_BOX = "\"This\" likely connects to a \"that.\"",
		TELEPORTATO_SW_CRANK = "Definitely for a cranking action of some kind.",
		TELEPORTATO_SW_POTATO = "This, I do not even...",
		TELEPORTATO_SW_RING = "One ring to teleport them all!",
		TELESCOPE = "To see how \"near\" I am to \"far\".",
		TELESTAFF = "Let us take a trip. I am not picky as to where.",
		TENT =
		{
			BURNT = "A good night's sleep, up in smoke.",
			GENERIC = "For roughing it.",
		},
		TENTACLE = "Calamari?",
		TENTACLESPIKE = "This would stick in my throat.",
		TENTACLESPOTS = "Would make a decent kitchen rag.",
		TENTACLE_GARDEN = "If only it were squid and not... whatever it is...",
		TENTACLE_PILLAR = "If only it were squid and not... whatever it is...",
		TENTACLE_PILLAR_ARM = "If only it were squid and not... whatever it is...",
		THATCHPACK = "Thatch you very much!",
		THULECITE = "Thule-... thulec-... it rolls off the tongue, does it not?",
		THULECITE_PIECES = "A pocketful of thule.",
		TIDALPOOL = "It traps snacks.",
		TIDAL_PLANT = "Inedible.",
		TIGERSHARK = "I wish you were a tiger shrimp instead!",
		TOPHAT = "For a night out on the town...?",
		TORCH = "Not great for caramelizing creme brulee, but it will do for seeing.",
		TOUCAN = "You are all nose.",
		TRAILMIX = "Energy food!",
		TRANSISTOR = "Positively charged to get my hands on one!",
		TRAP = "I do not wish to be so tricky, but the dinner bell calls me.",
		TRAP_TEETH = "This is not a cruelty-free trap.",
		TRAP_TEETH_MAXWELL = "I must remember where this is...",
		TRAWLNET = "Ah! The life of a fisherman!",
		TRAWLNETDROPPED =
		{
			GENERIC = "I hope the sea obliges my net with worthy catches.",
			SOON = "It is definitely filling up.",
			SOONISH = "It is close to full.",
		},
		TREASURECHEST =
		{
			BURNT = "Its treasure-chesting days are over.",
			GENERIC = "Treasure!",
		},
		TREASURECHEST_TRAP = "Hmmm, something does not feel right about this...",
		TREECLUMP = "Someone or something does not want me to tree-spass.",
		TRIDENT = "That's one giant fork!",
		TRINKET_1 = "Someone must have really lost their marbles.",
		TRINKET_10 = "Manmade masticators.",
		TRINKET_11 = "He doesn't seem trustworthy to me.",
		TRINKET_12 = "I know of no recipe that calls for this.",
		TRINKET_13 = "I'd prefer switcha... With a piece of duff.",
		TRINKET_14 = "Do they work with paring knives?",
		TRINKET_15 = "I prefer the lute, myself.",
		TRINKET_16 = "This has no business calling itself a plate.",
		TRINKET_17 = "I wouldn't wear this, even if it were my size.",
		TRINKET_18 = "I should be careful with this.",
		TRINKET_19 = "An odd prescription.",
		TRINKET_2 = "I'll hum my own tune.",
		TRINKET_23 = "What an interesting contraption.",
		TRINKET_3 = "Some things can't be undone.",
		TRINKET_4 = "Somewhere there's a lawn that misses you.",
		TRINKET_5 = "A rocketship for ants?",
		TRINKET_6 = "These almost look dangerous.",
		TRINKET_7 = "A distraction of little substance.",
		TRINKET_8 = "Ah, memories of bathing.",
		TRINKET_9 = "Buttons that are not so cute.",
		TROPICALFAN = "Like a cool ocean breeze.",
		MINIFAN = "Like a cool ocean breeze.",
		TROPICAL_FISH = "Catch of today!",
		TRUNKVEST_SUMMER = "Fashionably refreshing.",
		TRUNKVEST_WINTER = "Toasty and trendy.",
		TRUNK_COOKED = "Could use... Hm... I'm stumped...",
		TRUNK_SUMMER = "This meat has a gamey odor.",
		TRUNK_WINTER = "Not the finest cut of meat.",
		TUMBLEWEED = "What secrets do you hold?",
		TUNACAN = "Tuna, packed in oil!",
		TURBINE_BLADES = "Could work in a food processor.",
		TURF_SANDY = "It's like an ingredient for the ground.",
		TURF_ASH = "It's like an ingredient for the ground.",
		TURF_BADLANDS = "It's like an ingredient for the ground.",
		TURF_BEACH = "It's like an ingredient for the ground.",
		TURF_CARPETFLOOR = "Make fists with your toes...",
		TURF_CAVE = "It's like an ingredient for the ground.",
		TURF_CHECKERFLOOR = "It's like an ingredient for the ground.",
		TURF_DECIDUOUS = "It's like an ingredient for the ground.",
		TURF_DESERTDIRT = "It's like an ingredient for the ground.",
		TURF_DIRT = "It's like an ingredient for the ground.",
		TURF_FOREST = "It's like an ingredient for the ground.",
		TURF_FUNGUS = "It's like an ingredient for the ground.",
		TURF_FUNGUS_GREEN = "It's like an ingredient for the ground.",
		TURF_GRASS = "Will I need to cut this?",
		TURF_JUNGLE = "It's like an ingredient for the ground.",
		TURF_MARSH = "It's like an ingredient for the ground.",
		TURF_MEADOW = "It's like an ingredient for the ground.",
		TURF_MUD = "It's like an ingredient for the ground.",
		TURF_ROCKY = "It's like an ingredient for the ground.",
		TURF_SAVANNA = "It's like an ingredient for the ground.",
		TURF_SINKHOLE = "It's like an ingredient for the ground.",
		TURF_SWAMP = "It's like an ingredient for the ground.",
		TURF_UNDERROCK = "It's like an ingredient for the ground.",
		TURF_VOLCANO = "It's like an ingredient for the ground.",
		TURF_WOODFLOOR = "It's like an ingredient for the ground.",
		TURKEYDINNER = "I'm getting sleepy just looking at it!",
		TWIGS = "The start of a good cooking fire.",
		UMBRELLA = "I will try to remember not to open indoors.",
		UNAGI = "More like \"umami\"! Ooooh, mommy!",
		UNIMPLEMENTED = "It appears unfinished.",
		VENOMGLAND = "The worst kind of gland!",
		VINE = "Not a single grape on it...",
		VOLCANO = "Oh, this gets better and better...",
		VOLCANOSTAFF = "One must be careful with this.",
		VOLCANO_ALTAR =
		{
			GENERIC = "It appears to be some kind of altar.",
			OPEN = "It accepts offerings, I think.",
		},
		VOLCANO_ALTAR_BROKEN = "Now there will be no pleasing this thing!",
		VOLCANO_EXIT = "I will not let the door hit me on the way out!",
		BANANAPOP = "Perhaps not my most complicated dish, but no less tasty.",
		BISQUE = "Utterly divine!",
		CEVICHE = "Truly what I live for!",
		SEAFOODGUMBO = "Incredible! Just like Nana used to make!",
		SURFNTURF = "Mwah! Perfection.",
		SHARKFINSOUP = "I used Nana's secret recipe.",
		LOBSTERDINNER = "Being stranded is no reason not to eat well!",
		LOBSTERBISQUE = "I've truly outdone myself!",
		JELLYOPOP = "Hmmm... An interesting flavor.",
		WAFFLES = "Oh, brunch, I have missed you so!",
		WALLYINTRO_DEBRIS = "This leaves a bad taste in my mouth...",
		WALL_HAY =
		{
			BURNT = "That is what I expected.",
			GENERIC = "Calling it a \"wall\" is kind of a stretch.",
		},
		WALL_HAY_ITEM = "Hay look, a wall!",
		WALL_LIMESTONE = "Zesty wall.",
		WALL_LIMESTONE_ITEM = "Citrus-infused walls!",
		WALL_RUINS = "Look at the carvings...",
		WALL_RUINS_ITEM = "The stories these tell... fascinating...",
		WALL_STONE = "Good stone work.",
		WALL_STONE_ITEM = "I feel secure behind this.",
		WALL_WOOD =
		{
			BURNT = "Wood burns. Who knew? ...Me!?",
			GENERIC = "Putting down stakes.",
		},
		WALL_WOOD_ITEM = "Delivers a rather wooden performance as a wall.",
		WALRUS = "They move faster than you'd think.",
		WALRUSHAT = "Smells a little musty...",
		WALRUS_CAMP =
		{
			EMPTY = "Yes, vacancy.",
			GENERIC = "Some outdoorsy types made this.",
		},
		WALRUS_TUSK = "It won't be needing this anymore.",
		WARG = "Leader of the pack.",
		WASPHIVE = "Not your average bees.",
		WATERMELON = "Despite its name, it is mostly filled with deliciousness!",
		WATERMELONHAT = "Aaaahhhhhh sweet relief...",
		WATERMELONICLE = "I feel like a kid again!",
		WATERMELON_COOKED = "Could use mint and feta...",
		WATERMELON_SEEDS = "More watermelon, anyone?",
		WEBBERSKULL = "Stop staring at me or I'll bury you!",
		WETGOOP = "I am thankful my sous chefs are not around to witness this abomination...",
		WHALE_BLUE = "Why the long fishface?",
		WHALE_BUBBLES = "What the deuce?",
		WHALE_CARCASS_BLUE = "That is quite a lot of dead whale.",
		WHALE_CARCASS_WHITE = "That is quite a lot of dead whale.",
		WHALE_WHITE = "I have seen the devil!",
		WILDBORE = "Does not look like a placid piggy.",
		WILDBOREHOUSE = "How wild can they be if they live in houses?",
		WINTERHAT = "I know when to don this, and not a minute sooner.",
		WINTEROMETER =
		{
			BURNT = "Foresight is 0/0.",
			GENERIC = "Splendid. I should like to know when the worm is going to turn.",
		},
		WOODLEGS_CAGE = "Bonjour garcon, can you tell me... oh... I see...",
		WOODLEGS_KEY1 = "Some sort of menacing key.",
		WOODLEGS_KEY2 = "Some sort of menacing key.",
		WOODLEGS_KEY3 = "Some sort of menacing key.",
		VOLCANO_SHRUB = "I wonder what it used to be?",
		ROCK_OBSIDIAN = "Blast! I cannot mine it!",
		ROCK_CHARCOAL = "Barbecued.",
		DRAGOONDEN = "I do not like these fellows one bit.",
		WORM =
		{
			DIRT = "Dirty.",
			PLANT = "I see nothing amiss here.",
			WORM = "Worm!",
		},
		WORMHOLE =
		{
			GENERIC = "That is no ordinary tooth-lined hole in the ground!",
			OPEN = "Am I really doing this?",
		},
		WORMHOLE_LIMITED = "These things can look worse?",
		WORMLIGHT = "Radiates deliciousness.",
		YELLOWAMULET = "Puts some pep in my step!",
		YELLOWGEM = "I miss lemons...",
		YELLOWSTAFF = "I could stir a huge pot with this thing!",

		ARMORCACTUS = "If the enemies are pricked half as much as I was making it, it's worth it.",
		BIGFISHINGROD = "A prime ingredient-catcher.",
		--BOOK_METEOR = "There's not a single recipe to be found within.",
		BRAINJELLYHAT = "I can feel inspiration seeping into me! Wait, that's brain juice.",
		BUOY = "A beacon to light my way.",
		COCONUT_HALVED = "Delectable.",
		COFFEEBOT = "What a delight!",
		CRATE = "I hope a rations shipment lies within.",
		DEPLETED_BAMBOOTREE = "Perhaps one day it will return.",
		DEPLETED_BUSH_VINE = "It's all used up... for now.",
		DEPLETED_GRASS_WATER = "Will you recover soon, little tuft?",
		DOYDOYEGG_COOKED = "Bon appetit!",
		DRAGOONEGG = "What use is an egg that you cannot eat?",
		DRAGOONHEART = "It is lifeless, yet surprisingly hot to touch.",
		DRAGOONSPIT = "Dangerous and disgusting!",
		DUG_BUSH_VINE = "Now I can put it wherever I want.",
		FRESHFRUITCREPES = "Is this not a thing of beauty?",

		KRAKEN = "I can't take the heat! Get me out of this kitchen!",
		KRAKENCHEST = "What treasures do you hold?",
		KRAKEN_TENTACLE = "My poisons do nothing!",
		MAGIC_SEAL = "It's practically dripping with magicks.",
		MAGMAROCK_FULL = "This rocks.",
		MAGMAROCK_GOLD_FULL = "Wonder if I could harvest goldleaf from this?",
		MALE_PUPPET = "Free him!",
		MANRABBIT_TAIL = "The texture is exceptionally comforting.",
		MARBLETREE = "How supremely unnatural!",
		MONKEYBALL = "Seems like a waste of a good banana. Cute though.",
		MONSTERTARTARE = "This is a culinary abomination. I'm appalled.",
		MUSSELBOUILLABAISE = "The artistry in this dish lifts my spirits.",
		MYSTERYMEAT = "That can't possibly be edible.",
		OXHAT = "Much more waterproof than a chef's hat.",
		OX_FLUTE = "It plays a lilting tune.",
		OX_HORN = "A lovely souvenir from a once powerful beast.",
		PANDORASCHEST = "It's quite magnificent.",
		PARROT_PIRATE = "Such an amiable creature. Friends?",
		PEG_LEG = "Why on earth do I have this?",
		PERD = "A fellow with excellent taste.",
		PIRATEGHOST = "He may be a nice fellow, but I don't intend to find out.",
		RAWLING = "Your hair needs a brushing.",
		RELIC =
		{
			BROKEN = "A piece of culinary history has been lost.",
			GENERIC = "Ancient kitchenware.",
		},
		RESEARCHLAB4 =
		{
			BURNT = "Nothing but ashes.",
			GENERIC = "I won't even try to pronounce it...",
		},

		ROOK_NIGHTMARE = "What a monstrosity!",
		RUBBLE = "Delicious destruction.",
		RUINS_RUBBLE = "Delicious destruction.",
		SAIL_STICK = "Might make a good stirring stick.",
		SHADOWSKITTISH_WATER = "Oh dear.",
		SHARKITTENSPAWNER =
		{
			GENERIC = "That seems like something I should steer clear of.",
			INACTIVE = "A pile of sand like any other.",
		},
		SHIPWRECKED_ENTRANCE = "Bonjour!",
		SHIPWRECKED_EXIT = "Au revoir.",
		SNAKESKINSAIL = "Perhaps I'll sail to a land of spices.",
		SPEAR_LAUNCHER = "Now we're cooking!",
		SWEETPOTATOSOUFFLE = "Food that feeds the soul and nourishes the body.",
		SWIMMINGHORROR = "No need to come any closer, sir.",
		TIGEREYE = "Well, it's edible.",
		TRINKET_20 = "It looks expectant.",
		TRINKET_21 = "I'm afraid I won't fit.",
		TRINKET_22 = "Perfect for a candlelit dinner!",
		TURF_CAVE = "It's like an ingredient for the ground.",
		TURF_DECIDUOUS = "It's like an ingredient for the ground.",
		TURF_FUNGUS_RED = "It's like an ingredient for the ground.",
		TURF_MAGMAFIELD = "It's like an ingredient for the ground.",
		TURF_ROAD = "It's like an ingredient for the ground.",
		TURF_SNAKESKINFLOOR = "It's like an ingredient for the ground.",
		TURF_TIDALMARSH = "It's like an ingredient for the ground.",
		TWISTER = "Nature's blender!",
		TWISTER_SEAL = "I bet it's delicious, but I just don't have the heart to find out.",
		VOLCANO_ALTAR_TOWER = "Mon dieu!",
		WATERYGRAVE = "Let's open her up.",
		WHALE_TRACK = "My quarry is near!",
		WILBUR_CROWN = "Finally, the recognition I deserve. Does it get any bigger?",
		WILBUR_UNLOCK = "Salutations, my good simian fellow!",
		WILDBOREHEAD = "Is someone making a gourmet jerky?",
		WIND_CONCH = "Oh, how I'm homesick for conch snacks.",
		WOODLEGSBOAT = "Is that as fast as it goes?",
		WOODLEGSHAT = "It makes me feel... dangerous.",
		WOODLEGSSAIL = "I'm ready to set sail!",
		WRECK = "It sails no more.",
		CALIFORNIAROLL = "Classic Japanese fusion!",
	},
	DESCRIBE_GENERIC = "It is what it is...",
	DESCRIBE_SMOLDERING = "I fear that that is about to cook itself.",
	DESCRIBE_TOODARK = "I cannot see a thing!",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "Fresh! Err... perhaps too fresh.",
	},
}
