return {
	ACTIONFAIL =
	{
		REPAIRBOAT =
		{
			GENERIC = "Ugh, why would I do that now?",
		},
		SHAVE =
		{
			AWAKEBEEFALO = "Maybe I should wait for it to be distracted...",
			GENERIC = "Nu-uh.",
			NOBITS = "It's already shaved!",
		},
		WRITE =
        {
            GENERIC = "I can't write on it.",
        },
		RUMMAGE =
        {   
            GENERIC = "I can'tttttt.", 
        },
		COOK =
        {
            GENERIC = "I'm not too big on cooking.",
            TOOFAR = "It's all the way over thereeeee!",
        },
		STORE =
		{
			GENERIC = "It's full already.",
			NOTALLOWED = "They won't let me.",
		},
		CHANGEIN =
        {
            GENERIC = "Nah, too much effort.",
            BURNING = "That's way better than some dumb dresses!",
        },
        GIVE =
        {
            DEAD = "They won't fully appreciate my gift.",
            SLEEPING = "Not right now. It's sleeping.",
            BUSY = "It's busyyyy.",
        },
        TEACH =
        {
            KNOWN = "I knowwwww that already, geez!",
            CANTLEARN = "Ugh, whatever, I didn't wanna know anyway.",
        },
	},
	ACTIONFAIL_GENERIC = "I caaaan't!",
	ANNOUNCE_MAGIC_FAIL = "Why won't it work!!",
	ANNOUNCE_ADVENTUREFAIL = "You win THIS time, Maxwell.",
	ANNOUNCE_BOOMERANG = "Stupid boomerang!",
	ANNOUNCE_CHARLIE = "I'm not afraid of you!",
	ANNOUNCE_CHARLIE_ATTACK = "OUCH! You jerk!",
	ANNOUNCE_COLD = "The cold! It burns!",
	ANNOUNCE_HOT = "The heat is too intense!",
	ANNOUNCE_DUSK = "Night is coming. I need fire!",
	ANNOUNCE_WORMS = "I do NOT wanna see what made that sound!",
	ANNOUNCE_EAT =
	{
		GENERIC = "Yum!",
		PAINFUL = "Ugh! Nasty!",
		SPOILED = "That tasted terrible!",
		STALE = "That was kinda gross.",
		INVALID = "How would I even eat that!",
		YUCKY = "Eeeew, no way!",
	},
	ANNOUNCE_NOSLEEPONFIRE = "It's just the collapsing that concerns me.",
	ANNOUNCE_NODANGERSIESTA = "It's not time for a siesta, it's time for fighting!",
	ANNOUNCE_NONIGHTSIESTA = "I couldn't get comfortable there.",
	ANNOUNCE_NONIGHTSIESTA_CAVE = "I'd really rather be inside.",
	ANNOUNCE_NOHUNGERSIESTA = "I can't take a siesta while my tummy is grumbling!",
	ANNOUNCE_SHELTER = "You're good for something besides burning after all.",
	ANNOUNCE_BURNT = "I wish I'd let it go up in flames...",
	ANNOUNCE_TOOL_SLIP = "Still got my lighter!",
	ANNOUNCE_DAMP = "Uh oh!",
	ANNOUNCE_WET = "This could be bad!",
	ANNOUNCE_WETTER = "I hate it!",
	ANNOUNCE_SOAKED = "Ugh, this is the WORST!",
	ANNOUNCE_HOUNDS = "Show yourself!",
	ANNOUNCE_HUNGRY = "I need food!",
	ANNOUNCE_HUNT_BEAST_NEARBY = "I'll find you!",
	ANNOUNCE_HUNT_LOST_TRAIL = "Ohh... he got away.",
	ANNOUNCE_HUNT_LOST_TRAIL_SPRING = "Boooo, I lost track of him in the mud.",
	ANNOUNCE_ACCOMPLISHMENT= "Move, arrow! MOVE!",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "I DID IT!",	
	ANNOUNCE_LIGHTFIRE =
	{
		[1] = "Teehee!",
		[2] = "Pretty!",
		[3] = "Oops!",
		[4] = "I made a fire!",
		[5] = "Burn!",
		[6] = "I can't help myself!",
	},
	ANNOUNCE_PECKED = "No! Bad birdy!",
	ANNOUNCE_TORCH_OUT = "My precious light is gone!",
	ANNOUNCE_FAN_OUT = "Stupid thing broke!",
    ANNOUNCE_COMPASS_OUT = "Arrgh the needle is stuck!",
	ANNOUNCE_WORMHOLE = "I'll have to burn these clothes!",
	ANNOUNCE_TRAP_WENT_OFF = "Aah!",
    ANNOUNCE_CRAFTING_FAIL = "I'm missing something.",
    ANNOUNCE_QUAKE = "That sound probably doesn't mean good things.",
    ANNOUNCE_NODANGERSLEEP = "No time for sleep, there's fighting to do!",
    ANNOUNCE_NOHUNGERSLEEP = "My tummy is grumbling, I can't sleep!",
    ANNOUNCE_FREEDOM = "I'm free! Time for fires!",
    ANNOUNCE_RESEARCH = "That was useful, even if it didn't have anything about fires.",
    ANNOUNCE_NO_TRAP = "Like lighting a barrel of fish on fire.",
    ANNOUNCE_HIGHRESEARCH = "So much information!",
    ANNOUNCE_THORNS = "Ouch!",
    ANNOUNCE_NODAYSLEEP_CAVE = "Too spooky down here to sleep.",
    ANNOUNCE_BEES = "Aaaah! Pokey bugs!",
    ANNOUNCE_KNOCKEDOUT = "Argh, my little head!",
    ANNOUNCE_LOWRESEARCH = "Boo, that was boring.",
    ANNOUNCE_DEERCLOPS = "That sounded like a big mean monster man!",
    ANNOUNCE_MOSQUITOS = "Get away, you bloodsucking jerks!",
    ANNOUNCE_NODAYSLEEP = "I won't go inside when there's a great ball of fire in the sky.",
    ANNOUNCE_INSUFFICIENTFERTILIZER = "It looks slightly happier.",
	ANNOUNCE_CANFIX = "\nI think I can fix this!",
	ANNOUNCE_LIGHTNING_DAMAGE_AVOIDED = "I'm safe from the sky-fire.",
	ANNOUNCE_VOLCANO_ERUPT = "The fiery mountain speaks!",
	ANNOUNCE_TREASURE = "\"X\" marks the spot!",
	ANNOUNCE_CRAB_ESCAPE = "Shoot! It got away!",
	ANNOUNCE_SHARX = "Hey! Stop splashing around out there!",
	ANNOUNCE_MORETREASURE = "This day just got better.",
	ANNOUNCE_OTHER_WORLD_TREASURE = "This doesn't look like a map of this place.",
	ANNOUNCE_OTHER_WORLD_PLANT = "It won't grow. Maybe I should burn it instead.",
	ANNOUNCE_MAPWRAP_WARN = "That fog looks pretty dense.",
	ANNOUNCE_MAPWRAP_LOSECONTROL = "Uh oh. Which way was I going again?",
	ANNOUNCE_MAPWRAP_RETURN = "I couldn't see a thing in there!",
	ANNOUNCE_MESSAGEBOTTLE =
	{
		"The message is faded. I can't read it.",
	},
	ANNOUNCE_BOAT_DAMAGED = "My boat is wounded!",
	ANNOUNCE_BOAT_SINKING = "I'm going down!",
	ANNOUNCE_BOAT_SINKING_IMMINENT = "Goodbye cruel world!",
	ANNOUNCE_ENTER_DARK = "Where'd I put my lighter!?",
	ANNOUNCE_ENTER_LIGHT = "Oh, I can see! I thought I'd gone blind.",
	ANNOUNCE_INV_FULL = "I can't carry anymore!",
	ANNOUNCE_TRAWL_FULL = "My trawl is ready to reel in.",
	ANNOUNCE_UNIMPLEMENTED = "That looks dangerous! Burn it!",
	ANNOUNCE_WAVE_BOOST = "Weeee!",
	ANNOUNCE_WHALE_HUNT_BEAST_NEARBY = "Ooo, there's a big fishie nearby.",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL = "Grr, I lost it!",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL_SPRING = "The water's too rough to see!",

	BATTLECRY =
	{
		GENERIC = "It's you or me!",
		PIG = "Stupid pig!",
		PREY = "Get over here!",
		SPIDER = "Grrrrar!",
		SPIDER_WARRIOR = "Ew, kill iiiit!",
	},
	COMBAT_QUIT =
	{
		GENERIC = "That's what I thought!",
		PIG = "Get back here, pork chop!",
		PREY = "I'll get you next time!",
		SPIDER = "Bleh. I'll kill him later.",
		SPIDER_WARRIOR = "Not so tough now!",
	},
	
	DESCRIBE =
	{
		BIGFISHINGROD = "It's big.",
		DEVTOOL = "It's asking to be burned.",
		DEVTOOL_NODEV = "It's asking to be burned.",
		HOUNDFIRE = "I need it!",
		INVENTORYGRAVE = "Not everyone has what it takes out here.",
		INVENTORYMOUND = "Not everyone has what it takes out here.",
		MANDRAKE_COOKED = "The fire made this plant guy a lot quieter.",
		ROCK = "It's, like, a rock.",
		SLURPERPELT = "If I burnt it it would smell terrible. More terrible.",
		TREECLUMP = "Moooooooooooooove.",
		TURF_DESERTDIRT = "The ground is boring.",
		TURF_FUNGUS_GREEN = "The ground is boring.",
		TURF_FUNGUS_RED = "The ground is boring.",
		TURF_SWAMP = "Swampy.",
		WATERMELON_SEEDS = "I could grow them, but that sounds boring.",
		WORMHOLE_LIMITED = "It's almost burned out.",
		GLOMMER = "It's fuzzy! And slimy...",
        GLOMMERFLOWER = 
        {
        	GENERIC = "Why does everything have to be a flower?!",
        	DEAD = "I wonder if it burns...",
        },
        GLOMMERWINGS = "They're so small!",
        GLOMMERFUEL = "It's goopy and weird.",
        BELL = "Is it New Year's Eve? Are there FIREWORKS?!",
        MOOSE_NESTING_GROUND = "Ugh, it smells like bird butts!",
        STATUEGLOMMER = 
        {	
        	GENERIC = "Is that supposed to be something?",
        	EMPTY = "Looks about the same.",
    	},
		WEBBERSKULL = "It's not myyy way, but a burial will have to do.",
		MOLE =
		{
			HELD = "Out of the ground, into the fire.",
			UNDERGROUND = "Hiding from the light, huh?",
			ABOVEGROUND = "Coming up for a peek!",
		},
		MOLEHILL = "It burrows away from the sun's skyfire. Unnatural.",
		MOLEHAT = "I'm not sure about this...",
		NIGHTSTICK = "It'd be way cooler if it was on fire...",
		RABBITHOUSE=
		{
			GENERIC = "Ugh. Stupid rabbits.",
			BURNT = "Ha! Good result.",
		},
		TURF_DECIDUOUS = "The ground is boring.",
		TURF_SANDY = "The ground is boring.",
		TURF_BADLANDS = "The ground is boring.",
		BEARGER = "Whoa! Niiiice bear...",
		BEARGERVEST = "It's like swimming in fur.",
		ICEPACK = "Fuzzy backpack!",
		MOONROCKNUGGET = "Just another rock to me.",
		ROCK_MOON = "Just another rock to me.",
		BEARGER_FUR = "It's fur all the way down.",
		FURTUFT = "Black and white and fuzzy all over!",
		BIGFOOT = "What in the world!",
		BONESHARD = "I don't think they make good tinder.",
		BUZZARD = "Your neck is gross.",
		CACTUS = 
		{
			GENERIC = "Spines! My weakness! How did you know?",
			PICKED = "We'll call it a tie.",
		},
		CACTUS_MEAT_COOKED = "It seems fine now.",
		CACTUS_MEAT = "It still looks dangerous.",
		CACTUS_FLOWER = "Yet another flower.",
		COLDFIRE =
		{
			EMBERS = "Uh oh. It's almost gone!",
			GENERIC = "I like fire of all kinds.",
			HIGH = "BURN! BURN FASTER! AND BLUER!",
			LOW = "This fire is small and boring.",
			NORMAL = "Burn!",
			OUT = "Awww. It's all over.",
		},
		CATCOON = "Here, kitty!",
		CATCOONDEN = 
		{
			GENERIC = "I wouldn't burn it while someone lives there.",
			EMPTY = "It's all dried up and ready for burning.",
		},
		CATCOONHAT = "Cuddly hat.",
		COONTAIL = "I've kept stranger things than this.",
		COOKPOT =
		{
			COOKING_LONG = "The fire still has quite a bit of work to do.",
			COOKING_SHORT = "The fire is doing its thing!",
			DONE = "I'm glad I cooked with fire.",
			EMPTY = "I could put food in it and fire underneath it.",
			BURNT = "At least it went out in a blaze of glory.",
		},
		EYEBRELLAHAT =	"If I wear it, I don't have to look at it...",
		ARMORDRAGONFLY = "Yay! More FIRE!!!",
		DRAGON_SCALES = "Oooooooh! I LIKE these.",
		DRAGONFLYCHEST = "I'm not sure why you'd want something that DOESN'T burn...",
		DECIDUOUSTREE = 
		{
			BURNING = "YES! BURN!",
			BURNT = "I wish it was still burning.",
			CHOPPED = "Burning it would've been better.",
			GENERIC = "I bet it would burn well.",
			POISON = "A fire would set'em straight.",
		},
		ACORN_COOKED = "Looks like you won't become a tree after all.",
		BIRCHNUTDRAKE = "Aaah! Set it on fire!",
		FARMPLOT =
		{
			GENERIC = "Sigh. It's a pile of dirt.",
			GROWING = "Hurry up, dirtpile. Feed me!",
			NEEDSFERTILIZER = "Stupid thing needs poop.",
			BURNT = "It was a nice finale.",
		},
		COLDFIREPIT =
		{
			EMBERS = "Uh oh. It's almost gone!",
			GENERIC = "I could watch it for hours, even though it's cold.",
			HIGH = "BURN! BURN FASTER! AND BLUER!",
			LOW = "This fire is small and boring. And blue.",
			NORMAL = "Burn!",
			OUT = "I should make the fire come back.",
		},
		FIRESUPPRESSOR = 
		{	
			ON = "I wish you'd shut your lid and stop putting out fires.",
			OFF = "And stay off!",
			LOWFUEL = "Almost out.",
		},
		ICEHAT = "It's a real damper on my mood.",
		LIGHTNINGGOAT = 
		{
			GENERIC = "Bouncy goat.",
			CHARGED = "You're crazy!",
		},
		LIGHTNINGGOATHORN = "I can hear the lightning if I hold it to my ear.",
		GOATMILK = "It's fuzzy with electricity. Yuck.",
		MEATRACK =
		{
			DONE = "It's ready!",
			DRYING = "Come on meat, dry already!",
			DRYINGINRAIN = "Forget the rain! Dry!",
			GENERIC = "I want to hang some meat!",
			BURNT = "Maybe the fire wasn't the best drying method...",
		},
		MERMHEAD = 
		{
			GENERIC = "That's what you get for being so stinky!",
			BURNT = "Double whammy!",
		},
		MERMHOUSE = 
		{
			GENERIC = "No one would care if this burned down.",
			BURNT = "It's true, no one cares.",
		},
		FLOWERSALAD = "I'd rather eat a bowl of flames.",
        ICECREAM = "Well, soooometimes cold things are okay.",
        WATERMELONICLE = "Why would you freeze a fruit when you could burn it?",
        TRAILMIX = "Crunch crunch crunch.",
        HOTCHILI = "Now that's my kind of heat!",
        GUACAMOLE = "Holy moley, that's tasty!",
		MOOSE = "What in the world...",
		MOOSEEGG = "It's huuuuge!",
		MOSSLING = "Its feathers are frazzled.",
		FEATHERFAN = "I dunno... it could put out some fires...",
		TROPICALFAN = "I dunno... it could put out some fires...",
		GOOSE_FEATHER = "So snuggly!",
		STAFF_TORNADO = "Always whirling! Swirling towards destruction!",
		PIGHEAD = 
		{	
			GENERIC = "I guess I have it alright.",
			BURNT = "It can always get worse, I guess.",
		},
		PIGHOUSE =
		{
			FULL = "He's doing pig things in there.",
			GENERIC = "These pigs have questionable taste in architecture.",
			LIGHTSOUT = "You jerk! Let me in!",
			BURNT = "Nice redecorating job!",
		},
		FERTILIZER = "A bucket full of nasty.",
		RAINOMETER = 
		{	
			GENERIC = "Rain is the anti-fire. Boo!",
			BURNT = "Take that, rain!",
		},
		RAINCOAT = "This'll do the trick.",
		RAINHAT = "Anything to keep the water away.",
		RESEARCHLAB = 
		{	
			GENERIC = "Even I don't know everything... yet.",
			BURNT = "There's no learning from that now.",
		},
		RESEARCHLAB2 = 
		{
			GENERIC = "Even I don't know everything... yet.",
			BURNT = "There's no learning from that now.",
		},
		RESEARCHLAB3 = 
		{
			GENERIC = "A dark and powerful energy radiates from it.",
			BURNT = "Now it's dark and not very powerful.",
		},
		RESEARCHLAB4 = 
		{
			GENERIC = "I can use the hat like a cauldron!",
			BURNT = "Double, double toil and... oh. It's burned.",
		},
		RESURRECTIONSTATUE = 
		{
			GENERIC = "That's my insurance policy.",
			BURNT = "My policy was canceled.",
		},
		ROCK_ICE = 
		{
			GENERIC = "I don't think there's any way it'd burn.",
			MELTED = "As useless as water ever was.",
		},
		ROCK_ICE_MELTED = "As useless as water ever was.",
		ICE = "Chilly.",
        REFLECTIVEVEST = "Vests are so in.",
		HAWAIIANSHIRT = "I wonder if it'd burn as nicely as actual flowers do.",
		TENT = 
		{
			GENERIC = "I got all the badges in Girl Scouts.",
			BURNT = "Well, I've still got my badges.",
		},
		SIESTAHUT = 
		{
			GENERIC = "They taught us how to make these in Girl Scouts.",
			BURNT = "I always set them on fire.",
		},
		TRANSISTOR = "Electrical doo-dah, doo-dah.",
		TREASURECHEST = 
		{
			GENERIC = "It's a trunk for my junk.",
			BURNT = "The trunk burned nicely.",
		},
		TUMBLEWEED = "It looks highly flammable.",
		GRASS_UMBRELLA = "Pretty as can be!",
		PALMLEAF_UMBRELLA = "It's so nice!",
		UNIMPLEMENTED = "It's not finished. But I bet it still burns.",
		WALL_HAY = 
		{	
			GENERIC = "That looks so flammable!",
			BURNT = "It was flammable!",
		},
		WALL_WOOD = 
		{
			GENERIC = "That could totally catch on fire.",
			BURNT = "It did catch on fire!",
		},
		WARG = "You're a big mean jerk!",
		WATERMELON = "I once knew a melon named Walter. He was a jerk.",
		WATERMELON_COOKED = "Warm, sweet, juicy Walter.",
		WATERMELONHAT = "Well, that's one use for this fruit.",
		WINTEROMETER = 
		{
			GENERIC = "It would be better if it measured fire.",
			BURNT = "If you'd measured fire, maybe you woulda been prepared!",
		},
		HOME = "I'm gonna burn it.",
		HOMESIGN = 
		{
			GENERIC = "Less reading! More burning!",
			UNWRITTEN = "I should burn something into it.",
			BURNT = "Hahaha, yesss!",
		},
		BEEBOX =
		{
			READY = "Yay! I can steal honey!",
			FULLHONEY = "Yay! I can steal honey!",
			GENERIC = "Come on fat bees, make me honey!",
			NOHONEY = "Nothing to see here.",
			SOMEHONEY = "Patience.",
			BURNT = "Smoked you out!",
		},
		LIVINGTREE = "It might be alive, but it'll still burn.",
		ICESTAFF = "Booooring.",
		WORMLIGHT = "Light without fire. Unnatural.",
		WORMLIGHT_LESSER = "It feels like grandma's hands.",
		WORM =
		{
		    PLANT = "Light without fire. Unnatural.",
		    DIRT = "Does dirt normally move around?",
		    WORM = "It's so furry!",
		},
		WORMLIGHT_PLANT = "Light without fire. Unnatural.",
		EEL = "I don't like the look it's giving me!",
		EEL_COOKED = "Fire improves everything.",
		UNAGI = "You can make it fancy but it's still an eel.",
		EYETURRET = "I wish it lit stuff on fire.",
		EYETURRET_ITEM = "It's no good until I place it.",
		MINOTAURHORN = "I wonder if the rings are an indication of age.",
		MINOTAURCHEST = "I want big horns like that!",
		THULECITE_PIECES = "This Thulecite crumbled to pieces.",
		POND = "This pond will definitely not ignite. How dull.",
		POND_ALGAE = "It must need a lot of water.",
		GREENSTAFF = "It won't start a fire but I guess it's still useful.",
		POTTEDFERN = "I'd rather burn them.",

		BOOK_BIRDS = "Less reading, more burning!",
		BOOK_TENTACLES = "Looks like kindling to me!",
		BOOK_GARDENING = "Ughh, who cares?",
		BOOK_BRIMSTONE = "That's my favorite book!",
		BOOK_SLEEP = "Bo-oring!",
		LUCY = "We could be good friends, you and I.",
		BALLOONS_EMPTY = "I could fill them with flammable gas.",
		SPEAR_WATHGRITHR = "I prefer a flame, but to each her own.",
		WAXWELLJOURNAL = "Would make a great bedtime story... for nightmares!",

		ABIGAIL_FLOWER = 
		{ 
			GENERIC = "Looks flammable.",
			LONG = "It's just asking for a burning.",
			MEDIUM = "Ugh, it's weird!",
			SOON = "Burning is still an option.",
			HAUNTED_POCKET = "It's burning a hole in my pocket! Heh.",
			HAUNTED_GROUND = "I don't want to mess with that.",
		},

		THULECITE = "I don't think it would burn.",
		ARMORRUINS = "Not sure I want to wear this.",
		RUINS_BAT = "This will keep the nasties at bay.",
		RUINSHAT = "It seems like there's something flowing through it.",
		NIGHTMARE_TIMEPIECE = --Keeps track of the nightmare cycle
		{
			CALM = "Looks normal to me.",	--Calm phase
			WARN = "It's warning me.",	--Before nightmare
			WAXING = "The fuel is coming to life!", --Nightmare Phase first 33%
			STEADY = "It's almost humming.", --Nightmare 33% - 66%
			WANING = "I think it's turning off.", --Nightmare 66% +
			DAWN = "I guess it's nearly over.", --After nightmare
			NOMAGIC = "I don't think it's working.", --Place with no nightmare cycle.
		},
		BISHOP_NIGHTMARE = "Ahhh!",
		ROOK_NIGHTMARE = "It has a nasty smile.",
		KNIGHT_NIGHTMARE = "It looks pretty worn down.",
		MINOTAUR = "Poor thing. Trapped in this maze.",	--Monster in labyrinth
		SPIDER_DROPPER = "They come from above.",	--White spider that comes from the roof
		NIGHTMARELIGHT = "Light without fire is unnatural.",	--Lights that activate during nightmare.
		GREENGEM = "This one feels really light.",
		RELIC = "I guess someone lived here before.",	--Fixed relic
		RUINS_RUBBLE = "I could probably fix that up.",	--Broken relic
		MULTITOOL_AXE_PICKAXE = "It's so useful!",	--Works as axe and pickaxe
		ORANGESTAFF = "It gives me a headache.",	--Teleports player.
		YELLOWAMULET = "It seems to absorb the darkness around it.",	--Emits light, player walks faster.
		GREENAMULET = "I feel my mind open when I wear it.",	--Reduce cost of crafting

		SLURPER = "Do they have little fires in their bellies?",
		SLURPER_PELT = "Eeewwwww, it's still alive!",
		ARMORSLURPER = "Oh, ick! Ick! Ick! Ick! Eeeeeewwwwww!",
		ORANGEAMULET = "It picks up my burning materials for me!",
		YELLOWSTAFF = "It's magical.",
		YELLOWGEM = "It sparkles.",
		ORANGEGEM = "This one makes my fingers tingle.",
		PALMTREE =
        {
			BURNING = "Wooow! So much fire!",
			BURNT = "A major improvement.",
			CHOPPED = "That took a few swings.",
			GENERIC = "You have a curious lack of branches.",
		},
		TELEBASE = 
		{
			VALID = "I can feel the magic!",
			GEMS = "It needs something more.",
		},
		GEMSOCKET = 
		{
			VALID = "I wonder how they hover?",
			GEMS = "It's so empty!",
		},
		STAFFLIGHT = "It's so beautiful!",

        LIGHTER = "It's my lucky lighter!",


        ANCIENT_ALTAR =
        {
        	WORKING = "Oooo! An afterlife intercom.",
        	BROKEN = "The dead can't get through here.",
        },  
        ANCIENT_ALTAR_BROKEN = "The dead can't get through here.",

        ANCIENT_STATUE = "Drat, won't burn.",

        LICHEN = "A gross, crusty plant.",
		CUTLICHEN = "Blah, tastes like sawdust.",

        CAVE_BANANA = "Bananas!",
        CAVE_BANANA_COOKED = "Yum!",
        CAVE_BANANA_BURNT = "That's all I wanted!",
        CAVE_BANANA_TREE = "Looks burnable!",
        ROCKY = "We don't have much in common.",

        BLUEAMULET = "Boo to this.",
		PURPLEAMULET = "Has science gone too far?",
		TELESTAFF = "It's quite a rush to use.",
		MINERHAT = "It's not real fire, but it's still pretty fun.",
		MONKEY = "Joke's on you! I can burn this poo.",
		MONKEYBARREL = "What a wonderfully flammable home.",

		HOUNDSTOOTH="It's sharp. I like it!",
		ARMORSNURTLESHELL="Less defense! More offense!",
		BAT="Cute little guy!",
		BATBAT = "I can hit my enemies with it.",
		BATWING="Yuck!",
		BATWING_COOKED="Yuck!",
		BEDROLL_FURRY="It's too frilly.",
		BUNNYMAN="Ugh. They look so stupid.",
		FLOWER_CAVE="It's burning inside.",
		FLOWER_CAVE_DOUBLE="It's burning inside.",
		FLOWER_CAVE_TRIPLE="It's burning inside.",
		GUANO="It burns like normal poop.",
		LANTERN="Fire is not meant to be contained like this!",
		LIGHTBULB="It's called a \"lightbulb\" but it's kinda heavy.",
		MANRABBIT_TAIL="I won that argument.",
		MUSHTREE_TALL=
		{
            GENERIC = "Gross. This tree is sick all over.",
            BLOOM = "Ack! It stinks!",
        },
		MUSHTREE_MEDIUM=
		{
            GENERIC = "Gross. It smells like leprechaun butt.",
            BLOOM = "It's spreading junk everywhere.",
        },
		MUSHTREE_SMALL=
		{
            GENERIC = "Gross. It's all mushroomy.",
            BLOOM = "Ew, I don't want to get too close.",
        },
        MUSHTREE_TALL_WEBBED = "That one got what it deserves.",
        SPORE_TALL = "It's like colorful sparks!",
        SPORE_MEDIUM = "It's like colorful sparks!",
        SPORE_SMALL = "It's like colorful sparks!",
        SPORE_TALL_INV = "It feels flammable.",
        SPORE_MEDIUM_INV = "It feels flammable.",
        SPORE_SMALL_INV = "It feels flammable.",
		MUSHTREE_TALL="Gross. This tree is sick all over.",
		MUSHTREE_MEDIUM="Gross. It smells like leprechaun butt.",
		MUSHTREE_SMALL="Gross. It's all mushroomy.",

		SLURTLE="I want to blow it up!",
		SLURTLE_SHELLPIECES="Heh. It broke.",
		SLURTLEHAT="It fits my head.",
		SLURTLEHOLE="I should burn them out.",
		SLURTLESLIME="I love this stuff!",
		SNURTLE="Kaboom!",
		SPIDER_HIDER="What a frustrating jerk!",
		SPIDER_SPITTER="Get over here!",
		SPIDERHOLE="It's full of spiders.",
		STALAGMITE="Rocks are boring.",
		STALAGMITE_FULL="Rocks are boring.",
		STALAGMITE_LOW="Rocks are boring.",
		STALAGMITE_MED="Rocks are boring.",
		STALAGMITE_TALL="More boring rocks.",
		STALAGMITE_TALL_FULL="More boring rocks.",
		STALAGMITE_TALL_LOW="More boring rocks.",
		STALAGMITE_TALL_MED="More boring rocks.",

		TURF_CARPETFLOOR = "The ground is boring.",
		TURF_CHECKERFLOOR = "The ground is boring.",
		TURF_DIRT = "The ground is boring.",
		TURF_FOREST = "The ground is boring.",
		TURF_GRASS = "The ground is boring.",
		TURF_MARSH = "The ground is boring.",
		TURF_ROAD = "The ground is boring.",
		TURF_ROCKY = "The ground is boring.",
		TURF_SAVANNA = "The ground is boring.",
		TURF_WOODFLOOR = "The ground is boring.",
		TURF_DRAGONFLY = "My lighter doesn't work on it.",

		TURF_CAVE="The ground is boring.",
		TURF_FUNGUS="The ground is boring.",
		TURF_SINKHOLE="The ground is boring.",
		TURF_UNDERROCK="The ground is boring.",
		TURF_MUD="The ground is boring.",
		
		TURKEYDINNER = "A feast of burned bird!",
		TWIGS = "A bunch of small twigs. Good for fires, among other things.",
		POWCAKE = "I wonder if it is flammable.",
        CAVE_ENTRANCE = 
        {
            GENERIC="Who plugged that hole?",
            OPEN = "I hope there's lava down there somewhere.",
        },
        CAVE_EXIT = "It's too dark and stuffy down here.",
        CAVE_ENTRANCE = "Who plugged that hole?",
        CAVE_ENTRANCE_RUINS = "Who plugged that hole?",

        CAVE_ENTRANCE_OPEN = 
        {
            GENERIC = "I don't want to go in that gross hole!",
            OPEN = "I hope there's lava down there somewhere.",
        },
        CAVE_EXIT = 
        {
            GENERIC = "It's cooler down here, anyway.",
            OPEN = "It's too dark and stuffy down here.",
        },

		MAXWELLPHONOGRAPH = "I like more exciting music.",
		PIGGUARD = "I like his attitude!",
		BOOMERANG = "It's not the most exciting weapon.",
		ADVENTURE_PORTAL = "Maybe that leads home.",
		AMULET = "I'm invincible! Well, maybe not. But it feels good.",
		ANIMAL_TRACK = "It leads to my new friend.",
		ARMORGRASS = "A waste of flammable materials.",
		ARMORMARBLE = "If I have to fight I might as well be protected.",
		ARMORWOOD = "Now I can take on the world!",
		ARMOR_SANITY = "Like being wrapped in smoke.",
		ASH =
		{
			GENERIC = "Leftovers from a fire. I wish it was still here.",
			REMAINS_GLOMMERFLOWER = "I wish I saw the way that weird flower burned.",
			REMAINS_EYE_BONE = "I bet that eye thing was quite a sight wreathed in fire!",
			REMAINS_THINGIE = "I wish this thing was still burning, whatever it was.",
		},
		AXE = "It's very sharp.",
		BABYBEEFALO =
		{
			GENERIC = "Even the babies are ugly.",
			SLEEPING = "WAKE UP!",
		},
		BACKPACK = "I could fit like a million lighters in here.",
		BACONEGGS = "The yellow mucus-y part is gross, but the bacon is great!",
		BANDAGE = "Eww, do I have to?",
		BASALT = "It's too hard to break!",
		BEARDHAIR = "Uh, where did this come from?",
		BEDROLL_STRAW = "Musty.",
		BEE =
		{
			GENERIC = "It's fat, but that stinger looks dangerous.",
			HELD = "Pocket full of bees!",
		},
		BEEFALO =
		{
			FOLLOWER = "Er, are you following me?",
			GENERIC = "What a disgusting, hairy beast!",
			NAKED = "Ha! He's all naked now!",
			SLEEPING = "They look even dumber when they're sleeping.",
		},
		BEEFALOHAT = "I've taken his hair and put it on my own!",
		BEEFALOWOOL = "Ha! I stole his hair!",
		BEEHIVE = "It's full of bees!",
		BEEMINE = "Bees inside. Should've put some fire in there for good measure.",
		BEEMINE_MAXWELL = "Mosquitoes inside. They don't sound happy.",
		BEEHAT = "This will keep the pokeys off of me.",
		BERRIES = "Red berries taste the best.",
		BERRIES_COOKED = "Red berries with fire somehow taste even better.",
		BERRYBUSH =
		{
			BARREN = "Eat poop, stupid plant!",
			WITHERED = "All dried out. Primed for fire!",
			GENERIC = "Mmmmm. Berries.",
			PICKED = "I want more berries!",
		},
		BIRDCAGE =
		{
			GENERIC = "Bird prison!",
			OCCUPIED = "Ha! Gotcha now!",
			SLEEPING = "Stupid bird. Wake up!",
			HUNGRY = "What's all the fuss about?",
			STARVING = "He won't be quiet!",
			DEAD = "At least he's quiet now.",
			SKELETON = "I should probably clean that up.",
		},
		BIRDTRAP = "I'll catch those creepy birds.",
		BIRD_EGG = "It smells like a bird's butt.",
		BIRD_EGG_COOKED = "Yuck. The yellow part is all runny.",
		BISHOP = "It's a bishop!",
		BISHOP_CHARGE_HIT = "Owwww!",
		BLOWDART_FIRE = "This is my favorite thing in the whole wide world.",
		BLOWDART_SLEEP = "Tranquilized things are easier to light on fire.",
		BLOWDART_PIPE = "Good practice for blowing into a fire.",
		BLUEGEM = "Ugh. This one is ugly.",
		BLUEPRINT = "This will save some experimentation.",
		BELL_BLUEPRINT = "This will save some experimentation.",
		BLUE_CAP = "It smells like a gym sock!",
		BLUE_CAP_COOKED = "I changed it with fire!",
		BLUE_MUSHROOM =
		{
			GENERIC = "Dumb mushroom.",
			INGROUND = "Hey! You! Get up here!",
			PICKED = "Maybe it will return some day.",
		},
		BOARDS = "Boards. They'll burn, same as other wood.",
		BONESTEW = "Just add fire to food and voila!",
		BUGNET = "I can catch a bug!",
		BUSHHAT = "Too passive!",
		BUTTER = "Tasty, and just a little bit insecty.",
		BUTTERFLY =
		{
			GENERIC = "Flutter away, butterfly!",
			HELD = "I want to squish it.",
		},
		BUTTERFLYMUFFIN = "Heehee, look at that butterfly stuck in the muffin.",
		BUTTERFLYWINGS = "No more flying for that butterfly!",
		CAMPFIRE =
		{
			EMBERS = "Uh oh. It's almost gone!",
			GENERIC = "I like fire.",
			HIGH = "BURN! BURN FASTER!",
			LOW = "This fire is small and boring.",
			NORMAL = "Burn!",
			OUT = "Awww. It's all over.",
		},
		CANE = "I can walk more easily with this!",
		CARROT = "Yuck. It's all vegetabley.",
		CARROT_COOKED = "Still vegetabley, but better for having been in fire.",
		CARROT_PLANTED = "Maybe its special carrot friend is in the ground.",
		CARROT_SEEDS = "Seeds for a yucky orange vegetable.",
		CAVE_FERN = "Looks flammable.",
		CHARCOAL = "Mmmm. Smells like fire.",
        CHESSJUNK1 = "Dead windup horsey.",
        CHESSJUNK2 = "Dead windup priest.",
        CHESSJUNK3 = "Dead windup castle.",
		CHESTER = "He's so fuzzy!",
		CHESTER_EYEBONE =
		{
			GENERIC = "It's rude to stare.",
			WAITING = "At least it's not looking at me anymore.",
		},
		COOKEDMEAT = "Unseasoned meat... great.",
		COOKEDMONSTERMEAT = "It's still gross.",
		COOKEDSMALLMEAT = "I'll need more than appetizers if I'm going to survive.",
		CORN = "A sweet vegetable, yum!",
		CORN_COOKED = "Ooh, this one explodes when it goes in fire!",
		CORN_SEEDS = "Seeds for my favorite explosive vegetable.",
		CROW =
		{
			GENERIC = "I think it's waiting for me to die.",
			HELD = "Not so smart now, are you?",
		},
		CUTGRASS = "Cut grass, ready for burning. Or maybe crafting.",
		CUTREEDS = "Cut reeds, ready for burning. Or maybe crafting.",
		CUTSTONE = "Perfectly squared for maximum enjoyment.",
		DEADLYFEAST = "Fire didn't cure this dish of being nasty.",
		DEERCLOPS = "Holy crap!",
		DEERCLOPS_EYEBALL = "Stop staring at me!",
		DIRTPILE = "Who just leaves dirt lying around in the forest?",
		DIVININGROD =
		{
			COLD = "It's making some kind of noise.",
			GENERIC = "It's full of electrical junk.",
			HOT = "Gah! Enough with the beeping!",
			WARM = "This thing is getting noisier.",
			WARMER = "I must be close!",
		},
		DIVININGRODBASE =
		{
			GENERIC = "Not sure what this does. Doesn't seem like it's fiery things.",
			READY = "Just needs to be unlocked with a key. Not fire, unfortunately.",
			UNLOCKED = "It's whirring now!",
		},
		DIVININGRODSTART = "I'll make something out of it.",
		DRAGONFLY = "It's filled with fire!",
		LAVASPIT = 
		{
			HOT = "The coolest drool!",
			COOL = "Cool drool, literally.",
		},
		LAVA_POND = "Yes! Yessss!",
		LAVAE = "Why can't we be friends?",
		LAVAE_PET = 
		{
			STARVING = "I can see her ribs!",
			HUNGRY = "I think she wants some burnings.",
			CONTENT = "My own little burninator.",
			GENERIC = "She's... perfect.",
		},
		LAVAE_EGG = 
		{
			GENERIC = "I think a fire is trying to escape.",
		},
		LAVAE_EGG_CRACKED =
		{
			COLD = "It has a chill.",
			COMFY = "That egg looks happy.",
		},
		LAVAE_TOOTH = "I hope she's not a biter.",
		DRAGONFRUIT = "It looks sort of like a fire!",
		DRAGONFRUIT_COOKED = "It looks more like a fruit that's been in a fire now.",
		DRAGONFRUIT_SEEDS = "Seeds for that fire-looking fruit.",
		DRAGONPIE = "Fire fruit in a pie? Oh boy!",
		DRUMSTICK = "Bang on the drum all day!",
		DRUMSTICK_COOKED = "Do I satisfy my hunger or do I bang on the drum?",
		DURIAN = "Ew, stinky!",
		DURIAN_COOKED = "Yuck, it smells just as bad cooked!",
		DURIAN_SEEDS = "Smelly seeds for a smelly fruit.",
		EARMUFFSHAT = "Smells like rabbit butt.",
		EGGPLANT = "Definitely not a bird.",
		EGGPLANT_COOKED = "Using fire on it made it a tastier eggplant.",
		EGGPLANT_SEEDS = "Will these seeds make a plant or baby bird?",
		STUFFEDEGGPLANT = "It's still not a bird, but I stuffed it like one!",
		DUG_BERRYBUSH = "What's the matter, got no dirt?",
		DUG_GRASS = "What's the matter, got no dirt?",
		DUG_MARSH_BUSH = "What's the matter, got no dirt?",
		DUG_SAPLING = "What's the matter, got no dirt?",
		EARMUFFS = "Smells like rabbit butt.",
		ACORN = 
		{
		    GENERIC = "Hey there, tree seed.",
		    PLANTED = "You'll be a real tree soon.",
		},
		EVERGREEN =
		{
			BURNING = "YES! BURN!",
			BURNT = "I wish it was still burning.",
			CHOPPED = "One less tree in the world.",
			GENERIC = "It looks like it would burn well.",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "YES! BURN!",
			BURNT = "I wish it was still burning.",
			CHOPPED = "One less tree in the world.",
			GENERIC = "Die in a fire!",
		},
		EYEPLANT = "They spread like fire.",
		FEATHERHAT = "I am a phoenix!",
		FEATHER_CROW = "Crow feather. It probably smells terrible on fire.",
		FEATHER_ROBIN = "Redbird feather. It probably smells terrible on fire.",
		FEATHER_ROBIN_WINTER = "Snowbird feather. It probably smells terrible on fire.",
		FEM_PUPPET = "She looks scared half to death.",
		FIREFLIES =
		{
			GENERIC = "I wish they didn't run away!",
			HELD = "They're like little fires in my pocket!",
		},
		FIREHOUND = "I actually kind of like that one.",
		FIREPIT =
		{
			EMBERS = "Uh oh. It's almost gone!",
			GENERIC = "I could watch it for hours.",
			HIGH = "BURN! BURN FASTER!",
			LOW = "This fire is small and boring.",
			NORMAL = "Burn!",
			OUT = "I should make the fire come back.",
		},
		FIRESTAFF = "This is my absolute favorite toy.",
		FISH = "Slippery fishy!",
		FISHINGROD = "Fishing for the answer with a hook, line and sinker.",
		FISHSTICKS = "What you see is what you get. Sticks of fish.",
		FISHTACOS = "Convenient taco-grip.",
		FISH_MED = "Time to chuck it in the fire!",
		FISH_MED_COOKED = "It actually looks kinda edible.",
		FISH_COOKED = "Less slippery now that it's found fire.",
		FLINT = "The poor man's fire-starter.",
		FLOWER = "I don't have time to waste on flowers.",
		FLOWERHAT = "A halo of flowers. Too bad it's not a burning halo of flowers.",
		FLOWER_EVIL = "Ugh, that smells terrible.",
		FOLIAGE = "Fuel for the fire.",
		FOOTBALLHAT = "Sports are hard.",
		FROG =
		{
			DEAD = "I showed him!",
			GENERIC = "He's too damp to burn.",
			SLEEPING = "They're cute when they're sleeping.",
		},
		FROGGLEBUNWICH = "Maybe I won't notice that it's frog legs in the sandwich.",
		FROGLEGS = "It still twitches every now and then. Freaky.",
		FROGLEGS_COOKED = "The fire made it stop twitching. Fire is the best.",
		FRUITMEDLEY = "Yum, fruit!",
		GEARS = "These must make them move.",
		GHOST = "I can't kill what's already dead.",
        GHOST_SAILOR = "He'd probably be happier if he could make fire.",
		GOLDENAXE = "It won't light trees on fire, but at least it's shiny.",
		GOLDENPICKAXE = "It won't light rocks on fire, but at least it's shiny.",
		GOLDENPITCHFORK = "It won't light the ground on fire, but at least it's shiny.",
		GOLDENSHOVEL = "It won't make flaming pits, but at least it's shiny.",
		GOLDNUGGET = "Where am I going to spend this.",
		GRASS =
		{
			BARREN = "It needs poop.",
			WITHERED = "Nice and dry, ready to burn!",
			BURNING = "Fire! Wooo!",
			GENERIC = "It's a flammable tuft of grass.",
			PICKED = "Grass stubble is kind of useless.",
		},
		GREEN_CAP = "Boring!",
		GREEN_CAP_COOKED = "I changed it with fire!",
		GREEN_MUSHROOM =
		{
			GENERIC = "Stupid mushroom.",
			INGROUND = "Hey! You! Get up here!",
			PICKED = "Maybe it will return some day.",
		},
		GUNPOWDER = "Oooooooooh! Shiny!",
		HAMBAT = "Pleased to meat you!",
		HAMMER = "I prefer sharp implements.",
		HEALINGSALVE = "It burns! But, where's the fire?",
		HEATROCK =
		{
			FROZEN = "Frozen solid.",
			COLD = "It's stone cold.",
			GENERIC = "A fire would liven this thing up!",
			WARM = "No flame, no real heat... what fun is that?",
			HOT = "Look at how it glows!",
		},
		HONEY = "Sweet and delicious!",
		HONEYCOMB = "It's waxy.",
		HONEYHAM = "Fire, ham and honey go well together.",
		HONEYNUGGETS = "Honey-covered morsels that have met my friend, fire.",
		HORN = "I can hear those hairy beasts inside.",
		HOUND = "What a jerk!",
		HOUNDMOUND = "Uh oh, I don't like the look of that.",
		HOUNDBONE = "Gross.",
		ICEBOX = "That is the opposite of fire.",
		ICEHOUND = "Gross! Cold!",
		INSANITYROCK =
		{
			ACTIVE = "Am I seeing things?",
			INACTIVE = "Doesn't look flammable. How boring.",
		},
		JAMMYPRESERVES = "Wham, bam, jam! Thank you, ma'am.",
		KABOBS = "Meat and fire, now with a stick!",
		KILLERBEE =
		{
			GENERIC = "I like the cut of that bee's jib.",
			HELD = "Buzz!",
		},
		KNIGHT = "It's a pony!",
		KOALEFANT_SUMMER = "We will be great friends!",
		KOALEFANT_WINTER = "He sure looks warm...",
		KRAMPUS = "Stay back, you big jerk!",
		KRAMPUS_SACK = "The holidays came early this year!",
		LEIF = "He looks flammable!",
		LEIF_SPARSE = "He looks flammable!",
		LIGHTNING_ROD =
		{
			CHARGED = "Aww, all glow but no fire.",
			GENERIC = "All the lightning goes here!",
		},
		LITTLE_WALRUS = "He looks tasty.",
		LIVINGLOG = "It looks upset.",
		LOCKEDWES = "He's trapped by those mean statues!",
		LOG =
		{
			BURNING = "Burn, log, buuuurn!",
			GENERIC = "Wood! So flammable! Hooray!",
		},
		LUREPLANT = "I bet a quick fire would take care of this.",
		LUREPLANTBULB = "It's mine now.",
		MALE_PUPPET = "He looks scared half to death.",
		MANDRAKE =
		{
			DEAD = "Why did this plant have a face?",
			GENERIC = "That's not a normal plant.",
			PICKED = "Now that's just creepy!",
		},
		COOKEDMANDRAKE = "The fire didn't get rid of its face. Gives me the willies.",
		MANDRAKESOUP = "The face doesn't wash away!!",
		MARBLE = "It's heavy!",
		MARBLEPILLAR = "I wonder if the rest burnt down.",
		MARBLETREE = "The worst kind of tree. The non-flammable kind.",
		MARSH_BUSH =
		{
			BURNING = "Burn, thorns!",
			GENERIC = "It looks sharp.",
			PICKED = "Those thorns hurt!",
		},
		MARSH_PLANT = "It's all plant-y.",
		MARSH_TREE =
		{
			BURNING = "YES! BURN!",
			BURNT = "I wish it was still burning.",
			CHOPPED = "Not so spiky now, are you?",
			GENERIC = "It looks dangerous!",
		},
		MAXWELL = "He's so condescending.",
		MAXWELLHEAD = "He sure likes to talk.",
		MAXWELLLIGHT = "These are no fun. They light themselves.",
		MAXWELLLOCK = "Now I just need a key.",
		MAXWELLTHRONE = "Looks sticky.",
		MEAT = "I could make this better with FIRE!",
		MEATBALLS = "Meat made into spheres and improved with fire.",
		MEAT_DRIED = "Chewy, but satisfying.",
		MERM = "Eww, it's all swampy.",
		MONSTERLASAGNA = "Noodles, meat and clumps of hair. Nasty.",
		MONSTERMEAT = "Gross. It's full of hairs.",
		MONSTERMEAT_DRIED = "It's dry and smells strange.",
		MOSQUITO =
		{
			GENERIC = "So annoying!",
			HELD = "Keep that mouth away from me!",
		},
		MOSQUITOSACK = "Blood must bubble in currents muggy and thick.",
		MOUND =
		{
			DUG = "Better it than me.",
			GENERIC = "It's full of dead stuff, I bet.",
		},
		NIGHTLIGHT = "It's like fire, but purple!",
		NIGHTMAREFUEL = "Eww, it's still warm!",
		NIGHTSWORD = "It's like my dreams can hurt real things!",
		NITRE = "There are tiny explosions trapped inside.",
		ONEMANBAND = "I can do the pyrotechnics too!",
		PANDORASCHEST = "Kind of tacky.",
		PANFLUTE = "Music is boring.",
		PAPYRUS = "I bet it'd burn!",
		PENGUIN = "Run away, tiny dancers.",
		PERD = "Evil bird! Get away from my yummy berries!",
		PEROGIES = "Tasty things, sealed with fire.",
		PETALS = "Stupid flowers. They're almost useless.",
		PETALS_EVIL = "Ew, they're sticky.",
		PICKAXE = "It's very pointy.",
		PIGGYBACK = "I made a backpack out of butts!",
		PIGKING = "Blech. What a slob.",
		PIGMAN =
		{
			DEAD = "I wonder how they taste.",
			FOLLOWER = "Ick. It's following me.",
			GENERIC = "Ugh. They're fragrant.",
			GUARD = "He's not the boss of me!",
			WEREPIG = "Bring it on, piggie!",
		},
		PIGSKIN = "Ha ha. A pig's butt.",
		PIGTORCH = "These pigs sure know how to have a good time.",
		PINECONE = 
		{
		    GENERIC = "Hey there, tree seed.",
		    PLANTED = "You'll be a real tree soon.",
		},
		PITCHFORK = "Three times the pointiness.",
		PLANTMEAT = "Eww, it's all slimy.",
		PLANTMEAT_COOKED = "Fire makes everything better.",
		PLANT_NORMAL =
		{
			GENERIC = "I'll eat it if I have to.",
			GROWING = "Hurry up, you stupid plant!",
			READY = "Oh boy. Vegetables.",
			WITHERED = "It's crackly and dry. Good kindling!",
		},
		POMEGRANATE = "Is it supposed to have this many parts?",
		POMEGRANATE_COOKED = "Fire always makes things better.",
		POMEGRANATE_SEEDS = "Looks like the part from inside the fruit.",
		POOP = "Ew. Nasty. But useful.",
		PUMPKIN = "I wonder what would happen if I applied fire.",
		SCORCHED_SKELETON = "Ewwwwwwwwwww!",
		PUMPKINCOOKIE = "Cookies!!!",
		PUMPKIN_COOKED = "Fire on the outside turned out pretty well.",
		PUMPKIN_LANTERN = "Fire on the inside is amazing!",
		PUMPKIN_SEEDS = "Seeds for fire's best vegetable-friend: the pumpkin.",
		PURPLEGEM = "Weird!",
		RABBIT =
		{
			GENERIC = "He looks tasty.",
			HELD = "I have him right where I want him!",
		},
		RABBITHOLE = 
		{
			GENERIC = "Stupid rabbits. Come out so I can eat you.",
			SPRING = "Stupid rabbits must be stuck down there.",
		},
		RATATOUILLE = "Vegetables. So many vegetables.",
		RAZOR = "Why did I build this?",
		REDGEM = "So pretty!",
		RED_CAP = "I like the color.",
		RED_CAP_COOKED = "I changed it with fire!",
		RED_MUSHROOM =
		{
			GENERIC = "Pretty!",
			INGROUND = "Hey! You! Get up here!",
			PICKED = "Maybe it will return some day.",
		},
		REEDS =
		{
			BURNING = "Burn! Yeah!",
			GENERIC = "It's a burnable clump of reeds.",
			PICKED = "I can't do anything with reed stubble.",
		},
        RELIC = 
        {
            GENERIC = "Old furniture.",
            BROKEN = "Bits and pieces, pieces and bits.",
        },
        RUBBLE = "Broken furniture.",
		RESURRECTIONSTONE = "I guess I should touch it?",
		ROBIN =
		{
			GENERIC = "A redbird. The color of fire, but not a phoenix.",
			HELD = "It's cozy in my pocket.",
		},
		ROBIN_WINTER =
		{
			GENERIC = "It looks cold out here. I bet it wants a fire.",
			HELD = "It's so fluffy.",
		},
		ROBOT_PUPPET = "They look scared half to death.",
		ROCK_LIGHT =
		{
			GENERIC = "There's heat in there, just waiting to get out!",
			OUT = "Aww, it's cooled off.",
			LOW = "The lava is cooling.",
			NORMAL = "A pool of fire!",
		},
		ROCKS = "What's the point of collecting these again?",
        ROOK = "It's a castle!",
        ROPE = "What can I tie up with this?",
		ROTTENEGG = "Ew! Why? Oh Why?!",
		SANITYROCK =
		{
			ACTIVE = "I wonder what these markings mean.",
			INACTIVE = "Where'd it go?",
		},
		SAPLING =
		{
			BURNING = "Burn! Yeah!",
			WITHERED = "It's so dry, it's like it WANTS to be on fire.",
			GENERIC = "I should pick it.",
			PICKED = "Poor little limp tree.",
		},
		SEEDS = "Farming is boring.",
		SEEDS_COOKED = "No good for farming now.",
		SEWING_KIT = "But destruction is so much more fun!",
		SHOVEL = "Not great for fighting.",
		SILK = "Mmmmmm. Smooth.",
		SKELETON = "Oh my. I hope you at least went out in a blaze of glory.",
		SKELETON_PLAYER = "That gives me the willies.",
		SKULLCHEST = "Ooooh, spooky!",
		SMALLBIRD =
		{
			GENERIC = "Not quite a phoenix, but still cute. I guess.",
			HUNGRY = "Are you hungry?",
			STARVING = "Okay, okay! I get it, you're hungry.",
		},
		SMALLMEAT = "I could make this better with FIRE!",
		SMALLMEAT_DRIED = "Chewy, but satisfying.",
		SPAT = "I don't like your face!",
		SPEAR = "Feel my jabby wrath!",
		SPIDER =
		{
			DEAD = "Ha! I showed you!",
			GENERIC = "He's nasty. I should kill him.",
			SLEEPING = "I could take him.",
		},
		SPIDERDEN = "That's just nasty.",
		SPIDEREGGSACK = "Tons of tiny disgusting spiders.",
		SPIDERGLAND = "Eeeeew it's slimy and stinky!",
		SPIDERHAT = "Who's your mommy!",
		SPIDERQUEEN = "Kill it with fire!",
		SPIDER_WARRIOR =
		{
			DEAD = "He had it coming.",
			GENERIC = "Maybe I could kill it... with FIRE.",
			SLEEPING = "Maybe I should just leave that one alone.",
		},
		SPOILED_FOOD = "At least it's still flammable.",
		STATUEHARP = "Such a nice statue. Shame if something were to happen to it.",
		STATUEMAXWELL = "I'm beginning to dislike that man.",
		STEELWOOL = "Make a spark, it'll still burn.",
		STINGER = "It's pokey!",
		STRAWHAT = "A hat made of straw. To think, it could've been tinder.",
		SUNKBOAT = "It's too far out, I can't even burn it!",
		SWEATERVEST = "Not as nice as a flaming vest, but it'll do.",
		TAFFY = "Sugary things burn great, but I should eat this instead.",
		TALLBIRD = "I don't think it wants to be friends.",
		TALLBIRDEGG = "Does it like fire?",
		TALLBIRDEGG_COOKED = "Fire makes them so much better.",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "Needs more fire!",
			GENERIC = "Arise, my phoenix!",
			HOT = "Is there such a thing as too much fire?",
			LONG = "How long is this going to take?",
			SHORT = "I'm getting tired of waiting.",
		},
		TALLBIRDNEST =
		{
			GENERIC = "That egg could use some fire!",
			PICKED = "The nest is empty.",
		},
		TEENBIRD =
		{
			GENERIC = "I feel like he understands me.",
			HUNGRY = "He sure eats a lot.",
			STARVING = "Don't look at me! Get your own food.",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "I just want to see this world burn.",
			GENERIC = "I like the way the symbols glow.",
			LOCKED = "Needs to be unlocked somehow.",
			PARTIAL = "I'm making a monstrosity!",
		},
		TELEPORTATO_BOX = "It feels warm.",
		TELEPORTATO_CRANK = "What's this part good for?",
		TELEPORTATO_POTATO = "Perhaps I could melt it into a more pleasing shape.",
		TELEPORTATO_RING = "This is too precious to burn!",
		TENTACLE = "Not at all cuddly.",
		TENTACLESPOTS = "Ewwwww.",
		TENTACLESPIKE = "It's pointy and slimy.",
		TENTACLE_PILLAR = "It's quivering.",
		TENTACLE_PILLAR_HOLE = "What a smell! Light a match next time!",
		TENTACLE_PILLAR_ARM = "Awwww, they want hugs!",
		TENTACLE_GARDEN = "I hear little digging sounds.",
		
		LAVA_POND_ROCK = "Oh great, another stinkin' rock!",
		LAVA_POND_ROCK2 = "Oh great, another stinkin' rock!",
		LAVA_POND_ROCK3 = "Oh great, another stinkin' rock!",
		LAVA_POND_ROCK4 = "Oh great, another stinkin' rock!",
		LAVA_POND_ROCK5 = "Oh great, another stinkin' rock!",
		LAVA_POND_ROCK6 = "Oh great, another stinkin' rock!",
		LAVA_POND_ROCK7 = "Oh great, another stinkin' rock!",

		TOPHAT = "A top hat and a lighter, a perfect combination.",
		TORCH = "Fire is so pretty.",
		TRAP = "It's a bit passive aggressive, but it'll work.",
		TRAP_TEETH = "It would be better with fire.",
		TRAP_TEETH_MAXWELL = "What kind of jerk leaves this lying around?",
		TRINKET_1 = "I'll bet the fire that melted these was fiercely hot.",
		TRINKET_10 = "I don't think dentures burn well.",
		TRINKET_11 = "Ooh, I wonder if he has a flamethrower!",
		TRINKET_12 = "All dried up, like it got too close to the fire.",
		TRINKET_2 = "A cheap fake. It probably doesn't even burn properly.",
		TRINKET_3 = "The knot is stuck. Who needs a knife when you've got fire?",
		TRINKET_4 = "He looks like he was forged in flame.",
		TRINKET_5 = "Check out those tiny thrusters. Such explosive power!",
		TRINKET_6 = "Not even a spark.",
		TRINKET_7 = "Fire is more fun.",
		TRINKET_8 = "I've never liked bathing with water.",
		TRINKET_9 = "You can strike a match on a zipper, but not on buttons.",
		TRUNKVEST_SUMMER = "Now I'll be with my friend forever.",
		TRUNKVEST_WINTER = "Not as warm as a good fire, but still pretty good!",
		TRUNK_COOKED = "I'm still not sure I want to eat this.",
		TRUNK_SUMMER = "Well, part of him is still cuddly.",
		TRUNK_WINTER = "It's so soft and squishy!",
		UMBRELLA = "I love the color!",
		WAFFLES = "Hi, waffles!",
		WALL_HAY_ITEM = "Hmmm. I wonder if these will burn.",
		WALL_STONE = "Eh. I guess that's okay.",
		WALL_STONE_ITEM = "These are surprisingly heavy.",
		WALL_RUINS = "And they'll huff and they'll puff!",
		WALL_RUINS_ITEM = "Will they fit in my pockets?",
		WALL_WOOD_ITEM = "I hate hiding.",
		WALL_MOONROCK = "Safe for now.",
		WALL_MOONROCK_ITEM = "I guess I could carry it.",
		WALRUS = "Stop following me!",
		WALRUSHAT = "I kind of like the look of it.",
		WALRUS_CAMP =
		{
			EMPTY = "I'm not going in there. Yuck!",
			GENERIC = "Why does everyone have a nicer house than me?",
		},
		WALRUS_TUSK = "Nom nom nom.",
		WARDROBE = 
		{
			GENERIC = "I want to set it on fire.",
            BURNING = "Yes! Burn!",
			BURNT = "Aww, the fire burned out.",
		},
		WARG = "You're a big mean jerk!",
		WASPHIVE = "I had better keep my distance.",
		WETGOOP = "How did it go wrong?! It was engulfed in fire and everything.",
		WINTERHAT = "It's not warm enough for my liking.",
		WORMHOLE =
		{
			GENERIC = "Poke it with a stick!",
			OPEN = "I wonder if it likes spicy food?",
		},
		ACCOMPLISHMENT_SHRINE = "I hate that arrow!", 

		------------------------------------------------------capy--------------------------------
		AERODYNAMICHAT = "Brisk movement snuffs fires.",
		ARMOR_LIFEJACKET = "But will it keep my lighter dry?",
		ARMOR_SNAKESKIN = "This coat makes me feel dangerous.",
		ARMOR_WINDBREAKER = "Wind is the enemy of fire.",
		ARMORLIMESTONE = "It's so... heavy.",
		ARMOROBSIDIAN = "Hit me and BURN!",
		ARMORSEASHELL = "Try me, baddies.",
		ARMOUREDBOAT = "Nothing's gonna take a bite out of this boat.",
		BABYOX = "You may be small, but you smell big.",
		BALLPHIN = "You don't look particularly flammable.",
		BALLPHINPOD = "A family of bouncy things.",
		BAMBOOTREE = "A stick-y shrub.",
		BERRYBUSH2_SNAKE = "Mmmmm. Berries.",--I don't think these should have diff name or examine text
		BERRYBUSH_SNAKE = "Mmmmm. Berries.",--I don't think these should have diff name or examine text
		BIOLUMINESCENCE = "It's a cold light. Not like a flame at all.",
		BLOWDART_POISON = "A sick kiss.",
		BOAT_LANTERN = "Light without a flame. I don't like it one bit.",
		BOTTLELANTERN = "The light is so cold and alien.",
		BURIEDTREASURE = "If I don't like the treasure I'll just set the chest on fire.",
		BUSH_VINE = "I bet these crackle and pop when they burn.",
		SNAKEDEN = "I bet these crackle and pop when they burn.",--I don't think these should have diff name or examine text
		CANNONSHOT = "Fire!",
		CAPTAINHAT = "I no longer have that sinking feeling.",
		CARGOBOAT = "I can carry so many flammables on this.",
		CHIMINEA = "Do you like your house, fire? You're welcome.",
		CIRCLINGSEAGULL = "Fly into the sun, jerks.",
		CLOTHSAIL = "Nice stitching.",
		COCONUT = 
		{
		    GENERIC = "An edible tree thing.",
		    PLANTED = "Hurry up and grow, I want the shade.",
		},
		COCONUT_COOKED = "Mmmm, toasty.",
		COFFEE = "I suddenly feel motivated.",
		COFFEEBEANS = "These could use fire.",
		COFFEEBEANS_COOKED = "Ahhh, that aroma.",
		COFFEEBUSH = "This bush flourishes near the volcano's fire!",
		CORAL = "Pretty colors.",
		CORALREEF = "I wish I had a snorkel.",
		CUTLASS = "This sword smells.",
		DEAD_SWORDFISH = "Ugh, fire would get rid of that smell.",
		DEPLETED_BAMBOOTREE = "Anymore bamboos? Helloooo?",
		DEPLETED_BUSH_VINE = "Come back!",
		DOYDOY = "There is no spark behind its eyes.",
		DOYDOYBABY = "You poor little dummy.",
		DOYDOYEGG = "Dumb egg.",
		DOYDOYEGG_COOKED = "Cooking this dumb egg was smart of me.",
		DOYDOYEGG_CRACKED = "The planet just got a little dumber.",
		DOYDOYFEATHER = "This would burn.",
		DOYDOYNEST = "A dummy is born every second.",
		DUBLOON = "Pirate monies!",
		DUG_BAMBOOTREE = "You need ground, fast.",
		DUG_BERRYBUSH2 = "Would you like to live again?",
		DUG_BUSH_VINE = "Would you like to go back into the ground?",
		DUG_COFFEEBUSH = "I know just what to do with you.",
		EARRING = "So shiny!",
		FABRIC = "Amazing what you can do with bamboo.",
		FEATHERSAIL = "Gotta hand it to those dumdums... they make good sails!",
		FIRERAIN = "Let it rain!",
		FIRERAINSHADOW = "Here it comes!",
		FISHINHOLE = "Why here, fishies?",
		GASHAT = "I like not smelling smelly smells.",
		GOLDENMACHETE = "I don't want to scuff it up.",
		ICEMAKER = "It turns fire into ice. Boo.",
		IRONWIND = "Now we're gettin' somewhere.",
		JELLYFISH = "It's shriveling up.",
		JELLYFISH_DEAD = "Won't be stingin' anyone now.",
		JELLYFISH_COOKED = "It actually looks edible.",
		JELLYFISH_PLANTED = "I'll call you \"Jerald\".",
		JELLYJERKY = "Looks chewy.",
		JUNGLETREESEED =
        {
            GENERIC = "A future forest fire.",
            PLANTED = "A not-so-distant future forest fire.",
        },
		LAVAPOOL = "What marvelous heat and fury!",
		LIMESTONE = "It's made of crushed, dead fishies.",
		LIMPETS = "A little lick of flame and you'll be tasty.",
		LIMPETS_COOKED = "Pretty good!",
		LOBSTERHOLE = "The happy lobster home.",
		LOGRAFT = "Campfire wood has other uses, apparently!",
		MOSQUITO_POISON = "Shoo! Away!",
		MUSSEL = "Open up, fella.",
		MUSSEL_COOKED = "The fire opens their shells.",
		MUSSEL_STICK = "The mussels like this stick for some reason.",
		OBSIDIAN = "A fire rock!",
		OBSIDIAN_WORKBENCH = "Fire items can be forged here!",
		OBSIDIANAXE = "Such an axe! It cuts AND burns?!",
		OBSIDIANCOCONADE = "I get more \"boom\" for my buck with obsidian.",
		OBSIDIANFIREPIT =
		{
			EMBERS = "Uh oh. It's almost gone!",
			GENERIC = "I could watch it for hours.",
			HIGH = "BURN! BURN FASTER!",
			LOW = "This fire is small and boring.",
			NORMAL = "I feel so pampered!",
			OUT = "I should make the fire come back.",
		},
		OBSIDIANMACHETE = "A fire machete is a girl's best friend!",
		SPEAR_OBSIDIAN = "I poke. They burn!",
		OBSIDIANSPEARGUN = "I'll give it my best fiery shot!",
		PACKIM = "Friend or foe?",
		PACKIM_FISHBONE = "This looks meaningful.",
		PALMLEAF = "You'll burn.",
		PALMTREE_BURNT = "What a lovely smell.",
		PALMTREE_STUMP = "Another one bites the dust.",
		PARROT = "What a fiery color of red you are.",
		PIRATEHAT = "I feel so piratey.",
		PIRATIHATITATOR = "Cursed pirate magic?",
		POISONHOLE = "Nature is so gross.",
		RAFT = "It would be unwise to light this on fire while at sea.",
		ROWBOAT = "Rowing? Really?",
		SAIL = "It makes use of the wind.",
		SAND = "Big deal, it's sand.",
		SANDBAG = "A bag of sand.",
		SANDBAG_ITEM = "So I put this on the ground?",
		SANDHILL = "Oh, look! It's some sand.",
		SEAGULL = "Does it fear fire? It should.",
		SEASACK = "I have to wear this soggy thing on my back?",
		SEASHELL = "Just some stupid seashell.",
		SEASHELL_BEACHED = "Just some stupid seashell.",
		SEATRAP = "C'mon, swim inside! It's cozy in there!",
		SEAWEED = "Soggy sea grass.",
		SEAWEED_COOKED = "Not bad once you add fire.",
		SEAWEED_DRIED = "Healthy jerky.",
		SEAWEED_PLANTED = "Soggy sea grass.",
		SHARX = "Jerks that swim.",
		SLOTMACHINE = "This seems like a waste of time.",
		SNAKE = "Jerks that slither.",
		SNAKE_FIRE = "We share similar interests, monster thing.",
		SNAKESKIN = "Leathery.",
		SNAKESKINHAT = "Water just runs right off it.",
		SPEAR_POISON = "I hope I don't jab myself.",
		SPEARGUN = "A handy tool upon the waves.",
		SPEARGUN_POISON = "This is almost too naughty.",
		STUNGRAY = "Now I've smelled everything.",
		SUPERTELESCOPE = "I can see to the ends of the earth.",
		SWORDFISH = "En garde!",
		TELESCOPE = "You can't hide from me now, islands!",
		TIGERSHARK = "My nightmares have come true!",
		TIGERSHARKSHADOW = "Not good! Not good!",
		TOUCAN = "I like your nose.",
		TRAWLNET = "I'll catch a bunch of wet stuff with this.",
		TRAWLNETDROPPED = "Everything is going to be wet in there.",
		TREEGUARD = "I don't like you. You don't like me.",
		TRIDENT = "This is all wet.",
		TRINKET_13 = "Is this fire water? It's orange.",
		TRINKET_14 = "I don't have any pins...",
		TRINKET_15 = "Oh, this would burn.",
		TRINKET_16 = "Litter is a terrible thing.",
		TRINKET_17 = "Not my style.",
		TRINKET_18 = "I wonder if this is worth anything?",
		TRINKET_19 = "Brain cloud? Sounds tragic.",
		TURBINE_BLADES = "What do these do?",
		TURF_BEACH = "The ground is boring.",
		TURF_JUNGLE = "The ground is boring.",
		VENOMGLAND = "Gross! I wish I had gloves.",
		VINE = "I could use this for something. Or I could just burn it.",
		VOLCANO = "The biggest, fieriest fire in all the land!",
		VOLCANO_ALTAR = "Why would I wanna appease the volcano? Then it wouldn't shoot fire!",
		VOLCANO_ALTAR_BROKEN = "There's no way to quench the volcano's hunger now!",
		VOLCANO_EXIT = "I'd hate to leave this place...",
		VOLCANOSTAFF = "I am the goddess of fiery destruction!",
		WALL_LIMESTONE = "It's all bumpy.",
		WALL_LIMESTONE_ITEM = "You don't look like you would burn easily.",
		WHALE_BLUE = "I didn't know they even made fish that big.",
		WHALE_CARCASS_BLUE = "It's starting to spoil. Gross.",
		WHALE_CARCASS_WHITE = "Victory doesn't smell very good...",
		WHALE_WHITE = "I see fire in its eyes!",
		CRABHOLE = "Come out and play with me!",
		CRAB =
		{
			GENERIC = "Stop running away!",
			HIDDEN = "I'm pretty sure a crabbit is hiding there.",
		},
		BERMUDATRIANGLE = "I feel kinda dizzy looking at it.",
		BOATCANNON = "I wonder if I can start fires with this?",
		BOATREPAIRKIT = "This should patch up any little leaks.",
		MACHETE = "Or I could just burn my way through.",
		LUGGAGECHEST = "Ooo! I hope there are useful items inside.",
		DRAGOON = "If only I could figure out how to train one.",
		ANTIVENOM = "This'll help if I'm poisoned.",
		BAMBOO = "Looks flammable.",
		FROG_POISON = "Yuck! Stay away from me.",
		OX = "You look pretty sturdy.",
		PEACOCK = "Pretty!",
		SEAGULL_WATER = "\"Squawk\" yourself.",
		SNAKE_POISON = "Those are some pointy fangs.",
		SOLOFISH = "Doesn't seem very smart.",
		SPOILED_FISH = "Gross.",
		TWISTER = "Stay away from my precious flames!",
		SAND_CASTLE =
		{
			GENERIC = "It's cute, I guess.",
			SAND = "It's a castle made of sand. A sandcastle.",
		},
		SNAKEOIL = "I'm not convinced.",
		LOBSTER = "Come here, you!",
		MESSAGEBOTTLE = "Bottled paper!",
		MESSAGEBOTTLEEMPTY = "It's a bottle.",
		SHARK_FIN = "The fin fell off.",
		VOLCANO_ALTAR =
		{
		 	GENERIC = "An altar to the sate the fire gods!",
		 	OPEN = "Ready to consume the fire!",
		},
		ELEPHANTCACTUS = "Don't rub up against me!",
		ELEPHANTCACTUS_ACTIVE = "Yowch!",
		ELEPHANTCACTUS_STUMP = "And stay down!",
		DOUBLE_UMBRELLAHAT = "If I bought this in a store I'd feel burned.",
		MUSSEL_FARM =
		{
			GENERIC = "Just out of reach.",
			STICKPLANTED = "You will be mine soon.",
		},
		WOODLEGS_CAGE = "He seems a little cagey.",

		 PIRATIHATITATOR =
		 {
		 	GENERIC = "This is just ridiculous.",
		 	BURNT = "Now it's more my style.",
		 },
		 COFFEEBUSH =
		 {
		 	BARREN = "It's dripped its last drop.",
		 	PICKED = "Aw, but I wanted another cup...",
		 	WITHERED = "It needs ash and love. Mostly just ash.",
		 	GENERIC = "Hot java from hot lava!",
		 },
		 DUG_ELEPHANTCACTUS = "I don't have to water you, right?",
		 WHALE_BUBBLES = "What's making those bubbles?",

		ARMORCACTUS = "This way I won't get burned by those cacti.",
		BAMBOOTREE =
		{
			BURNT = "Aww, can I burn it again?",
			CHOPPED = "It'll come back.",
			GENERIC = "Kindling!",
		},
		BLOWDART_FLUP = "This blows.",
		BLUBBER = "I bet this burns bright!",
		BLUBBERSUIT = "It squishes when I move...",
		BOAT = "Must. Not. Burn...!",
		BOAT_TORCH = "Strangely not for torching boats.",
		BRAINJELLYHAT = "I feel smarter, but also grosser...",
		BUOY = "Buoy, I'm glad I have this.",
		BUSH_VINE =
		{
			BURNT = "Those are fun to burn!",
			CHOPPED = "That's how you untangle them.",
			GENERIC = "I bet these crackle and pop when they burn.",
		},
		COCONADE =
		{
			BURNING = "Here we go...",
			GENERIC = "First it booms, then it burns.",
		},
		COCONUT_HALVED = "Aha! Now you're food!",
		COFFEEBOT = "It makes coffee!",
		COMPASS =
		{
			E = "East!",
			GENERIC = "I can't get a reading.",
			N = "North!",
			NE = "Northeast!",
			NW = "Northwest!",
			S = "South!",
			SE = "Southeast!",
			SW = "Southwest!",
			W = "West...",
		},
		CORAL_BRAIN = "I could learn to love the taste...",
		CORAL_BRAIN_ROCK = "Genius idea, hiding out with these dumb regular corals.",
		CRATE = "If I burn it, whatever's inside burns too...",
		DEPLETED_GRASS =
		{
			GENERIC = "What a sorry looking piece of... grass?",
		},
		DEPLETED_GRASS_WATER = "It's taking a little rest.",
		DRAGOONDEN = "A bunch of hotheads live there.",
		DRAGOONEGG = "I think this hot rock is actually a hot egg.",
		DRAGOONHEART = "Nothing like a hot meal.",
		DRAGOONSPIT = "A burning puddle of hork.",
		FISH_RAW = "Needs fire!",
		FISH_RAW_SMALL = "I like sushi, but I prefer it flame-broiled.",
		FISH_RAW_SMALL_COOKED = "Fish and fire go well together.",
		FLAMEGEYSER = "Glorious...",
		FLOTSAM = "It's out there, but I'm over here.",
		FLUP = "Flup off!",
		FRESHFRUITCREPES = "Ooo la la.",
		GRASS_WATER = "This doesn't need to be watered.",
		HAIL_ICE = "Ugh, just melt already.",
		HOME = "Who lives here, I wonder?",
		ICEMAKER =
		{
			HIGH = "It's fully fueled!",
			LOW = "It needs more fuel.",
			NORMAL = "Make that ice.",
			OUT = "It's out of fuel.",
			VERYLOW = "It's nearly out of fuel.",
		},
		JUNGLETREE =
		{
			BURNING = "Wow! So much fire!",
			BURNT = "A major improvement.",
			CHOPPED = "That took a few swings.",
			GENERIC = "That's a whole lot of tree to burn!",
		},
		KNIGHTBOAT = "Check out your boat, mate.",
		KRAKEN = "Kill it with fire!",
		KRAKENCHEST = "Don't mind if I do.",
		KRAKEN_TENTACLE = "Eww, stay away!",
		LIMPETROCK =
		{
			GENERIC = "That gross food is trying to eat that rock.",
			PICKED = "The rock won't be bothered by those suckers for a bit.",
		},
		LIVINGJUNGLETREE = "There's something odd about this tree.",
		LOBSTER_DEAD = "Edible in a pinch.",
		LOBSTER_DEAD_COOKED = "Lobster for dinner! Pinch me!",
		MAGIC_SEAL = "It's so glowy.",
		MAGMAROCK = "Magma-nificent!",
		MAGMAROCK_FULL = "Magma-nificent!",
		MAGMAROCK_GOLD = "Magma-nificent!",
		MAGMAROCK_GOLD_FULL = "Magma-nificent!",
		MANGROVETREE = "No need to water this guy.",
		MANGROVETREE_BURNT = "Burned right down to the, uh, water.",
		MARSH_PLANT_TROPICAL = "Plant-y.",
		MERMFISHER = "Ugh, bet you never get that fish smell out.",
		MERMHOUSE_FISHER = "Fish mongers.",
		MONKEYBALL = "I bet the monkeys would have a ball with this thing.",
		MONSTERTARTARE = "Gross!",
		MOSQUITOSACK_YELLOW = "Something disgusting dropped this.",
		MUSSELBOUILLABAISE = "Mmm, smells good!",
		MYSTERYMEAT = "Parenting is gross.",
		NEEDLESPEAR = "I could jabber on about this all day.",
		OCTOPUSCHEST = "It's filled with sea treats!",
		OCTOPUSKING = "He looks kinda dozy.",
		OXHAT = "Ox-cellent!",
		OX_FLUTE = "I hear a storm a-coming.",
		OX_HORN = "I could use an ox-tra one of these.",
		PALMLEAF_HUT = "Keeps the elements away, but it would burn so easy.",
		PARROT_PIRATE = "You're a skreechy scallywag.",
		PEG_LEG = "I haven't pegged down what this does yet.",
		PIGTENT = "It smells terrible!",
		PIKE_SKULL = "Nasty.",
		PIRATEGHOST = "What \"arrrr\" you?",
		PIRATEPACK = "Carrying this will build chest muscles.",
		PORTAL_SHIPWRECKED = "Time to get outta here.",
		PRIMEAPE = "Hey lil buddy, do you like to play with fire too?",
		PRIMEAPEBARREL = "What a monkey sty.",
		RAWLING = "He keeps me company.",
		REDBARREL = "My favorite type of barrel!",
		ROCK_CHARCOAL = "It drops burned things!",
		ROCK_OBSIDIAN = "This rock makes me so excited, I just want to explode!",
		SAIL_STICK = "I'm the queen of this boooooat!",
		SANDBAGSMALL = "Keeps the home fires burning.",
		SANDBAGSMALL_ITEM = "Keeps the home fires burning.",
		SHADOWSKITTISH_WATER = "What's that??",
		SHARKITTEN = "Hey cutie, where's your mom?",
		SHARKITTENSPAWNER =
		{
			GENERIC = "My shark radar is burning.",
			INACTIVE = "Why is this sand dune here?",
		},
		SHARK_GILLS = "I guess it doesn't need to breathe with these anymore.",
		SHARK_TEETHHAT = "Wearing this gives me a toothy grin.",
		SHIPWRECKED_ENTRANCE = "Here goes!",
		SHIPWRECKED_EXIT = "I'm outta here.",
		SNAKEDEN =
		{
			BURNT = "Those were fun to burn!",
			CHOPPED = "That's how you untangle them.",
			GENERIC = "I bet these crackle and pop when they burn.",
		},
		SNAKESKINSAIL = "What a morbid sail.",
		SPEAR_LAUNCHER = "Only thing better than a spear is the gun that shoots them.",
		SUNKEN_BOAT =
		{
			ABANDONED = "Where'd they go?",
			GENERIC = "Someone out there is all wet.",
		},
		SUNKEN_BOAT_BURNT = "Double whammy.",
		SUNKEN_BOAT_TRINKET_1 = "I can't say that word!",
		SUNKEN_BOAT_TRINKET_2 = "I've put away childish things.",
		SUNKEN_BOAT_TRINKET_3 = "It wants to meet my lighter.",
		SUNKEN_BOAT_TRINKET_4 = "No idea what that is.",
		SUNKEN_BOAT_TRINKET_5 = "Not my size.",
		SWEETPOTATOSOUFFLE = "Cooked to perfection!",
		SWEET_POTATO = "A welcome change from red berries.",
		SWEET_POTATO_COOKED = "The flames definitely improved it.",
		SWEET_POTATO_PLANTED = "It would be cuter on fire!",
		SWEET_POTATO_SEEDS = "Seeds. Sweet.",
		SWIMMINGHORROR = "You can swim? Horrible!",
		TELEPORTATO_SW_BASE = "Seems like it's missing a thing or two.",
		TELEPORTATO_SW_BOX = "A part for something.",
		TELEPORTATO_SW_CRANK = "For cranking?",
		TELEPORTATO_SW_POTATO = "Wonder what it does?",
		TELEPORTATO_SW_RING = "This goes with something else, I think.",
		THATCHPACK = "Thatch you very much.",
		TIDALPOOL = "I wonder which way it would swirl if you flushed it?",
		TIDAL_PLANT = "It's a plant.",
		TIGEREYE = "Don't look at me like that!",
		TRAWLNETDROPPED =
		{
			GENERIC = "What's in the baaaag?",
			SOON = "It's going to sink soon!",
			SOONISH = "I believe that bag is sinking.",
		},
		TREASURECHEST_TRAP = "Dirty trick!",
		TRINKET_20 = "I can't say that word!",
		TRINKET_21 = "I've put away childish things.",
		TRINKET_22 = "It wants to meet my lighter.",
		TRINKET_23 = "Broken what?",
		TROPICAL_FISH = "Such pretty colors.",
		TUNACAN = "Aw, but I like mine with Ballphin!",
		TURF_ASH = "Ashy.",
		TURF_MAGMAFIELD = "Explosive!",
		TURF_MEADOW = "Serene.",
		TURF_SNAKESKINFLOOR = "Gross.",
		TURF_TIDALMARSH = "Squelchy.",
		TURF_VOLCANO = "Hot footin'.",
		TWISTER_SEAL = "I've been burned by cute things before.",
		VOLCANO_ALTAR_TOWER = "A monument to fire!",
		VOLCANO_SHRUB = "You come pre-burnt!",
		WALLYINTRO_DEBRIS = "Did I do that?",
		WATERYGRAVE = "Something's fishy here.",
		WHALE_TRACK = "Where there's bubbles there's fire!",
		WILBUR_CROWN = "You'd have to have a tiny little head to fit this.",
		WILBUR_UNLOCK = "Fancy monkey.",
		WILDBORE = "Not wild about being close to this guy.",
		WILDBOREHEAD = "Blech!",
		WILDBOREHOUSE = "Add fire and you'd get BBQ!",
		WIND_CONCH = "Hope no fires get blown out.",
		WOODLEGSBOAT = "A fine ship.",
		WOODLEGSHAT = "I don't think it was made for me.",
		WOODLEGSSAIL = "This sail looks like it would be special to someone.",
		WOODLEGS_KEY1 = "A key to what?",
		WOODLEGS_KEY2 = "Something must be locked up somewhere.",
		WOODLEGS_KEY3 = "Another key.",
		WRECK = "Someone has regrets.",
		CALIFORNIAROLL = "Oh, goody. Fish rolled in seaweed.",
		BANANAPOP = "This is the opposite of burning.",
		BISQUE = "I guess I could eat that.",
		CEVICHE = "It's still slimy.",
		SEAFOODGUMBO = "Ew, what IS this?",
		SURFNTURF = "Ugh. This is old person food!",
		SHARKFINSOUP = "And I didn't even burn it!",
		LOBSTERDINNER = "Yummmmmmm!",
		LOBSTERBISQUE = "I'm gonna eat this entire thing!",
		JELLYOPOP = "I want twenty!",
		VOLCANO_SHRUB = "No fair! I didn't get to burn you!",
		ROCK_OBSIDIAN = "The... most... beautiful rock... I've ever... seen...",
		ROCK_CHARCOAL = "Charrific!",
	},
	DESCRIBE_TOODARK = "I need more light!",
	DESCRIBE_GENERIC = "It's just asking to be burned.",
	DESCRIBE_SMOLDERING = "Hooray, it's about to light on fire!",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "Ughhhh!",
	},
}